### ISSUE TITLE
SetDefaultTTL not setting default TTL after previous RR has one

### ISSUE THREAD

**Issue by cretz** [miekg/dns#1000]
As seen [in the playground](https://play.golang.org/p/ekf0cTKXBe4) from the following code:

```go
package main

import (
	"fmt"
	"strings"

	"github.com/miekg/dns"
)

func main() {
	zone := `
example.com.             120  IN     A        1.2.3.6
ns                            IN     A        2.3.4.1
`
	p := dns.NewZoneParser(strings.NewReader(zone), "example.com.", "")
	p.SetDefaultTTL(3600)
	rr, _ := p.Next()
	fmt.Printf("RR 1: %v\n", rr)
	rr, _ = p.Next()
	fmt.Printf("RR 2: %v\n", rr)
}
```

The result is:

    RR 1: example.com.	120	IN	A	1.2.3.6
    RR 2: ns.example.com.	120	IN	A	2.3.4.1

But I would expect the last one to have a TTL of 3600. Even if there's not a way to fix this without fear of those relying on this behavior, can you think of any way around it to apply a default TTL after parsing to RRs where it wasn't explicitly specified?

**Comment by miekg** [comment]
This is exactly how DNS RRs should be parsed. So this is WAI I believe

**Comment by cretz** [comment]
Ah, ok I confirmed it's NSD that deviates from the RFC. From RFC 1035 section 5.1 you are correct:

> Omitted class and TTL values are default to the last explicitly stated values.

Others like my self might be confused by NSD or assumed, as I did incorrectly, that `SetDefaultTTL` was the equivalent of `$TTL`. Sorry to bother.
