### ISSUE TITLE
[Feature] Support .bit

### ISSUE THREAD

**Issue by WorryTheBirds12** [miekg/dns#1001]
**Feature**: Support .bit TLD (similar to OpenNic)
https://www.wikipedia.org/wiki/NameCoin

__________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/78654780-feature-support-bit)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by miekg** [comment]
if it speaks DNS is supported by this library, otherwise it isn't
