### ISSUE TITLE
Suggestion: Continuous Fuzzing Integration

### ISSUE THREAD

**Issue by yevgenypats** [miekg/dns#1002]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see and example of in the wild integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

@miekg

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Suggestion: Continuous ..." ]
>Let me know if this is something worth working on.

yes, please do. Also see https://github.com/coredns/coredns/pull/3093

**Comment by yevgenypats** [comment]
Cool. Yes, I'm aware of the coredns PR (There is an issue regarding the go-fuzz modules there that we need to find a way to solve).

Also forgot to mention we have a reward program (just rolled it 2 days ago). If you would like to do the integration yourself I'll be happy to reward you as well as get unbiased feedback about how smooth was the integration. If you currently don't have time for that and prefer me to do this then I can happily contribute the PR but you won't be eligible for the reward. let me know what works best for you.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Suggestion: Continu..." ]
>Cool. Yes, I'm aware of the coredns PR (There is an issue regarding the go-fuzz modules there that we need to find a way to solve).
>
>Also forgot to mention we have a reward program (just rolled it 2 days ago). If you would like to do the integration yourself I'll be happy to reward you as well as get unbiased feedback about how smooth was the integration. If you currently don't have time for that and prefer me to do this then I can happily contribute the PR but you won't be eligible for the reward. let me know what works best for you.

cool :) But seeing that coredns already being stalled, I fear I don't have the 
time to figure that all out. So please contribute a PR :)

**Comment by yevgenypats** [comment]
sounds good. will do.

**Comment by miekg** [comment]
this is waiting for go modules support in gofuzz

**Comment by marco-m** [comment]
Hello, in case you are not aware, go-fuzz now has initial Go module support: https://github.com/dvyukov/go-fuzz#modules-support
