### ISSUE TITLE
How to find server port?

### ISSUE THREAD

**Issue by bookmoons** [miekg/dns#1003]
It seems I can start a server on an OS-selected port with port 0:

```go
server := &dns.Server{
    Addr: "127.0.0.1:0",
    Net: "udp",
}
server.ListenAndServe()
```

If you start a server like this, is there a way to find the port it was assigned to?

**Comment by tmthrgd** [comment]
This should work:

```go
server.NotifyStartedFunc = func() {
    addr := server.Listener.Addr()
    _ = addr
}
```

Alternatively create your own `net.Listener` and call `ActivateAndServe` instead.

**Comment by bookmoons** [comment]
Worked just fine. Thanks a lot.

**Comment by bookmoons** [comment]
A little more info for future readers: If you listening with `"udp"` you want `server.PacketConn.LocalAddr()`. Same return type.

**Comment by bookmoons** [comment]
A little more info for future readers: If you're listening with `"udp"` you want `server.PacketConn.LocalAddr()`. Same return type.
