### ISSUE TITLE
When parsing a bind file, all relative names are converted to absolute ones

### ISSUE THREAD

**Issue by mostfunkyduck** [miekg/dns#1029]
I'm not familiar with the myriad specs on this topic, so I'm not sure if this is a bug or enhancement.  The basic problem is that when you parse a zone file, all names are converted into absolute ones, even if they are represented as relative names in the zone file itself.  Because of that, callers which are trying to read the zone file and compare the contents to what's currently live will see that all records with relative names in the label or the value require modification.

I ran into this with cli53, where I logged a bug (https://github.com/barnybug/cli53/issues/280).  It hits an issue with this because when it exports from route53, the zone file will contain relative names.  Upon import, those same names are made absolute and show up as requiring a change.

*Steps to reproduce*
Run the following code:
``` package main

import (
  "github.com/miekg/dns"
  "os"
  "io"
  "fmt"
)

func main() {
  var reader io.Reader
  origin := ""
  filename := "example.com."
  f, err := os.Open(filename)
  if err != nil {
    panic(err)
  } 
  defer f.Close()
  reader = f

  tokensch := dns.ParseZone(reader, origin, filename)
  for token := range tokensch {
    if token.Error != nil {
      panic(token.Error)
    }
    fmt.Printf("%s\n", token.RR)
  }
}

```
using a zone file with the following contents:
```$ORIGIN example.com.
subdomain 300	IN	NS ns-613.awsdns-12.net
```

*Expected results*
This will output a record with exact same format as the record in the zone file

*Actual results*
The output appends the origin to all relative names
```
subdomain.example.com.	300	IN	NS	ns-613.awsdns-12.net.example.com.
```

I think there should be a flag to toggle the absolute name behavior, or it can be removed altogether if there's no spec mandating it. I will submit a PR for the latter

**Comment by miekg** [comment]
This is correct behaviour according to the DNS spec

**Comment by miekg** [comment]
you can use `.` as the origin, so nothing longer than that will be added to create fully qualified names.
