### ISSUE TITLE
Suggestion: Msg string formatting without newline and tab characters

### ISSUE THREAD

**Issue by aaronhnatiw** [miekg/dns#1034]
The `Msg` type should have a method that returns a properly formatted string for logging purposes. Outputting to the `dig` format is okay for one-offs, but when used for logging, it retains all the `\t` and `\n` strings which is painful to parse visually or programmatically.

This is similar to #163, but the problem is more generally with the whole `String()` method for the `Msg` type.

**Comment by aaronhnatiw** [comment]
For anyone who came here looking for a string formatting function to remove the newline and tab characters from `msg.String()` output, here is the function I've used:

```go
func formatMsgForLog(msg dns.Msg) string {
	return strings.ReplaceAll(strings.ReplaceAll(msg.String(), "\t", " "), "\n", " ")
}
```

**Comment by miekg** [comment]
you, indeed need to do the above are write your own formatter taking in a *dns.Msg
