### ISSUE TITLE
After Shutdown(), should server still be allowed to call ListenAndServe()?

### ISSUE THREAD

**Issue by evantorrie** [miekg/dns#1036]
A newly created Server which has had `Server.Shutdown()` called on it returns `&Error{err: "server not started"}`.  However, unlike go's http server, `dns.Server` still allows you to call `Server.ListenAndServe()` after a `Shutdown()` call.

Is this expected behavior? Or would it be better to follow `http.Server`'s lead and once a server is `Shutdown()`, it will forever return `&Error{err: "Server closed"}`?

**Comment by tmthrgd** [comment]
That would probably make sense, but I think the Server is technically reusable currently. It wouldn’t be hard to change and I can’t imagine it’s exactly a common occurrence.
