### ISSUE TITLE
The function named msgLenWithCompressionMap is undefined?

### ISSUE THREAD

**Issue by CXeon** [miekg/dns#1038]
# github.com/miekg/dns
..\..\..\..\..\github.com\miekg\dns\msg_truncate.go:38:7: undefined: msgLenWithCompressionMap
..\..\..\..\..\github.com\miekg\dns\msg_truncate.go:47:14: dns.popEdns0 undefined (type *Msg has no field or method popEdns0)
..\..\..\..\..\github.com\miekg\dns\msg_truncate.go:61:13: too many arguments in call to r.len
..\..\..\..\..\github.com\miekg\dns\msg_truncate.go:99:13: too many arguments in call to r.len
	have (int, map[string]struct {})
	want ()

**Comment by tmthrgd** [comment]
Your GOPATH is messed up somehow. Delete the miekg/dns and then run a fresh go get. That should get you into a working state.
