### ISSUE TITLE
regression: “dns: overflow packing opt” after EDNS0 commit

### ISSUE THREAD

**Issue by stapelberg** [miekg/dns#1045]
Starting at commit a98e771ba54f32f7273c037cb8a6e7a7aef6a654, my router7 tests start failing:

```
~/go/src/github.com/miekg/dns master % git reset --hard 22cda6dc4f8b43ab129d7e79c24975180a0aace6
HEAD is now at 22cda6dc Speed up NextLabel and PrevLabel (#1039)

~router7 % go test -count=1 github.com/rtr7/router7/integration/dns 
ok  	github.com/rtr7/router7/integration/dns	0.013s

~/go/src/github.com/miekg/dns master % git reset --hard a98e771ba54f32f7273c037cb8a6e7a7aef6a654
HEAD is now at a98e771b Export EDNS0 interface (#1041)

~router7 % go test -count=1 github.com/rtr7/router7/integration/dns
2019/12/06 21:52:56 dns.go:424: resolving [{8.8.8.8.in-addr.arpa. 12 1}] failed: dns: overflow packing opt
2019/12/06 21:52:57 dns.go:424: resolving [{8.8.8.8.in-addr.arpa. 12 1}] failed: dns: overflow packing opt
2019/12/06 21:52:58 dns.go:424: resolving [{8.8.8.8.in-addr.arpa. 12 1}] failed: dns: overflow packing opt
--- FAIL: TestDNS (3.01s)
    dns_test.go:38: exit status 9
FAIL
FAIL	github.com/rtr7/router7/integration/dns	3.011s
FAIL
```

Not sure if the mistake is easy to spot, so let me know if you need more details.

Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] regression: “dns: overf..." ]
>Starting at commit a98e771ba54f32f7273c037cb8a6e7a7aef6a654, my router7 tests start failing:
>
>```
>~/go/src/github.com/miekg/dns master % git reset --hard 22cda6dc4f8b43ab129d7e79c24975180a0aace6
>
>~router7 % go test -count=1 github.com/rtr7/router7/integration/dns
>ok  	github.com/rtr7/router7/integration/dns	0.013s
>
>~/go/src/github.com/miekg/dns master % git reset --hard a98e771ba54f32f7273c037cb8a6e7a7aef6a654
>HEAD is now at a98e771b Export EDNS0 interface (#1041)
>
>~router7 % go test -count=1 github.com/rtr7/router7/integration/dns
>2019/12/06 21:52:56 dns.go:424: resolving [{8.8.8.8.in-addr.arpa. 12 1}] failed: dns: overflow packing opt
>2019/12/06 21:52:57 dns.go:424: resolving [{8.8.8.8.in-addr.arpa. 12 1}] failed: dns: overflow packing opt
>2019/12/06 21:52:58 dns.go:424: resolving [{8.8.8.8.in-addr.arpa. 12 1}] failed: dns: overflow packing opt
>--- FAIL: TestDNS (3.01s)
>    dns_test.go:38: exit status 9
>FAIL
>FAIL	github.com/rtr7/router7/integration/dns	3.011s
>FAIL
>```
>
>Not sure if the mistake is easy to spot, so let me know if you need more details.

i'll revert for the time being, thanks for your report.

**Comment by tmthrgd** [comment]
Let's make sure we include a test case (similar to whatever github.com/rtr7/router7/integration/dns is doing).

**Comment by tomponline** [comment]
@miekg we also experienced issues with this commit, but we worked around it with this fix: https://github.com/lxc/lxd/pull/6569

We're not sure if our original usage was wrong though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] regression: “dns: o..." ]
>Let's make sure we include a test case (similar to whatever github.com/rtr7/router7/integration/dns is doing).

+1

The PR itself looked mostly harmless, so that can def. be improved.
