### ISSUE TITLE
Explain ActivateAndServe Asshole

### ISSUE THREAD

**Issue by dalu** [miekg/dns#1057]
https://godoc.org/github.com/miekg/dns#Server.ActivateAndServe

reads

ActivateAndServe starts a nameserver with the PacketConn or Listener configured in *Server. Its main use is to start a server from systemd.

Fine. Do you have an example in which context systemd plays a role there or how to use this function in conjunction with systemd? I'm guessing you mean socket activation.
Do you just do the usualy socket and service combo and listen via net.Conn and pass it to the server? I don't get why systemd, what does systemd have to do in all this?

**Comment by miekg** [comment]
2 definitions found

From WordNet (r) 3.0 (2006) [wn]:

  asshole
      n 1: insulting terms of address for people who are stupid or
           irritating or ridiculous [syn: {asshole}, {bastard},
           {cocksucker}, {dickhead}, {shit}, {mother fucker},
           {motherfucker}, {prick}, {whoreson}, {son of a bitch},
           {SOB}]
      2: vulgar slang for anus [syn: {arse}, {arsehole}, {asshole},
         {bunghole}]

From Moby Thesaurus II by Grady Ward, 1.0 [moby-thesaurus]:

  20 Moby Thesaurus words for "asshole":
     anus, boob, booby, bung, bunghole, chump, ding-a-ling, dingbat,
     dingdong, galoot, goof, jerk, jerk-off, klutz, mutt, prize sap,
     sap, saphead, sawney, schlemiel



/close
/lock
