### ISSUE TITLE
deprecate old parser

### ISSUE THREAD

**Issue by miekg** [miekg/dns#1059]
There is a new zone parser that works better than the old. It's time to start thinking about deprecating the old parser somewhere in 2020.

Specially this means removing: `ParseZone` and `parseZone` and cleaning up the tests.

**Comment by miekg** [comment]
generate_test.go and parse_test.go  are heavy users of the old parser...

**Comment by tmthrgd** [comment]
@miekg They shouldn’t be hard to switch over. They should all map pretty cleanly. Another option would be to just move the `ParseZone` functions into the test files if they haven’t been converted in time.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] deprecate old parse..." ]
>@miekg They shouldn’t be hard to switch over. They should all map pretty cleanly. Another option would be to just move the `ParseZone` functions into the test files if they haven’t been converted in time.

true. I was just too lazy to do the work :-)
