### ISSUE TITLE
i/o timeout unless Fqdn

### ISSUE THREAD

**Issue by sporkmonger** [miekg/dns#1063]
I'm not sure if this is a code bug or a documentation bug, but I accidentally failed to call `dns.Fqdn()` when setting `ptr.Ptr` and it appears that this results in an i/o timeout when the client tries to query the server. Calling `dns.Fqdn()` first fixes it. I couldn't find anything in the documentation calling out the need for `Ptr` values to be fully-qualified (though it's obvious in retrospect), and the i/o timeout had me looking in all the wrong places trying to resolve. Unclear if the fix should be documentation highlighting that this could happen or if it should just automatically call `dns.Fqdn()` for you, or if it should toss a `dns.ErrFqdn` somewhere, but the surprise i/o timeout is pretty hard to debug and track down to root cause.

**Comment by tmthrgd** [comment]
Can you provide a reproducer? It’s hard to determine where a big may be otherwise.

**Comment by sporkmonger** [comment]
Working code:
```
func MockHandler(answers []string) dns.HandlerFunc {
	return func(w dns.ResponseWriter, req *dns.Msg) {
		m := new(dns.Msg)
		m.SetReply(req)

		m.Answer = make([]dns.RR, len(answers))
		for i, answer := range answers {
			m.Answer[i] = &dns.PTR{
				Hdr: dns.RR_Header{Name: m.Question[0].Name, Rrtype: dns.TypePTR, Class: dns.ClassINET, Ttl: 60},
				Ptr: dns.Fqdn(answer),
			}
		}

		w.WriteMsg(m)
	}
}
```

i/o timeout (if answer isn't already FDQN):
```
func MockHandler(answers []string) dns.HandlerFunc {
	return func(w dns.ResponseWriter, req *dns.Msg) {
		m := new(dns.Msg)
		m.SetReply(req)

		m.Answer = make([]dns.RR, len(answers))
		for i, answer := range answers {
			m.Answer[i] = &dns.PTR{
				Hdr: dns.RR_Header{Name: m.Question[0].Name, Rrtype: dns.TypePTR, Class: dns.ClassINET, Ttl: 60},
				Ptr: answer,
			}
		}

		w.WriteMsg(m)
	}
}
```

**Comment by andrewtj** [comment]
Both those snippets ignore the error returned by `WriteMsg()`. Perhaps this [example](https://github.com/miekg/dns/blob/bfd86012221c91df2a9a82a02e6e9a6ab70bd323/doc.go#L215) should be updated.

**Comment by tmthrgd** [comment]
As @andrewtj said, you need to be checking the error from `WriteMsg`. Ultimately the code ends up calling `packDomainName` with `Ptr` which hits this check: https://github.com/miekg/dns/blob/aae7df65e6178e7937664e9c3036f62fc2098d7c/msg.go#L215-L217.

You’ll need to ensure that Ptr is always a FQDN yourself and I don’t think that’s something this library should do automatically.

If someone wants to open a PR checking the error that would be fine. I’ll close this issue though.

**Comment by sporkmonger** [comment]
Cool, thanks. Yeah, I copied from those examples.

**Comment by sporkmonger** [comment]
Something along these lines presumably?

```go
err := w.WriteMsg(m)
if err != nil {
	msg := new(dns.Msg)
	msg.SetRcode(req, dns.RcodeServerFailure)
	w.WriteMsg(msg)
}
```

**Comment by andrewtj** [comment]
@sporkmonger yep. I think I'd add a comment on the second `WriteMsg()` pointing out that it's unlikely to fail, and if it does you can't do much other than log the failure.

**Comment by tmthrgd** [comment]
Error handling is complex and for an example, I’d rather just something like:
```go
if err := w.WriteMsg(m); err != nil {
    // handle error
}
```

Simply replying with an error may not always be the correct approach.
