### ISSUE TITLE
1.1.26: "go generate" fails: can't find import: "github.com/miekg/dns"

### ISSUE THREAD

**Issue by onlyjob** [miekg/dns#1066]
```
src/github.com/miekg/dns/duplicate.go
2019/12/30 01:23:37 can't find import: "github.com/miekg/dns"
exit status 1
src/github.com/miekg/dns/duplicate.go:3: running "go": exit status 1
```

**Comment by onlyjob** [comment]
The following patch appears to fix the problem - please review:

~~~~
--- a/duplicate_generate.go
+++ b/duplicate_generate.go
@@ -40,9 +40,9 @@
 }

 func main() {
        // Import and type-check the package
-       pkg, err := importer.Default().Import("github.com/miekg/dns")
+       pkg, err := importer.For("source", nil).Import("github.com/miekg/dns")
        fatalIfErr(err)
        scope := pkg.Scope()

        // Collect actual types (*X)
--- a/msg_generate.go
+++ b/msg_generate.go
@@ -45,9 +45,9 @@
 }

 func main() {
        // Import and type-check the package
-       pkg, err := importer.Default().Import("github.com/miekg/dns")
+       pkg, err := importer.For("source", nil).Import("github.com/miekg/dns")
        fatalIfErr(err)
        scope := pkg.Scope()

        // Collect actual types (*X)
--- a/types_generate.go
+++ b/types_generate.go
@@ -82,9 +82,9 @@
 }

 func main() {
        // Import and type-check the package
-       pkg, err := importer.Default().Import("github.com/miekg/dns")
+       pkg, err := importer.For("source", nil).Import("github.com/miekg/dns")
        fatalIfErr(err)
        scope := pkg.Scope()

        // Collect constants like TypeX
~~~~

See also https://github.com/golang/go/issues/25723.

**Comment by tmthrgd** [comment]
This seems like it’s superseded by the pending #1050. While waiting for that to merge, there’s a simple workaround from the linked go issue: `go install`.

There’s very little reason to run `go generate` in this library unless you’re planing on opening a pull request.

I’m going to close this for now, but feel free to reopen if #1050 doesn’t get merged.

**Comment by onlyjob** [comment]
"Simple workaround" is unavailable to downstream package maintainers where library is built in pristine controlled environment. Installation recursion is best to avoid (e.g. previous release of the library may be already installed so the test could be misleading as it is not testing what it should test).

Maybe for this library `go generate` is not too important but generally speaking it is a good practice for build integrity and reproducibiity.

I'm looking forward for #1050 to get merged, if you think it is a better solution. Thanks.

**Comment by tmthrgd** [comment]
@onlyjob I’m confused at where you’ve heard that, but running `go generate` as a consumer is definitely not good practice and isn’t even possible in module mode. It’s very much a tool for package maintainers. Either way, yes #1050 is the solution here and will likely be merged relatively soon.

**Comment by onlyjob** [comment]
I am the package maintainer. ;)

**Comment by tmthrgd** [comment]
I meant package author, as in miekg, or contributors (PR authors). I’m not sure what package maintainer means in this context.

Anyway #1050 has been merged so this issue is resolved regardless.

**Comment by onlyjob** [comment]
Thanks!
