### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by Serizao** [miekg/dns#1072]
Hello,
I have problem with your soft :

I have go soft with 500 go routine. All go routine loop on the resolution module. At the beginning that work fine but after few second the program exit with error :

<img width="501" alt="Capture d’écran 2020-02-09 à 17 32 18" src="https://user-images.githubusercontent.com/11671895/74105924-4e414500-4b62-11ea-9dd7-e60a449dd555.png">

The code of my do routine is :

```go
func resolv(to int, from int, data []string,wg *sync.WaitGroup, nums chan string){
  defer wg.Done()
  c := dns.Client{}
  m := dns.Msg{}
  for i := to ; i<from ; i++ {
       m.SetQuestion(dns.Fqdn(data[i]), dns.TypeA)
       r, _, err := c.Exchange(&m, "8.8.8.8:53")
       if err != nil {
           log.Fatal(err,"---")
       }
       if len(r.Answer) != 0 {
           nums<-data[i]
       }
    }
}
```
and i not think that the network beacause I try it on hosted OVH server

I have you any idea why ?

**Comment by miekg** [comment]
google public dns might block you
