### ISSUE TITLE
TXT query on cloudflare.com returns empty answer

### ISSUE THREAD

**Issue by bn4t** [miekg/dns#1074]
Hi,
I have a weird issue:

When I query `cloudflare.com` for TXT records I get an empty answer instead of the expected records. 
The same query using dig and the same dns server returns the expected records.

The TXT query works for all domains I tested except `cloudflare.com`. I've also tried using different dns servers with no luck.

Am I doing something wrong on my end or is this just a weird bug?

### How to reproduce
````
package main

import (
	"github.com/miekg/dns"
	"log"
)

func main()  {

	c := dns.Client{}
	m := dns.Msg{}
	m.SetQuestion("cloudflare.com.", dns.TypeTXT)
	r, _, err := c.Exchange(&m, "1.1.1.1:53")
	if err != nil {
		log.Fatal(err)
	}
	log.Print(r)

}
````

**Comment by miekg** [comment]
Ghe, I was mystified as well, but cloudflare sets Tc:

~~~
;; flags: qr tc rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
~~~
not putting anything in the answer is borderline RFC incompliant though...

**Comment by bn4t** [comment]
Ah, thanks for the response. Must have missed the truncate flag.
