### ISSUE TITLE
i/o timeout when test to send mutiple msg

### ISSUE THREAD

**Issue by 4huo** [miekg/dns#1076]
`	m1.Question = make([]dns.Question,2)

	m1.Question[0] = dns.Question{dns.Fqdn("www.google.com"), dns.TypeA, dns.ClassINET}

	m1.Question[1] = dns.Question{dns.Fqdn("www.google.co.uk"), dns.TypeA, dns.ClassINET}

	in, _, err := c.Exchange(m1, "8.8.8.8:53")
`
when i tried this, I got i/o timeout err.
how should I do to get both www.google.com and www.google.co.uk result.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] i/o timeout when test t..." ]
>`	m1.Question = make([]dns.Question,2)
>	m1.Question[0] = dns.Question{dns.Fqdn("www.google.com"), dns.TypeA, dns.ClassINET}
>	m1.Question[1] = dns.Question{dns.Fqdn("www.google.co.uk"), dns.TypeA, dns.ClassINET}
>	in, _, err := c.Exchange(m1, "8.8.8.8:53")
>`
>when i tried this, I got i/o timeout err.
>how should I do to get both www.google.com and www.google.co.uk result.

you can't. This was a nice idea when DNS started (1984), but no implementation has ever
supported multiple questions

/close

**Comment by 4huo** [comment]
Ah, maybe my question is wrong. I am writing a dns brute tool. I just want to send some domains to a dns server and wait to receive valid A records. like this:
map["8.8.8.8"]{"www.google.com","www2.google.com"}.
