### ISSUE TITLE
add ESNI resource record type

### ISSUE THREAD

**Issue by mrbluecoat** [miekg/dns#1078]
Per https://chris-wood.github.io/draft-ietf-tls-esni/draft-ietf-tls-esni.html#rfc.section.8.3 can you add `ESNI` to your list of DNS types in https://github.com/miekg/dns/blob/master/types.go ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] add ESNI resource recor..." ]
>Per https://chris-wood.github.io/draft-ietf-tls-esni/draft-ietf-tls-esni.html#rfc.section.8.3 can you add `ESNI` to your list of DNS types in https://github.com/miekg/dns/blob/master/types.go ?

I don't think so, if this is the "spec" for the record: https://chris-wood.github.io/draft-ietf-tls-esni/draft-ietf-tls-esni.html#publishing-key
is this in network order? How are `cipher_suites` represented in the records? How does the
text representation look?

The type code is also not registered yet: https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-4

/Miek

--
Miek Gieben

**Comment by mrbluecoat** [comment]
No problem.  I'll revisit in May when the draft expires: https://datatracker.ietf.org/doc/draft-ietf-tls-esni/

Thanks for your consideration
