### ISSUE TITLE
how to send multiple packets in one lookup

### ISSUE THREAD

**Issue by yulinsec** [miekg/dns#1079]
When using many goroutines(more than 2000) to question, it will take a lot of cpu. 

Therefore, I think that I should send much more(more than one udp message) data in one lookup to imporove I/O and ease the cpu. 
I read the godoc, but have not found out the solutions. 

Thanks your time for this issues.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] how to send multiple pa..." ]
>When using many goroutines(more than 2000) to question, it will take a lot of cpu.
>
>
>Therefore, I think that I should send much more(more than one udp message) data in one lookup to imporove I/O and ease the cpu.
>I read the godoc, but have not found out the solutions.
>
>Thanks your time for this issues.

This library provides functions to interacts with the dns - it doesn't mandate starting a
goroutine. The server does do this, but you can limit that yourself.

/close
