### ISSUE TITLE
docker SIGSEV by goroutine 10181 miekg/dns?

### ISSUE THREAD

**Issue by ralfi** [miekg/dns#1086]
Hi,

since a few days my docker.io-19.03 on Debian unstable crashes with this messages ...

``
3 22:35:52 <myDockerHost> dockerd[2472708]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x11 pc=0x55bbc9db237b]
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: goroutine 10181 [running]:
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: github.com/docker/libnetwork.(*resolver).ServeDNS(0xc000c95500, 0x55bbcb91cec0, 0xc001e752c0, 0xc001e92b40)
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: #011/build/docker.io-yDS88k/docker.io-19.03.6+dfsg1/.gopath/src/github.com/docker/libnetwork/resolver.go:487 +0x79b
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: github.com/miekg/dns.(*Server).serveDNS(0xc0009a8900, 0xc000e02200, 0x2f, 0x200, 0xc001e752c0)
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: #011/build/docker.io-yDS88k/docker.io-19.03.6+dfsg1/.gopath/src/github.com/miekg/dns/server.go:609 +0x2e2
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: github.com/miekg/dns.(*Server).serveUDPPacket(0xc0009a8900, 0xc000a4a230, 0xc000e02200, 0x2f, 0x200, 0xc0000d6b90, 0xc001e95240)
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: #011/build/docker.io-yDS88k/docker.io-19.03.6+dfsg1/.gopath/src/github.com/miekg/dns/server.go:549 +0xb4
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: created by github.com/miekg/dns.(*Server).serveUDP
Mar 3 22:35:52 <myDockerHost> dockerd[2472708]: #011/build/docker.io-yDS88k/docker.io-19.03.6+dfsg1/.gopath/src/github.com/miekg/dns/server.go:479 +0x2ae
Mar 3 22:35:52 <myDockerHost> matrix-synapse[2478824]: time="2020-03-03T22:35:52+01:00" level=error msg="error waiting for container: unexpected EOF"
Mar 3 22:35:52 <myDockerHost> matrix-riot-web[2478803]: time="2020-03-03T22:35:52+01:00" level=error msg="error waiting for container: unexpected EOF"
Mar 3 22:35:52 <myDockerHost> matrix-postgres[2478754]: time="2020-03-03T22:35:52+01:00" level=error msg="error waiting for container: unexpected EOF"
Mar 3 22:35:52 <myDockerHost> matrix-mailer[2478764]: time="2020-03-03T22:35:52+01:00" level=error msg="error waiting for container: unexpected EOF"’
``

Could it be related to this library?
Thanks in advance and for any useful hints!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] docker SIGSEV by gorout..." ]
>Hi,
>
>Could it be related to this library?

maybe. Can you provide a test case without the docker code and only our code and reproduce
the crash?

pcap with dns data would be needed as well (or would make this easier)

**Comment by ralfi** [comment]
Hi miekg,
if you tell me how i will try it ...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] docker SIGSEV by go..." ]
>Hi miekg,
>if you tell me how i will try it ...

sorry, I can't make time for this. Looks docker problem to me, so they need to fix,
deep/dive it.

happy to jump in when we're doing something wrong

/close

**Comment by ralfi** [comment]
Thats right, its related to docker 19.03. debian packages, switching to docker-ce from docker repos solve this issue ...
