### ISSUE TITLE
Add  CHANGELOG file?

### ISSUE THREAD

**Issue by atc0005** [miekg/dns#1089]
Hi,

New user of the library (thanks!), just getting started and have already noticed multiple recent releases (healthy project!).

Would you consider adding a CHANGELOG?

https://keepachangelog.com/

The recent releases appear to be explained well by the commits on master (https://github.com/miekg/dns/commits/master), so while it is not necessary, adding a CHANGELOG file could make it easier to tell at a glance what new features/bugfixes are available in future releases.

**Comment by miekg** [comment]
Yes I've considered it and it's a lot of work and hard to automate... So
git log is your friend for now

**Comment by atc0005** [comment]
> Yes I've considered it and it's a lot of work and hard to automate... So git log is your friend for now

Fair enough. 

Thanks for providing this package. I'm new to Go, but the provided examples and other documentation were very helpful in getting me started.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Add  CHANGELOG file..." ]
>> Yes I've considered it and it's a lot of work and hard to automate... So git log is your friend for now
>
>Fair enough.
>
>Thanks for providing this package. I'm new to Go, but the provided examples and other documentation were very helpful in getting me started.

Thank you, that's good to hear :-)

/close
