### ISSUE TITLE
Is submitting multiple questions per message generally supported?

### ISSUE THREAD

**Issue by atc0005** [miekg/dns#1092]
Hi,

Newbie here, so apologies if the question completely misses the point or fails to take common DNS 101 concepts into account.

Short version: Is it supported to include multiple dns.Question{} entries on a message submitted to a DNS server in order to retrieve multiple record types in one go? For example, both `A` and `AAAA` records in one request?

If it is supported, is it common place or just on some servers?

I worked from this example I found in the docs:

```golang
m1 := new(dns.Msg)
m1.Id = dns.Id()
m1.RecursionDesired = true
m1.Question = make([]dns.Question, 1)
m1.Question[0] = dns.Question{"miek.nl.", dns.TypeMX, dns.ClassINET}
```

and modified it like so:

```golang

	fqdn := dns.Fqdn("www.yahoo.com")

	msg := new(dns.Msg)
	msg.Id = dns.Id()
	msg.RecursionDesired = true
	msg.Question = make([]dns.Question, 2)
	msg.Question[0] = dns.Question{
		Name:   fqdn,
		Qtype:  dns.TypeA,
		Qclass: dns.ClassINET,
	}
	msg.Question[1] = dns.Question{
		Name:   fqdn,
		Qtype:  dns.TypeAAAA,
		Qclass: dns.ClassINET,
	}
```

and then submitted the message to a DNS server (leaving out some code to shorten the example):

```golang
	in, err := dns.Exchange(msg, server+":53")
	fmt.Printf("response: %#v\n", in)
```

Google's 8.8.8.8 and 8.8.4.4 IPs returned an answer for the first question, but nothing for the second (as far as I can tell). Other servers I queried didn't give anything back (again, as far as I can tell). I'm too new to this package (and generally new to Golang) to really know what I'm doing, so I wanted to first start with the "is this supported" question before going too much further.

Thanks in advance for your help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Is submitting multiple ..." ]
>Hi,
>
>Newbie here, so apologies if the question completely misses the point or fails to take common DNS 101 concepts into account.
>
>Short version: Is it supported to include multiple dns.Question{} entries on a message submitted to a DNS server in order to retrieve multiple record types in one go? For example, both `A` and `AAAA` records in one request?

No, this is not supported. The original DNS RFCs allow this, but in practice it never
works. Most DNS server see multiple questions as an error.

**Comment by atc0005** [comment]
> @miekg: No, this is not supported. The original DNS RFCs allow this, but in practice it never
works. Most DNS server see multiple questions as an error.

Thanks for confirming, I appreciate your help!

**Comment by atc0005** [comment]
@miekg I forgot to ask: Do you have any interest in a PR which expands on the documentation comments here:

https://github.com/miekg/dns/blob/923fc6bc72a50be11293e1a5caa68d0752a4386e/types.go#L212-L218

Perhaps something like:

> Question holds a DNS question. Usually there is just one. While the original DNS RFCs allow multiple questions in the question section of a message, in practice it never works. Because most DNS servers see multiple questions as an error, it is recommended to only have one question per message.

**Comment by tmthrgd** [comment]
@atc0005 Feel free to open a PR with your suggested change.

**Comment by atc0005** [comment]
> @tmthrgd Feel free to open a PR with your suggested change.

Done, thanks!
