### ISSUE TITLE
Overflowing header size for some dkim requests.

### ISSUE THREAD

**Issue by semihalev** [miekg/dns#1100]
I updated latest v1.1.29 in my repo but I got some error messages about overflowing header size for some dkim requests. I can create simple test about that.

Here is the sample request:
```
dig txt strato-dkim-0002._domainkey.sharabati-denim.com @1.1.1.1

; <<>> DiG 9.10.6 <<>> txt strato-dkim-0002._domainkey.sharabati-denim.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35717
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;strato-dkim-0002._domainkey.sharabati-denim.com. IN TXT

;; ANSWER SECTION:
strato-dkim-0002._domainkey.sharabati-denim.com. 150 IN	TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt3a1nbhQdD0MtbPT1r8DGZefoQlj3fSgtWdINsXsRl55OmOAf2QNR8B0SwC59dWqA+isuH/bQnU0f0OmO5A7p+cyfT9EekbWslP575NAnAYpsUJlBv/0O8qA6T/cLoDz6LsUYv000gFRqSSUe1BZnJ/sjg0f96UCkomT1aQRpSUSDwNYCqpQKQ/fWg9IS2fL+" "d2kR1rckqwoKdgbEtjr4i+ICn2SUodI1KkGusIivuBueMYfDh8RGYKvFv40UZlBSfuX71GkzEPvQPnQTfXLqM9F8q1kWq/mdWYy5R0KrWptAnuAmCZqujkgWmcqzLoTMln04oOxGFp/zkf8iA75lwIDAQAB"

;; Query time: 421 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Apr 27 12:03:29 +03 2020
;; MSG SIZE  rcvd: 547
```

**Comment by miekg** [comment]
the first string part is 256 octets, probably off-by-one somewhere....

**Comment by miekg** [comment]
~~~ go
func TestParseTXTLimit(t *testing.T) {
	txt := `strato-dkim-0002._domainkey.sharabati-denim.com. 150 IN	TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt3a1nbhQdD0MtbPT1r8DGZefoQlj3fSgtWdINsXsRl55OmOAf2QNR8B0SwC59dWqA+isuH/bQnU0f0OmO5A7p+cyfT9EekbWslP575NAnAYpsUJlBv/0O8qA6T/cLoDz6LsUYv000gFRqSSUe1BZnJ/sjg0f96UCkomT1aQRpSUSDwNYCqpQKQ/fWg9IS2fL+" "d2kR1rckqwoKdgbEtjr4i+ICn2SUodI1KkGusIivuBueMYfDh8RGYKvFv40UZlBSfuX71GkzEPvQPnQTfXLqM9F8q1kWq/mdWYy5R0KrWptAnuAmCZqujkgWmcqzLoTMln04oOxGFp/zkf8iA75lwIDAQAB"`

	rr, err := NewRR(txt)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%s", rr)
}
~~~
parse it just fine

**Comment by semihalev** [comment]
I think here;

https://github.com/miekg/dns/blob/d128d10d176b810543f8fecd089082a29d3f159d/msg_helpers.go#L99

**Comment by semihalev** [comment]
```go
func Test_Overflow(t *testing.T) {
	req := new(dns.Msg)
	req.SetQuestion("strato-dkim-0002._domainkey.sharabati-denim.com.", dns.TypeTXT)
	req.SetEdns0(1400, true)
	req.RecursionDesired = true

	resp, err := dns.Exchange(req, "ns3.stratoserver.net:53")

	if err != nil {
		t.Fatal(err)
	}
	t.Logf("%s", resp)
}
```
produced the error

**Comment by semihalev** [comment]
Okey I understand. Their UDP message size is 512 and The message cannot be fit in that. Message size 547 on TCP. The server should return truncate tag on UDP instead answer. I don't know, how can we handle that. 

Can we add truncate tag instead error?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Overflowing header ..." ]
>Okey I understand. Their UDP message size is 512 and The message cannot be fit
>in that. Message size 547 on TCP. The server should return truncate tag on UDP
>instead answer. I don't know, how can we handle that.
>
>Can we add truncate tag instead error?

msg.Truncated is true in that case; we stopped erroring on that, because everything is WAI

**Comment by semihalev** [comment]
I played on dig, dig try with TCP in that case.

**Comment by semihalev** [comment]
I'm working on a PR. I think, we can return a new type error like `OverflowError` instead `Error`. Application side can understand overflow errors easily. if you good about that, i'll prepare a PR about this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Overflowing header ..." ]
>I'm working on a PR. I think, we can return a new type error like OverflowError
>instead Error. Application side can understand overflow errors easily. if you
>good about that, i'll prepare a PR about this.

I don't think that's a good idea, TC is not an error in the typical sense. Checking Tc bit
is enough for the client.

**Comment by semihalev** [comment]
I closed PR, I think this is currently unimportant.
