### ISSUE TITLE
PackRR: nsec bits out of order

### ISSUE THREAD

**Issue by lanrat** [miekg/dns#1106]
When calling `dns.PackRR` with a record returned by the `ZoneParser`, the following error is given `dns: nsec bits out of order`

This error appears to be thrown on every zone from [ICANN's CZDS](https://czds.icann.org/) service.

Below is an example record/program that demonstrates this behavior.
```golang
package main

import (
	"encoding/hex"
	"log"

	"github.com/miekg/dns"
)

var rrString = "8T6HBIPGHL7M581KEH1R8FQ04SVR2HB7.AAA.     60      IN      NSEC3   1 1 1 DA7F7354 ohv3tq940bmdot5iercl0taegd513i1p DNSKEY NS NSEC3PARAM RRSIG SOA"

func main() {
	rr, err := dns.NewRR(rrString)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Got RR1: %s", rr.String())
	rrBytes := make([]byte, dns.MaxMsgSize)
	len, err := dns.PackRR(rr, rrBytes, 0, nil, false)
	if err != nil { // err: dns: nsec bits out of order
		log.Fatal(err)
	}
	rrBytes = rrBytes[:len]
	log.Printf("Converted to bytes: %s", hex.EncodeToString(rrBytes))
	rr2, _, err := dns.UnpackRR(rrBytes, 0)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Got RR2: %s", rr2.String())
}
```

**Comment by miekg** [comment]
the types in this nsec3 are not in the correct order. Erroring is the correct things to do here.

**Comment by lanrat** [comment]
> the types in this nsec3 are not in the correct order. Erroring is the correct things to do here.

If that is the case then the error should be thrown on `dns.NewRR` and not `dns.PackRR`.

However, now that 100% of the zones from the CZDS service contain records like this, I would like strongly suggest considering my fix in #1109.

**Comment by miekg** [comment]
CZDS seems full of brokeness. We will not repeat past mistakes of accepting broken data.

The zone parser operates (mostly) on garbage in, garbage out

**Comment by miekg** [comment]
CZDS seems full of brokeness. We will not repeat past mistakes of accepting broken data.

The zone parser operates (mostly) on garbage in, garbage out

**Comment by lanrat** [comment]
Another problem here is that it is possible to manually create or modify the `NSEC3.TypeBitMap` variable, which this library explicitly allows by making the `TypeBitMap` type public. But without sorting before packing, the library will error.

If it is the user's responsibility to sort `TypeBitMap` whenever working with these types the documentation should be updated to say so.

**Comment by tmthrgd** [comment]
@lanrat I don't think it's appropriate to sort automatically in this case, but if you want to open a PR to document that they need to be ordered I don't see any harm in that.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] PackRR: nsec bits o..." ]
>@lanrat I don't think it's appropriate to sort automatically in this case, but
>if you want to open a PR to document that they need to be ordered I don't see
>any harm in that.

I must admit I can't find this requirement in either RFC 2535 nor 4034, nor 5155, which either means
it's assumed to be sorted (because that how they end up on the wire) or you're allowed to
put them in any order in the presentation format.

Probably warrants an email to dnsop@

**Comment by lanrat** [comment]
Are there any updates on this?

Thanks.

**Comment by miekg** [comment]
I haven't sent an email, or maybe I did, can't remember.

This lib is not checking in any case; https://github.com/miekg/dns/pull/1245
