### ISSUE TITLE
Challenge

### ISSUE THREAD

**Issue by semihalev** [miekg/dns#1113]
Yesterday night I found a crazy problem. I investigated that and I didn't find any solution about that. 

Here the problem details;

I'm trying resolve a domain from own authoritative server but I received timeout. I wrote small test and same result. I tested with dig, same timeout. I tested both _udp_ and _tcp_ and same timeout. I tested on darwin and linux same timeout. I started powerdns-recursor on my machine and interestingly answered from same authoritative server. I watched tcpdump, i'm sure powerdns used same authoritative server. The other public resolvers (1.1.1.1, 8.8.8.8, 9.9.9.9) also answer correctly. I didn't understand anything about that. I wrote another test with Golang built-in resolver. I got timeout again. Another interesting result is, I received answers correctly for A, NS, MX, from main domain. I watched tcpdump for powerdns while sending and receiving queries. I sent same query and same bytes with this test.

This is small challenge, if anyone here for any comment, I will be happy. 

You can see, you will receive answer from `A usaid.gov` `MX usaid.gov` and many others.

The test;
```go
func TestUsaid(t *testing.T) {
	req := new(dns.Msg)
	req.SetQuestion("www.usaid.gov.", dns.TypeA)
	req.SetEdns0(1400, true)
	req.RecursionDesired = true

	resp, err := dns.Exchange(req, "12.96.42.221:53")
	if err != nil {
		t.Fatalf("%v", err)
	}

	t.Logf("%v", resp)
}
```

**Comment by miekg** [comment]
dns can be weird, this can be anything.

Note sure anyone here as the time to look into this.

tentatively closing as it has nothing to do with the library code

/close
