### ISSUE TITLE
dns.IsFqdn() sometimes returns false for valid unicode fully qualified domains

### ISSUE THREAD

**Issue by lanrat** [miekg/dns#1124]
The `dns.IsFqdn()` function checks that the provided domain ends with a '.' and has an even number of escape sequences in [defailts.go](https://github.com/miekg/dns/blob/master/defaults.go#L269). However if the input string is unicode (the default in go), then there could be an off-by-one error causing the `IsFqdn()` function to return false when it should not.

For example, the domain `коммерция-спб.рф.` is fully qualified, but `IsFqdn()` returns false because the last non '.' code point is 2 bytes wide.

It appears that the problem is because `strings.LastIndexFunc()` returns the index of the byte into the string, and not the rune offset. This can be fixed by making the escape sequence detection rune aware instead of using the byte offset.

Below is a very simple test to demonstrate the failure:
```golang
func TestFqdn(t *testing.T) {
	d := "коммерция-спб.рф."
	if !IsFqdn(d) {
		t.Fatalf("%s not fqdn", d)
	}
}
```

I am aware that the domains should be converted to punycode using the `golang.org/x/net/idna` package, but many higher level functions inside this package rely on `IsFqdn()` which sometimes gets called before there is a chance to convert to punycode. Additionally `IsFqdn()` works correctly on most all other unicode domains, only erroring on a few that have a wider code point before their ending '.'

@tmthrgd you submitted the CL adding this check and tests for this case in #896 so I'd like to hear your thoughts on this.

Thanks.

**Comment by lanrat** [comment]
Looks like this could be a 1 line fix by changing the `IsFqdn()` return statement from:
```golang
return (len(s2)-i)%2 != 0
```
to
```golang
return (len([]rune(s2))-len([]rune(s2[:i])))%2 != 0
```
making it rune aware.

`len([]rune(string)` is optimized by the go compiler and should not have any performance impact. source: https://github.com/golang/go/issues/24923

**Comment by lanrat** [comment]
If it is acceptable to make `IsFqdn()` rune aware then the for loop in `IsDomainName()` should be changed to `for i, char := range s` instead of `i := 0; i < len(s); i++` making it rune aware as well.

I can submit a PR if this is an acceptable solution.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] dns.IsFqdn() sometimes ..." ]
>For example, the domain коммерция-спб.рф. is fully qualified, but IsFqdn()
>returns false because the last non '.' code point is 2 bytes wide.

encoding domain as strings is, if you're very pedantic, the wrong encoding because it's
UTF-8 and not ASCII. The protocol itself ossified into ascii, so making this "see" other
dots as ASCII dots is not the right thing to do. This is also why the whole puny code was
needed in the first place.

/close

**Comment by lanrat** [comment]
The actual issue here is not because it is "seeing" other dots as ASCII dots, but because the function assumes that each character is exactly 1 byte.

If you don't want to support non-ASCII inputs (garbage in, garbage out) that's fine. I just want to be clear on the reason.

**Comment by tmthrgd** [comment]
I'm pretty sure the intention is to only work on ASCII/punycode domain names, so while the fix isn't all that hard it does commit to something that I don't think is intentional behaviour. It's definitely underdocumented though, which probably should be fixed.
