### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by MilindPurswani** [miekg/dns#1126]
Hi, 

I am currently facing this error 

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
	/path/to/script/main.go:43 +0x62c

```

Here is the relevant code:

```go
m.SetQuestion(dns.Fqdn("20.api.playstation.com"), dns.TypeCNAME)
m.RecursionDesired = true
r, _, err2 := c.Exchange(m, "8.8.8.8:53")
if r, ok := r.Answer[0].(*dns.CNAME); ok {  //line 43
    fmt.Println("No Problem")
    fmt.Println(r.Target)
}
```

When I try to print the entire result, this is the answer:

```
;; opcode: QUERY, status: NXDOMAIN, id: 40905
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;20.api.playstation.com.	IN	 CNAME

;; AUTHORITY SECTION:
api.playstation.com.	300	IN	SOA	dns1.p05.nsone.net. unixadmin.sonynei.net. 2020060108 28800 14400 2419200 86400

```

Naturally, since the CNAME is empty, I assume this could be related to it.

Can you please look help me out here? I can't check if `== nil` or compare with `len()` since this is of the type dns.RR and can't be converted to string. Also, `== ""` fails too. How do we handle these errors?

Thanks,

**Comment by aaranmcguire** [comment]
Hi MilindPurswani,

It seems like this query returns no answers. You should check the length of `r.Answer`, or use it in a for loop to get multiple answers.

Hope that helps.

**Comment by MilindPurswani** [comment]
Thanks,

That solved it 👍
