### ISSUE TITLE
Invalid parsing of LOC records

### ISSUE THREAD

**Issue by Fluepke** [miekg/dns#1131]
Hey,

[RFC1876](https://tools.ietf.org/html/rfc1876#section-2) defines an "8-bit _float_" to use for the fields `SIZE`, `HORIZ PRE` and `VERT PRE`.

Parsing of these values is implemented in [stringToCm](https://github.com/miekg/dns/blob/master/scan.go#L1201), which is (unfortunately) flawed:

| Input | Expected (mantissa, exponent) | Got (mantissa, exponent) |
|:-----:|:-----------------------------:|:------------------------:|
|  0.1m |              1, 1             |           1, 0           |
|  10m  |              1, 3             |           A, 2           |
|  0.3m |              3, 1             |           3, 0           |

Will submit a PR to fix this

**Comment by miekg** [comment]
this is waiting for the PR to be updated with some comments

**Comment by Fluepke** [comment]
This was closed by https://github.com/miekg/dns/commit/da812eed45cba1ce4c978e746039483064b8f92d
