### ISSUE TITLE
write operation not permitted  

### ISSUE THREAD

**Issue by caleb-letsgo** [miekg/dns#1137]
Error on Android device：write udp 192.168.1.39:40200->192.168.1.1:53: write: operation not permitted

Here is the code snippet：
var conn net.Conn
if conn, err = d.dialer.Dial("udp", server); err != nil {
	log.Error(err)
	return
}
defer conn.Close()

var rtt time.Duration
r, rtt, err = d.localDnsClient.ExchangeWithConn(msg, &dns.Conn{Conn: conn})

**Comment by semihalev** [comment]
This is OS limitation problem. You should check your Android device network permissions.
