### ISSUE TITLE
Pass variables to handler

### ISSUE THREAD

**Issue by ArturSS7** [miekg/dns#1144]
Hello. Is there any way to pass a database pointer to dns handler, so it would look something like this
`udpHandler := dns.NewServeMux()`
`udpHandler.HandleFunc(".", HandlerUDP(db))`
And handler function will look like this
`func HandlerUDP(w dns.ResponseWriter, req *dns.Msg, db *sql.DB)`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Pass variables to handl..." ]
>Hello. Is there any way to pass a database pointer to dns handler, so it would
>look something like this
>udpHandler := dns.NewServeMux()
>udpHandler.HandleFunc(".", HandlerUDP(db))
>And handler function will look like this
>func HandlerUDP(w dns.ResponseWriter, req *dns.Msg, db *sql.DB)

use a closure over your handler function is one way
