### ISSUE TITLE
A DNS request that matches no handler should be answered with RcodeRefused

### ISSUE THREAD

**Issue by ghost** [miekg/dns#1146]
In serve_mux.go, `ServeDNS` currently uses `HandleFailed` when no matching handler is found. Instead, I believe the query should be answered with `RcodeRefused`.

I don't believe there is an RFC that outright mandates this, but I do believe it is the general consensus to refuse a query for an unknown domain to an authoritative server.

It will at least help distinguish between actual server failures and just a request for an unknown domain when writing DNS servers using this library :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] A DNS request that matc..." ]
>In serve_mux.go, ServeDNS currently uses HandleFailed when no matching handler
>is found. Instead, I believe the query should be answered with RcodeRefused.
>
>I don't believe there is an RFC that outright mandates this, but I do believe
>it is the general consensus to refuse a query for an unknown domain to an
>authoritative server.
>
>It will at least help distinguish between actual server failures and just a
>request for an unknown domain when writing DNS servers using this library :)

fair point


/label bug

**Comment by miekg** [comment]
care to provide a PR?

**Comment by brian5hea** [comment]
> care to provide a PR?

of course. https://github.com/miekg/dns/pull/1151

**Comment by miekg** [comment]
is merged
