### ISSUE TITLE
Spurious "id mismatch" errors when making high volume of requests

### ISSUE THREAD

**Issue by AGWA** [miekg/dns#1156]
When making a high volume of requests (~250 / second) to the same server, `Exchange` begins returning "id mismatch" (`ErrId`) errors some of the time.  I verified with packet captures that the server was returning replies with the correct ID, indicating a bug in this library.  Let's Encrypt, another high volume user of this library, has also experienced peculiar "id mismatch" errors: https://github.com/letsencrypt/boulder/issues/4532

Upon further investigation, I determined that the following sequence of events triggers the spurious errors:

1. At time 0, we send a query with ID X from port P.

2. At time T, we time out the query due to lack of response, and then send a different query with ID Y. By coincidence, the new query is sent from the same port number P (since port numbers are only 16 bits, this can happen with non-negligible probability when making queries at a high rate).

3. At time T+epsilon, we receive a response to the original query. Since the ID in this response is X, not Y, `exchange` returns `ErrId`, preventing the second query from succeeding.

PR #1155 fixes the problem by ignoring replies with invalid IDs, since such replies are clearly not associated with the request.  However, the PR was rejected so I am opening this issue for discussion.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Spurious "id mismatch" ..." ]
>When making a high volume of requests (~250 / second) to the same server,
>Exchange begins returning "id mismatch" (ErrId) errors some of the time. I
>verified with packet captures that the server was returning replies with the
>correct ID, indicating a bug in this library. Let's Encrypt, another high
>volume user of this library, has also experienced peculiar "id mismatch"
>errors: letsencrypt/boulder#4532
>
>Upon further investigation, I determined that the following sequence of events
>triggers the spurious errors:
>
> 1. At time 0, we send a query with ID X from port P.
>
> 2. At time T, we time out the query due to lack of response, and then send a
>    different query with ID Y. By coincidence, the new query is sent from the
>    same port number P (since port numbers are only 16 bits, this can happen
>    with non-negligible probability when making queries at a high rate).
>
> 3. At time T+epsilon, we receive a response to the original query. Since the
>    ID in this response is X, not Y, exchange returns ErrId, preventing the
>    second query from succeeding.
>
>PR #1155 fixes the problem by ignoring replies with invalid IDs, since such
>replies are clearly not associated with the request. However, the PR was
>rejected so I am opening this issue for discussion.

I haven't see these words used in that PR

**Comment by AGWA** [comment]
Hi, thanks for looking at this.

The timeout occurs because I'm using `ExchangeContext` with a deadline, and the server doesn't reply to the query in time.  This is working as expected.

The PR doesn't wait indefinitely for a reply - when the deadline expires, `ReadMsg` will return with an error and this will break the loop.

**Comment by miekg** [comment]
Ack. That's true, it will timeout.

But I'm confused on the context use. I think even without one this will
still happen when the port gets re-used. I wonder about the frequency of
that though (and if this should be fixed).

**Comment by tmthrgd** [comment]
I agree that this is a problem and probably `ErrId` shouldn't have been included at all. I can't find many uses of `ErrId` in the wild, two uses of it in a retry loop are [here](https://github.com/shuque/scantlsa/blob/9a3f63274a261e24086529a4ef7ab91b4526e2e2/main.go#L188) and [here](https://github.com/shuque/getdns/blob/6995075842c48a8f87080c029cc9f608b89646f0/main.go#L85). Other than those two, there is the logging in letsencrypt/boulder which is for debugging this very issue and a few cases of people returning it in their own exchange functions or proxies.

It would probably be pretty safe to resurrect #1155 and deprecate the error. Alternatively, I do have an idea how we can handle this more gracefully without breaking anyone<sup>†</sup>. What we could do is record when a mismatched message ID is detected, but only return that error if the query fails or times-out before the correct response is received. That would end up looking something like this:
```go
...
var idErr error
for {
	r, err = co.ReadMsg()
	if err != nil || r.Id == m.Id {
		break
	}
	if err == nil && r.Id != m.Id {
		idErr = ErrId
	}
}
if r == nil && idErr != nil {
	return nil, 0, idErr
}
return r, ..., err
```

That might be too subtle and fragile though. I do #1155 should be safe and I can't see any public code that should break (even the two retry loops should continue to work pretty much the same).

This is the GitHub search query I used if anyone wants to see what uses are out there: `"dns.ErrId" -path:/vendor/ language:Go`.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Spurious "id mismat..." ]
>I agree that this is a problem and probably ErrId shouldn't have been included
>at all. I can't find many uses of ErrId in the wild, two uses of it in a retry
>loop are here and here. Other than those two, there is the logging in
>letsencrypt/boulder which is for debugging this very issue and a few cases of
>people returning it in their own exchange functions or proxies.
>
>It would probably be pretty safe to resurrect #1155 and deprecate the error.

Ok, let's do that then.

We _might_ leave ErrId as an indentifier? (Not sure if that helps, or makes things worse)

/Miek

--
Miek Gieben

**Comment by tmthrgd** [comment]
Thinking about it, while `ErrId` doesn’t make sense for UDP connections, where we see this issue, it potentially does make sense for TCP connections. They can’t be impacted by stray responses only be legitimate failures. That’s actually the behaviour of the stdlib `net` package’s DNS client: https://golang.org/src/net/dnsclient_unix.go.

I’m going to suggest that tweak over on the PR.
