### ISSUE TITLE
How to Exchange with a DNS server which has ipv6 address?

### ISSUE THREAD

**Issue by whenyd** [miekg/dns#1157]
I have a dns server with  ipv6, how to update a new RR.

what address arg should passed to `c.Exchange`?

The `[ipv6]:53` is wrong, and `ipv6:53` return an error `too many colons in address`.

😭 😭 😭

**Comment by tmthrgd** [comment]
Per the docs for `Dial` in `net`:
> If the host is a literal IPv6 address it must be enclosed in square brackets, as in "[2001:db8::1]:80" or "[fe80::1%zone]:80". The zone specifies the scope of the literal IPv6 address as defined in RFC 4007. The functions JoinHostPort and SplitHostPort manipulate a pair of host and port in this form.

**Comment by whenyd** [comment]
The form "[2001:db8::1]:80" and "[fe80::1%zone]:80" are tried at the beginning, but they are not work, error is `connect: A socket operation was attempted to an unreachable network`.

I doubt that if the function `client.Exchange()` could accept an ipv6 address?
