### ISSUE TITLE
If the function client.Exchange() could accept an ipv6 address?

### ISSUE THREAD

**Issue by whenyd** [miekg/dns#1158]
As I mentioned in the issue #1157 , the form "[2001:db8::1]:80" and "[fe80::1%zone]:80" are tried at the beginning, but they are not work, the error is: `dial udp [ipv6]:53: connect: A socket operation was attempted to an unreachable network`. If without square brackets, error is `too many colons in address`. The `ipv6` is my dns server.

So now, I doubt that if the function client.Exchange(msg, address) could accept an ipv6 address.
Or there is another way of exchanging with an ipv6 server, could you show me that?

**Comment by semihalev** [comment]
You are tried to connect unreachable network. `Exchange` function accept ipv6 addresses.

**Comment by tmthrgd** [comment]
This is either a problem with your network or the host you're trying to connect to. This library already supports IPv6 in the forms I mentioned without issue. I'd suggest making sure you have a working IPv6 stack and a working IPv6 internet connection.

This is outside the scope of this library and I'm afraid no one here will be able to help you. Try asking on StackExchange/StackOverflow if you can't make it work.

**Comment by whenyd** [comment]
but it is ok to ping6 to dns server at host

**Comment by whenyd** [comment]
It is ok to ping6 to dns server at host, so I don't know why.

**Comment by tmthrgd** [comment]
@whenyd That sounds like some sort of firewall issue then. Ping sends an ICMP packet which is not the same as a UDP packet to a specific port. Like I said, you'll find more help from StackExchange or StackOverflow.

**Comment by whenyd** [comment]
@tmthrgd OK, thanks.
