### ISSUE TITLE
How to use Windows default nameservers?

### ISSUE THREAD

**Issue by coolaj86** [miekg/dns#1159]
Does this library supply a way to set the resolver to the default Windows resolver?

Since https://github.com/go-acme/lego/issues/1015 uses this dns package rather than the system package (and I completely understand why), it is blocked in Windows environments where the system resolver must be used (i.e. outbound 53 is blocked).

I see that there's a utility for fetching Unix resolvers, but I'm not seeing a function for Windows so far.

**Comment by miekg** [comment]
no such code exists in this lib

**Comment by AkihiroSuda** [comment]
os/exec-ing `powershell.exe -NoProfile -NonInteractive "Get-DnsClientServerAddress -AddressFamily IPv4  | Select-Object -ExpandProperty ServerAddresses"` may work
