### ISSUE TITLE
Question: SetReply while recursing

### ISSUE THREAD

**Issue by ahmetb** [miekg/dns#1167]
Sorry for this question, as I am aware that this library is meant to be used by low-level DNS implementations and the programmer must know what they're doing.

In my little toy DNS server implementation I am registering root zone `.` to a HandlerFunc whose responsibility is solely to recurse into the original nameserver (say, GCE DNS).

In a nutshell my code does this:

```go
func (d *dnsHijack) recurse(w dns.ResponseWriter, msg *dns.Msg) {
	r, err := dns.Exchange(msg, net.JoinHostPort(d.nameserver, "53"))
	if err != nil {
		servfail(w, msg)
		return
	}
	r.SetReply(msg)
	w.WriteMsg(r)
}
```

In this case, this actually works when there is an ANSWER section returned. However, if the ANSWER section is missing, it returns `status: NOERROR` even though the queried nameserver is returning `NXDOMAIN`. (In both cases, ADDITIONAL section is missing, if any).

However, if I comment out the `r.SetReply(msg)` statement, it works as expected. 

What’s the reason this might be the case? Isn’t SetReply used to indicate "this is the reply to this message" in this case? Am I holding it wrong? TIA.

-------

## Appendix

With SetReply+WriteMsg:

```
$ dig +search A x.example.com
; <<>> DiG 9.16.6 <<>> +search A x.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49151
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;x.example.com.			IN	A

;; AUTHORITY SECTION:
example.com.		1799	IN	SOA	ns.icann.org. noc.dns.icann.org. 2020091009 7200 3600 1209600 3600

;; Query time: 34 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 07 17:57:45 UTC 2020
;; MSG SIZE  rcvd: 107
```

Without SetReply:

```
$ dig +search A xyz.example.com
; <<>> DiG 9.16.6 <<>> +search A xyz.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43282
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;xyz.example.com.		IN	A

;; AUTHORITY SECTION:
example.com.		1270	IN	SOA	ns.icann.org. noc.dns.icann.org. 2020091009 7200 3600 1209600 0

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 07 17:58:18 UTC 2020
;; MSG SIZE  rcvd: 109
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Question: SetReply whil..." ]
>In this case, this actually works when there is an ANSWER section returned.
>However, if the ANSWER section is missing, it returns status: NOERROR even
>though the queried nameserver is returning NXDOMAIN. (In both cases, ADDITIONAL
>section is missing, if any).

SetReply doesn't copy the rcode and defaults to NOERROR:
(can't remember the rational, seems odd now)

https://github.com/miekg/dns/blob/master/defaults.go#L23

>
/Miek

--
Miek Gieben
