### ISSUE TITLE
Allow any net.PacketConn and don't assume it is *net.UDPConn

### ISSUE THREAD

**Issue by guillaumerose** [miekg/dns#1168]
When using this project in combination of a userland tcpip stack, we don't have a *net.UDPConn but a custom net.PacketConn. It would be great to be able to start the DNS server.

The use case will be to add a built-in DNS server in https://github.com/majek/slirpnetstack/ or in https://github.com/code-ready/gvisor-tap-vsock

Links:
tcpip stack: https://github.com/google/gvisor/tree/master/pkg/tcpip
adapter for the stack and go net interfaces: https://github.com/google/gvisor/blob/master/pkg/tcpip/adapters/gonet/gonet.go#L570
Current patch I use: https://github.com/guillaumerose/dns-1/commit/fe9b991fbece42eb3ef3a118dc043aecf1f48d1c

**Comment by tmthrgd** [comment]
I’m not sure how this can work in a backwards compatible way. `*net.UDPConn` is in some exported interfaces and is required for OOB data that helps properly route packets to the correct network interfaces.

Any proposal would have to be backward compatible and preserve that special case(?). Feel free to try and come up with something, you could conceivably add a `ReadPacketConn` as an optional method on the reader type.
