### ISSUE TITLE
Does it support mDNS functions? (That can be used for service discovery, for example.)

### ISSUE THREAD

**Issue by MaoJianwei** [miekg/dns#1179]
Hi friends,

I like that principle, "Less is more.".

I'm insterested in that questions:
1. Does it support mDNS functions? (That can be used for service discovery, for example.)
2. Is it just a protocol lib, which only defines DNS message formats, without DNS interaction workflows?

Thanks,
Mao

**Comment by miekg** [comment]
See https://github.com/miekg/dns/issues/423 and https://github.com/miekg/dns/issues/436

The lib has evolved since then, i.e. `ErrTruncated` is gone. In general you'll have to use
your own function to listen for message (due to multicase), but mdns is just dns so the
parsing function should work

**Comment by MaoJianwei** [comment]
Thanks miekg, great lib!

Mao
