### ISSUE TITLE
Does dns.Client or dns.Dialer support multicast DNS with IPv6? 

### ISSUE THREAD

**Issue by MaoJianwei** [miekg/dns#1180]
Hi,

When I do _r, rtt, err := c.Exchange(m, nameserverV6)_ for mDNS with IPv6, it reports:
**;; dial udp6 [ff02::fb]:5353: connect: invalid argument**

Does dns.Client or dns.Dialer support multicast DNS with IPv6? 

By the way, mDNS for IPv4 (224.0.0.251:5353) is normal.

Thanks,
Mao

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Does dns.Client or dns...." ]
>Hi,
>
>When I do r, rtt, err := c.Exchange(m, nameserverV6) for mDNS with IPv6, it
>reports:
>;; dial udp6 [ff02::fb]:5353: connect: invalid argument
>
>Does dns.Client or dns.Dialer support multicast DNS with IPv6?
>
>By the way, mDNS for IPv4 (224.0.0.251:5353) is normal.

dunno, we just call the underlaying net.Dial functions, no magic from our side.
