### ISSUE TITLE
Obtaining HTTPS `SVCBKeyValue` value wire format encoding

### ISSUE THREAD

**Issue by chris-wood** [miekg/dns#1183]
The `SVCBKeyValue` only publicly exports these functions:

```
type SVCBKeyValue interface {
	Key() SVCBKey          // Key returns the numerical key code.
	String() string        // String returns the string representation of the value.
}
```

The `String()` function returns the presentation format for the value, which is useful for debugging purposes. However, many use cases require the wire format encoding of the value, which does not match that of the presentation format. Unless there's some other preferred way of getting this data, could we add a new function to this interface that returns the wire format? Perhaps:

```
type SVCBKeyValue interface {
   Raw() []byte // Wire format representation of the value
}
```

**Comment by miekg** [comment]
No. Any data from the wire is converted into "normal" values (string, int,
net.Addr, etc.). If SVC needs something else the implementation is wrong.

**Comment by chris-wood** [comment]
> No. Any data from the wire is converted into "normal" values (string, int,net.Addr, etc.). If SVC needs something else the implementation is wrong.

Sorry, can you elaborate? As a concrete example, users of the `SVCBECHConfig` parameter need the internal `ECH []byte` value, in wire format. How is a user of this library supposed to get that value now?

**Comment by tmthrgd** [comment]
@chris-wood Is the `ECH` field of `SVCBECHConfig` not already in wire format? The `pack` and `unpack` methods don't do anything but copy.

**Comment by chris-wood** [comment]
> @chris-wood Is the ECH field of SVCBECHConfig not already in wire format? The pack and unpack methods don't do anything but copy.

It is, yeah. I guess what’s not clear to me is the idiomatic way to get a SVCBECHConfig from a SVCBKeyValue. I assume I’m just being slow and this isn’t actually a problem with the API, so hopefully some clarification will resolve this!

**Comment by tmthrgd** [comment]
@chris-wood No worries happy to clarify. All you need to do is a type assertion:
```go
var kv SVCBKeyValue
ech, ok := kv.(*SVCBECHConfig)
```

Alternatively you may want to use a type switch:
```go
var kv SVCBKeyValue
switch kv := kv.(type) {
case *SVCBECHConfig:
	// use kv *SVCBECHConfig here
case ...:
	...
}
```

Then you can get at the ECH field and use it however you need.

I'll close this now as I believe that should solve your problem.

**Comment by chris-wood** [comment]
Yep — thanks!
