### ISSUE TITLE
Cannot access from outside localhost

### ISSUE THREAD

**Issue by bitbreakr** [miekg/dns#1191]
Hello,

I am currently making a project using this library.
The issue that is have is that i cannot access my launched go build from outside localhost, like from a vps.

I have tried the following, but nothing works:

`&dns.Server{Addr: "0.0.0.0:" + strconv.Itoa(service.Port), Net: "udp"}`
`&dns.Server{Addr: ":" + strconv.Itoa(service.Port), Net: "udp"}`

Do you guys know why ?

Thanks in advance

**Comment by tmthrgd** [comment]
Either form will work fine. This is almost certainly a firewall issue. Make sure you’ve opened the port you’re using.
