### ISSUE TITLE
I need a pointer

### ISSUE THREAD

**Issue by D-sense** [miekg/dns#1197]
Hi.
Please can anyone point me to some examples of how to use this package?

Basically, what I need is a way of querying a domain name in order to get its DNS records, Authoritative server, route53/cloudDNS. 
Thanks

**Comment by kokjason** [comment]
https://github.com/miekg/exdns

**Comment by D-sense** [comment]
@kokjason, thank you.

I seem to be getting everything working except two things:
(1) I get a "dns: domain must be fully qualified" error when trying to querying PTR:

`r.Message.SetQuestion("157.240.29.35", dns.TypePTR)
	res, _, err := r.Client.Exchange(r.Message, net.JoinHostPort(server, port))
	if err != nil {
		return nil, err
	}
` 

(2) Also, please how can I manage timeout? (this happens sometimes).

**Comment by kokjason** [comment]
@D-sense 

(1) Did you loss port?
"157.240.29.35"+":53"
sorry, I'm not sure that.

(2) Yes, it happens sometimes. But I also donot know how to manage.

**Comment by D-sense** [comment]
Thank you.

**Comment by gibson042** [comment]
@D-sense reverse-lookup PTR records for IPv4 address 157.240.29.35, if they exist, would be stored at 35.29.240.157.in-addr.arpa. You need to split the address into four octets, join their decimal representations in reverse order as DNS labels, and suffix with in-addr.arpa (cf. https://tools.ietf.org/html/rfc1035#section-3.5 ).

**Comment by D-sense** [comment]
@gibson042 , thank you!
