### ISSUE TITLE
TLS connections send packet length & packet data seperately

### ISSUE THREAD

**Issue by mzealey** [miekg/dns#1199]
I think for some reason the tls library is not honouring the `net.Buffers` code here https://github.com/miekg/dns/blob/428cef31872d7aee10c55a9450929bc9b645b292/client.go#L336 ?

When dumping + decrypting with wireshark, a normal TCP connection is doing single-packet based queries, however TLS is always sending 2 packets per query (& for response when upstream is running this library too). Here is a screenshot from wireshark:

![image](https://user-images.githubusercontent.com/6083471/101497074-9ea05380-397b-11eb-9263-821f0f86cf0b.png)

**Comment by mzealey** [comment]
Same issue at https://github.com/miekg/dns/blob/master/server.go#L758 on server side of things

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] TLS connections sen..." ]
>Same issue at https://github.com/miekg/dns/blob/master/server.go#L758 on server
>side of things

is this bad? Happy to take a PR that helps fix this.
