### ISSUE TITLE
Data function for RR

### ISSUE THREAD

**Issue by Kloenk** [miekg/dns#1204]
Currently the RR interface only has a String() function which also prints the Header. IMHO there should also be a function which prints only the Data as string, without the header informations.

**Comment by miekg** [comment]
Every RR has public struct members that allow you to extract this information with the correct types. If you only care about the rdata a strings you can just convert to string and index that at the correct position.

**Comment by Kloenk** [comment]
I found the type, but then I have to create a switch case for every possible type.
Npt sure what you mean with index at the correct position, how would I get this index?

**Comment by aaranmcguire** [comment]
I do like the idea of this PR as it would clean up some of my logic, but if we don't want to do this, the easy way of just getting the data is:

```
strings.Replace(rr.String(), rr.Header().String(), "", 1)
```

Works for all types, so no need to make a switch case.

**Comment by miekg** [comment]
Yes you either need to type switch or do what Aaran says. There is no need
to add this code to the lib, easy to do outside of it.

/close
