### ISSUE TITLE
Would you please upgrade the dependency golang.org/x/sys to the latest version ? :-P

### ISSUE THREAD

**Issue by jemygraw** [miekg/dns#1210]
We have a project that depends on miekg/dns package and it is great in most cases.
But we have a corner case to compile the project under windows and meets an error like this.
```
../../../../../../pkg/mod/github.com/!microsoft/go-winio@v0.4.11/privilege.go:129:7: assignment mismatch: 2 variables but "golang.org/x/sys/windows".GetCurrentProcess returns 1 values
```
After some investigation, we found that `miekg/dns` rely on a version of golang.org/x/sys that may break the compile.
So it is very appreciated that you can upgrade the dependency of golang.org/x/sys to the latest version.

**Comment by tmthrgd** [comment]
I don't believe we use that method or library here at all so this isn't a bug here. You can update indirect dependencies as you would regular dependencies. `go get golang.org/x/sys@latest` or similar should work.

It's still my understanding that in the go modules world, dependencies shouldn't in general update their dependencies to fix other code. It causes churn for other importers for instance and puts extra work on libraries like this one.

I'm going to close this, but feel free to reopen if you disagree or can't make that work.
