### ISSUE TITLE
A slim version of miekg/dns is available to everyone who want to build a DNS forwarder/stub/analyzer

### ISSUE THREAD

**Issue by AZ-X** [miekg/dns#1213]
It could save 300kb+of binary size approximately comparing to miekg/dns@v1.1.37. 
[visit pkg.go.dev for details](https://pkg.go.dev/github.com/AZ-X/dns)
[or visit github repository](https://github.com/AZ-X/dns)
[repique `demonstrates`  the usage of it.](https://github.com/AZ-X/pique)
@miekg
I would like to help if you want me to maintain this slimmed version as a branch inside this repository.
Welcome any PR to slimmer's repository about security or features.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] A slim version of miekg..." ]
>It could save 300kb+of binary size approximately comparing to miekg/
>dns@v1.1.37.
>visit pkg.go.dev for details
>or visit github repository
>repique demonstrates the usage of it.
>@miekg
>I would like to help if you want me to maintain this slimmed version as a
>branch inside this repository.
>Welcome any PR to slimmer's repository about security or features.

Anyone googling will hopefully see this issue and your repo. There is no need to have a
branch in this repo to host this.

/close

**Comment by AZ-X** [comment]
OK.

**Comment by tmthrgd** [comment]
I agree this doesn't belong as part of this repo. Though I am curious what you removed that made that much of a difference, could you breifly elaborate? The compilers dead code elimination pass should eliminate anything not being used, so that might indicate something is forcing code to be kept in the binary that shouldn't be.

**Comment by AZ-X** [comment]
> I agree this doesn't belong as part of this repo. Though I am curious what you removed that made that much of a difference, could you breifly elaborate? The compilers dead code elimination pass should eliminate anything not being used, so that might indicate something is forcing code to be kept in the binary that shouldn't be.

I am a go beginner not an elaborator... anyway try [the copy  v1.1.36](https://pkg.go.dev/github.com/AZ-X/dns@v1.1.36) first.

**Comment by AZ-X** [comment]
Don't forget to star it @tmthrgd

**Comment by miekg** [comment]
From a very casual inspection it seems server.go and client.go are gone.

**Comment by AZ-X** [comment]
> From a very casual inspection it seems server.go and client.go are gone.

Yes! Keep an eye on it and star it. 

:electron:
--


[v1.1.37](https://pkg.go.dev/github.com/AZ-X/dns@v1.1.37)

**Comment by AZ-X** [comment]
Diversity begins. [v1.1.38](https://pkg.go.dev/github.com/AZ-X/dns@v1.1.38)

**Comment by AZ-X** [comment]
[v1.1.39](https://pkg.go.dev/github.com/AZ-X/dns@v1.1.39)

**Comment by steabert** [comment]
> I agree this doesn't belong as part of this repo. Though I am curious what you removed that made that much of a difference, could you breifly elaborate? The compilers dead code elimination pass should eliminate anything not being used, so that might indicate something is forcing code to be kept in the binary that shouldn't be.

Just importing this package without using anything will add it to an executable, so I think the DCE cannot detect that the code is unused. I have no idea why though. There are some sources online that go into this, but nothing I found useful for figuring out what's going on in the library here. Maybe @miekg knows why?
