### ISSUE TITLE
oss-fuzz build broken

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#1223]
In go1.16 module mode is on by default (https://golang.org/doc/go1.16#go-command) which has caused the fuzzer to fail today.

Here is the relevant part of the error log:
```
Step #4: + compile_go_fuzzer github.com/miekg/dns FuzzNewRR fuzz_newrr fuzz
Step #4: Running go-fuzz -tags fuzz -func FuzzNewRR -o fuzz_newrr.a github.com/miekg/dns
Step #4: -: no required module provides package github.com/miekg/dns: working directory is not part of a module
```

I don’t know if this is a problem is this repo, the oss-fuzz repo or the oss-fuzz project, but it’s a problem somewhere. Maybe a newer version of go-fuzz needs to be used or module mode forced off. I’m not familiar enough with it to know.

**Comment by miekg** [comment]
ah. Well maybe go 1.16 will finally be the extra push to make all these tools
'module' aware.

We'll see what happens

**Comment by mvdan** [comment]
That's happening in https://github.com/google/oss-fuzz/issues/5213, FYI. It's a bit tricky because their design is very GOPATH-centric.

**Comment by miekg** [comment]
revisit the fuzzing once we standardize on go 1.18
