### ISSUE TITLE
Do we have any plans to support XDP/ebpf？

### ISSUE THREAD

**Issue by ChenYahui2019** [miekg/dns#1229]
XDP/ebpf could improve DNS performance greatly. Other DNS products have started to supported XDP/ebpf. 
So, do we have such plan?
For example: `ListenAndServe` can use XDP to receive UDP packets.

reference material:
https://knot-resolver.readthedocs.io/en/stable/daemon-bindings-net_xdpsrv.html
https://indico.dns-oarc.net/event/33/contributions/749/attachments/721/1229/202002sf_xdp_v4.pdf
https://www.nlnetlabs.nl/downloads/publications/DNS-augmentation-with-eBPF.pdf

Thx.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Do we have any plans to..." ]
>XDP/ebpf could improve DNS performance greatly. Other DNS products have started
>to supported XDP/ebpf.
>So, do we have such plan?
>For example: ListenAndServe can use XDP to receive UDP packets.
>
>reference material:
>https://knot-resolver.readthedocs.io/en/stable/daemon-bindings-net_xdpsrv.html
>https://www.nlnetlabs.nl/downloads/publications/DNS-augmentation-with-eBPF.pdf

no, if this is done (at all) it should be done in the std libary.

/close
