### ISSUE TITLE
LOC: latitude/longitude parsing error

### ISSUE THREAD

**Issue by mikhirev** [miekg/dns#1232]
Hi!

When parsing `LOC` records, the [latitude](https://github.com/miekg/dns/blob/375601dc8836795fe825c4c5724877c8e068d2f5/scan_rr.go#L612) and [longitude](https://github.com/miekg/dns/blob/375601dc8836795fe825c4c5724877c8e068d2f5/scan_rr.go#L648) decimal parts are temporarily saved to `float32` that has not enough precision. This can be checked on an example from [RFC1876](https://www.rfc-editor.org/rfc/rfc1876.html#section-4).

Reproducer code:

```
package main

import (
	"fmt"
	"github.com/miekg/dns"
)

func main() {
	rr, _ := dns.NewRR("loiosh.kei.com. LOC 42 21 43.952 N 71 5 6.344 W -24m 1m 200m")
	fmt.Println(rr)
}
```

Expected output:

```
loiosh.kei.com.	3600	IN	LOC	42 21 43.952 N 71 05 6.344 W -24m 1m 200m 10m
```

Actual output:

```
loiosh.kei.com.	3600	IN	LOC	42 21 43.951 N 71 05 6.343 W -24m 1m 200m 10m
```

Note 0.001 second error in both latitude and longitude values.

**Comment by miekg** [comment]
Yep, that seems to point to a bug that needs fixing
