### ISSUE TITLE
Add new function to RR interface

### ISSUE THREAD

**Issue by mikhirev** [miekg/dns#1233]
Hi!

Currently it is possible to get a complete text representation of `RR` with the `String()` function and a header part with the `Header()` function. Please consider adding a new function that will return a text representation of `RR` data (without header). The motivation is implementing a JSON marshaler for the [format](https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format) used by Google and Cloudflare DoH servers where `data` is a separate field.

**Comment by miekg** [comment]
This has come up before. You can easily just index the strings and get the
right string, so no changes are needed.

/close

**Comment by mikhirev** [comment]
> You can easily just index the strings and get the right string

Do you mean something like `rr.String()[len(rr.Header()+1:]`?
