### ISSUE TITLE
Error parsing SIG RR with omitted original TTL field

### ISSUE THREAD

**Issue by mikhirev** [miekg/dns#1239]
Hi Miek!

The `SIG` type is implemented as if it were identical to `RRSIG`, but there is at least one difference in presentation format. In `RRSIG`

> The Original TTL field value MUST be represented as an unsigned
> decimal integer.

(from [RFC4034](https://www.rfc-editor.org/rfc/rfc4034.html#section-3.2)) while in `SIG`

> If the original TTL, which applies to the type signed, is the same as
> the TTL of the SIG RR itself, it may be omitted.  The date field
> which follows it is larger than the maximum possible TTL so there is
> no ambiguity.

(from [RFC2535](https://www.rfc-editor.org/rfc/rfc2535.html#section-7.2)).

As [the same parser is used](https://github.com/miekg/dns/blob/db96610e5e1145f4aa4c3d738e64bb1602bfe28a/scan_rr.go#L881) for both `SIG` and `RRSIG` RRs, parsing `SIG` with omitted original TTL [fails](https://github.com/miekg/dns/blob/db96610e5e1145f4aa4c3d738e64bb1602bfe28a/scan_rr.go#L918-L921).

**Comment by miekg** [comment]
Ha, that's a nice find, but note that 4034 obsoletes 2535, so not sure where this leaves `SIG`, but taking that into account I don't think this warrants changes in this lib

**Comment by andrewtj** [comment]
If I recall correctly even BIND doesn't support that syntax.
