### ISSUE TITLE
Add support for algorithm Ed448

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/dns#1241]
Defined in [RFC 8080](https://tools.ietf.org/html/rfc8080), support for DNSKEY algorithm Ed448 (16) would be greatly appreciated. Even though Ed448 is not on the standard library yet, there are some third-party implementations, for instance: https://github.com/cloudflare/circl/tree/master/sign/ed448

**Comment by miekg** [comment]
If it is in x/crypto it's fine to add. We want to minimize our deps, so
will not add another 3rd party module just for this algorithm.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] Add support for alg..." ]
>Totally understand. Just wanted to show there is demand for it, in case it goes
>into standard lib in the future

ack. If an alg is supported in either *and* there is a draft/rfc for it, it should be
supported here as well (as a general rule)

/close
