### ISSUE TITLE
Is there any way to carry bytes in RDATA of TXT RR?

### ISSUE THREAD

**Issue by riverbaby** [miekg/dns#1242]
I'd like to carry customized structure through RDATA in TXT RR, but I see the definition of TXT RR is as the following:
```golang
type TXT struct {
    Hdr RR_Header
    Txt []string `dns:"txt"`
}
```
Seems it only supports string content. Is there any way I can fill some customized structures into TXT's RData, for example, some binary bytes?

Could someone give me some advice? Thanks very much.

**Comment by tmthrgd** [comment]
You’ll have to use some sort of encoding like base64 or hexadecimal. See the standard libraries encoding packages.

**Comment by riverbaby** [comment]
well noted, I ignore this before. Appreciate your answer.
