### ISSUE TITLE
Clarifications on DNSSEC

### ISSUE THREAD

**Issue by qdm12** [miekg/dns#1251]
Hi there,

First of all thank you for this amazing library, it made my DNS journey way more fun.

Now, I'm working on a DNS proxy which I would like to validate DNSSEC signatures when they are present.

I am however a bit confused if this is baked in or not. For example:

```go
// If the received message contains a TSIG record the transaction signature
// is verified. This method always tries to return the message, however if an
// error is returned there are no guarantees that the returned message is a
// valid representation of the packet read.
func (co *Conn) ReadMsg() (*Msg, error) {
```

seems to say it is, but I wanted to check. For example in my case I did not set `TsigSecret` in either the `*dns.Conn` or the `*dns.Client`, so it also seems like nothing would be done. I'm working on an implementation querying DNSKEY and DS records for zones and validating RRSIG with these, but I'm starting to wonder if all I'm doing is actually necessary.

Thanks!!

**Comment by miekg** [comment]
Thanks!

TSIG is an older, different way of validating a DNS message. It has nothing
to do with dnssec, you don't need it in your setup

**Comment by qdm12** [comment]
Great thanks for clarifying. So effectively we need to handle the validation ourselves, although you already put in the work to handle the DNSSEC records as well as verifying signatures.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] Clarifications on D..." ]
>Great thanks for clarifying. So effectively we need to handle the validation
>ourselves, although you already put in the work to handle the DNSSEC records as
>well as verifying signatures.

yes, getting the RRsets from packets, sorting those, getting the RRSIG(s) and DNSKEY(s)
and then validating the lot
