### ISSUE TITLE
AXFR: bad key algorithm

### ISSUE THREAD

**Issue by aaplmike** [miekg/dns#1254]
Hello. Receiving bad key algorithm using sample code provided, with my fqdn, tsig key and server substituted. Tsig key was generated using `tsig-keygen -a md5 internal-key`. Also tried generating HmacSHA256 key as well. Same error every time.

Dig command with same key sent always completes successfully.

**Comment by andrewtj** [comment]
HMAC-MD5 support was removed in #1187 but the example in the docs was not updated. You'll either need to switch to a supported algorithm or implement [`TsigProvder`](https://pkg.go.dev/github.com/miekg/dns#TsigProvider).

**Comment by dmavrommatis** [comment]
@andrewtj can I ask how you can use the custom `TsigProvider` interface? It seems that `tsigVerifyProvider` is not exported and the `TsigVerify` is hard-coded to use the default one.
```
func TsigVerify(msg []byte, secret, requestMAC string, timersOnly bool) error {
	return tsigVerify(msg, tsigHMACProvider(secret), requestMAC, timersOnly, uint64(time.Now().Unix()))
}
```
