### ISSUE TITLE
Closing TLS connections gracefully

### ISSUE THREAD

**Issue by ameshkov** [miekg/dns#1257]
There's a problem with the way DNS-over-TLS server connections are closed.

The problem is that it sends an extra packet (TLS close_notify) to the connection that was already closed on the client-side.

Here's how it looks in Wireshark:
![image](https://user-images.githubusercontent.com/5947035/115753748-33907000-a3a4-11eb-84f8-ca711022352d.png)

This extra packet is unnecessary, and it also does not allow to close TCP connection gracefully.

The solution would be to store a pointer to the original TCP connection as well and close it instead of the `tls.Conn` when the connection was closed from the client-side.

**Comment by tmthrgd** [comment]
That’s just how TLS connections work, alerts are sent on close. We’re definitely not going to be closing anything out from underneath crypto/tls.

If you believe this behaviour is a bug in crypto/tls, then I’d suggest opening an issue against golang/go. Closing here.
