### ISSUE TITLE
Error when packing/unpacking the "zero" CDS-record

### ISSUE THREAD

**Issue by frelon** [miekg/dns#1261]
Hi!

When trying to implement the [DNSSEC Delete Algorithm](https://tools.ietf.org/html/rfc8078#section-4) it says to use a CDS record that looks as follows:

`CDS 0 0 0 0`

I created a test to try to pack this record:
```
func TestPackCDS(t *testing.T) {
	b := make([]byte, 100)
	cds := new(CDS)
	cds.Digest = "0"
	_, err := PackRR(cds, b, 0, make(map[string]int), false)
	if err != nil {
		t.Errorf("failed to pack CDS: %v", err)
	}
}
```

But it shows the error

> failed to pack CDS: encoding/hex: odd length hex string

Removing the dns:hex tag on DNSKEY struct fixes this, could it be a solution?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/dns] Error when packing/unpa..." ]
>Hi!
>
>When trying to implement the DNSSEC Delete Algorithm it says to use a CDS
>record that looks as follows:

where does it say this?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/dns] Error when packing/unpa..." ]
>Hi!
>
>When trying to implement the DNSSEC Delete Algorithm it says to use a CDS
>record that looks as follows:

oh, it's in rfc 8078. that's a bug then

**Comment by miekg** [comment]
I suspect that 00 as the last string would work, but technically 0 _is_ valid hex, probably makes sense to allow it for all hex fields

**Comment by miekg** [comment]
https://play.golang.org/p/W14wHA0_NXb

with "0000" it's valid base64. I don't think "0" is valid base64...

**Comment by miekg** [comment]
ha see https://www.rfc-editor.org/errata_search.php?rfc=8078
the library is correct
