### ISSUE TITLE
Pass ResponseWriter to MsgAcceptFunc

### ISSUE THREAD

**Issue by mzealey** [miekg/dns#1263]
It would be nice to be able to get details about the connection (eg remote address, protocol) from the `MsgAcceptFunc` to make routing/allow decisions based on this as well as the headers of the packet, for example dropping/refusing packets if a certain ratelimit is passed.

**Comment by miekg** [comment]
I think this makes sense even though it is backwards incompatible.

you can do these checks later in the chain, but moving this before parsing the entire package makes sense to me.
