### ISSUE TITLE
Removing edns0 local entry in dns.Msg

### ISSUE THREAD

**Issue by nicolas-martin** [miekg/dns#1264]
Hi,

This is not an issue but rather me trying to get some guidance.

I'm trying to sanitize our outgoing requests by removing the client mac address located in the dns.EDNS0_LOCAL (opt code 65001).

I can retrieve the value just fine
```
if opt != nil {
        if len(opt.Option) == 0 {
	        return "", errors.New("opt.option of len 0")
        }
        for _, v := range opt.Option {
	        switch m := v.(type) {
	        case *dns.EDNS0_LOCAL:
		        return net.HardwareAddr(m.Data).String(), nil
	        }
        }
        
        return "", errors.New("no EDNS0_LOCAL found")

}
```

However I can't find a way to remove it. 

```
opt := msg.IsEdns0()

newExtra := []dns.RR{}
for _, v := range opt.Option {
    switch v.(type) {
    case *dns.EDNS0_LOCAL:
	    continue
    default:
	    newExtra = append(newExtra, v) // <-- missing header
    }
}
msg.Extra = newExtra
```
I've also had a look at the truncate method. Which uses `Extra` but I'm having the same issues. I'm a bit confused as to what I should cast it as or which property I should be using.

**Comment by miekg** [comment]
https://pkg.go.dev/github.com/miekg/dns#hdr-EDNS0
