### ISSUE TITLE
TXT record output is double quoted

### ISSUE THREAD

**Issue by peak-load** [miekg/dns#1265]
I'm making simple geoip data DNS resolver with dns and there is a problem that my data contains spaces (Organization name or ISP name in GeoIP-ISP db). All TXT data is escaped and quoted somewhere in DNS code, as  my service sends wrong data to client.

**Actual result:**
```
dig @x.x.x.x -t txt geoip +short
"95.91.yy.yy,3209,Vodafone" "GmbH"
```
**Expected result (with space unmodified)**
```
dig @x.x.x.x -t txt geoip +short
"95.91.yy.yy,3209,Vodafone GmbH"
```

**Example result from other DNS service with no spaces double quoted**
```
dig @8.8.8.8 -t txt cloudflare.com +short | head -n1
"v=spf1 ip4:199.15.212.0/22 ip4:173.245.48.0/20 include:_spf.google.com include:spf1.mcsv.net include:spf.mandrillapp.com include:mail.zendesk.com include:stspg-customer.com include:_spf.salesforce.com -all"
```

**My result when I modify my code to return SPF record**
```
var txt string = "v=spf1 ip4:199.15.212.0/22 ip4:173.245.48.0/20 include:_spf.google.com include:spf1.mcsv.net include:spf.mandrillapp.com include:mail.zendesk.com include:stspg-customer.com include:_spf.salesforce.com -all"
```

```
dig @x.x.x.x -t txt geoip +short
"v=spf1" "ip4:199.15.212.0/22" "ip4:173.245.48.0/20" "include:_spf.google.com" "include:spf1.mcsv.net" "include:spf.mandrillapp.com" "include:mail.zendesk.com" "include:stspg-customer.com" "include:_spf.salesforce.com" "-all"
```

**My code:** 
https://gist.github.com/peak-load/ce863d4ee01b63a5296e5d739c8f78a4

Please suggest how can I get spaces with no double quotes in reply?

**Comment by tmthrgd** [comment]
First a little top, don’t use `strings.Split` to get the remote IP address, it will fail for IPv6. Instead use `net.SplitHostPort` (IIRC).

From briefly looking at your code, the problem is you’re using `NewRR` which is designed to parse a specific presentation format, not raw data. Instead try constructing the RR manually, I.e. manually construct a `dns.Txt`. It’s also a lot slower to be parsing.

**Comment by peak-load** [comment]
@tmthrgd thanks for your advice! 

Result is: `rr := &dns.TXT{Hdr: dns.RR_Header{Name: q.Name, Rrtype: dns.TypeTXT, Class: dns.ClassINET, Ttl: 3600}, Txt: []string{txt}}`
