### ISSUE TITLE
Mapping input to dns.TypeX

### ISSUE THREAD

**Issue by till** [miekg/dns#1266]
Thanks again for this library. It's a life-saver (or at least time-saver, if I am being less dramatic). :) 

I wrote a little tool to check if DNS servers are in sync and came across this last night. Maybe this is the wrong place to ask, but I am trying to map input to your constants. So for example, imagine:

```
foo --type MX
```

And that gets somehow _translated_ to `dns.TypeMX`, so I can use it to query.

I can duplicate your `const` and create a mapping. But I am wondering if I am missing anything that can do this without duplicating your constants?

**Comment by tmthrgd** [comment]
Glad it could be so useful for you!

You want `StringToType`. It’s exactly what you’re looking for.
