### ISSUE TITLE
Query with EDNS0 NSID enabled

### ISSUE THREAD

**Issue by natesales** [miekg/dns#1267]
I'm looking to retrieve the NSID string from a query. I see that there's a EDNS0_NSID type but I'm having some trouble using it in practice. I found an old example but the API has changed since then:

https://github.com/miekg/dns/blob/c729cdd971b67216c3ae82d185c8bbdd78e85639/_examples/q/q.go#L82-L93

Is there a current example of using data from EDNS fields?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/dns] Query with EDNS0 NSID e..." ]
>I'm looking to retrieve the NSID string from a query. I see that there's a
>EDNS0_NSID type but I'm having some trouble using it in practice. I found an
>old example (https://github.com/miekg/dns/blob/
>c729cdd971b67216c3ae82d185c8bbdd78e85639/_examples/q/q.go#L82) but the API has
>changed since then. Is there an example of using data from EDNS fields?

this might help

https://pkg.go.dev/github.com/miekg/dns#hdr-EDNS0

/Miek

--
Miek Gieben
