### ISSUE TITLE
expose `SessionUDP.context` and `udpOOBSize`

### ISSUE THREAD

**Issue by asgarciap** [miekg/dns#1269]
Is there any reason why we can't access the SessionUDP.context (out-of-band data) field?
Since we can create specific DecorateReader in a server it should be also possible to access this field after calling the ReadFromSessionUDP function.

Also it would be nice to set via a callback function the udpOOBSize value.

https://github.com/miekg/dns/blob/ce48a4b9efe6d545069a62147da9d67825f98fa1/udp.go#L32

**Comment by tmthrgd** [comment]
Why? What would that let you do you can't do now? We don't export things without a compelling need.

**Comment by asgarciap** [comment]
Because the OOB data contains important stuff that can be needed if I implement a DecoratedReader.
An specific example/use case that I'm facing now is trying to run a DNS server with transparent proxy support. In that case I will need to use the OOB data to access the orginal destination address/port of the DNS request.

**Comment by miekg** [comment]
this looks to be very niche. You should probably run a local fork for the time being, maybe this will come up more in the future, but for now these will not be exported.
