### ISSUE TITLE
EDNS: Wrong EDNS0 Option unpacked

### ISSUE THREAD

**Issue by mgranderath** [miekg/dns#1271]
I'm working using the `edns-tcp-keepalive` option but it seems that it is always unpacked as the `EDNS0_LOCAL` struct and not the `EDNS0_TCP_KEEPALIVE` struct. 

An example test for reproducing this error is down below:

```golang
func TestClientEDNS0TCPKeepAlive(t *testing.T) {
	handler := func(w ResponseWriter, req *Msg) {
		m := new(Msg)
		m.SetReply(req)

		m.Extra = make([]RR, 1, 2)
		m.Extra[0] = &TXT{Hdr: RR_Header{Name: m.Question[0].Name, Rrtype: TypeTXT, Class: ClassINET, Ttl: 0}, Txt: []string{"Hello local edns"}}

		// reply with the same option
		m.Extra = append(m.Extra, req.Extra[0])

		w.WriteMsg(m)
	}

	HandleFunc("miek.nl.", handler)
	defer HandleRemove("miek.nl.")

	s, addrstr, _, err := RunLocalUDPServer(":0")
	if err != nil {
		t.Fatalf("unable to run test server: %s", err)
	}
	defer s.Shutdown()

	m := new(Msg)
	m.SetQuestion("miek.nl.", TypeTXT)

	ec1 := &EDNS0_TCP_KEEPALIVE{}
	ec1.Code = EDNS0TCPKEEPALIVE
	o := &OPT{Hdr: RR_Header{Name: ".", Rrtype: TypeOPT}, Option: []EDNS0{ec1}}
	m.Extra = append(m.Extra, o)

	c := new(Client)
	r, _, err := c.Exchange(m, addrstr)
	if err != nil {
		t.Fatalf("failed to exchange: %s", err)
	}

	if r == nil {
		t.Fatal("response is nil")
	}
	if r.Rcode != RcodeSuccess {
		t.Fatal("failed to get a valid answer")
	}

	txt := r.Extra[0].(*TXT).Txt[0]
	if txt != "Hello local edns" {
		t.Error("Unexpected result for miek.nl", txt, "!= Hello local edns")
	}

	got := r.Extra[1].(*OPT).Option[0]
	if _, ok := got.(*EDNS0_TCP_KEEPALIVE); !ok {
		t.Error("Did not receive back EDNS0_TCP_KEEPALIVE")
	}
}
```

**Comment by tmthrgd** [comment]
That option code is missing from `makeDataOpt` here:
https://github.com/miekg/dns/blob/ce48a4b9efe6d545069a62147da9d67825f98fa1/msg_helpers.go#L441

Want to send a PR?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] EDNS: Wrong EDNS0 O..." ]
>That option code is missing from makeDataOpt here:
>https://github.com/miekg/dns/blob/ce48a4b9efe6d545069a62147da9d67825f98fa1/
>msg_helpers.go#L441
>
>Want to send a PR?

is there a (neat) way to have a test that we have all them in this switch?

**Comment by mgranderath** [comment]
Opened the PR with the simple fix. I've thought about covering all of them before but I don't think it's easily doable. Let me know though and I'll either add that test or the one above as a regression test .

**Comment by tmthrgd** [comment]
> [ Quoting ***@***.***> in "Re: [miekg/dns] EDNS: Wrong EDNS0 O..." ]
> That option code is missing from makeDataOpt here: https://github.com/miekg/dns/blob/ce48a4b9efe6d545069a62147da9d67825f98fa1/ msg_helpers.go#L441 Want to send a PR?
> is there a (neat) way to have a test that we have all them in this switch?

Not that I’m aware of. There are golang proposals for features like that, but none have been accepted nor do I really think they will. staticcheck doesn’t even support this.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] EDNS: Wrong EDNS0 O..." ]
>    [ Quoting @.***> in "Re: [miekg/dns] EDNS: Wrong EDNS0 O..." ]
>    That option code is missing from makeDataOpt here: https://github.com/miekg
>    /dns/blob/ce48a4b9efe6d545069a62147da9d67825f98fa1/ msg_helpers.go#L441
>    Want to send a PR?
>    is there a (neat) way to have a test that we have all them in this switch?
>
>Not that I’m aware of. There are golang proposals for features like that, but
>none have been accepted nor do I really think they will. staticcheck doesn’t
>even support this.

I think moving the code into edns0.go will make sense, then the list of const is right
above the switch.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] EDNS: Wrong EDNS0 O..." ]
>Not that I’m aware of. There are golang proposals for features like that, but
>none have been accepted nor do I really think they will. staticcheck doesn’t
>even support this.

https://github.com/miekg/dns/pull/1273
