### ISSUE TITLE
Excess FD errors

### ISSUE THREAD

**Issue by chris-wood** [miekg/dns#1295]
Running from a fresh build of tip of `master` on macOS, I'm seeing the following:

```
$ echo "google.com" | ./zdns A
{"data":{"protocol":"udp","resolver":"[2001:558:feed::2]:53"},"error":"write udp 10.0.0.184:59008-\u003e[2001:558:feed::2]:53: address 2001:558:feed::2: non-IPv4 address","name":"google.com","status":"ERROR","timestamp":"2021-09-05T20:38:25-07:00"}
FATA[0000] unable to create socketlisten udp 10.0.0.184:0: socket: too many open files 
```

I assume this isn't expected, so I'm wondering if this is a regression. I could of course be using it wrong, too! Happy to provide any additional information if it would be helpful.

**Comment by miekg** [comment]
I don't know what zdns is, but seems unrelated to this library

**Comment by chris-wood** [comment]
Well, that's embarrassing. I filed this issue on the wrong repo. Oops!
