### ISSUE TITLE
The testable example "ExamplePrivateHandle" is incorrectly passing

### ISSUE THREAD

**Issue by ameowlia** [miekg/dns#1299]
👋  Hello, 

I am investigating the golang issue: https://github.com/golang/go/issues/48362, where testable examples are causing false positives when the output comment block is not the last comment block example.

I ran a parser against the [top golang repos](https://github.com/kaxap/arl/blob/master/README-Go.md), including this repo and I found this bug with your [ExamplePrivateHandle testable example](https://github.com/miekg/dns/blob/4e8fe099f421b9920a5f2d5ec95579453796140b/example_test.go#L121-L146).

If you combine the comment blocks to test as intended (see below) your test fails because the id is not `1234` like the output expects.

This is the code I suspect that you intended:

```
func ExamplePrivateHandle() {
	dns.PrivateHandle("APAIR", TypeAPAIR, NewAPAIR)
	defer dns.PrivateHandleRemove(TypeAPAIR)

	rr, err := dns.NewRR("miek.nl. APAIR (1.2.3.4    1.2.3.5)")
	if err != nil {
		log.Fatal("could not parse APAIR record: ", err)
	}
	fmt.Println(rr)

	m := new(dns.Msg)
	m.Id = 12345
	m.SetQuestion("miek.nl.", TypeAPAIR)
	m.Answer = append(m.Answer, rr)

	fmt.Println(m)
	
	// Output: miek.nl.	3600	IN	APAIR	1.2.3.4 1.2.3.5
	// ;; opcode: QUERY, status: NOERROR, id: 12345
	// ;; flags: rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
	//
	// ;; QUESTION SECTION:
	// ;miek.nl.	IN	 APAIR
	//
	// ;; ANSWER SECTION:
	// miek.nl.	3600	IN	APAIR	1.2.3.4 1.2.3.5
}
```

This fails with:

```
$ go test ./...
--- FAIL: ExamplePrivateHandle (0.00s)
got:
miek.nl.        3600    IN      APAIR   1.2.3.4 1.2.3.5
;; opcode: QUERY, status: NOERROR, id: 49593
;; flags: rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;miek.nl.       IN       APAIR

;; ANSWER SECTION:
miek.nl.        3600    IN      APAIR   1.2.3.4 1.2.3.5
want:
miek.nl.        3600    IN      APAIR   1.2.3.4 1.2.3.5
;; opcode: QUERY, status: NOERROR, id: 12345
;; flags: rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;miek.nl.       IN       APAIR

;; ANSWER SECTION:
miek.nl.        3600    IN      APAIR   1.2.3.4 1.2.3.5
FAIL
FAIL    github.com/miekg/dns    2.974s
ok      github.com/miekg/dns/dnsutil    (cached)
FAIL
```

**Comment by ameowlia** [comment]
This isn't simple "just move one comment" case. In this case the `id` changes every time you run this code. I'll let you handle this PR @tmthrgd 😄

**Comment by miekg** [comment]
You can provide a function that returns an ID that is static for this test.

**Comment by miekg** [comment]
Fixed via https://github.com/miekg/dns/pull/1354
