### ISSUE TITLE
Concurrent processing of TCP queries from the same connection

### ISSUE THREAD

**Issue by rdrozhdzh** [miekg/dns#1314]
The RFC 7766 (see https://datatracker.ietf.org/doc/html/rfc7766#section-6.2.1.1) suggests that

>    DNS servers (especially recursive) MUST expect to receive pipelined
   queries.  The server SHOULD process TCP queries concurrently, just as
   it would for UDP.

The term pipelining is defined there as

>    o  Pipelining: the sending of multiple queries and responses over a
      single TCP connection but not waiting for any outstanding replies
      before sending another query.

Is it possible to implement pipelining and concurrent query processing in `dns.Server`?

Probably, the updated part of `func (srv *Server) serveTCPConn()` may look like below (added WaitGroup and goroutine)

```go
	var wgCo sync.WaitGroup
	for q := 0; (q < limit || limit == -1) && srv.isStarted(); q++ {
		m, err := reader.ReadTCP(w.tcp, timeout)
		if err != nil {
			// TODO(tmthrgd): handle error
			break
		}
		wgCo.Add(1)
		go func() {
			srv.serveDNS(m, w)
			wg.Done()
		}()
		if w.closed {
			break // Close() was called
		}
		if w.hijacked {
			break // client will call Close() themselves
		}
		// The first read uses the read timeout, the rest use the
		// idle timeout.
		timeout = idleTimeout
	}
	wgCo.Wait()
```

Any comments, ideas?

**Comment by miekg** [comment]
I think this make sense... Do you an actual use-case that breaks for you?

Do we need another `wg` ? Can we reuse the one we have, or does that lead to problem?

**Comment by rdrozhdzh** [comment]
Hi @miekg,

The existing waitgroup waits for all TCP connections to be closed before shutting down the server. 
The new waitgroup is created for each TCP connection and waits for all queries from this connection are processed before closing the connection. The existing waitgroup cannot be reused for this purpose.

The only my concern about this code is that it looks incompatible with Close(), Hijack() functionality provided by server to external handlers. Though, I'm not aware of any coredns plugins using this functionality. Not sure about other applications/projects which use dns.Server.

Probably, it makes sense to make this feature configurable (e.g. via environment variable) and use synchronous query processing (i.e. existing behavior) by default, and enable asynchronous query processing only when upper-level software doesn't use "Hijack" functionality.

**Comment by tmthrgd** [comment]
I think the necessary changes here are a lot more complex than this. The code really wasn't intended to support pipelined TCP requests. Is there actually a pressing change here beyond the RFC SHOULD? How do other DNS servers handle pipelined TCP requests?

**Comment by rdrozhdzh** [comment]
The reasoning behind this request is that I'm working on a coredns plugin which will forward DNS queries to upstream servers through a single TCP/TLS connection as described in RFC 7766. I intend to share this plugin with coredns community after completing and testing my work.
However, lack of pipelining support in coredns server will make it inefficient to chain several coredns'es with a new plugin. At high query rate, the subsequent client queries will spend too much time in TCP queue on server side while the server processes previous queries from the same connection. I.e. the latency for particular query will include the processing time of all the queries queued before in addition to the processing time of the wanted query.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] Concurrent processi..." ]
>However, lack of pipelining support in coredns server will make it inefficient

I agree with Tom, that at this point this is theoretical.

There is also nothing stopping you from using (say) 10 tcp conns. Even with tcp pipelining
implemented you can still get head-of-line blocking

**Comment by tmthrgd** [comment]
Do public DNS resolvers and servers properly handle TCP pipelining?
