### ISSUE TITLE
License is not clear

### ISSUE THREAD

**Issue by steven-varga** [miekg/dns#1327]
Great project! Can you please clarify if this project AS-IS|MIT|BSD|LGPL|...  or confirm the license file is non-standard on purpose.  -- I am not quite sure how to interpret the license.

**Comment by hrieke** [comment]
And let me add my own two cents to this- 
The BSD 3-clause that Google uses includes a Patent Provision (https://github.com/golang/go/blob/master/PATENTS).
Where is that file in the repo?
Thanks

**Comment by miekg** [comment]
License is BSD-3-clause as detected by pkg.go.dev: https://pkg.go.dev/github.com/miekg/dns?tab=licenses

**Comment by steven-varga** [comment]
Thanks! I may optionally use this library for a cloud cluster project, with requirements to list/acknowledge licenses.
