### ISSUE TITLE
Reuse of Unbound UDP Sockets for Requests 

### ISSUE THREAD

**Issue by spencerdrak** [miekg/dns#1329]
Hello,

I'm working on a project (`zmap/zdns`) that provides high-speed and high-volume DNS lookups, and relies on this library. In support of that goal, we've forked and made a patch to this library to allow reuse of a single, non-connected UDP socket between outbound DNS requests to various hosts, which we need in order to achieve the performance that our application needs.

I'm curious if this team would be open to reviewing a PR if we were to write one that achieves this same functionality. I would imagine a method that achieves the following:

- Take in a connection and a destination address
- The connection would be a `net.UDPConn` wrapping a non-connected socket, to allow use of the `WriteTo` method on a `net.PacketConn` interface
- So long as the connection is an unbound UDP socket, reuse it for requests by specifying the remote address to `WriteTo` to increase performance
- If preferred, allow the user to specify that a connected socket be used instead, to maintain behavior similar to the current state of the library.

This would likely also require some changes to the `Conn` Struct in the client, as well as a new (or modified) 'ExchangeWithConn` method.

Is there any considerations or ideas that this team might have for such an endeavor? I'm working on a possible PR but wanted to get some input as to the feasibility or broader usefulness of such a feature.

Thank you!

**Comment by tmthrgd** [comment]
That certainly sounds interesting. Could you clarify in what ways would the behaviour differ versus what we currently do?

**Comment by spencerdrak** [comment]
So, the way that I envision this looking (and the way that our patch is currently working, but again, open to change) is that another function is created in `client.go` - this function would behave almost the same as `ExchangeWithConn` but this function would accept a `net.UDPConn` that wraps a non-connected socket. This is where the behavior itself differs - the function also accepts a parameter specifying the address that should be sent to, and will re-use the same underlying socket for a variety of hosts using the `WriteTo` method instead of just `Write`. The socket itself never changes and there's no call to `net.Conn.Write()` - instead, just the call to `net.PacketConn.WriteTo`. 

There'd also have to be some way to specify whether or not the user wants to choose this behavior vs the original behavior, or a cleaner way to bundle them together if that's what is best.

Does that answer your question? Happy to provide more details if I've not answered fully. 

Thank you!

**Comment by tmthrgd** [comment]
So I do understand how the API would differ, but what I'm wanting to know is say a miekg/dns/v2 had a different API and we decided to make this change completely transparently to the caller, what observable differences would there be? Like would any applications actually break? Would packets being sent be at all different? Would performance be worse in any situations?

**Comment by spencerdrak** [comment]
Hi there, sorry for the delay in answering. To answer those questions:

- Applications would have to call `miekg/dns` differently, or, `miekg/dns` would need some way of determining where to what remote host to write to with the given socket. In our case, we have some logic that calls `miekg/dns` with the `net.Conn` and remote address, so we are doing that work and then `miekg/dns` can just reuse the socket and send to wherever it's specified. However, having that wrapped up into `miekg/dns` may save some headache on the application side.
- No, the actual packets being sent would remain the same. 
- I don't see any scenarios where performance would be worse.

**Comment by miekg** [comment]
How would a _minimal_ PR look like?
