### ISSUE TITLE
Trying to generate RRSIGs: crypto.PrivateKey does not implement crypto.Signer

### ISSUE THREAD

**Issue by stevemeier** [miekg/dns#1330]
Hello,

thank you for this very useful library.

I am currently experimenting with DNSSEC (trying to generate RRSIGs in a minimalistic server) but I am stuck. I have only been using Go for about two years, so maybe my understanding of the language is just not sufficient.

Here is the code I have so far:
```
package main

import "fmt"
import "os"
import "time"
import "github.com/miekg/dns"


func main() {
	dkeyfile, _ := os.Open("./ed25519.key")
	dkey := new(dns.DNSKEY)
	dprivkey, dpkerr := dkey.ReadPrivateKey(dkeyfile, "./ed25519.key")

	newrr, _ := dns.NewRR("www.example.org. 60 IN A 192.0.2.42")
	rrsig := new(dns.RRSIG)
	rrsig.Algorithm = dns.ED25519
	rrsig.KeyTag = 12345		// wrong ID, fix later
	rrsig.SignerName = "example.org."
	rrsig.Inception = sig_timestamp(time.Now().Add(-1 * time.Hour))
	rrsig.Expiration = sig_timestamp(time.Now().Add(23 * time.Hour))

	dnssign := rrsig.Sign(dprivkey, []dns.RR{newrr})
	fmt.Println(dnssign)
}

func sig_timestamp (when time.Time) (uint32) {
	u32, _ := dns.StringToTime(when.Format("20060102150405"))
	return u32
}
```

The `ed25519.key` file contains a private key also generated with this module:
```
% cat ed25519.key
Private-key-format: v1.3
Algorithm: 15 (ED25519)
PrivateKey: Yd/zscVkVkzPs4a6a..........
```

Trying to run this throws the following error:
```
./signer2.go:22:23: cannot use dprivkey (type crypto.PrivateKey) as type crypto.Signer in argument to rrsig.Sign:
	crypto.PrivateKey does not implement crypto.Signer (missing Public method)
```

If I generate a private key at runtime using `rsa.GenerateKey(rand.Reader, 2048)` the code works.
As I read the documentation, both functions return `crypto.PrivateKey` but then my code should run.

I am using `go version go1.16.5 darwin/amd64` on OSX 11.6.1.

Any helpful comments are appreciated. Thanks!

**Comment by tmthrgd** [comment]
You need to be checking the errors. It’s likely you’re getting an error and `dprivkey` is nil.

**Comment by stevemeier** [comment]
Hello @tmthrgd,

I updated the example to include error handling:

```
package main

import "fmt"
import "log"
import "os"
import "time"
import "github.com/miekg/dns"

func main() {
	dkeyfile, fileerr := os.Open("./ed25519.key")
	if fileerr != nil { log.Fatal(fileerr) }
	dkey := new(dns.DNSKEY)
	dprivkey, dpkerr := dkey.ReadPrivateKey(dkeyfile, "./ed25519.key")
	if dpkerr != nil { log.Fatal(dpkerr) }

	newrr, rrerr := dns.NewRR("www.example.org. 60 IN A 192.0.2.42")
	if rrerr != nil { log.Fatal(rrerr) }
	rrsig := new(dns.RRSIG)
	rrsig.Algorithm = dns.ED25519
	rrsig.KeyTag = 12345		// wrong ID, fix later
	rrsig.SignerName = "example.org."
	rrsig.Inception = sig_timestamp(time.Now().Add(-1 * time.Hour))
	rrsig.Expiration = sig_timestamp(time.Now().Add(23 * time.Hour))

	dnssign := rrsig.Sign(dprivkey, []dns.RR{newrr})
	fmt.Println(dnssign)
}

func sig_timestamp (when time.Time) (uint32) {
	u32, stterr := dns.StringToTime(when.Format("20060102150405"))
	if stterr != nil { log.Fatal(stterr) }
	return u32
}
```

However, go refuses to even run this. The error is still:
```
./signer2.go:25:23: cannot use dprivkey (type crypto.PrivateKey) as type crypto.Signer in argument to rrsig.Sign:
	crypto.PrivateKey does not implement crypto.Signer (missing Public method)
```

And this is the part I do not understand. Why does this work with `rsa.GenerateKey` but not with the functions of this module if both return `crypto.PrivateKey` according to the documentation?

Thanks for your help!

**Comment by tmthrgd** [comment]
Ah I see of course this is a compile time error. The problem is that private keys aren't necessarily capable of signing messages. It's true that all the currently implemented ones do, but some don't. You'll need to add a cast to `crypto.Signer` to satisfy the method. Something like: 

```go
	signer, ok := dprivkey.(crypto.Signer)
	if !ok {
		return ... // handle error
	}

	dnssign := rrsig.Sign(signer, []dns.RR{newrr})
	fmt.Println(dnssign)
```
