### ISSUE TITLE
Question around support for "extended" SPF records

### ISSUE THREAD

**Issue by wguo-github** [miekg/dns#1332]
Hi, I'm facing an issue when using the library to parse SPF records that happen to be longer than 255 characters, and was wondering if I'm doing something wrong. The TXT records follow the [RFC approach](https://www.rfc-editor.org/rfc/rfc7208#section-3.3) of using double quotes to mark the start/end of the concatenated record. For example, SPF on domain `us.eversrv.com`:

`"v=spf1 ip4:69.63.146.128/26 ip4:69.63.158.32/28 ip4:68.169.14.0/24 ip4:154.0.13.104/29 ip4:69.63.148.88/30 ip4:69.63.148.92/31 ip4:69.63.148.94 ip4:69.63.149.149/32 ip4:69.63.149.150/31 ip4:69.63.149.152/29 ip4:69.63.149.160/30 ip4:69.63.149.164 ip4:69.63" ".159.119 ip4:69.63.159.92 ip4:69.63.159.128/31 ~all"`

The above single logical record yields two physical TXT records:

<img width="1323" alt="Screen Shot 2022-01-10 at 11 53 09 am" src="https://user-images.githubusercontent.com/98504631/151286238-8f409a05-5277-4b06-a11a-49d7508aa8f3.png">

Wondering whether it'd be beyond the scope of the DNS library to cater for this scenario, and allow us to abstract away the fact that there's two TXT records that were read, and instead present them as a single logical TXT record?

An alternative I explored was to leverage the `Rdlength` field provided in the header, to see if we could do the concatenation ourselves. However something I didn't quite understand is why the `Rdlength` number doesn't match the actual length of the record - i.e. for the above example, it says length is 308 whereas the actual length is 306 chars. The reported length seems to be off by `1 * number of physical TXT records` (?).

Thanks for your help on this!

**Comment by andrewtj** [comment]
> The above single logical record yields two physical TXT records:

No, that's a single TXT record containing two character strings. TXT records are composed of one or more character strings which themselves are made up of a single byte for the length of the character string followed by that many bytes. Since multiple character strings are inherent to the format you're probably better off working with that rather than trying to hide it.

**Comment by wguo-github** [comment]
Thanks for clarifying - you're right that it yields a single TXT record containing multiple strings. I think we should be able to work with this by taking into account the "extra" byte (indicating length) for each string, and then determine the "actual" length of the TXT record as `Rdlength - (size of Txt []string slice)`.

**Comment by andrewtj** [comment]
We? You're proposing to redefine `Txt []string` as `Txt string` in this package? That's a breaking change to an inferior representation. That's not going to happen.

**Comment by wguo-github** [comment]
Hi Andrew, sorry my wording was unclear - I meant that we'd be able to work around this locally for our own use case, and wasn't proposing making any changes to the library.

**Comment by andrewtj** [comment]
No worries, it sounds like you're all sorted then. Are you happy to close this? You're welcome to come back if you have any further questions.
