### ISSUE TITLE
udp queries return 0 records in aws ec2 amazon linux

### ISSUE THREAD

**Issue by matti** [miekg/dns#1335]
I can only reproduce this in aws ec2 - testing locally on a mac or debian based machine works.

Running dig against 1.1.1.1 works 100%
```
while true; do dig @1.1.1.1 -t A www.microsoft.com | grep status; done
...
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48978
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26272
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21609
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28989
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58746
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1444
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15235
```

Running dig against localhost where a server using this library running (github.com/matti/harderdns) gives ~25% NXDOMAIN
```
while true; do dig @localhost -t A www.microsoft.com | grep status; done
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64507
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32834
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 44257
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60170
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 6366
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43808
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60896
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40570
```

if I start the server so that it uses 

```
	c := dns.Client{
		Timeout: timeout,
		Net:     "tcp",
	}
```

eg. `harderdns -net tcp 1.1.1.1:53` then all queries work 100%.

Could anyone point me to the right direction here?

**Comment by miekg** [comment]
very much off-topic for this lib, prolly should ask the author of harderdns.

/close

**Comment by matti** [comment]
@miekg yes, I am the author of harderdns - asking for what I am missing here. I'm more than happy to provide more details.

**Comment by matti** [comment]
I find it weird that I can not reproduce this in other machines than ec2 - and, that plain dig works in ec2.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] udp queries return ..." ]
>I find it weird that I can not reproduce this in other machines than ec2 - and,
>that plain dig works in ec2.

I have no idea, not using or knowing how ec2 works.

**Comment by tmthrgd** [comment]
Check with the race detector enabled. That might be relevant. Not sure otherwise.

**Comment by matti** [comment]
@tmthrgd sorry whats that? found this: https://github.com/miekg/dns/blob/master/client_test.go

**Comment by tmthrgd** [comment]
@matti Check out https://go.dev/blog/race-detector and https://go.dev/doc/articles/race_detector. It's part of the go tool.
