### ISSUE TITLE
SIG(0) with ED25519 panic: crypto: requested hash function #0 is unavailable

### ISSUE THREAD

**Issue by adam-burns** [miekg/dns#1339]
Learning how to use this comprehensive library, Sign() in snippet

```
        pk, err := keyRR.Generate(256)
        now := uint32(time.Now().Unix())
        sig0RR := new(dns.SIG)
        sig0RR.Hdr.Name = "."
        sig0RR.Hdr.Rrtype = dns.TypeSIG
        sig0RR.Hdr.Class = dns.ClassANY
        sig0RR.Algorithm = uint8(dns.ED25519)
        sig0RR.Expiration = now + 300
        sig0RR.Inception = now - 300
        sig0RR.KeyTag = keyRR.KeyTag()
        sig0RR.SignerName = keyRR.Hdr.Name
        mb, err := sig0RR.Sign(pk.(crypto.Signer), m)
```

and variations has resulted in a panic condition

```
panic: crypto: requested hash function #0 is unavailable

goroutine 1 [running]:
crypto.Hash.New(0x64bce0)
        /home/go/src/crypto/crypto.go:134 +0x99
github.com/miekg/dns.(*SIG).Sign(0xc000072540, {0x7f6c085d7980, 0xc00000e180}, 0xc000161ec8)
        /home/go/src/github.com/miekg/dns/sig0.go:46 +0x205
main.main()
        /home/src/test_go/update.go:129 +0xed9
exit status 2
```
Doubting my code, I locally patched `sig0_test.go` to test ED25519 with
```
diff --git a/sig0_test.go b/sig0_test.go
index 1abdc4af..3f4fb04f 100644
--- a/sig0_test.go
+++ b/sig0_test.go
@@ -12,7 +12,7 @@ func TestSIG0(t *testing.T) {
        }
        m := new(Msg)
        m.SetQuestion("example.org.", TypeSOA)
-       for _, alg := range []uint8{ECDSAP256SHA256, ECDSAP384SHA384, RSASHA1, RSASHA256, RSASHA512} {
+       for _, alg := range []uint8{ED25519, ECDSAP256SHA256, ECDSAP384SHA384, RSASHA1, RSASHA256, RSASHA512} {
                algstr := AlgorithmToString[alg]
                keyrr := new(KEY)
                keyrr.Hdr.Name = algstr + "."
@@ -27,6 +27,8 @@ func TestSIG0(t *testing.T) {
                        keysize = 384
                case RSASHA512:
                        keysize = 1024
+               case ED25519:
+                       keysize = 256
                }
                pk, err := keyrr.Generate(keysize)
                if err != nil {
```
but invoking `go test -run SIG0 -v` also results in a similar panic condition
```
=== RUN   TestSIG0
--- FAIL: TestSIG0 (0.00s)
panic: crypto: requested hash function #0 is unavailable [recovered]
        panic: crypto: requested hash function #0 is unavailable

goroutine 19 [running]:
testing.tRunner.func1.2({0x709dc0, 0xc0000998c0})
        /home/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /home/go/src/testing/testing.go:1212 +0x218
panic({0x709dc0, 0xc0000998c0})
        /home/go/src/runtime/panic.go:1038 +0x215
crypto.Hash.New(0x716860)
        /home/go/src/crypto/crypto.go:134 +0x99
github.com/miekg/dns.(*SIG).Sign(0xc0000a63c0, {0x7ddfe8, 0xc0000b6120}, 0x7d53ce)
        /home/src/dns/sig0.go:46 +0x205
github.com/miekg/dns.TestSIG0(0xc000083860)
        /home/src/dns/sig0_test.go:48 +0x3db
testing.tRunner(0xc000083860, 0x787258)
        /home/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /home/go/src/testing/testing.go:1306 +0x35a
exit status 2
FAIL    github.com/miekg/dns    0.007s
```

A quick search suggests the following to be triggering the panic in the crypt library?

https://github.com/miekg/dns/blob/84af068d469b2c93521aaa1d88745b613ac77a5d/sig0.go#L41
https://github.com/miekg/dns/blob/84af068d469b2c93521aaa1d88745b613ac77a5d/dnssec.go#L67-L78

Noting [this comment](https://github.com/miekg/dns/blob/84af068d469b2c93521aaa1d88745b613ac77a5d/dnssec.go#L305-L312), is there a mechanism by which ED25519 can work with SIG(0)?

Thanks!

**Comment by miekg** [comment]
Looks like a bug, and I can't discover why we used Hash(0) for this algo.
SIG(0) signing should just work IMO

**Comment by adam-burns** [comment]
Don't fully understand the why, but perhaps [this MR thread segment](https://github.com/miekg/dns/pull/458#discussion_r151066496) helps explain to someone who could?

Thanks again! :)

**Comment by adam-burns** [comment]
Is this comment in the crypto library code relevant to a fix?

https://github.com/golang/crypto/blob/dad33157f4bf4f89d0a15a28ea3ccee0bf2f48a5/ed25519/ed25519.go#L41-L46

**Comment by andrewtj** [comment]
It looks like SIG0 was overlooked when ED25519 was introduced. Both `SIG`'s `Sign` and `Verify` functions will need updating to do the same special casing [`RRSIG`'s `Sign`](https://github.com/miekg/dns/blob/84af068d469b2c93521aaa1d88745b613ac77a5d/dnssec.go#L304) does. It might make sense to introduce an internal null `hash.Hash` to make the code less gnarly.

**Comment by miekg** [comment]
that seems like a sensible idea, see https://github.com/miekg/dns/pull/1340 for a potential solution. Not as clean as I would like, but it passes the tests.

@adam-burns could you try that branch?

**Comment by tmthrgd** [comment]
Ed25519 uses `crypto.Hash(0)` as you don't prehash the message before signing like you would with other algorithms.

I overlooked the error case, but not the implementation. [RFC 8080](https://datatracker.ietf.org/doc/html/rfc8080) doesn't make any mention of SIG or SIG(0) records, only of RRSIG:
>   This document defines the use of DNSSEC's DS, DNSKEY, and RRSIG
>   resource records (RRs) with a new signing algorithm, EdDSA, using a
>   choice of two curves: Ed25519 and Ed448.

As far as I'm aware, there isn't any standard for doing this, as such the most we should do is return an error IMO.

**Comment by andrewtj** [comment]
BIND supports EdDSA. It also supports ECDSA and the RSA SHA2 family, which this package also supports and whose RFCs only mention DNSKEY and RRSIG.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] SIG(0) with ED25519..." ]
>Are you aware of any other software that implements Ed25519 for SIG(0)? I'm
>inclined to take the RFC at face value here and that it only intended support
>for the listed records.

I'm not aware anyone caring enough about sig(0) to write it down in an RFC. I do like to
just make it possible if people want to play with sig(0) and newer algorithms - regardless
of RFC status.

(The only nit would be that algorithm numbers don't much, but I can't recall if sig(0) and
dnssec algos are unified in any way)

**Comment by adam-burns** [comment]
> Are you aware of any other software that implements Ed25519 for SIG(0)? I'm inclined to take the RFC at face value here and that it only intended support for the listed records.

nsupdate implements SIG(0) message signing for authentication with Ed25519 keys generated by dnssec-keygen -a ED25519 (with -T DNSKEY | KEY) and BIND accepts and performs update. See https://bind9.readthedocs.io/en/latest/advanced.html#sig-0

**Comment by adam-burns** [comment]
> that seems like a sensible idea, see #1340 for a potential solution. Not as clean as I would like, but it passes the tests.
> 
> @adam-burns could you try that branch?

The branch removes the panic.

Initial tests indicate when i invoke `m.Unpack(mb)` on the message then send to DNS server, i get a `RcodeServerFailure` `ServFail` response.

I then added pre-validation tests in my code before sending to the server, based on sig0_test.go code:
```
                // verify signing
                var sigrrwire *dns.SIG
                switch rr := m.Extra[0].(type) {
                case *dns.SIG:
                        sigrrwire = rr
                default:
                        log.Fatalf("expected SIG RR, instead: %v", rr)
                }

                for _, rr := range []*dns.SIG{sig0RR, sigrrwire} {
                        id := "sig0RR"
                        if rr == sigrrwire {
                                id = "sigrrwire"
                        }
                        if err := rr.Verify(keyRR, mb); err != nil {
                                log.Fatalf("failed to verify “%s” signed SIG(%s): %v", algstr, id, err)
                        }
                }
```
This produces log entry `failed to verify “ED25519” signed SIG(sig0RR): dns: bad signature`

**Comment by miekg** [comment]
ack, it still works with the other algos? As that changed (a bit) as well.

**Comment by adam-burns** [comment]
> ack, it still works with the other algos? As that changed (a bit) as well.

Hmm. I tried running with a ECDSAP256SHA256 keypair (alg=13), which, with the same pre-verification above, indicated not , ie
`failed to verify “ECDSAP256SHA256” signed SIG(sig0RR): dns: bad signature`

**Comment by miekg** [comment]
adding ED25519 to TestSIG(0) make it just work? See PR

**Comment by miekg** [comment]
ok, then #1340 should be good to go @tmthrgd PTAL

**Comment by tmthrgd** [comment]
> ok, then #1340 should be good to go @tmthrgd PTAL

I’ll take a look and review tonight.

**Comment by tmthrgd** [comment]
If it’s implemented elsewhere, then we can do it. I don’t like that it’s not documented though. I guess we just have to live with that.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [miekg/dns] SIG(0) with ED25519..." ]
>If it’s implemented elsewhere, then we can do it. I don’t like that it’s not
>documented though. I guess we just have to live with that.

thought about that too. I feel this PR (or follow up) should document some of the things
said in this thread and say more about sig(0) and maybe a bit about dnssec as well.

**Comment by miekg** [comment]
has been merged. closing
