### ISSUE TITLE
Information cannot be passed from the TCP/UDP read decorators to server handler 

### ISSUE THREAD

**Issue by Fattouche** [miekg/dns#1345]
This allows server operators to pass data from the read decorators to the actual DNS handlers.
    
An example use case where this is needed is when there is any proxying service between eyeball and DNS server. In order
to preserve the client IP, the proxy server might have to use PROXY protocol v2. If you don't have a context you can read and see
the client IPs in the decorators but your handler will not know this information and therefore might not be able to do things like:
    
    1. Block specific IPs
    2. Verify TSIGs based off specific IP
    3. Respond with TSIGs based off source IP
    4. Respond with different answers based off Geo Location
    
Apart from knowing the source IP, there is other situations where you might want to pass information parsed in the read decorators to the handler.

**Comment by miekg** [comment]
context.Context didn't exist when this library was created, otherwise a _lot_ of function would have had a ctx argument. It's too late now. We could duplicate everything and add a context like the std library does, but it's a lot of churn, just to add a context.
