### ISSUE TITLE
TSIGProvider Generate and Verify functions don't have access to the DNS Message

### ISSUE THREAD

**Issue by Fattouche** [miekg/dns#1347]
This causes problems on zone transfers where the server is hosting many different zone names. Passing the DNS Message via the context as a parameter opens up many possibilities for how TSIGs are handled. For example:

1. We could use a sync.RWMutex to ensure that even after the server has been started, TSIGs can be rotated out of band without worrying about data races.
2. We could allow multiple zones with different names to support TSIGs with the same name. 

There is many more possibilities that this could open up. I.E Zone specific TSIG verification/Generation.

**Comment by miekg** [comment]
But you would only need the zone name, no? 
Also 'causes problems'  means what exactly?
