### ISSUE TITLE
 How to get server's ip from udp packet with destination ip?

### ISSUE THREAD

**Issue by victory460** [miekg/dns#1357]
https://github.com/miekg/dns/blob/dedee46bd49c8cec935b3db23bd036bccdd4eb1d/server.go#L43-L44
How to get server's ip from udp packet with destination ip? 
If server running on a host with multiple addresses, get one of local ip make confusing.
Thanks a lot.

**Comment by miekg** [comment]
if the packet hit your server, surely you can use LocalAddr(). Otherwise I don't understand the question.

**Comment by lk3687051** [comment]
@miekg  hello but when I bind it to 0.0.0.0  I always get  LocalAddr is  0.0.0.0, Not the real IP.
