### ISSUE TITLE
String() in SVCBAlpn conversion doesn't escape properly

### ISSUE THREAD

**Issue by shane-kerr** [miekg/dns#1361]
I _think_ the idea is that `String()` routines should provide something that is presentation format, suitable for DNS zone files.

The `SVCBAlpn` type contains an array of strings. If set via the `unpack()` function (or by direct initialization) it can contain non-printable characters, but the corresponding `String()` function does not attempt to escape them. Such DNS messages are bogus, of course, but such is DNS. The code in the `SVCBLocal` type properly escapes any values.

If this is a bug that makes sense to fix, I can submit a PR.

Note that the code in PR #1359 seems to have a similar issue.

**Comment by shane-kerr** [comment]
Here's a simple program demonstrating the issue:
https://go.dev/play/p/QjQB7IRdRB0

**Comment by miekg** [comment]
yes, Stringyfied value should be suitable for inclusion in zone files, so PR welcome.

thanks!

**Comment by shane-kerr** [comment]
Fixes merged!
