### ISSUE TITLE
Do you have any plans to support DoQ (DNS-over-Quic) in the near future?

### ISSUE THREAD

**Issue by viagram** [miekg/dns#1370]
I hope this is possible!

**Comment by miekg** [comment]
What do you miss/need? According to https://www.ietf.org/archive/id/draft-ietf-dprive-dnsoquic-12.html you can just create a net.Conn with some quic library and send queries.

Server side support will only happen once quic is in the std lib I guess, or we would need a ListenAndServe that takes a `listener`

**Comment by miekg** [comment]
quic-go uses Streams which are not net.Conn`s, and we don't want to pull all of that in this library. Quic/http3 is slowly happening in Go's std lib, until that is done I don't see what can be done in this library.

If you want to play with it yourself, various things can be wrapped in dns.Conn and the server could check if the conn support quic or some such

**Comment by miekg** [comment]
I haven't look too closely, but i would assume it would work like this:

You use a lib that does quic in Go (haven't looked lately, are there any?). That
should give you a net.Conn which can then be used.

There might be some need for helper functions, but we also don't have these for DoH, so I
don't think we should do that for DoQ either.

/Miek

--
Miek Gieben
