### ISSUE TITLE
IPSECKEY tag not supported

### ISSUE THREAD

**Issue by asergeyev** [miekg/dns#138]
IPSECKEY has following struct field:

    Gateway     string `dns:"ipseckey"`

This tag is not supported right now and it trips "bad tag packing string: ipseckey" error in  packStructValue.

By [RFC 4025](http://tools.ietf.org/html/rfc4025) that is ipv4 or v6 address depending on GatewayType field.  I'm not quite sure if I can fix this myself but want to file as issue for now.

**Comment by miekg** [comment]
I'm going to take a stab a fixing the IPSECKEY record the coming days (will be ugly).

**Comment by miekg** [comment]
See https://github.com/miekg/dns/commit/477cb4d3fac4a78db02381f0bc2bad51f9cce3d2

Somewhat "elegant". Only needs work in Unpack and some more tests.

**Comment by miekg** [comment]
Finished the rest (and added tests)

```
% ./q IPSECKEY @linode.atoom.net ipseckey.dnssex.nl       
;; opcode: QUERY, status: NOERROR, id: 21488
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 2

;; QUESTION SECTION:
;ipseckey.dnssex.nl.	IN	 IPSECKEY

;; ANSWER SECTION:
ipseckey.dnssex.nl.	86400	IN	IPSECKEY	10 1 2 192.0.2.3 AQNRU3mG7TVTO2BkR47usntb102uFJtugbo6BSGvgqt4AQ==

;; AUTHORITY SECTION:
dnssex.nl.	86400	IN	NS	linode.atoom.net.
dnssex.nl.	86400	IN	NS	ns-ext.nlnetlabs.nl.
dnssex.nl.	86400	IN	NS	omval.tednet.nl.

;; ADDITIONAL SECTION:
linode.atoom.net.	43200	IN	A	176.58.119.54
linode.atoom.net.	43200	IN	AAAA	2a01:7e00::f03c:91ff:feae:e74c

;; query time: 8964 µs, server: linode.atoom.net.:53(udp), size: 305 bytes
```

**Comment by asergeyev** [comment]
Very neat. I did not run it but tests seem to be covering all cases.
