### ISSUE TITLE
No way for HandlerFunc to know if the query came over TLS

### ISSUE THREAD

**Issue by jelu** [miekg/dns#1380]
I know this may be a corner case but I want to know if the `ResponseWriter` `LocalAddr()`/`RemoteAddr()` went over TLS or not.

I can't see a way to get to that information as `Server.Net` isn't really accessible in that callback and you can map multiple server against the same mux.

Only possible way to do this that I can see is to add a function (for example) `ServerNet` to `ResponseWriter` interface (or something similar).

Or maybe any of you have a better idea?

**Comment by miekg** [comment]
Why should it care?

Does net/http from the std lib have a way to do this?

**Comment by jelu** [comment]
> Does net/http from the std lib have a way to do this?

From what I can see, yes because you can pull it from `Request.URL`.

**Comment by jelu** [comment]
Nevermind, found a way.

**Comment by miekg** [comment]
Happy to be pointed to some code so I can paste it in this issue for
prosperity's sake

**Comment by jelu** [comment]
That code is not public but it was kinda easy (and a bit shameful I thought
of it after creating the issue), just map ip:port:tcp/udp to the real
protocol after creating the listener then use that for lookup using
ResponseWriter's LocalAddr().

**Comment by chantra** [comment]
@jelu couldn’t you use theConnectionState introduced in #728 ?

**Comment by jelu** [comment]
@chantra Oh hmm, yeah I've could have used that if I wanted to know if it was TLS or not and probably look at negotiated ALPN for DoT vs DoQ, but now with the mapping I can check for any protocol as long as they don't share port and IP protocol :D
