### ISSUE TITLE
big TXT record return only 3 values  

### ISSUE THREAD

**Issue by limbo127** [miekg/dns#1391]
Hello, 
we are using big TXT record 
example : 
./q TXT xxxx.cloud 
;; Truncated
;; opcode: QUERY, status: NOERROR, id: 9073
;; flags: qr tc rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; ANSWER SECTION:
xxx.	60	IN	TXT	"{'endpointV4  ***}"
xxx.	60	IN	TXT	"{'endpointV4'*** }" : 
xxx.	60	IN	TXT	"{'endpointV4':****}"

with dig 
nicolas@gallet:/tmp/exdns/q$ dig TXT xxxxx

; <<>> DiG 9.16.1-Ubuntu <<>> TXT xxxx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8919
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;xxxx IN	TXT

;; ANSWER SECTION:
xxx.	60	IN	TXT	"{'endpointV4  ***}"
xxx.	60	IN	TXT	"{'endpointV4'*** }" : 
xxx.	60	IN	TXT	"{'endpointV4':****}"
xxx.	60	IN	TXT	"{'endpointV4  ***}"
xxx.	60	IN	TXT	"{'endpointV4'*** }" : 
xxx.	60	IN	TXT	"{'endpointV4':****}"

Any suggestion ?
Regards, 
Nicolas

**Comment by miekg** [comment]
Truncated
