### ISSUE TITLE
Query regarding NSEC TypeBitMap 

### ISSUE THREAD

**Issue by andrewheberle** [miekg/dns#1393]
This is more a call for help rather than an issue, where I just have zero clue how to properly generate the `dns.NSEC.TypeBitMap` value for a `dns.NSEC` response.

I have read RFC4034, but I just can't grok what I need to set in a `[]uint16` slice to make things work.

For background I'm working on a mDNS responder, which as per RFC6762, negative responses for A/AAAA questions can be responded to using a NSEC record (rather than NXDOMAIN)...not for it's normal purpose for DNSEC, but instead as a way of expressing which records do or do not exist for a given name.

Is there any helper functions available or docs on how I put together such a response?

As an example, if I my application was to get a request for an A record for a service that only provided Ipv4 access, I would want to respond with the A record in `dns.Msg.Answer` (I'm fine with this), but also include a NSEC response in `dns.Msg.Extra` indicating that the AAAA is not available...or visa versa, which is often more common where I need to respond that AAAA is not available but A is so the client does not continue mDNS requests over and over again until a timeout is reached.

**Comment by miekg** [comment]
You should probably also read: https://www.rfc-editor.org/rfc/rfc7129

A too short reply:

if the actual name exist and the type doesn't you need to set the bitmap with the types
that _do_ exist.

If the name doesn't exist you need to look for the closest encloser and get its nsec, that
nsec should list the types of the closest encloser (iirc).

/Miek

--
Miek Gieben
