### ISSUE TITLE
Is there a way to unmarshal JSON into a dns.Msg

### ISSUE THREAD

**Issue by mosajjal** [miekg/dns#1405]
Hi, 

It appears that a JSON-marshalled dns.Msg can't be reliably converted back to dns.Msg using the default Marshaller. It throws this error

```
cannot unmarshal object into Go struct field Msg.Answer of type dns.RR
```

Is there a way to reliably do this? I reckon we might need to write separate JSON unmarshal functions for each RR and add that function to the interface? I haven't tested that though

**Comment by miekg** [comment]
DNS and json are not friends. However when using this lib for the conversion, why wouldn't the Unmarshal just work, i.e. what's missing?

**Comment by mosajjal** [comment]
https://go.dev/play/p/pNDALJt0jI6

this is just an example. the Answer section remains nil. what would you recommend for serializing the DNS object? I want to put them on a Kafka cluster and pick them up  somewhere else.

**Comment by miekg** [comment]
ah, so this would mean every RR type needs a json unmarshal function, which is not going to happen. 
You could convert to text or just the binary and pick that up on the other side.

**Comment by mosajjal** [comment]
just for future reference, I made a slow and dirty unmarshaller that actually spits out the equivalent `dns.Msg`-Marshalled object [here](https://gist.github.com/mosajjal/bb3800060b98204e0a8ad5c01fa640b5). Super ugly and slow (~25k per second) but gets the job done
