### ISSUE TITLE
dns.Client could support proxy

### ISSUE THREAD

**Issue by nervmor** [miekg/dns#1412]
I need to send dns resolve request to a ipv6 server, but my network is only ipv4 supported.
Could dns.Client supports proxy dialer like it used in net.http?
With this support and a socks5 proxy, my question is resolved.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/dns] dns.Client could suppor..." ]
>I need to send dns resolve request to a ipv6 server, but my network is only
>ipv4 supported.
>Could dns.Client supports proxy dialer like it used in net.http? With this
>support and a socks5 proxy, my question is resolved.

if you have a net.Conn you can make your own dns.Conn and use that.

**Comment by nervmor** [comment]
Oh, I see.
Use the ExchangeWithConn func with Conn created by my code.
Thanks a lot.
