### ISSUE TITLE
Client.Dialer uses a concrete type

### ISSUE THREAD

**Issue by linkdata** [miekg/dns#1419]
Because Client.Dialer has a concrete type (*net.Dialer), it's not possible to plug in another networking provider (e.g. WireGuard).
Please consider using the pattern used by e.g. https://pkg.go.dev/net/http#Transport (having a function variable) or https://pkg.go.dev/golang.org/x/net/proxy#ContextDialer (having an interface variable).

**Comment by tmthrgd** [comment]
This is already possible using `ExchangeWithConn`: https://github.com/miekg/dns/pull/1395#issuecomment-1373134672. Unfortunately the existing code cannot be changed without breaking backward-compatibility.
