### ISSUE TITLE
Request for adding public interface for sprintName function

### ISSUE THREAD

**Issue by grasstractor** [miekg/dns#1423]
Hi there,

I've been using your package and noticed that there's a private function called sprintName(other sprint* functions as well) that would be really useful for my use case. However, since it's currently not exposed as a public function, I can't call it directly. I'm wondering if you could add a public interface for this function, so that external packages can use it as well.

Thank you for your time and effort!

**Comment by tmthrgd** [comment]
`sprintName` is publicly exported as `(Name).String`: https://github.com/miekg/dns/blob/d8fbd0a7551ae5476df0eb003b247322761c6e82/defaults.go#L383-L386

`dns.Name(s).String()` is the same as `dns.sprintName(s)`. Does that cover your use case?

**Comment by grasstractor** [comment]
> 

Yes, thanks a lot, for now this solves my use case, but sprintTxt and sprintTxtOctet don't seem to have similar exposure, so I can't say if maybe they will be useful in the future.
