### ISSUE TITLE
The description in the comment section of the structure EDNS0_TCP_KEEPALIVE seems to be incorrect

### ISSUE THREAD

**Issue by grasstractor** [miekg/dns#1424]
https://github.com/miekg/dns/blob/d8fbd0a7551ae5476df0eb003b247322761c6e82/edns.go#L686-L688

Accoding to RFC7828: 

- OPTION-LENGTH:   the value 0 if the TIMEOUT is omitted, the value 2 if it is present;
- Clients MUST specify an OPTION-LENGTH of 0 and omit the TIMEOUT value.
- Servers MUST specify the TIMEOUT value that is currently associated with the TCP session. 
- The DNS server SHOULD send an edns-tcp-keepalive option with a timeout of 0 if it deems its local resources are too low too service more TCP keepalive sessions or if it wants clients to close currently open connections.

When a client initiates a query and wishes to maintain a tcp connection, it should set the length field to 0. That is, the client should set this field to always be 0.
But for the server, if the server supports keeping tcp connections, then it should set this field to 2 in the reply and set the value of timeout. And only when the server wants to close the tcp connection immediately, it should set the value of length to 0.

I initiated a request to a c-root‘s mirror server that included tcp-keep-alive, and from the response it looks like that should be correct.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/12790465/221557378-d3a69f4c-d8b2-4be0-8785-1e7ac157e8ea.png">

So while I agree that the length field is indeed useless, it is not deprecated as currently described, and I am not aware of any updates to the RFC7828 document.

**Comment by tmthrgd** [comment]
The field being deprecated refers specifically to the field in the `EDNS0_TCP_KEEPALIVE` struct not the field in the DNS wire-format. If you look, you'll notice that nothing reads or writes that field and it is indeed always zero.

Is there a practical problem here? Are there any situations where an explicit zero must be sent on the wire rather than omitting the timeout value? (That is `length == 2 && timeout == 0` rather than `length == 0`).

**Comment by grasstractor** [comment]
> The field being deprecated refers specifically to the field in the `EDNS0_TCP_KEEPALIVE` struct not the field in the DNS wire-format. If you look, you'll notice that nothing reads or writes that field and it is indeed always zero.
> 
> Is there a practical problem here? Are there any situations where an explicit zero must be sent on the wire rather than omitting the timeout value? (That is `length == 2 && timeout == 0` rather than `length == 0`).

The case of "length == 2 && timeout == 0" should not occur, but the case of "length == 2 && timeout! = 0" should be very common, if the length == 2 can be set correctly when replying to EDNS0_TCP_KEEPALIVE as a DNS server, then there should be no problem

**Comment by tmthrgd** [comment]
@grasstractor Okay great! Yes the library handles the length itself, it's simply the struct field that is ignored. If `timeout` is non-zero, it gets encoded on the wire correctly (`length = 2`) and if zero, it gets left out (`length = 0`). Will close this.
