### ISSUE TITLE
Userspace networking and setUDPSocketOptions

### ISSUE THREAD

**Issue by DentonGentry** [miekg/dns#1427]
I'm trying to build a DNS server where the UDP+IP stack runs entirely in userspace, on a [Tailscale network](https://tailscale.com/kb/1112/userspace-networking/) using [gVisor's netstack](https://gvisor.dev/docs/user_guide/networking/). I pass in a PacketConn from the userspace networking stack, but `ActivateAndServe` fails because `setUDPSocketOptions` fails.

I don't see a way to make this work: `setUDPSocketOptions` ends up making system calls to set socket options, which the userspace networking stack can neither implement nor intercept. Is there a different way to start a Server which would be more amenable? Do I need to write my own Server class and use this package for handling packet manipulation?

**Comment by tmthrgd** [comment]
@DentonGentry Hmm, interesting. There's certainly a lot of cool stuff happening over at Tailscale.

`setUDPSocketOptions` should only ever be called if the type of `PacketConn` is explicitly `*net.UDPConn`:
 
https://github.com/miekg/dns/blob/85afa114a5d1ecd5fe28ceefe3ab74ab7b931335/server.go#L363-L364

That could simply be avoided with `struct{ net.PacketConn }{pconn}` to hide the type.

From looking at the code you've referenced though, I don't quite understand how that case could be triggered. Are you sure that's the function that's failing?
