### ISSUE TITLE
LOC RFC correction

### ISSUE THREAD

**Issue by systemcrash** [miekg/dns#1437]
I think it should be [RFC1876](https://datatracker.ietf.org/doc/html/rfc1876) as it is on the lines below it

https://github.com/miekg/dns/blob/4c50fd8ad87911d21a9cf1f4d8a0ac03205fe1fa/types.go#L201

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/dns] LOC RFC correction (Iss..." ]
>I think it should be RFC1876 as it is on the lines below it
>
>https://github.com/miekg/dns/blob/4c50fd8ad87911d21a9cf1f4d8a0ac03205fe1fa/
>types.go#L201

yes, indeed
