### ISSUE TITLE
TXT Record Lookup has problems with aol.com

### ISSUE THREAD

**Issue by moverval** [miekg/dns#1448]
Hello everyone,

I am currently builting a type of custom mail server. I chose to use this project for looking up spf records, but sadly for some sites, neither an error nor the txt records are returned. It is important that all records are checked, else authorized mail will land in spam.

## Steps to reproduce

I wrote this function to lookup the record.

```go
func LookupSPF(domain string, nameserver string) (string, error) {
	m := new(dns.Msg)
	m.SetQuestion(dns.Fqdn(domain), dns.TypeTXT)
	c := new(dns.Client)
	c.Dialer = &net.Dialer{
		Timeout: 10 * time.Second,
	}
	in, _, err := c.Exchange(m, nameserver)

	if err != nil {
		return "", err
	}

	for _, answer := range in.Answer {
		if answer, ok := answer.(*dns.TXT); ok {
			for _, record := range answer.Txt {
				// if IsSPF(record) {
					return record, nil
				// }
			}
		}
	}

	return "", ErrNotFound
}
```

It works when I try to lookup the records for `gmail.com`, `nsa.gov`, `privateemail.com`, `...`, but the library doesn't return anything when I try to lookup the records for `aol.com`. `aol.de`, `aol.ru`, and other local variants are working again.

**Comment by karasz** [comment]
Hi, you should check if your message is not truncated and if so, you should increase the buffer size for the `dns.Client`. y default the `dns.Client` uses UDP with a 512B buffer.
