### ISSUE TITLE
Question: Can this library be used to script DNS changes on a Windows DNS server?

### ISSUE THREAD

**Issue by MarkKharitonov** [miekg/dns#1451]
Given:

- A Windows server machine where the Azure DevOps build service is configured to run as gMSA that has modify access to a certain DNS zone on a certain on-prem Windows DNS server.
- A Powershell code executed by the build service can use the DnsServer Powershell module to modify the DNS zone in question without explicit authentication. E.g. the following command just works:
```
Add-DnsServerResourceRecord -A -Name $HostName -IPv4Address $IpAddress -ZoneName $DnsZone -ComputerName $DnsServer -AllowUpdateAny -TimeToLive 01:00:00
```
- The DNS zone in question does NOT support the dynamic DNS updates.

Assuming the go code would be run by the same build service is it possible to modify that same DNS zone using this library? For example, what would be the equivalent of the aforementioned Powershell command?

I have also asked this question here - https://stackoverflow.com/questions/76020621/how-to-update-windows-dns-using-golang-instead-of-powershell

**Comment by tmthrgd** [comment]
No idea honestly. You could disassemble the PowerShell command to see what it's doing.

I'm going to close this though as this library simply implemented the various DNS RFCs. However windows might do things is out of scope, sorry.
