### ISSUE TITLE
Potential goroutine leak in server.go

### ISSUE THREAD

**Issue by hhheiaenia** [miekg/dns#1461]
I notice the ctx.Done() needs a cancel function to unblock the statement of ctx.Done in https://github.com/miekg/dns/blob/master/server.go#LL421C20-L421C20, since the case may block forever if the case not met.
  I was wondering if this may leak the goroutine where the ctx.Done() locates?
Maybe what I said is not right, thank you for taking a look.

**Comment by miekg** [comment]
do you have a test that exhibits this?
