### ISSUE TITLE
upstream message helper that return overflow errors is not using any of the exported defined errors

### ISSUE THREAD

**Issue by SriHarsha001** [miekg/dns#1463]
The upstream message helper https://github.com/miekg/dns/blob/d83d31bedae5ce562b4686f7fbd70d4cba94424d/msg_helpers.go that return overflow errors is not using any of the exported defined errors from the package - https://github.com/miekg/dns/blob/master/msg.go#L51-L71  

This came up in PR review here - https://github.com/coredns/coredns/pull/6003/files#r1154665103

"To accurately identify the error by type rather than string compares"

What is the recommendation to implement this or Should we create types for these (overflow) errors ?

**Comment by miekg** [comment]
yes, types would have been better.
we are well aware these strings are part of the public api
