### ISSUE TITLE
$INCLUDE and relative paths

### ISSUE THREAD

**Issue by tungol** [miekg/dns#1474]
Hi,

I see that previously this project changed from treating $INCUDE directives relative to the CWD to being relative to the file: https://github.com/miekg/dns/issues/537

As far as I can tell, however, this behavior is not specified by the RFC one way or another, and implementations vary. Here's the relevant standard:

RFC-1035:
```
Two control entries are defined: $ORIGIN and $INCLUDE.  $ORIGIN is
followed by a domain name, and resets the current origin for relative
domain names to the stated name.  $INCLUDE inserts the named file into
the current file, and may optionally specify a domain name that sets the
relative domain name origin for the included file.  $INCLUDE may also
have a comment.  Note that a $INCLUDE entry never changes the relative
origin of the parent file, regardless of changes to the relative origin
made within the included file.
```

That RFC obsoleted the earlier RFC-883 which had this to say:
```
      An include line begins with $INCLUDE, starting at the first line
      position, and is followed by a local file name and an optional
      offset modifier.  The filename follows the appropriate local
      conventions.  The offset is one or more labels that are added to
      the offset in use for the file that contained the $INCLUDE.  If
      the offset is omitted, the included file is loaded using the
      offset of the file that contained the $INCLUDE command.  For
      example, a file being loaded at offset ARPA might contain the
      following lines:

                $INCLUDE <subsys>isi.data ISI
                $INCLUDE <subsys>addresses.data

      The first line would be interpreted to direct loading of the file
      <subsys>isi.data at offset ISI.ARPA.  The second line would be
      interpreted as a request to load data at offset ARPA.

      Note that $INCLUDE commands do not cause data to be loaded into a
      different zone or tree; they are simply ways to allow data for a
      given zone to be organized in separate files.  For example,
      mailbox data might be kept separately from host data using this
      mechanism.
```

I haven't been able to find another RFC which discusses $INCLUDE directives, though it's entirely possible I missed one.

Given that the most we get from either of these is "The filename follows the appropriate local conventions", could the behavior of relative includes be made a configuration option? I have an existing set of zone files which use "relative to CWD" includes, and I can certainly update the files, but it might be nice if the library could support either mode of operation.

**Comment by tungol** [comment]
Thinking about it more, the most flexible option would be a way to specify the base for relative includes, generically. Default can be the file. Something like `func (zp *ZoneParser) SetIncludeRelativeBase (p string)` maybe? Then the caller would have full control.

**Comment by miekg** [comment]
i don't think we need flexibility here
