### ISSUE TITLE
Expose SVCB Service Params fully to clients

### ISSUE THREAD

**Issue by neilcook** [miekg/dns#1489]
Hi, I'm a co-author of draft-ietf-add-dnr (RFC-to-be 9463). We recently moved this draft from using SVCB Service Params Presentation Format to Wire Format.

This means that DHCP vendors and other folks wanting to support the DNR RFC will need to be able to parse Service Params in presentation format and output them on the wire. Tools such as your library would be most useful here, however currently you only expose SVCB type directly to clients, not the SVCBKeyValue type. It would be great if Service Params were supported directly. I'd be happy to submit a PR with some changes in this direction if this is amenable?

**Comment by miekg** [comment]
Seems like a good reason to expose those. Please open an PR.

**Comment by neilcook** [comment]
Thanks, will do
