### ISSUE TITLE
Method for creating wire-format dns.Header from *dns.Msg?

### ISSUE THREAD

**Issue by eest** [miekg/dns#1499]
Hello,

I have access to a `*dns.Msg`, and another system wants me to give it the wire-format representation of the header flags (basically `dns.Header.Bits`). Looking around in the docs I have not been able to find a way to go from a `*dns.Msg` to a `dns.Header` or just the `Bits` fields or similar, however I have found some internal code that basically does this here:
https://github.com/miekg/dns/blob/b18c05cc13607aacb056a0f483e0f4c9229a1d67/msg.go#L752

Using that code and a copy of the unexported consts at https://github.com/miekg/dns/blob/b18c05cc13607aacb056a0f483e0f4c9229a1d67/types.go#L190... I could definitely create my own function for this but I thought I would ask if it would be in-scope for the library to supply something like that.

**Comment by miekg** [comment]
you'll need to Pack your msg https://pkg.go.dev/github.com/miekg/dns#Msg.Pack
and get the first 12 bytes and index further in there.

**Comment by eest** [comment]
@miekg thanks for the response! In my case where I don't really need a full header, only the equivalent of the `Bits` field in https://pkg.go.dev/github.com/miekg/dns#Header, would it still be preferable to Pack the message and index into the resulting bytes, or should i just reproduce https://github.com/miekg/dns/blob/b18c05cc13607aacb056a0f483e0f4c9229a1d67/msg.go#L755-L779 using the existing parsed fields in my Msg?
