### ISSUE TITLE
digest type 3 (GOST94)

### ISSUE THREAD

**Issue by nirajsorathiya101** [miekg/dns#1537]
Hello,

Is GOST94 digest algorithm whose digest type value is 3 not supported by function ToDS  ?  I was trying to convert DNSKEY into DS using digest type 3 but I could not.  Digest type 3 case is not handled in the switch code block.  

I am using v1.1.55 but the latest version also doesn't handle the case for digest type 3 :  https://github.com/miekg/dns/blob/v1.1.58/dnssec.go

Please correct me if I missed something here. Also, I would appreciate if someone have any suggestions to solve this problem.

Thanks !

Best ,
Niraj

**Comment by miekg** [comment]
GOST is not in the GO std lib and thus is not supported.

[ Quoting ***@***.***> in "[miekg/dns] digest type 3 (GOST94) ..." ]
>Hello,
>
>Is GOST94 digest algorithm whose digest type value is 3 not supported by
>function ToDS ? I was trying to convert DNSKEY into DS using digest type 3 but
>I could not. Digest type 3 case is not handled in the switch code block.
>
>I am using v1.1.55 but the latest version also doesn't handle the case for
>digest type 3 : https://github.com/miekg/dns/blob/v1.1.58/dnssec.go
>
>Please correct me if I missed something here. Also, I would appreciate if
>someone have any suggestions to solve this problem.
>
>Thanks !
>
>Best ,
>Niraj
>
>—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>You are receiving this because you are subscribed to this thread.*Message ID:
>***@***.***>
>
/Miek

--
Miek Gieben

**Comment by nirajsorathiya101** [comment]
Thanks a lot for the information.

Best regards,
Niraj
