### ISSUE TITLE
Idiomatic way of printing the IPs / A records returned by a query

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [miekg/dns#1546]
I just want to get / print the IPs / A records of a simple query.

Is there a more idiomatic way of going about it, rather than splitting the answer as per the example below

```go
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/miekg/dns"
)

func main() {
	m1 := new(dns.Msg)
	m1.RecursionDesired = true
	m1.Question = make([]dns.Question, 1)
	m1.SetQuestion(dns.Fqdn("skroutz.gr"), dns.TypeA)
	c := new(dns.Client)
	in, rtt, err := c.Exchange(m1, "8.8.8.8:53")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Round Trip Time: %s\n", rtt)
	for i := range in.Answer {
		if t, ok := in.Answer[i].(*dns.A); ok {
			answerParts := strings.Split(t.String(), "\t")
			fmt.Println(answerParts[len(answerParts)-1])
		}
	}
}
```

**Comment by pantelis-karamolegkos** [comment]
good suggestion; I see that it prints something in the likes of 

```
185.6.76.42
185.6.76.42
```

Is there an inherent library way of getting this either as a `[].netIP` or at least `[]string` or do I have to resort to manual parsing?

**Comment by pantelis-karamolegkos** [comment]
(and I don't get why it fetches twice the same A record)

**Comment by janik-cloudflare** [comment]
> Is there an inherent library way of getting this either as a []netIP or at least []string or do I have to resort to manual parsing?

The `t.A` from @rdrozhdzh' comment is a `net.IP`. To get it into an array, though, you'll have to write a loop yourself, since you're combining data from multiple records.

> (and I don't get why it fetches twice the same A record)

It shouldn't and doesn't for me. Did you remove the `fmt.Println` you already had in your initial code above?
