### ISSUE TITLE
`NSEC(3) block too long in type bitmap` <- should the max size enforcement be relaxed?

### ISSUE THREAD

**Issue by apostasie** [miekg/dns#1583]
Currently, `dns` will error and bail if the specified bitmap length is over 32 (which is - obviously - in line with the spec):
https://github.com/miekg/dns/blob/master/msg_helpers.go#L481

However, some consumer devices apparently send larger bitmaps. This is probably not compliant, but definitely done in the wild...
(also seems like mDNS clients I did try do NOT reject these).

I am wondering if the restriction here could be lifted (and replaced by a warning?) to increase interoperability and satisfy Postel's law? Is there an angle to this that would preclude doing so?

**Comment by miekg** [comment]
sorry, Postel's law is sort of considered a mistake, esp in the DNS, so this check wlll not be relaxed.

**Comment by apostasie** [comment]
That's ok. Thanks @miekg !
