### ISSUE TITLE
UDP serving broken on master

### ISSUE THREAD

**Issue by johanbrandhorst** [miekg/dns#1593]
As explained in https://github.com/miekg/dns/pull/1589#issuecomment-2276738695:

> I think this change unfortunately interacts badly with the default read timeout used in UDP servers (not TCP servers, in my testing). The default read timeout is 2 seconds, and it seems that any UDP server started via `ListenAndServe` or `ActivateAndServer` dies after 2 seconds of no traffic. It seems the TCP server is staying open, not sure why. Presumably this was already happening before, but we were just automatically retrying the error and so it was hidden from us.
> Is timing out UDP reads repeatedly while serving intentional? Digging around in the history, it seems the `Temporary()` check for UDP was introduced to fix a different bug (https://github.com/miekg/dns/pull/621), but I don't see it acknowledged that this will cause us to loop endlessly (albeit not too busily).
> Maybe we want to revert this until we have a better understanding of the impact, because on `master` right now any UDP servers just stop immediately once the ReadTimeout is hit.

**Comment by miekg** [comment]
reverting that commit, see https://github.com/miekg/dns/pull/1594
