### ISSUE TITLE
Maybe dead lock in Server.ListenAndServe

### ISSUE THREAD

**Issue by bronze1man** [miekg/dns#161]
I just saw it accidentally.

Please look at https://github.com/miekg/dns/blob/master/server.go#L243
It looks like it will lock forever if call Server.ListenAndServe 3 times.

**Comment by bronze1man** [comment]
It is not the only dead lock in that file.
https://github.com/miekg/dns/blob/master/server.go#L289
https://github.com/miekg/dns/blob/master/server.go#L320

**Comment by miekg** [comment]
yep. Thanks!
