### ISSUE TITLE
Support NODATA (NSEC/NSEC3 use case)

### ISSUE THREAD

**Issue by xinbenlv** [miekg/dns#1615]
For use case of NSEC/NSEC3 it seems a requirement to support NODATA, and this repo doesn't yet.

See the latest [RFC 9077](https://datatracker.ietf.org/doc/html/rfc9077) it reads

```md
[[RFC2308](https://datatracker.ietf.org/doc/html/rfc2308)] defines the TTL of the
Start of Authority (SOA) record that must be returned in negative answers
(NXDOMAIN or NODATA):
```

Case:

We are trying to deny existence of MX records or TXT records of a domain and only to found that CoreDNS doesn't support NODATA. After digging, I found that it's due to the dependency of this repo from 

See 

- [The line where CoreDNS parses StringToRcode](https://github.com/coredns/coredns/blob/387f34db9a4f6fefd4a6b54884772ccd4fc059e7/plugin/rewrite/rcode.go#L174)
- [The line CoreDNS parsing StringToRcode depends on miekg/dns](https://github.com/coredns/coredns/blob/387f34db9a4f6fefd4a6b54884772ccd4fc059e7/plugin/rewrite/rcode.go#L13)

Previously the request within this repo to support NODATA is in #428

**Comment by Chreo** [comment]
I trust you are aware that "NODATA" is not a defined RCODE (https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6)
When we say "NODATA" that is pseudo for NOERROR RCODE with an empty ANSWER section
That said. I could be potentially useful to have a helper function for DNS messages being defined as:
`func (m Msg) IsNODATAResponse() bool`
but as with anything, code talks...

**Comment by miekg** [comment]
thanks @Chreo 

this is completely not understanding how dns works
