### ISSUE TITLE
server.go's WriteMsg doesn't account for message size

### ISSUE THREAD

**Issue by michaelharo** [miekg/dns#162]
It's possible to create a reply message in a handler that is larger than the client will expect (>512 bytes w/o EDNS or >specified size with EDNS UDP size set).  When a reply message with UDP is too large I think the truncated flag should be set.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] server.go's WriteMsg doesn't ..." ]
>It's possible to create a reply message in a handler that is larger than the client will expect (>512 bytes w/o EDNS or >specified size with EDNS UDP size set). 

Yes, that's perfectly possible.

> When a reply message with UDP is too large I think the truncated flag should be set.

You must do this yourself in the handler.

/Miek

--
Miek Gieben

**Comment by michaelharo** [comment]
I'm unclear how to tell from the handler that the message will be too big.  As far as I can tell,  ResponseWriter.WriteMsg updates the message to handle tsig and that could alter the size of the message after the handler hands the message to WriteMsg.

Is the intended solution for my handler to handle tsig itself, call Pack() from the handler, check the size of the message, possibly set Truncated=true and rePack() + truncate the buffer, and then directly call Write instead of using WriteMsg?

**Comment by tsenart** [comment]
@miekg: Would you please explain why users of the library should set the TC bit themselves?

**Comment by andrewtj** [comment]
@tsenart I assume it's because setting the TC bit is not always the most appropriate behaviour. I could see some helpers for the common cases being useful, but this issue isn't really the place for that discussion.

**Comment by miekg** [comment]
+1 to what @andrewtj says. Also doing the TC stuff in WriteMsg is quite late in the game. In general the pattern for creating a response that fits, is building the message RRset by RRset and checking the Len() when you are doing that. For instance when adding RRsets to the additional section one should favor AAAA records when the original request was over IPv6 and also put some A's in there. With a request coming in over IPv4 the AAAA's might not be needed in the first place.

@andrewtj what helper function do you think will be useful?

**Comment by andrewtj** [comment]
@miekg maybe something to determine the appropriate payload size given the transport and clients message, and a packer that shrinks the Additional section if it can or drops the body and truncates otherwise (doing the right thing by Opt, RRSets, TSIG, etc).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] server.go's WriteMsg does..." ]
>@miekg maybe something to determine the appropriate payload size given the
>transport and clients message, and a packer that shrinks the Additional section
>if it can or drops the body and truncates otherwise (doing the right thing by
>Opt, RRSets, TSIG, etc).

Yes, ShrinkToSize(), I'll open an issue.

>---
>Reply to this email directly or view it on GitHub:
>https://github.com/miekg/dns/issues/162#issuecomment-112982399
/Miek

--
Miek Gieben
