### ISSUE TITLE
Improve String formatting for types

### ISSUE THREAD

**Issue by michaelharo** [miekg/dns#163]
I was looking into adding query logging to debug logs my program and wanted to use Question.String(), but String's formatting is geared towards dig style output and that's not ideal for a log file since it starts with a semicolon and includes tabs for whitespace.  In the end I ended up writing my own toString function that gave me "{name} {qclass} {qtype}" or "github.com. IN A".

I'm unsure what to suggest as a fix since I can see String behaving like dig as useful for how everything else behaves currently.  Maybe a package level setting or something for StringMode that may be set to "dig" or "plain" where "dig" is the current behavior and "plain" (or some better name) just prints the data from that type as a string without special formatting?  Or an sprintf style solution that may have a default formatter set for each type?

**Comment by miekg** [comment]
I think the cleanest way to do this is having a Printf/Sprintf family of functions, with special go-dns format strings in there. Prefxing each formatter with d seems to make sense, so:

* domain name: %dd
* ttl: %dt
* rdata: %dr  (splitting this one up is trickier, this might be extended with %<num>dr to say I want to print the <num>-th rdata (although this clashes with the "standard" way how formatters work)
* class: %dc
* ...

Maybe some more is needed to say,  print as int or string (so TTL might be printed as 84600 or 1d). The new string is then given to fmt.S/Fprintf to take care of the remaining formatters.

**Comment by miekg** [comment]
Turns out you can easily add custom formatters to the fmt package.

**Comment by miekg** [comment]
The soon to be merged 'format' branch, see https://github.com/miekg/dns/commit/aaa3aba4ed1c5273b1e0f7afa38e2a14564bb78e for the documentation. I've chosen the verbs to not clash with the current ones. Some stuff remains to be implemented.

**Comment by miekg** [comment]
What is actually the problem of writing your own? Getting the class (for instance). Is just a matter of
```
Class(r.Class).String()))
```

Getting access to the rdata *is* something that might be needed. I'm thinking of dropping the format modifiers and only focusing on the Field function in there (=format branch)

**Comment by miekg** [comment]
Merged format branch.
