### ISSUE TITLE
A records are stored as 16 bytes

### ISSUE THREAD

**Issue by miekg** [miekg/dns#166]
While working on the format branch I noticed that rr.A's are stored as 16 bytes. Even if you call To4() on it. Seems to be a limitation in the net package, but it is wasteful none the less.

**Comment by asergeyev** [comment]
Seem like adding copy of net.parseIPv4 with edited return and use it in setA and may be other places. 

I use int IPs for v4 but I added modified version that seem to do what you need, feel free to use it, repo is public domain code:  https://github.com/asergeyev/go-toys/tree/master/loadip (so far I'd ask to not import from there, that's unstable place)

**Comment by michaelharo** [comment]
I'm not sure I understand the problem.  When you call To4() on a net.IP you get back a 4 byte slice (or nil).  I confirmed this by looking at http://play.golang.org/p/98OA0dt7X8.

**Comment by asergeyev** [comment]
To4 just creates new slice without actually releasing underlying structure of 16. 
See http://blog.golang.org/go-slices-usage-and-internals  FindDigits/CopyDigits example. And copying each IP to new slice is somewhat wasteful so I suggested solution with new parser for v4 that could replace ParseIP(string).To4() combination.

**Comment by miekg** [comment]
I welcome a pr :-) don't have much time to work on this specific issue
myself.

**Comment by asergeyev** [comment]
Do you want to have some test that would actually show that we won some memory overall?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] A records are stored as 1..." ]
>Do you want to have some test that would actually show that we won some memory overall?

That would be really awesome

**Comment by asergeyev** [comment]
will do, in other PR though... we can merge test first, measure and merge fix, measure again then.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] A records are stored as 1..." ]
>will do, in other PR though... we can merge test first, measure and merge fix, measure again then.

fair enough, this doesn't have to be in the test. But some numbers would be
nice.

/Miek

--
Miek Gieben

**Comment by asergeyev** [comment]
// see PR, test converted to benchmark that shows no memory difference at high counts of iterations.
