### ISSUE TITLE
c.Exchange does not support long responses like AXFR

### ISSUE THREAD

**Issue by StalkR** [miekg/dns#167]
Hi there, cool library! I'm using it to build a "reverse proxy" that redirects requests to one server or another depending on the domain asked.
It works well, but I'm having an issue with AXFR: it looks like [c.Exchange](https://github.com/miekg/dns/blob/master/client.go#L156) only reads one message, not the whole thing?

To reproduce, sample proxy code:
```
package main

import (
        "log"

        "github.com/miekg/dns"
)

func main() {
        server := &dns.Server{Addr: ":53", Net: "tcp"}
        dns.HandleFunc(".", proxy)
        log.Fatal(server.ListenAndServe())
}

func proxy(w dns.ResponseWriter, req *dns.Msg) {
        c := &dns.Client{Net: "tcp"}
        resp, _, err := c.Exchange(req, "37.187.31.39:53")
        if err != nil {
                log.Println(w.RemoteAddr(), err)
                dns.HandleFailed(w, req)
                return
        }
        w.WriteMsg(resp)
}
```
Update IP with an existing DNS server that allows AXFR for a domain, then:
```
$ dig axfr stalkr.net @localhost +tcp
; <<>> DiG 9.9.5-6-Debian <<>> AXFR stalkr.net @localhost +tcp
;; global options: +cmd
stalkr.net.             3600    IN      SOA     ns0.stalkr.net. hostmaster.stalkr.net. 2015001401 3600 1800 604800 86400
stalkr.net.             3600    IN      RRSIG   SOA 8 2 3600 20150122000000 20150108000000 61206 stalkr.net. rhCGJDljnE9DVU2eVYxp7+JKxArEkJ567ydX0zDXOPS5KnTKfscO+qT1 2TDzm8Dy8jHHXTJKjdj34k4fRB7NtpByIXcTiv7g/Kf2mf33PCOBy8ti /QbHBH0ugLht6Onn+1XV4aCWWDBwL6xeLTF+7Q4UtayM50/p4YI1gV6I D6M=
;; communications error to 37.187.31.39#53: end of file
```

I'm explicitly using tcp to rule out a possible issue with udp/edns0/max message size.

**Comment by StalkR** [comment]
I suggest #168 to resolve this:
```
$ dig axfr stalkr.net @localhost +tcp
[...]
;; XFR size: 270 records (messages 1, bytes 34389)
```
You can notice only 1 message. If we do a direct query to the nameserver we can see it aggregated 5:
```
$ dig axfr stalkr.net @ns0.stalkr.net +tcp
;; XFR size: 270 records (messages 5, bytes 29482)
```

**Comment by andrewtj** [comment]
#168 will break for your use case if the zone is large as messages transmitted over TCP are limited by a two-byte length prefix.

Is there a reason you're not using [dns.Transfer](http://godoc.org/github.com/miekg/dns#Transfer)?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] c.Exchange does not suppo..." ]
>I suggest #168 to resolve this:
>```
>$ dig axfr stalkr.net @localhost +tcp
>[...]
>;; XFR size: 270 records (messages 1, bytes 34389)
>```
>You can notice only 1 message. If we do a direct query to the nameserver we can see it aggregated 5:
>```
>$ dig axfr stalkr.net @ns0.stalkr.net +tcp
>;; XFR size: 270 records (messages 5, bytes 29482)
>```

This should "just work" although it is badly tested.

--
Miek Gieben

**Comment by miekg** [comment]
In your proxy handler you need to look for the AXFR qtype and specifically handle that case (and IXFR) and use dns.Transfer.

**Comment by StalkR** [comment]
Hey guys, thanks for the quick replies!

I didn't see `dns.Transfer`, I just tried (see below).
I'm ok to have specific code to handle transfer, but it doesn't feel like the right solution: in my opinion a transfer is just another type of DNS query and it should work with a `dns.Client`? After all, it's entirely possible a normal query (not a transfer) returns more than one message and a `dns.Client` should be able to handle it in its `c.Exchange`. What do you think?


Taking the example code above and adding special support for zone transfer:
```
func proxy(w dns.ResponseWriter, req *dns.Msg) {
  transfer := false
  for _, q := range req.Question {
    switch q.Qtype {
    case dns.TypeIXFR, dns.TypeAXFR:
      transfer = true
    }
  }
  if transfer {
    t := new(dns.Transfer)
    c, err := t.In(req, "37.187.31.39:53")
    if err != nil {
      log.Println(w.RemoteAddr(), err)
      dns.HandleFailed(w, req)
      return
    }
    t.Out(w, req, c)
    return
  }

  c := &dns.Client{Net: "tcp"}
  resp, _, err := c.Exchange(req, "37.187.31.39:53")
  if err != nil {
    log.Println(w.RemoteAddr(), err)
    dns.HandleFailed(w, req)
    return
  }
  w.WriteMsg(resp)
}
```
First, am I using it right?

There are a few records, but a bunch of data is missing:
```
$ dig axfr stalkr.net @localhost +tcp
[...]
;; XFR size: 3 records (messages 2, bytes 12140)

$ dig axfr stalkr.net @37.187.31.39 +tcp
[...]
;; XFR size: 270 records (messages 5, bytes 29537)

$ diff <(dig axfr stalkr.net @37.187.31.39 +tcp | grep -v '^;' | sort -u) <(dig axfr stalkr.net @localhost +tcp | grep -v '^;' | sort -u)
```

Also sometimes I'm hitting this [panic](https://github.com/miekg/dns/blob/master/server.go#L596):
```
$ go run proxy.go
panic: not reached

goroutine 24 [running]:
github.com/miekg/dns.(*response).Write(0xc20807d440, 0xc20807e000, 0x8604, 0x8daa, 0x0, 0x0, 0x0)
        ~/go/src/github.com/miekg/dns/server.go:596 +0x51d
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] c.Exchange does not suppo..." ]
>Hey guys, thanks for the quick replies!
>
>I didn't see `dns.Transfer`, I just tried (see below).
>I'm ok to have specific code to handle transfer, but it doesn't feel like the right solution: in my opinion a transfer is just another type of DNS query and it should work with a `dns.Client`? After all, it's entirely possible a normal query (not a transfer) returns more than one message and a `dns.Client` should be able to handle it in its `c.Exchange`. What do you think?

No, a transfer is something completely different, although it looks eerily
similar to just exchanging message. Esp with Tsig stuff is different. If you go
back in the history of this project, you will find failed attempts to make AXFR
(and IXFR!) work with Exchange.

It's entirely *impossible* for a normal query to return more than one message.
If you think otherwise, please point to the relevant RFC :-)

>Taking the example code above and adding special support for zone transfer:
>```
>func proxy(w dns.ResponseWriter, req *dns.Msg) {
>  transfer := false
>  for _, q := range req.Question {
>    switch q.Qtype {
>    case dns.TypeIXFR, dns.TypeAXFR:
>      transfer = true
>    }
>  }
>  if transfer {
>    t := new(dns.Transfer)
>    c, err := t.In(req, "37.187.31.39:53")
>    if err != nil {
>      log.Println(w.RemoteAddr(), err)
>      dns.HandleFailed(w, req)
>      return
>    }
>    t.Out(w, req, c)
>    return
>  }
>
>  c := &dns.Client{Net: "tcp"}
>  resp, _, err := c.Exchange(req, "37.187.31.39:53")
>  if err != nil {
>    log.Println(w.RemoteAddr(), err)
>    dns.HandleFailed(w, req)
>    return
>  }
>  w.WriteMsg(resp)
>}
>```
>First, am I using it right?

Almost, as the documentation shows:

         c, err := t.In(m, "176.58.119.54:53")
         for r := range c { /* r.RR */ }

you need to range over the channel.

>There are a few records, but a bunch of data is missing:
>```
>$ dig axfr stalkr.net @localhost +tcp
>[...]
>;; XFR size: 3 records (messages 2, bytes 12140)
>
>$ dig axfr stalkr.net @37.187.31.39 +tcp
>[...]
>;; XFR size: 270 records (messages 5, bytes 29537)
>
>$ diff <(dig axfr stalkr.net @37.187.31.39 +tcp | grep -v '^;' | sort -u) <(dig axfr stalkr.net @localhost +tcp | grep -v '^;' | sort -u)
>```
>Also sometimes I'm hitting this [panic](https://github.com/miekg/dns/blob/master/server.go#L596):
>```
>$ go run proxy.go
>panic: not reached
>
>goroutine 24 [running]:
>github.com/miekg/dns.(*response).Write(0xc20807d440, 0xc20807e000, 0x8604, 0x8daa, 0x0, 0x0, 0x0)
>        ~/go/src/github.com/miekg/dns/server.go:596 +0x51d
>```

That's a bug. Hmmm, w.udp/w.tcp is not set in this case. I'll look into it.

/Miek

--
Miek Gieben

**Comment by StalkR** [comment]
> you need to range over the channel.
I saw that, I also saw [`t.Out`](https://github.com/miekg/dns/blob/master/xfr.go#L169) which does exactly this, so maybe the bug is in there?

**Comment by StalkR** [comment]
By the way, it looks like a race condition because the diff is not constant.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] c.Exchange does not suppo..." ]
>> you need to range over the channel.
>I saw that, I also saw [`t.Out`](https://github.com/miekg/dns/blob/master/xfr.go#L169) which does exactly this, so maybe the bug is in there?

t.Out: Out performs an outgoing transfer with the client connecting in w. 
This is when a *server* needs to output an axfr response.

But there is a bug there somewhere, otherwise you would not hit the panic.

>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/miekg/dns/issues/167#issuecomment-70059558
/Miek

--
Miek Gieben

**Comment by StalkR** [comment]
Yes, the proxy is both a client (when it asks the axfr to the real server), and a server (when it replies to the client).

**Comment by StalkR** [comment]
I think I found the issues:
- for the lost messages: as I suspected this `Envelope` is loosing information along the way, keeping the raw `Msg` and using it for `Out` solves this
- for the panic: `Out` doesn't wait for the goroutine, I made it synchronous

See https://github.com/StalkR/dns/compare/xfr?expand=1
Now the transfer is complete every time and doesn't crash.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] c.Exchange does not suppo..." ]
>I think I found the issues:
>- for the lost messages: as I suspected this `Envelope` is loosing information along the way, keeping the raw `Msg` and using it for `Out` solves this


Ah, the old 'concurrent access to shared data', this should have a simpler fix
than what you propose, but thanks for looking into it.

>- for the panic: `Out` doesn't wait for the goroutine, I made it synchronous

Hmmm, I wonder why I did that in the first place... Can you wrap this part in a
PR?

>See https://github.com/StalkR/dns/compare/xfr?expand=1
>Now the transfer is complete every time and doesn't crash.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] c.Exchange does not suppo..." ]
>By the way, it looks like a race condition because the diff is not constant.

So, with your PR merged, this still needs to be fixed. I'll take a look later
today.

/Miek

--
Miek Gieben

**Comment by StalkR** [comment]
Cool, so with #170 and #171 merged it solves everything. Thanks!
