### ISSUE TITLE
test AXFR code path(s)

### ISSUE THREAD

**Issue by miekg** [miekg/dns#169]
AXFR/IXFR is currently undertested. Please fix.

I could use miek.nl as a test domain, but I rather up a local server and axfr from that. Problem with that approach is that I'm testing the client code against the server code and not a third party axfr provider.

**Comment by flebarbe** [comment]
The IXFR query includes an SOA. The SOA looks uncomplete in my tests : The Primary name server and Responsible authority's mailbox fields are missing so the request is malformed. Do you confirm ?

**Comment by miekg** [comment]
Do you have some test code?

Currently the xfr test are commented out. Let me fix that as a first step.

**Comment by flebarbe** [comment]
The code I have is currently not in a state that I can share. :o)
The server I transfer from is not public anyway.
For now I just create an IXFR message and send it out.
I capture the request via tcpdump and inspect it with wireshark. It shows a malformed request.
There is 1 Authority RR in the request. This RR is an SOA field. However, this SOA field misses the Primary name server and Responsible authority's mailbox fields. The next field (serial number) is there but there are 2 missing.

**Comment by miekg** [comment]
How do you make the initial packet with setIxfr? That function looks a bit suspicious. I need to lookup what those values need to be, but setIxfr isn't setting them.

**Comment by flebarbe** [comment]
Section 3.3.13 of rfc 1035 defines the content of an SOA. From my understanding and from my tests with the current code, the two MNAME and RNAME fields are missing. The rest looks ok so far.

**Comment by miekg** [comment]
Yes, sure they must not be empty, but wondering what RFC 1995 says about the value in there.

In your code you can set the values "by hand", if you are stuck. That should make it work again.

**Comment by miekg** [comment]
ah, it must match the zones' one, which makes sense.

**Comment by flebarbe** [comment]
RFC 1995 section 3 reads :
    The IXFR query packet format is the same as that of a normal DNS
    query, but with the query type being IXFR and the authority section
    containing the SOA record of client's version of the zone.

The client is supposed to set MNAME and RNAME to the one it has. In this case, setIxfr() would need 2 more args.

In the meantime, I'd appreciate guidance as to how to set the values "by hand".

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] test AXFR code path(s) (#..." ]
>RFC 1995 section 3 reads :
>    The IXFR query packet format is the same as that of a normal DNS
>    query, but with the query type being IXFR and the authority section
>    containing the SOA record of client's version of the zone.
>
>The client is supposed to set MNAME and RNAME to the one it has. In this case, setIxfr() would need 2 more args.

yes, indeed.

>In the meantime, I'd appreciate guidance as to how to set the values "by hand".

Just access the SOA in the message and set the Ns and Mbox fields.

/Miek

--
Miek Gieben

**Comment by flebarbe** [comment]
The issue I had with missing MNAME and RNAME fields has been fixed by commit f2aff624fc8331a99f54097539f7ebd5bf2e1c87
