### ISSUE TITLE
TestClientAXFR failing

### ISSUE THREAD

**Issue by FiloSottile** [miekg/dns#174]
```
--- FAIL: TestClientAXFR (0.00s)
	xfr_test.go:34: error dns: no SOA
FAIL
```

**Comment by FiloSottile** [comment]
Platform: Darwin; Commit: f2aff62

**Comment by miekg** [comment]
This "let's use my homeserver for testing" might not be the best thing in the world...

```
--- FAIL: TestClientAXFR (0.00s)
	xfr_test.go:29: failed to setup axfr: dial tcp :53: connection refused
	xfr_test.go:30: 
FAIL
exit status 1
FAIL	github.com/miekg/dns	11.425s
```

**Comment by andrewtj** [comment]
[SIDN Labs DNS Workbench](https://workbench.sidnlabs.nl/index.html) might be a good alternative. Would introduce some variety and allow for testing TSIG too.

**Comment by miekg** [comment]
Yes, that would work better.
