### ISSUE TITLE
TSig check on second DNS message fails (TCP)

### ISSUE THREAD

**Issue by flebarbe** [miekg/dns#180]
I'm issuing an IXFR query using the lib and a TCP connection.
In my case, the server answers with several DNS messages (about 5000 RR total, each DNS message has about 1300 RR). TSigVerify returns ok on the first DNS message. Starting with the second DNS message, it fails because the received MAC and the computed one do not match.

This is implemented in tsig.go.
I had a look at RFC 2845 and the related section "4.4. TSIG on TCP connection".
Looking at the code, I'm not sure the correct elements are included in the byte stream that is hashed. Has anyone ever had success with this ?

**Comment by miekg** [comment]
There could be bugs lurking here... Yes. Can I publicly AXFR from your
server to test?

**Comment by miekg** [comment]
Ah, IXFR and TCP...Hmmm.

**Comment by flebarbe** [comment]
The server is public, but the key I use is not. :)

**Comment by andrewtj** [comment]
Had a quick look at this. Changing `(t *Transfer) ReadMsg()` to update `t.tsigRequestMAC` with `ts.MAC` following the call to `TsigVerify` allows a successful multi-envelope AXFR from a BIND test install. I'd need to revisit the RFC and find out what the behaviour of servers in the wild is before calling this a fix though as if memory serves a TSIG on every envelope isn't required (just first and last) with intermediary ones optionally being concatenated.

**Comment by miekg** [comment]
Cool.

tsig is required on each envelop except that you only check the running MAC, i.e. not the full message (AFAIK)

**Comment by miekg** [comment]
Can this be closed now?

**Comment by flebarbe** [comment]
yes.
