### ISSUE TITLE
Truncated packet handling

### ISSUE THREAD

**Issue by swynter-ladbrokes** [miekg/dns#181]
Greetings,

Having a little problem with truncated packet handling.
dig/regular dns seems to be able to handle truncated packets just fine but this library just ignores them completely.

![screen shot 2015-02-12 at 08 08 13](https://cloud.githubusercontent.com/assets/8284169/6157588/5ad34d76-b28e-11e4-9e63-a8d75370623c.png)

**Comment by miekg** [comment]
Would do you mean with "ignore"? And yes, if you don't handle the TC bit yourself (with this package), it's not handled for you.

**Comment by swynter-ladbrokes** [comment]
```
	// If we see a TC bit being set we return here, without
	// an error, because technically it isn't an error. So return
	// without parsing the potentially corrupt packet and hitting an error.
	// TODO(miek): this isn't the best strategy!
	if dns.Truncated {
		dns.Answer = nil
		dns.Ns = nil
		dns.Extra = nil
		return nil
	}
```

I mean a response comes in with a TC bit set and I get nothing

**Comment by swynter-ladbrokes** [comment]
Just to add - I'm making a TCP request to the upstream, the upstream appears to be making that request as UDP which is how the truncate flag is getting set.

I'm not saying this library is doing the wrong thing, but it'd be nice if I could at least get the packet back :D

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Truncated packet handling..." ]
>Just to add - I'm making a TCP request to the upstream, the upstream appears to be making that request as UDP which is how the truncate flag is getting set.
>
>I'm not saying this library is doing the wrong thing, but it'd be nice if I could at least get the packet back :D

You didn't show any code so it's hard to say what's wrong here. That an upstream
"converts" tcp into udp is not unheard of. But a TC bit on TCP request is not
valid in DNS. What should a resolver do?

So I'm still not sure what you're doing here and if there is a bug.

/Miek

--
Miek Gieben
