### ISSUE TITLE
DNSSEC validation

### ISSUE THREAD

**Issue by corny** [miekg/dns#185]
How can I import the root keys and what do I have to do to validate DNS results?
* `sigok.verteiltesysteme.net` should be valid
* `sigfail.verteiltesysteme.net` should be bogus

A piece of example code - or even better a client test would be great.

**Comment by miekg** [comment]
You need to write a full blown dnssec resolver, which is by no means easy. See miekg/unbound for a Go wrapper for unbound.

I'm no aware of a Go only DNSSEC resolver.

**Comment by corny** [comment]
Ok, thanks. I will try your unbound wrapper.

**Comment by corny** [comment]
I tried your libunbound wrapper. Unfortunately libunbound creates a thread for every lookup. Your Go library works well with 4 threads and 4000 go routines. It resolves around 240k domains per minute.
https://github.com/corny/dnsresolver/tree/master

libunbound does not scale well because having more than 50 threads does not result in more lookups per second on my machine. It makes around 6500 domains per minute with DNSSEC.
https://github.com/corny/dnsresolver/tree/libunbound

I reopen this issue because a validating recursive resolver in Go would be nice to heave.

**Comment by miekg** [comment]
True...

except writing such a beast is a multi-year effort.
