### ISSUE TITLE
Setting MsgHeader.RecursionDesired before calling SetQuestion causes value to be overwritten

### ISSUE THREAD

**Issue by aeden** [miekg/dns#196]
```golang
msg.Question = make([]dns.Question, 1)
msg.SetQuestion(dns.Fqdn(qname), qtype)
msg.MsgHdr.RecursionDesired = false
```

The RecursionDesired flag is false

```golang
msg.Question = make([]dns.Question, 1)
msg.MsgHdr.RecursionDesired = false
msg.SetQuestion(dns.Fqdn(qname), qtype)
```

The RecursionDesired flag is true.

**Comment by aeden** [comment]
Random bit of knowledge: the .io name servers timeout if you attempt to call them with RD=1. True story.

**Comment by miekg** [comment]
Yes, by design, but I see how this is not helpful. Extra documentation would help, not sure if I want to remove setting the header bits in SetQuestion.

**Comment by miekg** [comment]
This is basically WAI.

**Comment by aeden** [comment]
Just for my edification, what does WAI stand for?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Setting MsgHeader.Recursi..." ]
>Just for my edification, what does WAI stand for?

Work As Intented (After I updated the docs that is :) )
