### ISSUE TITLE
Convert between ACE and unicode fail with a domain with hyphen

### ISSUE THREAD

**Issue by gustavo-hms** [miekg/dns#198]
If an unicode domain has hyphen, ToPunycode converts it correctly to an ACE domain, but if I try to convert it back using FromPunycode, it generates a wrong result.

``` go
package main

import "github.com/miekg/dns/idn"

func main() {
	fqdn := "mamão-com-açúcar.com.br"
	fqdn = idn.ToPunycode(fqdn)
	println(fqdn, idn.FromPunycode(fqdn))
}
```

The above excerpt prints 
```
xn--mamo-com-acar-yeb1e6q.com.br xn--mamo-com-acar-yeb1e6q.com.br
```

This page does the right convertion: http://mct.verisign-grs.com/convertServlet?input=xn--mamo-com-acar-yeb1e6q.com.br

**Comment by miekg** [comment]
@asergeyev could you comment here? Don't have enough time to
delve into this as well. Thanks!

**Comment by asergeyev** [comment]
Sorry, give me couple more days to get to it! thanks for report!

**Comment by asergeyev** [comment]
Could you check and let me know what you think? coding at midnight is not a good thing...

**Comment by miekg** [comment]
Looks ok to me.

**Comment by gustavo-hms** [comment]
It works! Thank you!
