### ISSUE TITLE
Support for CH and other classes

### ISSUE THREAD

**Issue by jodrell** [miekg/dns#202]
I was looking at github.com/fcambus/rrda with the hope that I could modify it to let me do CH queries: when debugging issues with anycasted DNS servers, it's helpful to be able to get the id.server/hostname.bind value for the server answering the queries.

Unfortunately it seems that the IN class is hardcoded in defaults.go, which rrda uses. So this is a request to change this library to allow the class to be set by the consumer (with IN as the default).

**Comment by miekg** [comment]
I think this is more of a bug against rrda. The `defaults.go` is just that: extremely simple functions *iff* you work in the ClassINET.

Making the functions more generic and "implement" them in rrda should be very easy.

**Comment by miekg** [comment]
Closing as this is not a go dns issue.
