### ISSUE TITLE
Algorithm name mismatch when generating/reading private keys

### ISSUE THREAD

**Issue by roosmaa** [miekg/dns#206]
When using algorithm 7 (RSASHA1-NSEC3-SHA1) reading the generated private key doesn't work. This is due to two places having different string values:
- [dnssec_keyscan.go:53](https://github.com/miekg/dns/blob/master/dnssec_keyscan.go#L53) (RSASHA1NSEC3SHA1)
- [dnssec.go:610](https://github.com/miekg/dns/blob/master/dnssec.go#L610) (RSASHA1-NSEC3-SHA1)

I'd submit a PR fixing it, but I don't know which format is the correct one that BIND9 produces.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] Algorithm name mismatch when ..." ]
>When using algorithm 7 (RSASHA1-NSEC3-SHA1) reading the generated private key doesn't work. This is due to two places having different string values:
>- [dnssec_keyscan.go:53](https://github.com/miekg/dns/blob/master/dnssec_keyscan.go#L53) (RSASHA1NSEC3SHA1)
>- [dnssec.go:610](https://github.com/miekg/dns/blob/master/dnssec.go#L610) (RSASHA1-NSEC3-SHA1)
>
>I'd submit a PR fixing it, but I don't know which format is the correct one that BIND9 produces.

The mnemonic
http://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml
use the one with dashes: RSASHA1-NSEC3-SHA1 show that should be used there as
well. (Note: not tested with bind)

/Miek

--
Miek Gieben

**Comment by roosmaa** [comment]
Did some digging in BIND9 source. Seems there is a large mismatch between the algorithm names it uses and the ones in the iana.org website.

From `dst_parse.c`:

```c
	fprintf(fp, "%s %d ", ALGORITHM_STR, dst_key_alg(key));

	/* XXXVIX this switch statement is too sparse to gen a jump table. */
	switch (dst_key_alg(key)) {
	case DST_ALG_RSAMD5:
		fprintf(fp, "(RSA)\n");
		break;
	case DST_ALG_DH:
		fprintf(fp, "(DH)\n");
		break;
	case DST_ALG_DSA:
		fprintf(fp, "(DSA)\n");
		break;
	case DST_ALG_RSASHA1:
		fprintf(fp, "(RSASHA1)\n");
		break;
	case DST_ALG_NSEC3RSASHA1:
		fprintf(fp, "(NSEC3RSASHA1)\n");
		break;
	case DST_ALG_NSEC3DSA:
		fprintf(fp, "(NSEC3DSA)\n");
		break;
	case DST_ALG_RSASHA256:
		fprintf(fp, "(RSASHA256)\n");
		break;
	case DST_ALG_RSASHA512:
		fprintf(fp, "(RSASHA512)\n");
		break;
	case DST_ALG_ECCGOST:
		fprintf(fp, "(ECC-GOST)\n");
		break;
	case DST_ALG_ECDSA256:
		fprintf(fp, "(ECDSAP256SHA256)\n");
		break;
	case DST_ALG_ECDSA384:
		fprintf(fp, "(ECDSAP384SHA384)\n");
		break;
	case DST_ALG_HMACMD5:
		fprintf(fp, "(HMAC_MD5)\n");
		break;
	case DST_ALG_HMACSHA1:
		fprintf(fp, "(HMAC_SHA1)\n");
		break;
	case DST_ALG_HMACSHA224:
		fprintf(fp, "(HMAC_SHA224)\n");
		break;
	case DST_ALG_HMACSHA256:
		fprintf(fp, "(HMAC_SHA256)\n");
		break;
	case DST_ALG_HMACSHA384:
		fprintf(fp, "(HMAC_SHA384)\n");
		break;
	case DST_ALG_HMACSHA512:
		fprintf(fp, "(HMAC_SHA512)\n");
		break;
	default:
		fprintf(fp, "(?)\n");
		break;
	}
```

Also from what I can gather from looking at the parsing code, the actual string representation is ignored:

```c
	/*
	 * Read the algorithm line.
	 */
	NEXTTOKEN(lex, opt, &token);
	if (token.type != isc_tokentype_string ||
	    strcmp(DST_AS_STR(token), ALGORITHM_STR) != 0)
	{
		ret = DST_R_INVALIDPRIVATEKEY;
		goto fail;
	}

	NEXTTOKEN(lex, opt | ISC_LEXOPT_NUMBER, &token);
	if (token.type != isc_tokentype_number ||
	    token.value.as_ulong != (unsigned long) dst_key_alg(key))
	{
		ret = DST_R_INVALIDPRIVATEKEY;
		goto fail;
	}

	READLINE(lex, opt, &token);
```

So I'd propose just checking the number as well and not be concerned about the text. Shall I create a PR for that?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Algorithm name mismatch w..." ]
>Did some digging in BIND9 source. Seems there is a large mismatch between the algorithm names it uses and the ones in the iana.org website.
>
>From `dst_parse.c`:

wiiiiieeeee! :-(

I wrote the key parsing with BIND9 outputted files in my mind, so we should be
compatible with that. And internally consistent. So I think standardizing on
what IANA says are the names is good, while being lenient when reading from
these files.

This basically boils down to extended AlgorithmToString with the "wrong"
identifiers.

/Miek

--
Miek Gieben
