### ISSUE TITLE
Exchange() transparently uncompresses message without compress flag set 

### ISSUE THREAD

**Issue by discordianfish** [miekg/dns#216]
Hi,

if you use Exchange() to get compressed DNS response which still fits in 512 byte, you end up with a Msg *larger* than 512 and without compress flag set. That means if you write this message somewhere, it won't get compressed and you end up with a invalid message (udp, no EDNS, >512 bytes). Haven't test it but I think https://github.com/miekg/dnsrouter/blob/master/server.go#L119 should be affected as well.

This probably only affects stub resolvers not supporting EDNS, most notably netgo.

**Comment by miekg** [comment]
As you said on twitter, probably always setting Compress = true is best.

**Comment by discordianfish** [comment]
Can we check if the received message was compressed and only set compressed flag in this case?

**Comment by miekg** [comment]
I wonder if I should make this the default in msg.Unpack or putting it in Exchange only...

**Comment by miekg** [comment]
Yes, you can see if you followed compression pointers...

**Comment by miekg** [comment]
See compression branch which should fix this.

**Comment by discordianfish** [comment]
@miekg Wouldn't it be cleaner to only set it if the message was compressed? People might not want to compress the messages. At least @armon had some concerns about always compressing: https://github.com/hashicorp/consul/pull/971#issuecomment-104805965

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Exchange() transparently ..." ]
>@miekg Wouldn't it be cleaner to only set it if the message was compressed? People might not want to compress the messages. At least @armon had some concerns about always compressing: https://github.com/hashicorp/consul/pull/971#issuecomment-104805965

yes, but a lot more work and ugly refactoring.

Question: why are these messages send to? Why not just set compression there
(i.e. in the consul code?)

**Comment by discordianfish** [comment]
@miekg See the issue I linked to, @armon had some concerns about corrupted messages.

**Comment by miekg** [comment]
but concerns, or actual corruption?

**Comment by miekg** [comment]
Those comments say not much at all. Coming back to my question, why can't you set compression yourself? I do the same in SkyDNS.

**Comment by discordianfish** [comment]
@miekg Sure it's possible but I'm not a consul maintainer. Guess it would make sense to fix your dnsrouter and document that Exchange might return a message which is too big to be sent to a client unless compressed, then do the ugly refactoring sometime in the future.

**Comment by miekg** [comment]
Don't think this is a transitive property of the dns message. I don't store (in the message) if it came via UDP or TCP. This should be set on a per-connection basis.

**Comment by fastest963** [comment]
We recently ran into this issue where it was originally compressed before unpacking and then when re-packed it was not compressed. If the original message was compressed, I think it makes sense for `msg.Compress` to be true. Just like how if a message was truncated, `msg.Truncated` is true.

Though... we are also just setting compress on every single message now after running into this problem.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Exchange() transparently ..." ]
>message was compressed, I think it makes sense for `msg.Compress` to be true.
>Just like how if a message was truncated, `msg.Truncated` is true.

But msg.Truncated and msg.Compress are 2 entirely different things. Truncated
is actually set by the server. Changing that bit, changes the semantics of the
message. Compress OTOH is just meta data on *this* message in this communication
between *this* client and server. The fact that a message was send via TCP is
also *not* stored in the Msg struct...

/Miek

--
Miek Gieben

**Comment by andrewtj** [comment]
Setting `Msg.Compress` if a compression pointer is encountered during unpacking won't guarantee that a message will repack to the same size. Don't rely on `Msg.Compress` in place of a payload size check.

**Comment by andrewtj** [comment]
Closing as there hasn't been any activity for a while and it doesn't look like there is anything outstanding.

**Comment by hermansc** [comment]
I don't think this should be closed, as the original issue has not been fixed.

**Comment by andrewtj** [comment]
@hermansc If you've read through this issue and have something to add please do so.

**Comment by hermansc** [comment]
Sorry, I just came here from https://github.com/hashicorp/consul/issues/854#issuecomment-109272640 and since we're still having issues in Consul and this wasn't fixed I thought I'd let you know.

**Comment by andrewtj** [comment]
@hermansc No worries. For my 2¢ (and not necessarily @miekg's), there's nothing to do here, or at least nothing that doesn't involve deprecating `Msg.Compress`. In time I'd expect to see the signal to compress move elsewhere (and not be a boolean), but for the present, it might be a bit odd at first but it's not difficult to work with.
