### ISSUE TITLE
Connection limited to 128 requests

### ISSUE THREAD

**Issue by smalldave** [miekg/dns#218]
This is an issue that has cropped up when using the consul dns server.

The number of requests is limited to 128 for a single connection.

https://github.com/miekg/dns/blob/5a357a6fc5e85268b929350aa6423e2d56dcc4ff/server.go#L497

I'm doing a DNS query for every request I make as consul is load balancing traffic between services.
Creating a connection for each request leaves a lot of sockets in TIME_WAIT (at least in WIndows, I'd imagine it's the same elsewhere).
Make enough requests to services and you can easily run out of ports.

My solution to this was to keep the dns connection open but then I hit that limit.

What is the reason for the limit in the first place. Just that it's suspicious traffic that a public dns server probably doesn't want to serve?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] Connection limited to 128 req..." ]
>This is an issue that has cropped up when using the consul dns server.
>
>The number of requests is limited to 128 for a single connection.

Yes. See https://github.com/miekg/dns/blob/master/server.go#L496

>I'm doing a DNS query for every request I make as consul is load balancing traffic between services.
>Creating a connection for each request leaves a lot of sockets in TIME_WAIT (at least in WIndows, I'd imagine it's the same elsewhere).
>Make enough requests to services and you can easily run out of ports.

Yes, did you hit that limit?

>What is the reason for the limit in the first place. Just that it's suspicious traffic that a public dns server probably doesn't want to serve?

I think the limit should actually go (while reading some more about it). Not
sure if I close connection after a short timeout though (which would be needed
in the "there is no limit" case)

/Miek

--
Miek Gieben

**Comment by smalldave** [comment]
Hi,
Thanks for the quick reply. 
Hit the limit doing a couple of runs of a bench mark of 10000 requests. 
Ports sit in TIME_WAIT for 2 minutes on Windows.
Couldn't even browser the web :(
In reality we'd probably be ok but we do have bursts that could come close and having a ceiling like that would worry me.

**Comment by smalldave** [comment]
If there is currently no timeout then why add it?
The 128 request limit doesn't ensure the connection gets closed anyway does it?

**Comment by miekg** [comment]
yes. no limit means there should be some time out. I'm happy to take a PR
that makes this limit configurable and ups the limit to a higher value.

**Comment by smalldave** [comment]
happy to have a go (bad pun). 
still confused though. the time out and limit solve two different problems don't they?
the time out closes a connection that has been hanging around.
i could make 1 request and leave the connection open. the limit does nothing to close the connection in this case?

**Comment by miekg** [comment]
yes, such a pr would only: raise the limit + make it configurable

**Comment by holleman** [comment]
@smalldave  - curious, what are you using as a benchmark tool?

**Comment by smalldave** [comment]
Benchmarking is a bit grandiose. I'm working on a DNS client in C#. Weirdly I can't find any that can be pointed at a DNS server on a custom port. Also need to optimize for the zero TTL case when using with consul.

**Comment by smalldave** [comment]
@miekg looking at the code the connection is closed on receipt of a request. 
would it be better to close the connection after responding to the request?

**Comment by miekg** [comment]
uhm... yes :) although the client is likely to retry, but yes: fix is nice

**Comment by miekg** [comment]
Are sending a PR for this?

**Comment by smalldave** [comment]
Sorry. I did start work on the PR. For the particular problem I had though I was mistakenly assuming I wouldn't get enough information back over UDP.
I switched to UDP which obviously doesn't suffer from the connection problem.
I can dig up the changes if you want? 
From memory there wasn't that much to it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Connection limited to 128..." ]
>Sorry. I did start work on the PR. For the particular problem I had though I was mistakenly assuming I wouldn't get enough information back over UDP.
>I switched to UDP which obviously doesn't suffer from the connection problem.

Ack.

>I can dig up the changes if you want?
>From memory there wasn't that much to it.

Yes, please :)

Thanks!

**Comment by smalldave** [comment]
Apologies again @miekg. I cleaned out a number of git repos I wasn't using a while ago and dns must have been one of them.
Like I said I think it was pretty straightforward to do.
Having said that I have pretty much no experience of Go so you might be better off without my PR!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Connection limited to 128..." ]
>Apologies again @miekg. I cleaned out a number of git repos I wasn't using a while ago and dns must have been one of them.
>Like I said I think it was pretty straightforward to do.
>Having said that I have pretty much no experience of Go so you might be better off without my PR!

Np. I will fix it.

/Miek

--
Miek Gieben
