### ISSUE TITLE
Minor redundant code

### ISSUE THREAD

**Issue by asergeyev** [miekg/dns#220]
https://github.com/miekg/dns/blob/master/client.go#L330

does not seem you need those lines (330 to bottom), methods get copied from net.Conn since it's anonymous member of dns.Conn struct...

**Comment by asergeyev** [comment]
I can trim it and put test to verify interface would fit net.Conn in future (just in case someone changes something about it)

**Comment by miekg** [comment]
hmm, don't know why I added those. Prolly changed Conn from something to an
anonymous member and forgot to remove these.

Should be safe to remove. Don't need a test as this should be covered by
the go1 backwards compat guarantee.

Thanks for finding it!

**Comment by asergeyev** [comment]
I think this could be closed here, we can continue talking in PR
