### ISSUE TITLE
Lazy message reading in dns.Client

### ISSUE THREAD

**Issue by asergeyev** [miekg/dns#222]
Currently ReadMsg parses wire message fully before it returns (and reads next one). When you just need an answer very fast it's not quite ideal.

I can suggest small experiment with lazy reader that would return message header and blob to parse later...   Would that be interesting to have?   IMO it's not quite universal, only should come handy when reading lo-o-ots of messages from fast DNS cache that's close on network and does not give time for few reader threads to idle...

**Comment by miekg** [comment]
sgtm. we'll later see how this fits in.

**Comment by asergeyev** [comment]
Well... Added patch and PR...  Let me know what you think.... Somewhat for my needs (getting that wire Header is what I want to have as soon as possible and not worry about buffer allocation)

I wonder if ReadMsg could actually be changed now to ReadMsgBytes followed by Msg.Unpack and followed by Tsig validation.  Should be effectively same as it is now but will cut duplicated code between msg.Unpack and ReadMsg.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Lazy message reading in d..." ]
>Well... Added patch and PR...  Let me know what you think.... Somewhat for my needs (getting that wire Header is what I want to have as soon as possible and not worry about buffer allocation)

Yes, that makes sense.

>I wonder if ReadMsg could actually be changed now to ReadMsgBytes followed by Msg.Unpack and followed by Tsig validation.  Should be effectively same as it is now but will cut duplicated code between msg.Unpack and ReadMsg.

As commented in the PR, yes something like this should be wired up in the lib
itself. 99% of stuff hitting a server is crap, getting rid of it early and fast
is good.

Thanks!
