### ISSUE TITLE
Detect invalid ACE?

### ISSUE THREAD

**Issue by rafaeljusto** [miekg/dns#227]
Hi,

I would like to know if in this library is there any way to detect an invalid domain ACE format when using the idn package? (FromPunycode)

For example, the FQDN **xn--7warambrecmdctfmhlrtrmbpyjdccaaahkrgl4chlip9bclcgddbb4ooioa.bnnhg** according to [Verisign](http://mct.verisign-grs.com/convertServlet?input=xn--7warambrecmdctfmhlrtrmbpyjdccaaahkrgl4chlip9bclcgddbb4ooioa.bnnhg) fails due to `Error:: Disallowed/Unassigned 3A3`, but the FromPunycode returns `σειράτάξησυπουργείωνΣύνθεσηυπουργικούσυμβουλίουουουο.bnnhg`.

```go
package main

import (
	"github.com/miekg/dns/idn"
)

func main() {
	output := idn.FromPunycode("xn--7warambrecmdctfmhlrtrmbpyjdccaaahkrgl4chlip9bclcgddbb4ooioa.bnnhg")
	println(output)
}
```

Best regards,
Rafael Justo

**Comment by rafaeljusto** [comment]
I found a way to check for errors, converting the unicode back to ACE format and comparing with the initial ACE format. Will lose some performance to convert back to ACE, but it's a solution. =)

```go
package main

import (
	"github.com/miekg/dns/idn"
)

func main() {
	aces := []string{
		"xn--7warambrecmdctfmhlrtrmbpyjdccaaahkrgl4chlip9bclcgddbb4ooioa.bnnhg",
		"xn--a-bcdefghi-k4amdkp8de4at4dxdxcgrz4k6b.com.br",
	}

	for _, ace := range aces {
		unicode := idn.FromPunycode(ace)

		if idn.ToPunycode(unicode) != ace {
			println("invalid ACE -->", ace)
		} else {
			println("valid ACE   -->", ace)
		}
	}
}
```

Thanks!

Best regards,
Rafael Justo

**Comment by rafaeljusto** [comment]
Looking closely to the RFCs, looks like the algorithm is accepting invalid code points, according to [RFC 5892 (page 4)](https://tools.ietf.org/html/rfc5892#page-4).

```
o  DISALLOWED: Those that should clearly not be included in IDNs.
    Code points with this property value are not permitted in IDNs.
```

For example, the domain "Σ.test" is an invalid IDN because of the character Σ, but the small case "σ.test" is valid. According to [RFC 5892 (page 27)](https://tools.ietf.org/html/rfc5892#page-27):

```
03A3..03AB  ; DISALLOWED  # GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LE
03AC..03CE  ; PVALID      # GREEK SMALL LETTER ALPHA WITH TONOS..GREEK S
```

The problem appears to be that the library [converts to lower case](https://github.com/miekg/dns/blob/master/idn/punycode.go#L125) the unicode input bytes before encoding.

```go
package main

import (
	"github.com/miekg/dns/idn"
)

func main() {
	domains := []string{
		"σ.test", // valid
		"Σ.test", // invalid
	}

	for _, domain := range domains {
		ace := idn.ToPunycode(domain)
		unicode := idn.FromPunycode(ace)
		println(domain, ":::", ace, ":::", unicode)
	}
}
```

Output:
```
σ.test ::: xn--4xa.test ::: σ.test
Σ.test ::: xn--4xa.test ::: σ.test
```

**Comment by miekg** [comment]
Care to draft a pull request? :-)

[ Quoting <notifications@github.com> in "Re: [dns] Detect invalid ACE? (#227..." ]
>Looking closely to the RFCs, looks like the algorithm is accepting invalid code points, according to [RFC 5892 (page 4)](https://tools.ietf.org/html/rfc5892#page-4).
>
>```
>o  DISALLOWED: Those that should clearly not be included in IDNs.
>    Code points with this property value are not permitted in IDNs.
>```
>
>For example, the domain "Σ.test" is an invalid IDN because of the character Σ, but the small case "σ.test" is valid. According to [RFC 5892 (page 27)](https://tools.ietf.org/html/rfc5892#page-27):
>
>```
>03A3..03AB  ; DISALLOWED  # GREEK CAPITAL LETTER SIGMA..GREEK CAPITAL LE
>03AC..03CE  ; PVALID      # GREEK SMALL LETTER ALPHA WITH TONOS..GREEK S
>```
>
>The problem appears to be that the library [converts to lower case](https://github.com/miekg/dns/blob/master/idn/punycode.go#L125) the unicode input bytes before encoding.
>
>```go
>package main
>
>import (
>	"github.com/miekg/dns/idn"
>)
>
>func main() {
>	domains := []string{
>		"σ.test", // valid
>		"Σ.test", // invalid
>	}
>
>	for _, domain := range domains {
>		ace := idn.ToPunycode(domain)
>		unicode := idn.FromPunycode(ace)
>		println(domain, ":::", ace, ":::", unicode)
>	}
>}
>```
>
>Output:
>```
>σ.test ::: xn--4xa.test ::: σ.test
>Σ.test ::: xn--4xa.test ::: σ.test
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/miekg/dns/issues/227#issuecomment-121228210
/Miek

--
Miek Gieben

**Comment by rafaeljusto** [comment]
Sure! I'm on it.

**Comment by asergeyev** [comment]
IMO in this line:
https://github.com/miekg/dns/blob/master/idn/punycode.go#L149
you want to return nil to avoid returning UNICODE to someone who expects punycode.

You should also edit this paragraph (https://github.com/miekg/dns/blob/master/idn/punycode.go#L30):

    // This function would return incorrect result for strings for non-canonical
    // unicode strings.

(saying that it'll return nil for non-canonical strings and mention that function expects pre-lowercased strings)

**Comment by rafaeljusto** [comment]
Thanks! I will make the changes and do another PR.

**Comment by rafaeljusto** [comment]
@asergeyev I was thinking on returning an empty string in the function ToPunycode when there's an error in the encode (nil returned), so we don't change the exported function signature. What do you think?

```diff
diff --git a/idn/punycode.go b/idn/punycode.go
index 28c7dcc..670dc76 100644
--- a/idn/punycode.go
+++ b/idn/punycode.go
@@ -27,8 +27,8 @@ const (
 )
 
 // ToPunycode converts unicode domain names to DNS-appropriate punycode names.
-// This function would return incorrect result for strings for non-canonical
-// unicode strings.
+// This function would return an empty string result for domain names with
+// invalid unicode strings. This function expects domain names in lowercase.
 func ToPunycode(s string) string {
        tokens := dns.SplitDomainName(s)
        switch {
@@ -41,7 +41,11 @@ func ToPunycode(s string) string {
        }
 
        for i := range tokens {
-               tokens[i] = string(encode([]byte(tokens[i])))
+               t := encode([]byte(tokens[i]))
+               if t == nil {
+                       return ""
+               }
+               tokens[i] = string(t)
        }
        return strings.Join(tokens, ".")
 }
@@ -139,14 +143,16 @@ func tfunc(k, bias rune) rune {
        return k - bias
 }
 
-// encode transforms Unicode input bytes (that represent DNS label) into punycode bytestream
+// encode transforms Unicode input bytes (that represent DNS label) into
+// punycode bytestream. This function would return nil if there's an invalid
+// character in the label
 func encode(input []byte) []byte {
        n, bias := _N, _BIAS
 
        b := bytes.Runes(input)
        for i := range b {
                if !isValidRune(b[i]) {
-                       return input
+                       return nil
                }
 
                b[i] = preprune(b[i])
```

**Comment by asergeyev** [comment]
Looks good this way too, but decision is up to @miekg

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Detect invalid ACE? (#227..." ]
>Looks good this way too, but decision is up to @miekg

wrt to the api change?

**Comment by asergeyev** [comment]
yes.
