### ISSUE TITLE
URI Target Format Incorrect

### ISSUE THREAD

**Issue by andrewtj** [miekg/dns#232]
URI is currently defined as:
```go
type URI struct {
    Hdr      RR_Header
    Priority uint16
    Weight   uint16
    Target   []string `dns:"txt"`
}
```

[RFC 7553 section 4.4 and 4.5](https://tools.ietf.org/html/rfc7553#section-4.4) define Target as the remaining bytes in the record data following Priority and Weight presented as a single character-string.

I'm just lodging this issue for the minute as I don't have the cycles to do a fix.

**Comment by miekg** [comment]
Yes, they changed the format in the one of the previous drafts :(

It looks like we can re-use CAA's `dns:"octets"` for this. That would be a oneline change (and the parsing of course)

**Comment by miekg** [comment]
Look at the uri branch. Parse test (TestParseURI - new test) crashes though.

**Comment by miekg** [comment]
@andrewtj cleaned it up a bit: works and parses. Please take a look, before I merge. Thanks!

**Comment by andrewtj** [comment]
In `setURI()` check `endingToTxtSlice()` returns a single string. Since an empty target will be accepted off the wire accepting an empty string here is probably ok.

Other than that, looks good to me.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] URI Target Format Incorre..." ]
>In `setURI()` check `endingToTxtSlice()` returns a single string. Since an empty target will be accepted off the wire accepting an empty string here is probably ok.

You mean `_http._tcp.   3600    IN      URI     10 1 ""` is valid? That already
works. I've added it to the parse test.

/Miek

--
Miek Gieben

**Comment by andrewtj** [comment]
> You mean `_http._tcp.   3600    IN      URI     10 1 ""` is valid? That already
works. I've added it to the parse test.

Yeah I mentioned that because it's not valid according to the RFC (minimum length is 1) but it's not worth the effort of enforcing.

The first part, checking that `endingToTxtSlice()` returns one string is worth it though as at the minute `_http._tcp. 3600 IN URI 10 1 "a" "b"` will be accepted and treated as though it were `_http._tcp. 3600 IN URI 10 1 "a"`.

**Comment by miekg** [comment]
Yep that's true. I'll add it and merge.
