### ISSUE TITLE
Wants to separate timeouts from other errors

### ISSUE THREAD

**Issue by bortzmeyer** [miekg/dns#233]
In a DNS client, it is interesting to distinguish between timeouts (where you will try another of the authoritative name servers of the zone) and others errors. Back when dns.Error was net.Error, it was easy with the Timeout() method. How do I do now?

Today, I use 
```
if strings.Contains(err.Error(), "timeout")
```
Is there something more elegant?

**Comment by andrewtj** [comment]
Errors are returned as `error` (the built-in interface) so you should be able to do a type switch on them to look for a timeout. Eg:

```go
if err, ok := err.(*net.OpError); ok && err.Timeout() {
    // It's a timeout
}
```

**Comment by miekg** [comment]
Yes, this should just work like that.
