### ISSUE TITLE
race conditions detected on Go 1.5rc1

### ISSUE THREAD

**Issue by jmhodges** [miekg/dns#244]
The letsencrypt/boulder project has found some race conditions in the dns library on Go 1.5rc1. They appear to be real.

Here's a Travis CI build that exemplifies the issue: https://travis-ci.org/jmhodges/boulder/builds/75167987 (Search for "DATA RACE" in the build logs but beware that other non-dns races were found, as well.).

The issue appears to be a race when Server.Shutdown and Server.ListenAndServe are called in different goroutines. It appears there are a few fields on srv that are being written to without a mutex. Specifically, Listener, and PacketConn. I've not gone looking for other obvious races on srv fields. ListenAndServe/Shutdown have not yet been run in multiple goroutines in the miekg/dns test suite.

**Comment by jmhodges** [comment]
(Unfortunately, I cannot get TravisCI to work on the current miekg/dns suite. See https://travis-ci.org/jmhodges/dns/jobs/75174201 )

**Comment by jmhodges** [comment]
From inspecting the code, similar races exist in ActivateAndServe and Shutdown but, for reasons unknown, the miekg/dns test suite is not triggering them.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] race conditions detected on G..." ]
>The issue appears to be a race when Server.Shutdown and Server.ListenAndServe are called in different goroutines. It appears there are a few fields on srv that are being written to without a mutex. Specifically, Listener, and PacketConn. I've not gone looking for other obvious races on srv fields. ListenAndServe/Shutdown have not yet been run in multiple goroutines in the miekg/dns test suite.

No, they haven't. Do the test in Go 1.5 also run with GOMAXPROCS > 1 ?
I think we should just hold on to the lock in the startup/shutdown methods,
until they are done.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I need to closely trace the locks and unlocks, but indeed this fails with 1.5rc1.

**Comment by jmhodges** [comment]
Hm? Did that patch not fix the race conditions listed here?

**Comment by miekg** [comment]
I made it a defer after I merged this.
