### ISSUE TITLE
Can't get an invalid domain using IsDomainName

### ISSUE THREAD

**Issue by rushmorem** [miekg/dns#262]
I want to check some strings to see if they are valid domain names. I thought `IsDomainName` would be perfect for this. However, no matter what I throw at it, it always comes out as valid. I have tried all sorts of strings that are definitely not domain names. Am I missing something?

**Comment by 843723683** [comment]
sorry

**Comment by 843723683** [comment]
where are you from?

**Comment by rafaeljusto** [comment]
You could try a regular expression for a basic FQDN check:
```
^((([a-z0-9][a-z0-9\-]*[a-z0-9])|[a-z0-9]+)\.)*([a-z]+|xn\-\-[a-z0-9]+)\.?$
```

**Comment by rushmorem** [comment]
@rafaeljusto Thanks for the suggestion. In the current code I'm already using a regular expression. I thought using `IsDomainName` would be nicer.

**Comment by rushmorem** [comment]
@843723683 You mean as in country?

**Comment by miekg** [comment]
domain names are 8 bit clean, so yes, prolly every string *is* a valid domain name. There a lot of brain dead software out there that assumes it needs to be ascii, but down to the wire this is not true.

**Comment by rushmorem** [comment]
Thanks for clarifying @miekg. I'm still a little confused though. If this function is always going to return true then how can one make use of it?

**Comment by miekg** [comment]
No, invalid name is for instance `bla..com` (empty label). And of labels sizes larger than 63 and total size 255.

**Comment by rushmorem** [comment]
I see. Makes sense. Thanks.

**Comment by miekg** [comment]
You have to be careful with regexp though: `bla.com` and `bla\.c.om` are two different things. Better to your Split to the labels and check those.

**Comment by rushmorem** [comment]
Thanks for the tip. Will keep that in mind.

**Comment by rafaeljusto** [comment]
I added to IsDomainName test 3 more cases, one checking the label with more than 63 chars, other checking the total size of 255 chars and the last one checking for hyphens in positions 3 and 4 of a label (RFC 5890 - Section 2.3.1). The total size and the hyphens position test cases failed.

```diff
diff --git a/labels_test.go b/labels_test.go
index 2a3f3d0..641cb80 100644
--- a/labels_test.go
+++ b/labels_test.go
@@ -162,6 +162,9 @@ func TestIsDomainName(t *testing.T) {
                "www.example.com.": &ret{true, 3},
                "mi\\k.nl.":        &ret{true, 2},
                "mi\\k.nl":         &ret{true, 2},
+               "reallylonglabelreallylonglabelreallylonglabelreallylonglabelreal.com":                                                                                                                                                                                             &ret{false, 0},
+               "l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.n.g.d.o.m.a.i.n.n.a.m.e.l.o.": &ret{false, 128},
+               "qq--notavalidace.com": &ret{false, 2},
        }
        for d, ok := range names {
                l, k := IsDomainName(d)
```

**Comment by miekg** [comment]
Yeah, thought I didn't care about the total domain length as there is not technical reason for it being < 256. Prolly worth making that at least return an error. Btw the reason why it is not an error is to allow for some nasty remote debugging.

Don't why `qq--` would be a illegal domain name.

**Comment by rafaeljusto** [comment]
My bad! `qq--` is a valid label for a generic check, this would be a [IDN ace format check](http://mct.verisign-grs.com/convertServlet?input=qq--notavalidace.com).

I also checked for:
```
-example.com
example-.com
```
and they were considered valid. But according to [RFC 1034, section 3.5](https://tools.ietf.org/html/rfc1034#page-11), the label cannot start or end with a hyphen. Is this correct?

```diff
diff --git a/labels_test.go b/labels_test.go
index 2a3f3d0..3dc184d 100644
--- a/labels_test.go
+++ b/labels_test.go
@@ -162,6 +162,9 @@ func TestIsDomainName(t *testing.T) {
                "www.example.com.": &ret{true, 3},
                "mi\\k.nl.":        &ret{true, 2},
                "mi\\k.nl":         &ret{true, 2},
+               "reallylonglabelreallylonglabelreallylonglabelreallylonglabelreal.com": &ret{false, 0},
+               "-example.com": &ret{false, 2},
+               "example-.com": &ret{false, 2},
        }
        for d, ok := range names {
                l, k := IsDomainName(d)
```

**Comment by andrewtj** [comment]
@rafaeljusto that section is about interoperability with other naming systems. A domain name is a series of labels of 1 to 63 bytes, terminated by a zero-length label that shouldn't exceed 255 bytes. So `-example.com.` and `example-.com.` are valid domain names. That doesn't mean those names are necessarily valid as host names, etc, though.

**Comment by rafaeljusto** [comment]
Ok. Thanks @miekg and @andrewtj 
And sorry to be so headstrong. =)

**Comment by asergeyev** [comment]
Don't have enough time to look but it looks like there is  a bug... If you give longer label than 63 chars it should return invalid, otherwise packing would conflict with compression. And right now IsDomainName("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz.com") returns 2, true, which means that packDomainName created something that would be hard to unpack without knowing for sure that compression should be ignored.

**Comment by miekg** [comment]
Hehe :-) Nice. *That* might be worth fixing, OTOH "The package allows complete control over what is send out to the DNS"

**Comment by andrewtj** [comment]
> Don't have enough time to look but it looks like there is a bug... If you give longer label than 63 chars it should return invalid, otherwise packing would conflict with compression.

Supplying `strings.Repeat("a", 64) + "."` to `IsDomainName` returns `ok` as `false`.

> And right now IsDomainName("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz.com") returns 2, true, which means that packDomainName created something that would be hard to unpack without knowing for sure that compression should be ignored.

That whole string is 56 characters. The first label in it is 52 bytes and the second is 3. So isn't `2, true` the correct behaviour?
