### ISSUE TITLE
srv.started isn't unset after error starting.

### ISSUE THREAD

**Issue by schancel** [miekg/dns#263]
In the case where there is an error listening (e.g. bind addr already in use) and you would like to re-try listening a few times, you are unable to due to the boolean gate here:

https://github.com/miekg/dns/blob/master/server.go#L293

**Comment by miekg** [comment]
yep, that's a (small) bug.

**Comment by miekg** [comment]
Hmmm, the lock is also not unlocked.

**Comment by schancel** [comment]
Thanks!
