### ISSUE TITLE
Setting the source address of an AXFR

### ISSUE THREAD

**Issue by Squab** [miekg/dns#264]
Hello! I hope an issue is the right avenue for this request/question. If not feel free to point me in the right direction and shame me appropriately.

I'd like to essentially do this:
https://www.socketloop.com/tutorials/golang-set-up-source-ip-address-before-making-http-request

But for AXFRs. There is a use case where you might want to send your AXFR (or regular query) out of a specific interface or IP on a box that has permission to poke through the firewall.

I believe this can be accomplished by setting `LocalAddr` on the `Dialer` that eventually gets used in `Dial`, or `DialTimeout`: http://golang.org/src/net/dial.go?s=5630:5708#L42

I'm trying to figure out the best way to do this in this library. Perhaps you can already do it, and I just don't know how :smile: 

What I've come up with:

Add a `DialTimeoutSource` in `client.go` that looked something like:
```go
// DialTimeoutSource acts like Dial but takes a timeout and a source.
func DialTimeoutSource(network, address string, timeout time.Duration, source Addr) (conn *Conn, err error) {
	conn = new(Conn)
	d := net.Dialer{Timeout: timeout, LocalAddr: source}
	conn.Conn, err = d.Dial(network, address)
	if err != nil {
		return nil, err
	}
	return conn, nil
}
```
and make use of that in `func (t *Transfer) In` in `xfr.go`, by appending a `Source` field to the `Transfer` struct. 

Something like:
```go
// A Transfer defines parameters that are used during a zone transfer.
type Transfer struct {
	*Conn
....
	tsigTimersOnly bool
	Source         *Addr            // A source IP for the transfer
}

// Think we need to away to stop the transfer

// In performs an incoming transfer with the server in a.
func (t *Transfer) In(q *Msg, a string) (env chan *Envelope, err error) {
	timeout := dnsTimeout
	source := ""
	if t.DialTimeout != 0 {
		timeout = t.DialTimeout
	}
	if t.Source != nil {
		source = t.Source
	}
	t.Conn, err = DialTimeoutSource("tcp", a, timeout, source)
```

This doesn't solve the problem generally for other types of queries. I'll probably end up making this type of change for my personal use, and I'd be happy to submit a pull request. But if there's something better, more general, or cleaner that someone more familiar with the library could suggest, I'd be happy to implement that as well.

I'd love to know any ideas anyone has, or if I should do something different, or just sod off :rocket: 

Thank you @miekg or anyone else that has ideas!

**Comment by miekg** [comment]
You can create your own `Conn` on use that in Go dns, but I don't think there is support for this when doing a Transfer.
Maybe it is an idea to pull a `net.Dailer` into go dns that will give you the flexibility you need?

**Comment by miekg** [comment]
Adding a transferConn made actually be a nicer idea. Also mirrors
ExchangeConn which is nice.

**Comment by Squab** [comment]
So the `Transfer` struct does have a `T.conn`
```go
// A Transfer defines parameters that are used during a zone transfer.
type Transfer struct {
	*Conn
	DialTimeout    time.Duration     // net.DialTimeout, defaults to 2 seconds
	ReadTimeout    time.Duration     // net.Conn.SetReadTimeout value for connections, defaults to 2 seconds
	WriteTimeout   time.Duration     // net.Conn.SetWriteTimeout value for connections, defaults to 2 seconds
	TsigSecret     map[string]string // Secret(s) for Tsig map[<zonename>]<base64 secret>, zonename must be fully qualified
	tsigTimersOnly bool
}
```

What if I changed Transfer.in to optionally use a `Conn` if someone sets it before they call `transfer.In`

So it'd be this in `xfr.go`:
```go
// In performs an incoming transfer with the server in a.
func (t *Transfer) In(q *Msg, a string) (env chan *Envelope, err error) {
	timeout := dnsTimeout
	if t.DialTimeout != 0 {
		timeout = t.DialTimeout
	}
        if t.Conn != nil {
	    t.Conn, err = DialTimeout("tcp", a, timeout)
            if err != nil {
	            return nil, err
	        }
        }
```

So that way someone could set the `Conn` like:
```go
transfer := new(dns.Transfer)
message := new(dns.Msg)
message.SetAxfr(zone_name)
d := Dialer{Timeout: timeout, LocalAddr: somevar}
transfer.Conn, err = d.Dial(network, address)
channel, err := transfer.In(message, *master)
```

**Comment by miekg** [comment]
Looks nice. Also I need to take back my comment on ExchangeConn as I deprecated that :) The comment says mimic it with:
```
//      co := &dns.Conn{Conn: c} // c is your net.Conn
//      co.WriteMsg(m)
//      in, _  := co.ReadMsg()
//      co.Close()
```
I think your proposal matches that (somewhat) nicely. 

Please open a PR with this change.
