### ISSUE TITLE
No straight forward way to Parse *Msg from byte slice.

### ISSUE THREAD

**Issue by krolaw** [miekg/dns#266]
Since I found:
func IsMsg(buf []byte) error

I started looking for something like:
func ParseMsg(b []byte) (*Msg,error)

Alas, no luck.  I see that I might be able to parse a message, if I fake a net.Conn, and then pass the bytes through when Read() is called, wrapped in a dns.Conn a la:
func (co *Conn) ReadMsg() (*Msg, error)

But I'm hoping there might be an easier way, or point me in the right direction.

Thanks. :-)

**Comment by miekg** [comment]
Just do
```
m := new(dns.Msg)
m.PackBuffer(buf)
```

**Comment by andrewtj** [comment]
You're after [Msg.Unpack](http://godoc.org/github.com/miekg/dns#Msg.Unpack):

```go
package main

import "github.com/miekg/dns"

func main() {
	buf := make([]byte, 12)
	m := new(dns.Msg)
	if err := m.Unpack(buf); err != nil {
		panic(err)
	}
	println(m.String())
}
```

**Comment by krolaw** [comment]
Thanks, my bad.  Don't know why I didn't see it.

Thanks. again.
