### ISSUE TITLE
ParseZone should also return the value of a record

### ISSUE THREAD

**Issue by giskarda** [miekg/dns#269]
Hi,

It looks to me ParseZone doesn't return the value, Rdata, of a record. It might be good to have it.
I see the lexer should have some knowledge but I wasn't able to inject myself where the last token pre 'comment' is handled.

What do you think?
Riccardo

**Comment by miekg** [comment]
I don't really get what you want/need. ParseZone returns a channel of `*dns.Token`

**Comment by giskarda** [comment]
And a *dns.Token is:

type Token struct {
    // The scanned resource record when error is not nil.
    RR
    // When an error occured, this has the error specifics.
    Error *ParseError
    // A potential comment positioned after the RR and on the same line.
    Comment string
}

RR is 

type RR interface {
    // Header returns the header of an resource record. The header contains
    // everything up to the rdata.
    Header() *RR_Header
    // String returns the text representation of the resource record.
    String() string
    // contains filtered or unexported methods
}

I was wondering how can I get rdata after I parse the zone. It doesn't seem to be possible to me. (but maybe Im terribly wrong)

**Comment by miekg** [comment]
Ah, look at the `dns.Field` function which takes an RR (this is in the `format.go` file)

**Comment by giskarda** [comment]
Got it. Thanks. I adapted my code to include the value of Rdata while I try to parse a zone.

I still wonder why Rdata is not included by default in a Token object.

I wanted to write a patch by adding a Rdata field to the RR object that the Token returns. But Im sure that calling dns.Field() is not the appropriate way. And at the same time the use of reflection to do that while we construct the object seems a little bit overkill to me.

If you can provide any direction I might try to write some code. I still think it's useful when you parse a zone file to include the Rdata by default in the token object at least.

**Comment by andrewtj** [comment]
> I wanted to write a patch by adding a Rdata field to the RR object that the Token returns.

RR is an [interface](https://golang.org/ref/spec#Interface_types) that is concretely implemented by one of many structs (eg: [A](https://godoc.org/github.com/miekg/dns#A)). 

> But Im sure that calling dns.Field() is not the appropriate way. And at the same time the use of reflection to do that while we construct the object seems a little bit overkill to me.

I don't understand this.

What's the problem you are trying to solve?

**Comment by giskarda** [comment]
@andrewtj :The problem I'm trying to solve is to have the value of a dns record when I parse a zone file. Not only the Header or the comment.

A dns.Token (or RR object) per se doesn't contain the Rdata value without going through reflection.

It looks strange to me that 'the normal use case scenario' for a ParseZone operation is to retrieve everything but Rdata.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] ParseZone should also ret..." ]
>@andrewtj :The problem I'm trying to solve is to have the value of a dns record when I parse a zone file. Not only the Header or the comment.
>
>A dns.Token (or RR object) per se doesn't contain the Rdata value without going through reflection.

If you have an dns.RR you have to use a type switch or type assertion to get to
the rdata.

If dns.RR contains a TXT record you need something like rr.(*dns.TXT).Txt to get
the TXT.

It that what you want/need?

**Comment by andrewtj** [comment]
> @andrewtj :The problem I'm trying to solve is to have the value of a dns record when I parse a zone file. Not only the Header or the comment.

If “value of a dns record” means the text presentation of an RR, `RR.String()` might be what you're looking for, or are you after something else? (The original input or the text presentation of only the RR data perhaps?)

> A dns.Token (or RR object) per se doesn't contain the Rdata value without going through reflection.

> It looks strange to me that 'the normal use case scenario' for a ParseZone operation is to retrieve everything but Rdata.

I'm not sure I understand what you're saying so forgive me if this is off base. RR is an [interface](https://golang.org/ref/spec#Interface_types) not a concrete type. The concrete type that implements the interface will contain the record data in some form or other specific to that type. The original input is lost but since all the RR's implement [Stringer](https://golang.org/pkg/fmt/#Stringer) an equivalent text string can be produced. Depending on what you're actually doing (which is still unclear to me) this might even be an advantage as the presentation will be more predictable.

**Comment by giskarda** [comment]
@andrewtj I think I got your point.

I think it's better if I paste the code because something might be lost in translation.

```
package main

import (
	"log"
	"os"

	"github.com/miekg/dns"
)

func main() {
	filename := "example.com.zone"
	f, err := os.Open(filename)
	if err != nil {
		log.Println(err)
	}
	for token := range dns.ParseZone(f, "", "") {
		if token.Error != nil {
			log.Println(token.Error)
		} else {
			rrh := token.RR.Header()
			if rrh.Rrtype == dns.TypeA ||
				rrh.Rrtype == dns.TypeAAAA {
				rdata := dns.Field(token.RR, 1)
				log.Println(token.RR)
				log.Printf("name: %s, type: %d, rdata: %s", rrh.Name, rrh.Rrtype, rdata)
			}
		}
	}
}
```

What Im trying to achieve is to have a dns.ParseZone() that doesn't require me to call multiple function to have the data in a zone file ready to be used.


```
[~] ➔  cat example.com.zone.txt
; BIND db file for example.com

$TTL 86400

@       IN      SOA     ns1.example.com.      riccardo.setti.example.com. (
                        2015070401	; serial number YYMMDDNN
                        28800           ; Refresh
                        7200            ; Retry
                        864000          ; Expire
                        86400           ; Min TTL
			)

                NS      ns1.example.com.


$ORIGIN example.com.
example1	IN	A	10.10.10.10
example1	IN	A	10.10.10.11
example1	IN	AAAA	2001:db8::3
example2	IN	A	22.22.22.22
```

The output of RR.String() (don't ask me why it's doubled) is the actual line in the zone file.
What I would be like to have is something like the out log.Printf() line.
Something on the line of have a *dns.Token that includes
```
[~] ➔  GOPATH=~ go run dnsParseZone.go
2015/10/06 14:20:29 example1.example.com.	86400	IN	A	10.10.10.10
2015/10/06 14:20:29 example1.example.com.	86400	IN	A	10.10.10.10
2015/10/06 14:20:29 name: example1.example.com., type: 1, rdata: 10.10.10.10
2015/10/06 14:20:29 example1.example.com.	86400	IN	A	10.10.10.11
2015/10/06 14:20:29 example1.example.com.	86400	IN	A	10.10.10.11
2015/10/06 14:20:29 name: example1.example.com., type: 1, rdata: 10.10.10.11
2015/10/06 14:20:29 example1.example.com.	86400	IN	AAAA	2001:db8::3
2015/10/06 14:20:29 example1.example.com.	86400	IN	AAAA	2001:db8::3
2015/10/06 14:20:29 name: example1.example.com., type: 28, rdata: 2001:db8::3
2015/10/06 14:20:29 example2.example.com.	86400	IN	A	22.22.22.22
2015/10/06 14:20:29 example2.example.com.	86400	IN	A	22.22.22.22
2015/10/06 14:20:29 name: example2.example.com., type: 1, rdata: 22.22.22.22
[~] ➔
```

**Comment by andrewtj** [comment]
One way of getting just the RR data in presentation form is with a helper like this:

```go
func helper(rr dns.RR) string {
        return rr.String()[len(rr.Header().String()):]
}
```

Not great but it might be good enough.

The Stringers are all hand coded so it'd be a bit of slog to add a DataString method to the dns.RR interface. Whether or not that change would be accepted is another thing. I've been following this repo for a while and to my recollection there's been no similar request come up, and from what you've said it's difficult to say what the use-case is.

**Comment by miekg** [comment]
Yes, access to the rdata in a generic way is rare (at least for people using go dns). The work around the @andrewtj proposes is a good way to do it. I don't see a need for `DataString` as the `helper` function is only 1 line

**Comment by giskarda** [comment]
Ok got that. If there is no plan to add DataString I think I can close this issue. Do you agree?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] ParseZone should also ret..." ]
>Ok got that. If there is no plan to add DataString I think I can close this issue. Do you agree?

Ack.

--
Miek Gieben
