### ISSUE TITLE
Not building - errors

### ISSUE THREAD

**Issue by rquigley-woodleigh** [miekg/dns#276]
This package is not building for me (on Ubuntu Server 15.04). The error is:
```
go/src/github.com/miekg/dns/dnssec.go:257: undefined: crypto.Signer
go/src/github.com/miekg/dns/dnssec.go:321: undefined: crypto.Signer
go/src/github.com/miekg/dns/sig0.go:16: undefined: crypto.Signer
```

Am I doing something wrong, or is this an error with the code?

**Comment by andrewtj** [comment]
`crypto.Signer` was introduced in Go 1.4. You probably have an earlier version (you can check with `go version`).

**Comment by rquigley-woodleigh** [comment]
Yep, I’m running 'go version go1.3.3 linux/amd64’

I’ll try with a newer version.

**Comment by bortzmeyer** [comment]
It's a very annoying problem since Debian stable is at version 1.3.3. Any workaround?

**Comment by miekg** [comment]
No work around.... go dns supports the last 2 releases. Upgrade your golang
is your only option or try installing newer golang from a newer debian.

**Comment by bortzmeyer** [comment]
Currently no backports of Golang for Debian "stable" ("jessie"). And the packages from the newer "testing" version ("stretch") don't install. I had to upgrade a machine to "testing" and to make all my Go DNS compilations there :-(
And the executables I build there are not portable on older machines: "exec format error" So, yes, this problem is really painful.

**Comment by andrewtj** [comment]
@bortzmeyer you could build your own Go, or implement a `crypto.Signer` equivalent for <1.4 and use build constraints to bring in the appropriate implementations, interfaces and intermediaries. Is the later something you'd consider accepting a patch for @miekg?

**Comment by miekg** [comment]
I dunno... `crypto.Signer` was a major cleanup; don't like to add things back in *just* to make debian-stable happy. I don't really see why using Go (from source) would be a problem as this only needs to happen on the dev/build machines. Distributing go binaries is a non-issue.

Some I'm leaning towards 'no', *but* if I can be done cleanly and separately I'm willing to accept PRs to support go 1.3 again.

**Comment by asergeyev** [comment]
crypto.Hash is type that was changed along the way to create crypto.Signer. It would require bigger changes to dns lib than just adding misisng Signer and SignerOpts interfaces. Sure it also could be pulled to special lib that would abstract things away from DNS lib, I just don't know what is good pattern...

https://gist.github.com/asergeyev/3859a899d68101a38c03


Disclaimer: I do not care about debian as well. IMO there is no need to add this, just saying it's possible to put branch out there for people who care.

**Comment by andrewtj** [comment]
This can probably be closed. If and when a PR is submitted discussion can continue there.

**Comment by ostretsov** [comment]
@bortzmeyer you may use Docker to easily switch from one version to another.

**Comment by filippog** [comment]
FWIW `jessie-backports` now ships with golang 1.5.1 so it shouldn't be a problem to build there
