### ISSUE TITLE
RRSIG(DS) validates expired

### ISSUE THREAD

**Issue by sebastianbroekhoven** [miekg/dns#278]
;+ Secure signature, networking4all.com. RRSIG(DS) validates (DNSKEY com./51797/net) (*EXPIRED*)

It looks like the ValidityPeriod is not getting well.

If I do a lookup with dig:
networking4all.com.	86400	IN	RRSIG	DS 8 2 86400 20151024041810 20151017030810 51797 com.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] RRSIG(DS) validates expired (..." ]
>;+ Secure signature, networking4all.com. RRSIG(DS) validates (DNSKEY com./51797/net) (*EXPIRED*)
>
>It looks like the ValidityPeriod is not getting well.
>
>If I do a lookup with dig:
>networking4all.com.	86400	IN	RRSIG	DS 8 2 86400 20151024041810 20151017030810 51797 com.

Can you add/create a failing test for this?

/Miek

--
Miek Gieben

**Comment by sebastianbroekhoven** [comment]
Example: https://github.com/miekg/exdns/tree/master/q
Command: go run q.go -check -dnssec networking4all.com @ns1.networking4all.com

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] RRSIG(DS) validates expir..." ]
>Example: https://github.com/miekg/exdns/tree/master/q
>Command: go run q.go -check -dnssec networking4all.com @ns1.networking4all.com

Ack.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Fixed. Thanks for the report.
