### ISSUE TITLE
Shutdown() not shutting down

### ISSUE THREAD

**Issue by peter-mogensen** [miekg/dns#279]
I noticed a while ago that shutdown of your DNS server library stopped working in my example code.

I got around to investigating the reason and I believe the problem was introduced by calling .File() on the listener which in turn causes the Go std lib to call dup(2) on the file descriptor and setting it in non-blocking mode.
That causes the standard method of stopping Serve() by closing the listener to not work.

I don't think that issue is covered by the existing server_test.go.

Below is a patch against current master server_test.go to illustrate the problem - and a small monkey-patch to udp_linux.go to make the problem go away (it's probably not the most elegant way to solve it)

```
The attached example is for UDP, but I believe the problem is the same for TCP. 
==================================================================
diff --git a/server_test.go b/server_test.go
index b3e0c72..0f26e32 100644
--- a/server_test.go
+++ b/server_test.go
@@ -37,6 +37,29 @@ func AnotherHelloServer(w ResponseWriter, req *Msg) {
 	w.WriteMsg(m)
 }
 
+func RunLocalUDPServer2(laddr string) (*Server, string, chan struct{}, error) {
+	pc, err := net.ListenPacket("udp", laddr)
+	if err != nil {
+		return nil, "", nil, err
+	}
+	server := &Server{PacketConn: pc, ReadTimeout: time.Hour, WriteTimeout: time.Hour}
+
+	waitLock := sync.Mutex{}
+	waitLock.Lock()
+	server.NotifyStartedFunc = waitLock.Unlock
+
+	fin := make(chan struct{},0)
+	
+	go func() {
+		server.ActivateAndServe()
+		close(fin)
+		pc.Close()
+	}()
+
+	waitLock.Lock()
+	return server, pc.LocalAddr().String(), fin, nil
+}
+
 func RunLocalUDPServer(laddr string) (*Server, string, error) {
 	pc, err := net.ListenPacket("udp", laddr)
 	if err != nil {
@@ -47,7 +70,7 @@ func RunLocalUDPServer(laddr string) (*Server, string, error) {
 	waitLock := sync.Mutex{}
 	waitLock.Lock()
 	server.NotifyStartedFunc = waitLock.Unlock
-
+	
 	go func() {
 		server.ActivateAndServe()
 		pc.Close()
@@ -390,7 +413,7 @@ func TestShutdownTCP(t *testing.T) {
 }
 
 func TestShutdownUDP(t *testing.T) {
-	s, _, err := RunLocalUDPServer("127.0.0.1:0")
+	s, _, fin, err := RunLocalUDPServer2("127.0.0.1:0")
 	if err != nil {
 		t.Fatalf("Unable to run test server: %v", err)
 	}
@@ -398,6 +421,12 @@ func TestShutdownUDP(t *testing.T) {
 	if err != nil {
 		t.Errorf("Could not shutdown test UDP server, %v", err)
 	}
+	time.Sleep(time.Duration(2)*time.Second) // give it time to shut down.
+	select {
+	case <-fin:
+	default:
+		t.Error("Could not shutdown test UDP server. Gave up waiting")
+	}
 }
 
 type ExampleFrameLengthWriter struct {
diff --git a/udp_linux.go b/udp_linux.go
index 7a10785..307ef22 100644
--- a/udp_linux.go
+++ b/udp_linux.go
@@ -24,6 +24,10 @@ func setUDPSocketOptions4(conn *net.UDPConn) error {
 	if err := syscall.SetsockoptInt(int(file.Fd()), syscall.IPPROTO_IP, syscall.IP_PKTINFO, 1); err != nil {
 		return err
 	}
+	err = syscall.SetNonblock(int(file.Fd()), true)
+	if err != nil {
+		return err
+	}
 	return nil
 }
```

**Comment by peter-mogensen** [comment]
... ok... github broke that in so many ways... 
Anyway ... it was not really meant for anything but illustrating the problem.

**Comment by miekg** [comment]
@FiloSottile do you have a chance the look into this? Thanks!

**Comment by leavengood** [comment]
I have noticed this issue as well. It seems to only affect UDP servers, and applying the SetNonblock() change seems to fix it. I'm running it inside a Docker container, hence using Linux.

**Comment by miekg** [comment]
What SetNonblock change?

**Comment by leavengood** [comment]
The one at the end of the diff in peter-mogensen's post above.

**Comment by miekg** [comment]
Ah. Totally missed that...

**Comment by leavengood** [comment]
I tried making the same `syscall.SetNonblock()` call on the `*net.UDPConn` in my code, but it did not fix the problem. Adding it to `setUDPSocketOptions4()` in up_linux.go fixes it for me in my project. Maybe this isn't the right fix, but it is better than having the server lockup on Shutdown.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Shutdown() not shutting d..." ]
>I tried making the same `syscall.SetNonblock()` call on the `*net.UDPConn` in my code, but it did not fix the problem. Adding it to `setUDPSocketOptions4()` in up_linux.go fixes it for me in my project. Maybe this isn't the right fix, but it is better than having the server lockup on Shutdown.

Sorry for being super lazy here, but I'm very busy with work atm. Can you send a
PR for this?

Thanks!

/Miek

--
Miek Gieben

**Comment by leavengood** [comment]
I thought you might ask, and I can.

I did more digging and indeed if `File()` is never called on the UDPConn this problem doesn't happen, so I think Peter's code is good. I'll fork the repo, apply Peter's change, make sure the tests pass, and then do a PR.

Unless @peter-mogensen is listening and can do the PR himself :)

I'll wait a bit then proceed.

**Comment by miekg** [comment]
Nice! Thank you. No rush.

**Comment by peter-mogensen** [comment]
I'm listening... 
I use the SetNonBlock() in some unrelated code of my own where I can make guaranties about not doing anything else to the FD (it happens for TCP too). But I'm not sure it's the best general fix, which is why I didn't make this a PR.

The problem is that exiting from accept() on Close() only works if the socket is non-blocking (as default in Go), but the Go runtime sets the FD blocking every time it needs to call dup(2) .. like in every Go call to File().

There's been some talks about this on the list a few years ago - like:
https://groups.google.com/forum/#!topic/golang-nuts/yI8I-mUkl9o

**Comment by leavengood** [comment]
You probably know more about this than I do Peter but I think the fix is pretty good. I don't think anyone else will be affected by the fix, whereas right now I think the code is broken. The sockets FD is not used anywhere else.

I've run the tests and refactored your change a bit and am ready to do a PR.

One final point: I imagine this `SetNonblock` call should also be added to `setUDPSocketOptions6`?

**Comment by leavengood** [comment]
I'm heading home now, let me know if anything needs to be adjusted in the PR.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Shutdown() not shutting d..." ]
>I'm heading home now, let me know if anything needs to be adjusted in the PR.

PR looks good. One question though... that you might be able to answer. Why
didn't this only turn up recently? That udp code is pretty old.

Thanks for the PR!

/Miek

--
Miek Gieben

**Comment by peter-mogensen** [comment]
Because if what is calling Shutdown() proceeds to cause process exit, no one notices if accept() didn't actually exit.

**Comment by peter-mogensen** [comment]
Anyway ... as a final note, I think the Go-team should document this a bit. It seems like an implementation detail that the FD is set blocking whenever File() is called (like to get an *os.File) ... and it then causes the standard pattern of exiting an accept() loop by closing the Listener. (Speaking TCP here... the problem is the same for UDP and TCP)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Shutdown() not shutting d..." ]
>Anyway ... as a final note, I think the Go-team should document this a bit. It seems like an implementation detail that the FD is set blocking whenever File() is called (like to get an *os.File) ... and it then causes the standard pattern of exiting an accept() loop by closing the Listener. (Speaking TCP here... the problem is the same for UDP and TCP)

Send a patch :)

/Miek

--
Miek Gieben
