### ISSUE TITLE
Tsig is not being set in client request messages.

### ISSUE THREAD

**Issue by maquigu** [miekg/dns#284]
The client type function exchange doesn't set the message Tsig even if the client type TsigSecret var is set properly. TsigGenerate does not get called from client-side at all--shouldn't it? Thanks.

**Comment by andrewtj** [comment]
By my read Exchange should sign the message if the message contains a TSIG record. Are you placing a TSIG record in the message you pass to Exchange?

**Comment by andrewtj** [comment]
An example using the [SIDN workbench](https://workbench.sidnlabs.nl/index.html):

```go
package main

import (
        "time"
    
        "github.com/miekg/dns"
)   
    
func main() {
        qm := new(dns.Msg)
        qm.SetQuestion("types.wb.sidnlabs.nl.", dns.TypeNS)
        qm.SetTsig("wb_sha256.", dns.HmacSHA256, 300, time.Now().Unix())
        c := new(dns.Client)
        c.TsigSecret = map[string]string{"wb_sha256.": "npfrIJjt/MJOjGJoBNZtsjftKMhkSpIYMv2RzRZt1f8="}
        am, _, err := c.Exchange(qm, "bind9.sidnlabs.nl:53")
        if err != nil {
                panic(err)
        }
        println(am.String())
}
```

**Comment by maquigu** [comment]
That did the trick! Thank you for the prompt and thorough response. 
I wasn't setting the tsig properly, via the dns.Msg.SetTsig call. This works perfectly.
