### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bronze1man** [miekg/dns#286]
This panic happens when call w.Close() in a tcp dns server.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x73a807]

goroutine 378753 [running]:
github.com/miekg/dns.(*Server).readTCP(0xc82146fc70, 0x0, 0x1dcd65000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/fastcat/src/github.com/miekg/dns/server.go:562 +0x5d7
github.com/miekg/dns.(*defaultReader).ReadTCP(0xc82017e6d8, 0x0, 0x1dcd65000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/fastcat/src/github.com/miekg/dns/server.go:226 +0x5c
github.com/miekg/dns.(*Server).serve(0xc82146fc70, 0x7f9d658d9a48, 0xc8214a74d0, 0x7f9d658d9a20, 0xc82017fa68, 0xc82220caa0, 0xc, 0xc, 0x0, 0x0, ...)
        /root/fastcat/src/github.com/miekg/dns/server.go:552 +0x450
created by github.com/miekg/dns.(*Server).serveTCP
        /root/fastcat/src/github.com/miekg/dns/server.go:450 +0x3e9

https://github.com/miekg/dns/blob/master/server.go#L683
https://github.com/miekg/dns/blob/master/server.go#L555

**Comment by miekg** [comment]
Do you have a short test?

**Comment by bronze1man** [comment]
No.
Call w.Close() in a tcp dns server will panic for sure.

**Comment by miekg** [comment]
Ack. But what I mean is, can you make the smallest possible test case (and
a potential fix). I'm on holiday so I won't do much atm.

**Comment by andrewtj** [comment]
Test case:

```go
package main

import (
	"fmt"
	"io"
	"net"
	"time"

	"github.com/miekg/dns"
)

func main() {
	dns.HandleFunc(".", func(w dns.ResponseWriter, r *dns.Msg) {
		w.Close()
	})

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		panic(err)
	}
	addr := ln.Addr().String()
	fmt.Printf("Listening on %s\n", addr)

	go func() {
		c := &dns.Client{Net: "tcp"}
		m := new(dns.Msg).SetQuestion(".", 1)
		tries := 0
	exchange:
		_, _, err := c.Exchange(m, addr)
		if err != nil && err != io.EOF {
			fmt.Printf("Exchange failed: %s\n", err)
			if tries == 3 {
				return
			} else {
				tries += 1
				time.Sleep(time.Second)
				goto exchange
			}
		}
	}()

	server := &dns.Server{
		Addr:     addr,
		Net:      "tcp",
		Listener: ln,
	}
	server.ActivateAndServe()
}
```
