### ISSUE TITLE
support the SMIMEA record

### ISSUE THREAD

**Issue by miekg** [miekg/dns#289]
Filing as a bug because it is a nice one for beginners.

Add support for the [SMIMEA](https://datatracker.ietf.org/doc/draft-ietf-dane-smime/) record. The one thing I don't _really_ know if the format is final though.

**Comment by miekg** [comment]
Record type number is [53](http://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml)

**Comment by rolandshoemaker** [comment]
Closed by #410.
