### ISSUE TITLE
Reflectionless pack/unpack

### ISSUE THREAD

**Issue by cbranch** [miekg/dns#291]
Reflection is cool, but it is not without cost. In applications that do a lot of DNS record processing off the wire (both live or from pcaps) the garbage generated by the pack and unpack routines gets noticeable, almost all of that garbage is caused by reflection.

Since the majority of DNS traffic is pretty simple - A records - it's easy to special-case them as in PR #285. But there's no reason this can't be extended to all record types by adding more code generation.

Open questions:

- What is the interface for the Pack method implemented by every instance of RR? (Probably the same as PackRR, but worth asking the question.)
- Should we generate pack/unpack methods for an RR type by monomorphization? If not, should there be a consistent interface for unpacking each data type to simplify the code generation, and what would it look like?
- Do we also support Pack on the RR_Header type? (The use case is dynamic update where rdlength==0)

**Comment by miekg** [comment]
> Open questions:
>  
> * What is the interface for the Pack method implemented by every instance of RR? (Probably the same as PackRR, but worth asking the question.)

Yes, minus the rr argument of course. 

> * Should we generate pack/unpack methods for an RR type by monomorphization? If not, should there be  a consistent interface for unpacking each data type to simplify the code generation, and what would it look like?

```
% dict monomorphization
No definitions found for "monomorphization"
```
Not sure what you're asking here, but stuff should be "easily" be added to zgenerate.go?

> * Do we also support Pack on the RR_Header type? (The use case is dynamic update where rdlength==0

yes.

**Comment by cbranch** [comment]
Monomorphization is instantiating a complete instance of some generic code for each (used) combination of input types - that's my C++ background showing through, sorry.

To be more precise, what approach to code generation sounds better to you?

- Translate the big switch statement in (un)packStructValue but outputting the code within each case block. This has the effect of inlining every unpack of the message header, for example, or `(*DS).Pack()` having identical code to `(*CDS).Pack()`.
- Extract each case into its own function, and for a given RR insert code that calls an unpacker function for each struct field present.

I'd say the latter, but it's a bigger change.

**Comment by miekg** [comment]
I agree that the latter is the better thing to do, but as you say, more work.

**Comment by asergeyev** [comment]
my 2 cents, sorry for popping up....

There is other overhead in string/bytebuffer creation and value copying as the unpacking goes.  It might be that solid benchmark would help to understand if there is huge wins from removing Reflect or they are in 10% range.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Reflectionless pack/unpac..." ]
>my 2 cents, sorry for popping up....

No worries. I value your input :)

>There is other overhead in string/bytebuffer creation and value copying as the unpacking goes.  It might be that solid benchmark would help to understand if there is huge wins from removing Reflect or they are in 10% range.

I agree with that.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
@cbranch is it possible to do a more comprehensive benchmark?

**Comment by miekg** [comment]
To close the loop on this; yes it makes sense to remove reflection as it is faster. Currently a work in progress, but some of the most used RRs have been moved. This also allows use to kill the really long PackStructValue function in msg.go.
