### ISSUE TITLE
How do I disable Zone Transfers?

### ISSUE THREAD

**Issue by rushmorem** [miekg/dns#292]
When using this library to build a DNS server, how do I disable Zone Transfers if I don't need them?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] How do I disable Zone Transfe..." ]
>When using this library to build a DNS server, how do I disable Zone Transfers if I don't need them?

If you don't implement the backend code to actually send a zone transfer, you
don't need to do anything. The library doesn't magically enable zone transfers
for you, it only allows you to create/parse/generate such request/responses.

/Miek

--
Miek Gieben

**Comment by rushmorem** [comment]
Thanks @miekg. I thought as much, however, when I tested my implementation using http://mxtoolbox.com/DNSCheck.aspx it cautioned: `Open Zone Transfer Detected` so I wanted to shut it up.

**Comment by michaelharo** [comment]
Perhaps something like:
```go
if m.Question[0].Qtype == dns.TypeAXFR || m.Question[0].Qtype == dns.TypeIXFR {
  w.WriteMsg(new(dns.Msg).SetRcode(m, dns.RcodeNotAuth)))
  return
}
```

**Comment by rushmorem** [comment]
@michaelharo let me give it a shot. Thanks!

**Comment by rushmorem** [comment]
@michaelharo That did the trick. Thanks a lot!
