### ISSUE TITLE
Performance difference between TCP and UDP servers

### ISSUE THREAD

**Issue by khash** [miekg/dns#293]
I observed a huge difference between TCP and UDP servers:

```
$ time dig @localhost google.com 
real 0m1.037s
```

while 

```
$ time dig +tcp @localhost google.com
real	0m0.040s
```

Looking at the code, I have found that `m, s, e := reader.ReadUDP(l, rtimeout)` inside `Server.serveUDP` is holding up the response. Added the following logs:

```
	glog.V(15).Info("serveUDP is ready")
	// deadline is not used here
	for {
		m, s, e := reader.ReadUDP(l, rtimeout)
		glog.V(15).Info("Out of ReadUDP")
		srv.lock.RLock()
		if !srv.started {
			srv.lock.RUnlock()
			return nil
		}
		srv.lock.RUnlock()
		if e != nil {
			continue
		}
		srv.inFlight.Add(1)
		glog.V(15).Infof("Got message %s:%s:%s", m, l, s)
		go srv.serve(s.RemoteAddr(), handler, m, l, s, nil)
	}
```

This shows `serverUDP is ready` is logged immediately as soon as the server is started and `Got message` is logged immediately after the last `Out of ReadUDP`. However `reader.ReadUDP` is always held up as long as the timeout.

However while reducing `rtimeout` shows the code going through the loop much faster, but the queries still take about a second to come back. Profiling the rest of the code after this point doesn't show any points causing this (everything else after `Got message` log go through in less than 20ms). Also nothing in the rest of the code is different between TCP and UDP.

This is very puzzling. Any thoughts as to why this could be?

**Comment by khash** [comment]
To take out any of my custom code, I tried using https://github.com/kenshinx/godns and the results are the same. Using `time dig @8.8.8.8 +tcp google.com` and `time dig @8.8.8.8 +notcp google.com` doesn't make difference in performance.

**Comment by miekg** [comment]
Interesting observation... In the end this code calls: `ReadFromSessionUDP`, which calls `ReadMsgUDP`, is there a bug in there?
From the looks of it, it does not seem this code (i.e. what you reference) does anything whacky...

**Comment by andrewtj** [comment]
I tried to replicate this behaviour using go1.5.1 on a FreeBSD 10.2 VM and https://github.com/kenshinx/godns. I didn't really get any distinct result but that could be due to any number of things. Can you share some more details on your environment?

**Comment by khash** [comment]
I think I managed to get to the bottom of this. This was a combination of multiple things on top of each other (some local and some systemic) that caused the issue:

Issue with `localhost`:
- Using `localhost` with UDP was significantly slower than `127.0.0.1` as for TCP, performance was identical between `localhost` and `127.0.0.1`.
- Using a different name in `/etc/hosts` for `127.0.0.1` instead of `localhost` yielded in identical performance between TCP and UDP.
- Using an alias for `8.8.8.8` in `/etc/hosts` file doesn't affect the performance of queries. Both TCP and UDP work just as performant regardless of the IP or address.

This might be isolated to my test machine.

SingleInFlight flag:
- Changing the `SingleInFlight` flag for UDP to `false` improved the performance. It however didn't make any significant difference with TCP.

**Comment by asergeyev** [comment]
Good summary, thanks... BTW, use of "localhost" on modern OS often results in using "::1", just something to recall next time we chat about this.
