### ISSUE TITLE
Is it possible to support DNSCrypt

### ISSUE THREAD

**Issue by missdeer** [miekg/dns#297]
[DNSCrypt](https://dnscrypt.org/) protocol is widely used in China, hopefully, dns package could support this protocol.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] Is it possible to support DNS..." ]
>[DNSCrypt](https://dnscryptorg/) protocol is widely used in China, hopefully, dns package could support this protocol

Spec does not too difficult. Can't guarantee I have time for it though.

Would be nice if this was totally transparant, i.e. you set dns.Client.Crypt =
true and DNScrypt is supported.

/Miek

--
Miek Gieben

**Comment by bortzmeyer** [comment]
I would prefer to see support for DNS-over-TLS, which is a standard and is almost ready https://datatracker.ietf.org/doc/draft-ietf-dprive-dns-over-tls/

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Is it possible to support..." ]
>I would prefer to see support for DNS-over-TLS, which is a standard and is almost ready https://datatracker.ietf.org/doc/draft-ietf-dprive-dns-over-tls/

Send patches :)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
@missdeer DNS over TLS is now supported which might help you a bit...nobody is working DNScrypt yet AFAIK
