### ISSUE TITLE
Manipulating FQDNs

### ISSUE THREAD

**Issue by tlimoncelli** [miekg/dns#301]
While using miekg/dns I've written a number of utility functions.  I would like to upstream them because I think other people would find them useful.

func MakeFqdn(origin, s string) string
// Returns "s" + "." + origin but does the right thing if s=="@" or IsFqdn(s).

func StripFqdn(origin, s string) string
// Strips origin from s.  Returns "@" instead of "".  Returns s unchanged if it doesn't suffix with origin.

func GenerateZone(rrs []RR) string
// The opposite of ParseZone().  Generates a very pretty zonefile.

I'd gladly submit a PR however I would like your recommendation for which file to include these functions?

Thanks!

**Comment by miekg** [comment]
While I appreciate these functions (GenerateZone looks really interesting), I see a lot of code that does not even use `IsFqdn()` because nobody looks for such a function in go DNS. Although the `@` handling in zonefile is somewhat non obvious...

To invoke the README:
> If there is stuff you should know as a DNS programmer there isn't a convenience
> function for it.

@andrewtj what do you think?

**Comment by andrewtj** [comment]
I'm not sure they have broad use. I had a quick look for similar implementations and couldn't find any (but that doesn't mean much). They're probably fairly self-contained though so I wouldn't be opposed to adding them if only a handful of people would find them useful.

Regardless of whether they're merged I think we could do with some doc summarising the name util functions (I think they get a bit lost in `go doc`).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Manipulating FQDNs (#301)..." ]
>I'm not sure they have broad use. I had a quick look for similar implementations and couldn't find any (but that doesn't mean much). They're probably fairly self-contained though so I wouldn't be opposed to adding them if only a handful of people would find them useful.
>
>Regardless of whether they're merged I think we could do with some doc summarising the name util functions (I think they get a bit lost in `go doc`).

I am leaning towards not merging these, unless other people jump up and shout
that they really want this.

A Fit function (#223) and a CNAME/RR ordering function (https://github.com/skynetservices/skydns/issues/217)
would be something more useful and has a high change of being merged :)

grtz Miek

**Comment by tlimoncelli** [comment]
Well I had a PR that was mostly done so I finished it.  For your consideration, please review:

    https://github.com/miekg/dns/pull/302

Note: The functions were renamed TrimDomain and AddDomain.

I'm using miekg/dns mostly for automating DNS operations at StackOverflow and other projects. All of our code has repeated the TrimDomain and AddDomain functions, which is why we were inspired to contribute the functions to the project.  (Especially since there are odd edge-cases that some bite unsuspecting folks.)

**Comment by andrewtj** [comment]
Was this all wrapped in #302?

**Comment by miekg** [comment]
@andrewtj only the fqdn functions have been merged, not the zone pretty printing stuff.

Basically if there is going to be more pretty printing I want it to be super flexible, so people can build on top of it.

**Comment by andrewtj** [comment]
@miekg sounds like a good idea. There's a few instances of [this sort of thing](https://github.com/fcambus/rrda/blob/2bd46e785603e8df9c8328f1e444d2d91f52b05e/rrda.go#L57-L60) out there.

**Comment by miekg** [comment]
@andrewtj jep, something that makes that not needed.
Note there already is:
```
% godoc . Field 
func Field(r RR, i int) string
    Field returns the rdata field i as a string. Fields are indexed starting
    from 1. RR types that holds slice data, for instance the NSEC type
    bitmap will return a single string where the types are concatenated
    using a space. Accessing non existing fields will cause a panic.
```
