### ISSUE TITLE
Locally defined NS domains are not reached

### ISSUE THREAD

**Issue by Soullivaneuh** [miekg/dns#308]
If you define a NS server on `/etc/hosts`:

```bash
/go # cat /etc/hosts 
172.17.0.8  dnsmasq ccbbc15c11cd
172.17.0.8  dnsmasq_1 ccbbc15c11cd
```

The server is never reached on `c.Exchange` method.

You can see more details on RRDA implementation which use your library: https://github.com/fcambus/rrda/issues/8#issuecomment-178706669

**Comment by Soullivaneuh** [comment]
Related call: https://github.com/fcambus/rrda/blob/2bd46e785603e8df9c8328f1e444d2d91f52b05e/rrda.go#L110

**Comment by miekg** [comment]
But should it? Think this is the work of nsswitch, not the dns lib...

Although I can see the appeal of having this work out of the box.

**Comment by andrewtj** [comment]
Have you built `rrda` to use Go's `netgo` or `netcgo` resolver? (See [net](https://golang.org/pkg/net/)'s doc if you're not sure.) Only the later is liable to work and it'll need access to `/etc/hosts` (might be stating the obvious but I'm not sure how Docker does things).

**Comment by Soullivaneuh** [comment]
> Have you built rrda to use Go's netgo or netcgo resolver?

I'm sorry but I'm not really a Go expert (for now :-P), what do you mean? Compiling it with this module? Can you give me some command lines samples?

> might be stating the obvious but I'm not sure how Docker does things

Well, my Docker image is based on `go-alpine`, for the rest, it's just a classic Alpine Linux with same behaviors as host.

See Dockerfile: https://hub.docker.com/r/dockervan/rrda/~/dockerfile/

**Comment by andrewtj** [comment]
Setting the environment variable `GODEBUG=netdns=1` should tell you which resolver has been selected. You should see something like `go package net: using cgo DNS resolver` printed when `rrda` is started with that set. The “Name Resolution” section of [net's doc](https://golang.org/pkg/net/) has more information on Go's resolvers.

**Comment by Soullivaneuh** [comment]
Here is my `Dockerfile` with the GODEBUG env:

```Dockerfile
FROM golang:alpine

MAINTAINER Sullivan SENECHAL <soullivaneuh@gmail.com>

RUN apk add --update --no-cache git mercurial \
&& go get github.com/fcambus/rrda \
&& apk del git mercurial

EXPOSE 80

ENV GODEBUG "netdns=1"

CMD ["rrda", "-host=0.0.0.0", "-port=80"]
```

But nothing like you said is shown: 

```bash
$ docker-compose up rrda
Starting nadmin_dnsmasq_1
Recreating nadmin_rrda_1
Attaching to nadmin_rrda_1
rrda_1 | -------------------------------------------------------------------------------
rrda_1 |         RRDA (RRDA REST DNS API) 1.01 (c) by Frederic Cambus 2012-2016
rrda_1 | -------------------------------------------------------------------------------
rrda_1 | 
rrda_1 | Listening on : 0.0.0.0:80
```

**Comment by Soullivaneuh** [comment]
Oh I got it, I have to make it before building. Here is the result:

```
go package net: dynamic selection of DNS resolver
```

**Comment by andrewtj** [comment]
That's a bit ambiguous to me. Can you try setting `GODEBUG=netdns=cgo=1` which should force `cgo` to be used?

Might be interesting to run this as well:

```go
package main

import (
        "log"
        "net"
)   
    
func main() {
        addrs, err := net.LookupHost("dnsmasq")
        if err != nil {
                log.Fatal(err)
        }
        for _, a := range addrs {
                log.Printf("%s", a)
        }
}
```
I don't know anything about Docker so I've no pointers there.

**Comment by Soullivaneuh** [comment]
This is working well:

```Dockerfile
FROM golang:alpine

MAINTAINER Sullivan SENECHAL <soullivaneuh@gmail.com>

ENV GODEBUG "netdns=cgo"

RUN apk add --update --no-cache git mercurial \
&& go get github.com/fcambus/rrda \
&& apk del git mercurial

EXPOSE 80

CMD ["rrda", "-host=0.0.0.0", "-port=80"]
```

But even if I'm not a Golang expert, I thinkg `GODEBUG` is for... debug, isn't it? :-)

How to specify it on build without debug activation?

**Comment by andrewtj** [comment]
There's a `netcgo` build tag that I see you've found. Adding `-tags netcgo` to `go build` or `go install` is the least invasive way of enabling it.

**Comment by miekg** [comment]
using the system's resolver on alpine linux (which uses musl libc) is not the best thing ever. They are fixing it AFAIK but that resolver behaves different than the one in gilbc for instance. Not following search path, multiplexing queries over *all* nameservers.

**Comment by Soullivaneuh** [comment]
> They are fixing it AFAIK

Maybe do you have a related issue?

> but that resolver behaves different than the one in gilbc for instance. Not following search path, multiplexing queries over all nameservers.

Is that a problem for RRDA @fcambus?

**Comment by Soullivaneuh** [comment]
> There's a netcgo build tag that I see you've found. Adding `-tags netcgo` to `go build` or `go install`

Could this be combined with `go get` command?

**Comment by Soullivaneuh** [comment]
If I use `-tag netcgo` I have a missing include error:

```bash
/usr/local/go/src/net/cgo_linux.go:10:19: fatal error: netdb.h: No such file or directory
```

Have to find where to find it on Alpine Linux.

@ncopa, if you have some free time, could you give me a clue? :-)

**Comment by Soullivaneuh** [comment]
By mad, forgot to install `musl-dev`.

Works like a charm now, thanks!

**Comment by mekalz** [comment]
@Soullivaneuh I met the same error when compiling project using docker image golang:1.9.6-alpine-3.7 and solved it by install `musl-dev`, thx a lot

**Comment by jerome-laforge** [comment]
As workaround, you can also compile with `CGO_ENABLED=0` and `-tags netgo`
