### ISSUE TITLE
Support for larger DNS responses

### ISSUE THREAD

**Issue by prisamuel** [miekg/dns#312]
I'm seeing the same error message as #214 when using this library for querying SRV records from Consul's DNS interface. It appears to be a similar issue.

When the message size is smaller than 512, my requests succeed. But when the response size increases to 538 B I get an error with "dns: buffer size too small".

A typical Consul SRV response looks like this:
`bash-4.3# dig example.service.consul SRV

; <<>> DiG 9.10.2 <<>> example.service.consul SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42745
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2

;; QUESTION SECTION:
;example.service.consul. IN SRV

;; ANSWER SECTION:
example.service.consul. 0 IN SRV 1 1 32866 core-i-0a2b2rewr58f-172.17.5.34.node.dc1.consul.
example.service.consul. 0 IN SRV 1 1 32866 core-i-7fafffwerwwff-172.17.4.151.node.dc1.consul.
...
...

;; ADDITIONAL SECTION:
core-i-0a2b2rewr58f-172.17.5.34.node.dc1.consul. 0 IN A 172.17.5.34
core-i-7fafffwerwwff-172.17.4.151.node.dc1.consul. 0 IN A 172.17.4.151
...
...
;; Query time: 3 msec
;; SERVER: 10.0.42.1#53(10.0.42.1)
;; WHEN: Fri Feb 19 12:58:10 UTC 2016
;; MSG SIZE rcvd: 538`

On the RFC 2675 https://tools.ietf.org/html/rfc2675
A field that specifies the length in bytes of the UDP header and UDP data. The minimum length is 8 bytes because that is the length of the header. The field size sets a theoretical limit of 65,535 bytes (8 byte header + 65,527 bytes of data) for a UDP datagram. The practical limit for the data length which is imposed by the underlying IPv4 protocol is 65,507 bytes (65,535 − 8 byte UDP header − 20 byte IP header)

This is well below the specified limit. Will there be support for this on this library?

**Comment by andrewtj** [comment]
There's a couple of things to cover here. I'll start with the protocol and then go to the practicals.

[RFC 1035](http://tools.ietf.org/html/rfc1035) defines plain old DNS to 512 byte messages over UDP (65,535 over TCP). [EDNS0](https://tools.ietf.org/html/rfc6891) allows adding a pseudo RR called the OPT RR which carries additional configuration extensions/options. With this RR the sender of the message can specify what the largest datagram they can receive is, and the responder can adjust the size of the payload they send accordingly. So Consul shouldn't be sending a 538 byte response over UDP unless an EDNS0 OPT is present with a larger buffer size specified.

This package exposes the DNS in a fairly granular way. The UDP buffer size (`[]byte{}` allocation, not in the EDNS0 sense) can be configured on [dns.Client](https://godoc.org/github.com/miekg/dns#Client) and [dns.Conn](https://godoc.org/github.com/miekg/dns#Conn). The [OPT RR is supported](https://godoc.org/github.com/miekg/dns#OPT) and can be added to a `dns.Msg` manually or via [`Msg.SetEdns0`](https://godoc.org/github.com/miekg/dns#Msg.SetEdns0). If an `OPT` is present in a `dns.Msg` handed to [`Client.Exchange`](https://godoc.org/github.com/miekg/dns#Client.Exchange) the OPT RR's buffer size will be used as the receive buffer size.

**Comment by miekg** [comment]
As @asergeyev suggested we should add an option in the client to default to larger buffers. I.e. `client.<GoodDescriptiveName>` which we then use `c.Exchange` for `Exchange` we might just want to default to larger buffers.

**Comment by andrewtj** [comment]
@prisamuel were you able to get going with the pointers above?

**Comment by miekg** [comment]
Closing now that we have slightly better docs. In the end this whole discussion might result in a new function in `dnsutil`. For now: docs should suffice.

**Comment by prisamuel** [comment]
Thanks a lot. The documentation helped a lot.

Unfortunately I don't have an update on the initial issue. But I also found
that Consul can be configured to set to truncate responses.

https://www.consul.io/docs/agent/options.html#enable_truncate

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Support for larger DNS re..." ]
>Thanks a lot. The documentation helped a lot.
>
>Unfortunately I don't have an update on the initial issue. But I also found
>that Consul can be configured to set to truncate responses.
>
>https://www.consul.io/docs/agent/options.html#enable_truncate

what a strange option. Should default to true imho and the number 3 seems
rather arbitrary. 

But anyway, at least they *have* that option.
