### ISSUE TITLE
Retrieving and setting RDLEN

### ISSUE THREAD

**Issue by matje** [miekg/dns#316]
There is no easy way to retrieve the RDLEN of an RR. Some statements after a twitter discussion are:

- `PackRR` does not set it (maybe it should).
- A Len(RR) and Len(RR_Header) might be nice.

**Comment by andrewtj** [comment]
Can you provide some more detail?

**Comment by miekg** [comment]
Twitter chat starts here: https://twitter.com/pletterpet/status/702118581291581441

**Comment by miekg** [comment]
Note this is issue when parsing from strings, getting them from the wire will set the length.

**Comment by andrewtj** [comment]
Making `PackRR` set `Rdlength` could have side effects.

**Comment by miekg** [comment]
@andrewtj yep that could very well be (didn't look in detail). Making a simple Len is prolly sufficient for this usecase:
```
func Len(r RR) int {
   return r.len()
}
```
Or we could make `len` exported on all RRs. The former is more in line with what we do with `Copy` right now so that would be my preference.

**Comment by matje** [comment]
#333
