### ISSUE TITLE
Exchange() with TCP returns a null RTT

### ISSUE THREAD

**Issue by bortzmeyer** [miekg/dns#324]
When using `Exchange()̀̀` after a `client.Net = "tcp"`, the returned `rtt` seems to be always zero.

(Tested with Go 1.6 on an ARM processor and Go 1.5.1 on a PC, with godns just retrieved today.)

**Comment by miekg** [comment]
Can you add some test code that demonstrates the problem? (Yes, being lazy here)

**Comment by bortzmeyer** [comment]
On Sun, Feb 28, 2016 at 07:24:12AM -0800,
 Miek Gieben <notifications@github.com> wrote 
 a message of 27 lines which said:

> Can you add some test code that demonstrates the problem? (Yes,
> being lazy here)

I'm lazy too, but I want the bug to be solved so I have no choice.

Attached is a test code. When I run it, I get:

% ./tcp 8.8.8.8 nl       
(time 000 µs) 2 keys. TC=false

If I comment the line activating TCP, I get the expected reply:

% ./udp 8.8.8.8 nl       
(time 19518 µs) 2 keys. TC=false

I checked with tcpdump that I indeed used TCP in the first case and
UDP in the second.


package main

import (
	"fmt"
	"github.com/miekg/dns"
	"os"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Printf("%s NAMESERVER-IP ZONE\n", os.Args[0])
		os.Exit(1)
	}
	ns := os.Args[1]
	zone := dns.Fqdn(os.Args[2])
	m := new(dns.Msg)
	m.RecursionDesired = true
	m.Question = make([]dns.Question, 1)
	c := new(dns.Client)
	c.Net = "tcp" // Comment it and it will run with UDP
	m.Question[0] = dns.Question{zone, dns.TypeDNSKEY, dns.ClassINET}
	m.Id = dns.Id()
	in, rtt, err := c.Exchange(m, ns+":53")
	if err == nil && in != nil && len(in.Answer) > 0 {
		fmt.Printf("(time %.3d µs) %d keys. TC=%v\n", rtt/1e3, len(in.Answer), in.Truncated)
	} else {
		if err != nil {
			fmt.Printf("Error in query: %s\n", err)
		} else if in == nil {
			fmt.Printf("No answer received\n")
		} else if len(in.Answer) == 0 {
			fmt.Printf("Empty answer received. TC=%v\n", in.Truncated) // Common by default, since DNSKEY answers can be large
		}
	}
}

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Exchange() with TCP retur..." ]
>I'm lazy too, but I want the bug to be solved so I have no choice.

good :-)

Thanks reworked this into an actual test, see my issue-324 branch. (And
reproduced)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
https://github.com/miekg/dns/pull/325

**Comment by bortzmeyer** [comment]
It works for me, thanks. 

It was not very clear from the documentation but it seems the returned `rtt` is just the RTT of the DNS request itself, not taking into account (possible) time taken to establish the TCP connection?
