### ISSUE TITLE
DNS Response Recorder?

### ISSUE THREAD

**Issue by miekg** [miekg/dns#328]
Love this stuff: https://godoc.org/net/http/httptest#ResponseRecorder, makes doing (for instance) metrics a breeze. We should add something to dns to mimic this.

**Comment by miekg** [comment]
CoreDNS has this: https://github.com/miekg/coredns/blob/master/middleware/recorder.go

**Comment by miekg** [comment]
Also this should then sit in a `dnstest/` sub dir

**Comment by gregory-m** [comment]
Any plans to add this?

**Comment by miekg** [comment]
Seems easy enough to write yourself: https://github.com/miekg/coredns/tree/master/middleware/pkg/dnsrecorder

Not sure if we should pull this into this lib.

**Comment by gregory-m** [comment]
I actually wrote something like coredns dnsrecorder, but I think it should be in lib because every person who want to test his handlers will write own implementation. I think this is why httptest exists in stdlib.

**Comment by miekg** [comment]
Ok. Let move it to here in `dnstest` sub package.

**Comment by miekg** [comment]
I can live without this - less code to maintain
