### ISSUE TITLE
make `msg.Len()` more scalable

### ISSUE THREAD

**Issue by miekg** [miekg/dns#331]
Len() currently iterates over the entire message _every_ time it gets called. So if you're appending in a loop and calling Len() a lot you get a nasty surprise.
We should make this faster. Also see #330

**Comment by miekg** [comment]
We can track the current msg length and the 4 lengths of the different sections. And then only calculate the length when of the extra RRs that have been added since last time. This of course only works when *adding* RRs, when RR have been deleted, just redo the length calculation.

Down side is: if you *replace* an RR and want to get the length, there is a) no way to know what RR has changed and b) you would then need a way to reset the length counters....

**Comment by miekg** [comment]
We could track even more and also check for changed RR, but that house keeping would intro more memory use, etc. etc. Not really an option I think.

**Comment by miekg** [comment]
Think a new function `FastLen()` (better names welcome) with these changed semantics will be best. This adds a few struct members to Msg but that's not that bad.

**Comment by andrewtj** [comment]
It's probably worth starting with benchmarks for this one. I don't have much of an inclining as to where we're starting from or what the performance aim ought to be.

API wise a seperate opaque struct providing the context and implementation might have some benefits. It'd allow for some flexibility in the implementation and make it clear that housekeeping needs to be done. Public methods would allow for resetting to a section and record, and for returning the length.

**Comment by miekg** [comment]
Jep, actually benchmarking makes sense.

You're proposing adding special methods, `Add`, `Remove`, `Replace` on Msg that will recalc the length. That might actually be nicer.

**Comment by miekg** [comment]
Compression makes this also hard... as we drop the compression table and recalc. it every time we calculate the length. It still believe some kind of caching of these things and optimizing for the (I think) most common use-case (adding RRs) is valid.

**Comment by miekg** [comment]
hard to do in current code and architecture of this package.
