### ISSUE TITLE
How to use dns.ClientConfigFromFile in windows?

### ISSUE THREAD

**Issue by searchworld** [miekg/dns#334]
I just see the [blog](https://miek.nl/2014/August/16/go-dns-package/)  and want to use the code in windows with go. In unix the configure of nameserver is in "/etc/resolve.conf", but where can I get the nameserver in the windows?
Thanks!

**Comment by miekg** [comment]
I don't know, don't use windows...

**Comment by asergeyev** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365968(v=vs.85).aspx
Not sure if there is bindings for go or you have to mess with DLLs.

**Comment by asergeyev** [comment]
https://github.com/golang/sys/blob/master/windows/syscall_windows.go
looks like it's not wrapped. You might try to ask folks contributing to golang sys project about ways to use it. I don't think it's easy to find Go people with good Windows experience elsewhere.

**Comment by searchworld** [comment]
Thank you for reply. I have refer to a Java dns library and find that it get the local dns via parsing the ipconfig outcome. At last I used the golang's net library that default a local resolve.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] How to use dns.Clie..." ]
>Thank you for reply. I have refer to a Java dns library and find that it get the local dns via parsing the ipconfig outcome. At last I used the golang's net library that default a local resolve.

Does that work with `-net go`, i.e. is it all pure Go or does Go use the system
libaries?

If it is the first we should lift that code of out of std lib and use it in Go
DNS.

**Comment by searchworld** [comment]
Hello @miekg 
My case may be something of special. I have to run a dns resolve in the windows os with the given nameservers, or if not given, with the local nameserver. I find that go's dns library can only use the local resolve while your dns library need to provide an extra one. Now I combine these two to implement the case.

**Comment by miekg** [comment]
Not seeing activity, nor a PR, closing for now.

**Comment by moloch--** [comment]
Working example for windows: https://gist.github.com/moloch--/9fb1c8497b09b45c840fe93dd23b1e98
