### ISSUE TITLE
EDNS ExtendedRcode return uint size

### ISSUE THREAD

**Issue by McStork** [miekg/dns#341]
Hi,
After the recent update of ExtendedRcode, the return type which was uint8 should be upgraded to at least uint16, as [it can now return](https://github.com/miekg/dns/commit/b5f8285e2ab8f825c92ba68ddbbfe55c534b1064) an integer of a size up to 12bits.

**Comment by miekg** [comment]
yep, you're right and `uint8` was never good. Pondering just `int` or `uint16` as the fixed return code...
