### ISSUE TITLE
Local DNS

### ISSUE THREAD

**Issue by joeblew99** [miekg/dns#348]
Does this DNS support running in a LAN, and letting the clients (browsers in this case) discovering it automagically ?

Sorry about blunt question, but kind of stuck finding solution.

**Comment by miekg** [comment]
Yes and no. No as in this package does not do that and yes you can code it
up yourself with this package. Search for mdns golang to get some hits.

**Comment by joeblew99** [comment]
I need avahi right ?

I noticed mdns from hashicorp does it ?

**Comment by joeblew99** [comment]
I should explain that this is useful because i will have a single server and many client on a LAN, and it woudl be really nice if the clients can "know" the servers ip to connect to. i have no guarantee that the server Ip has not changed :) - its dynamic Ip allocate from the router, and i have no choide about changing that :)

But the other aspect to this was somethng really simple that golang just fights me on.
When the Client calls over http rest call, on the server i need to identify the clients by IP address.
Its supper easy, but in my code all i get back is "::1".
Any clues ?? 

````

// getClientIPByRequest tries to get directly from the Request.
// https://blog.golang.org/context/userip/userip.go
func getClientIPByRequest(req *http.Request) (ip string, err error) {

	// Try via request
	ip, port, err := net.SplitHostPort(req.RemoteAddr)
	if err != nil {
		log.Printf("debug: Getting req.RemoteAddr %v", err)
		return "", err
	} else {
		log.Printf("debug: With req.RemoteAddr found IP:%v; Port: %v", ip, port)
	}

	userIP := net.ParseIP(ip)
	if userIP == nil {
		message := fmt.Sprintf("debug: Parsing IP from Request.RemoteAddr got nothing.")
		log.Printf(message)
		return "", fmt.Errorf(message)

	}
	log.Printf("debug: Found IP: %v", userIP)
	return userIP.String(), nil

}

`````

**Comment by miekg** [comment]
Ahavi is some codename for the thing..mdns is the offical protocol name.

Don't know what hashicorp does or does not implement

**Comment by asergeyev** [comment]
I think it comes from  https://github.com/hashicorp/mdns , lib that can work as multicast DNS server and client.  I'd recommend reading things referenced from  http://www.multicastdns.org/

**Comment by joeblew99** [comment]
Ok cheers.
