### ISSUE TITLE
Panic on edns

### ISSUE THREAD

**Issue by semihalev** [miekg/dns#351]
Hey,

These days i received panic from dns servers. I checked debug logs and i found the problem.

The Log:
panic: runtime error: index out of range

The Line:
https://github.com/miekg/dns/blob/master/msg.go#L605

Thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Panic on edns (#351)..." ]
>Hey,
>
>These days i received panic from dns servers. I checked debug logs and i found the problem.
>
>The Log:
>panic: runtime error: index out of range
>
>The Line:
>https://github.com/miekg/dns/blob/master/msg.go#L605
>
>Thanks.

Yep, length check failing. Do you have a packet that triggers this (for the
test).

/Miek

--
Miek Gieben

**Comment by semihalev** [comment]
Miek,

I dont have the packet but I think came from google public dns servers. I received heavy dns request from them. They are using EDNS opt.
