### ISSUE TITLE
Client's Exchange always creates new socket

### ISSUE THREAD

**Issue by asergeyev** [miekg/dns#36]
There is issue I'm observing while trying to create fast moving tool with your library (which is great). 

On high levels of concurrency, when I let goroutines run wild I'm getting "dial udp a.b.c.d:53: too many open files" error. 

IMO that's due to client's exchange logic that only has single way of doing things ritght now, "Exchange() -> dial()/send()->write()/receive()->read()"

That will essentially create socket in OS for every operation and send/receive on it via "send and recv". Sendto and recvfrom in my situation would be most efficient but syscall lib is very hard to deal with, I'm trying to find simpler solutions...

IMO other version of Exchange could have additional net.Conn parameter for clients who send bunch of requests to same address... As coder I'd expect it this way:

```
dnsconn := c.Dial(addr)
for _, msg := range queries {
    resp, rtt, err := c.ExchangeWith(dnsconn)
    if err {
         ...
    }
    ...
}
```

Should not be hard to implement... You might suggest different way of handling that. I understand that retrying logic might require to keep more than one net.Conn inside of that "dnsconn" structure.

**Comment by detailyang** [comment]
`ExchangeConn` is not concurrent friendly which can receive other DNS query response
