### ISSUE TITLE
hmac algorithm names

### ISSUE THREAD

**Issue by mmonaco** [miekg/dns#362]
According to [RFC4635](https://tools.ietf.org/html/rfc4635), and what I can use with tools such as `dig`. The hmac algorithms doesn't need a trailing "." when passed in from the user. However, this library is throwing ErrKeyAlg...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] hmac algorithm names (#..." ]
>According to [RFC4635](https://tools.ietf.org/html/rfc4635), and what I can use with tools such as `dig`. The hmac algorithms doesn't need a trailing "." when passed in from the user. However, this library is throwing ErrKeyAlg...

No, it does need the dot because it is encoded as a domain name:

    1.  Introduction

       [RFC2845] specifies a TSIG Resource Record (RR) that can be used to
       authenticate DNS (Domain Name System [STD13]) queries and responses.
       This RR contains a domain name syntax data item that names the
       authentication algorithm used.

/Miek

--
Miek Gieben

**Comment by mmonaco** [comment]
Where do you actually see it like that in practice? Neither with `dig`, nor `pdnsutil` is that required. I opened the issue because I was surprised after some debugging that [lego](https://github.com/xenolf/lego/blob/master/providers/dns/rfc2136/rfc2136.go#L33) needed the trailing dot for `RFC2136_TSIG_ALGORITHM`. Also, FWIW, I pulled up on AXFRs in wireshark and on the wire is `hmac-256\0`.

Anyway, not a huge deal, but seemed likely that someone else might bump into the same issue.

**Comment by andrewtj** [comment]
`dig` and `pdnsutil` aren't libraries so what they do isn't all that relevant.

On the wire `hmac-256\0` would have been preceded by 8 as the wire format for names is the length of the label followed by the label, terminating in either a zero-length label or a pointer to another name.

Save for [dns.Fqdn()](https://godoc.org/github.com/miekg/dns#Fqdn) and [dns.IsFqdn()](https://godoc.org/github.com/miekg/dns#IsFqdn) I don't think unqualified names are accepted anywhere in this package.

The issue you bring up seems like something the authors of lego should address to me.

(Apologies for the terseness but I'm in a rush.)

**Comment by mmonaco** [comment]
Fair enough, thanks!
