### ISSUE TITLE
Too many pack/unpack string functions?

### ISSUE THREAD

**Issue by michaelharo** [miekg/dns#365]
I assume there are valid reasons to have all of these unpack combos as functions: 
- unpackTxt
- unpackTxtString
- unpackString
- unpackStringTxt

but I'm having trouble wrapping my head around it.  Could you add doc strings?

**Comment by miekg** [comment]
That's mainly my fault when I merged #360. Ive added unpackStringTxt, that just called unpackTxt.
* unpackStringTxt - unpacks `[]string`
* unpackString - unpacks `string`
these mirror the struct tags in `types.go` - at least that is the plan

unpackTxt and unpackTxtString are nominated to be killed in the ongoing (but almost finished!!) effort to fix #291. I expect half of msg.go to remain, maybe even less.

**Comment by michaelharo** [comment]
I look forward to that cleanup.  Any idea when to expect it to be committed?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Too many pack/unpac..." ]
>I look forward to that cleanup.  Any idea when to expect it to be committed?

Whenever I can make the time :) Anywhere between a couple of days to a week,
don't want to have the code linger in this limbo state too long.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
This cleanup has been done, still think this might be confusing. Please send PRs for further cleanups :-)
