### ISSUE TITLE
Put back Unpack/Pack Struct?

### ISSUE THREAD

**Issue by miekg** [miekg/dns#378]
This breaks backward compat. We can put these functions back in, but not make'm use reflection. Giant type-switch? Maybe just generate them as well into `zmsg.go`?

See https://github.com/miekg/unbound/pull/6

**Comment by miekg** [comment]
@tjeb you're going to take a look? The bottom part of msg_generate.go already prints a list of RR to unpack function (a map). Something similar can be done for PackStruct and UnpackStruct.

Had a bit too much fun yesterday deleting all that code :)

**Comment by miekg** [comment]
Or whatever - will take a look this evening/tomorrow anyway.

**Comment by tjeb** [comment]
Not quite sure how it could be generalized without reflection (at least going through the struct itself); perhaps something like this? Or is that too similar to what it was :) So still reflection, not all of the types just yet, and not sure if the type/val thing can be done more easily

```
func packStructElement(element interface{}, tag reflect.StructTag, msg []byte, off int) (off1 int, err error) {
    if tag == "" {
        switch element.(type) {
            case uint8:
                return packUint8(element.(uint8), msg, off)
            case uint16:
                return packUint16(element.(uint16), msg, off)
            case uint32:
                return packUint32(element.(uint32), msg, off)
            case string:
                // do we have a tag?
                return packString(element.(string), msg, off)
            default:
                return off, &Error{err: "Unknown type in struct: " + reflect.TypeOf(element).String()}
        }
    } else {
        switch tag {
            case `dns:"cdomain-name"`:
                off, _, err = packDomainName(element.(string), msg, off, nil, false)
                return off, err
            default:
                return off, &Error{err: "Unknown tag in struct: " + string(tag)}
        }
    }
}

func PackStruct(any interface{}, msg []byte, off int) (off1 int, err error) {
    typ := reflect.TypeOf(any)
    val := reflect.ValueOf(any)
    // loop through the struct's fields and set the map
    for i := 0; i < typ.NumField(); i++ {
        fval := val.Field(i).Interface()
        ftag := typ.Field(i).Tag
        
        off, err = packStructElement(fval, ftag, msg, off)
        if err != nil {
            return off, err
        }
    }

    return off, nil
}
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Put back Unpack/Pac..." ]
>Not quite sure how it could be generalized without reflection (at least going through the struct itself); perhaps something like this? Or is that too similar to what it was :) So still reflection, not all of the types just yet, and not sure if the type/val thing can be done more easily
>
>```
>func packStructElement(element interface{}, tag reflect.StructTag, msg []byte, off int) (off1 int, err error) {
>    if tag == "" {
>        switch element.(type) {
>            case uint8:
>                return packUint8(element.(uint8), msg, off)
>            case uint16:
>                return packUint16(element.(uint16), msg, off)
>            case uint32:
>                return packUint32(element.(uint32), msg, off)
>            case string:
>                // do we have a tag?
>                return packString(element.(string), msg, off)
>            default:
>                return off, &Error{err: "Unknown type in struct: " + reflect.TypeOf(element).String()}
>        }
>    } else {
>        switch tag {
>            case `dns:"cdomain-name"`:
>                off, _, err = packDomainName(element.(string), msg, off, nil, false)
>                return off, err
>            default:
>                return off, &Error{err: "Unknown tag in struct: " + string(tag)}
>        }
>    }
>}
>
>func PackStruct(any interface{}, msg []byte, off int) (off1 int, err error) {
>    typ := reflect.TypeOf(any)
>    val := reflect.ValueOf(any)
>    // loop through the struct's fields and set the map
>    for i := 0; i < typ.NumField(); i++ {
>        fval := val.Field(i).Interface()
>        ftag := typ.Field(i).Tag
>
>        off, err = packStructElement(fval, ftag, msg, off)
>        if err != nil {
>            return off, err
>        }
>    }
>
>    return off, nil
>}
>```

Prolly can't bring back the original semantics, like packing only an uint16. The 
only way (now) is doing a type switch and calling the appropiate pack/unpack 
method/function. 

Is that a bad idea: bring back a function with somewhat different semantics than 
before or just straight out killing it...

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Put back Unpack/Pac..." ]
>Well, both options are backwards incompatible. Probably better to at least break compile-time then :)

But clearly the pack header stuff should be exported. That could then be used in 
unbound?

/Miek

--
Miek Gieben

**Comment by tjeb** [comment]
just the header would have served the purpose in unbound wrapper, not sure if this is useful/needed anywhere else tbh :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Put back Unpack/Pac..." ]
>just the header would have served the purpose in unbound wrapper, not sure if this is useful/needed anywhere else tbh :)

Ack.

Yeah, let's hold off a bit in hastily (re-)adding newly exported functions.

This might one of those weird corner cases, packing the header by hand is the 
best way to do it.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Nobody complained (yet). Closing for now.
