### ISSUE TITLE
weird skydns test fail

### ISSUE THREAD

**Issue by miekg** [miekg/dns#382]
~~~
2016/06/23 19:33:06 skydns: incomplete CNAME chain from "server1.": name has fewer than 2 labels
--- FAIL: TestDNS (1.58s)
	server_test.go:356: failing: ;; opcode: QUERY, status: NOERROR, id: 49032
		;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
		
		;; QUESTION SECTION:
		;doesnotexist.skydns.test.	IN	 A
		
		;; ADDITIONAL SECTION:
		
		;; OPT PSEUDOSECTION:
		; EDNS: version 0; flags: do; udp: 4096
		: dns: NSEC block too long
2016/06/23 19:33:07 skydns: ready for queries on skydns.test. for tcp://127.0.0.1:9490 [rcache 0]
2016/06/23 19:33:07 skydns: ready for queries on skydns.test. for udp://127.0.0.1:9490 [rcache 0]
2016/06/23 19:33:07 skydns: ready for queries on skydns.test. for tcp://127.0.0.1:9500 [rcache 0]
2016/06/23 19:33:07 skydns: ready for queries on skydns.test. for udp://127.0.0.1:9500 [rcache 0]
2016/06/23 19:33:08 skydns: failure to forward stub request "read udp 127.0.0.1:54259->127.0.0.1:9440: i/o timeout"
2016/06/23 19:33:08 skydns: failure to forward stub request "read udp 127.0.0.1:54259->127.0.0.1:9440: i/o timeout"
FAIL
exit status 1
~~~
NSEC block too long?

**Comment by jlamillan** [comment]
I'm seeing this same thing using the latest skyDNS with etcd 2.3.7. Let me know if you have any insights.

**Comment by jlamillan** [comment]
https://github.com/miekg/dns/blob/dbffa4b0579699b05284017245acae52695dcfa8/msg_helpers.go#L530

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] weird skydns test f..." ]
>I'm seeing this same thing using the latest skyDNS with etcd 2.3.7. Let me know if you have any insights.

No, I only have the failing test in SkyDNS. I need something that fails as a
test in the dns package.

/Miek

--
Miek Gieben

**Comment by jlamillan** [comment]
Same here - just the single failure in TestDNS.

**Comment by miekg** [comment]
Any package capture?

**Comment by jlamillan** [comment]
> Any package capture?

2016/07/06 05:41:40 skydns: incomplete CNAME chain from "server1.": name has fewer than 2 labels
--- FAIL: TestDNS (0.77s)
	server_test.go:356: failing: ;; opcode: QUERY, status: NOERROR, id: 48490
		;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
		
		;; QUESTION SECTION:
		;doesnotexist.skydns.test.	IN	 A
		
		;; ADDITIONAL SECTION:
		
		;; OPT PSEUDOSECTION:
		; EDNS: version 0; flags: do; udp: 4096
		: dns: NSEC block too long
=== RUN   TestDedup

**Comment by miekg** [comment]
Ack. 😃

**Comment by miekg** [comment]
See <https://travis-ci.org/skynetservices/skydns/jobs/146941890> and the test in question is:

The `doesnotexist.skydns.test` do use DNSSEC, but this is NSEC3. This should not be hard to replicate. My first guess is that the NSEC code gets called for NSEC3.

**Comment by miekg** [comment]
See https://github.com/skynetservices/skydns/commit/5f2ccd23dd0a1182866eeaa74da7dd2ab8860efa, this is actually a SkyDNS issue, *but* Go DNS did change semantics. 

I have another PR for Go DNS that also fixes some NSEC/NSEC3 stuff.
