### ISSUE TITLE
Conn.Write performs unnecessary type assertion

### ISSUE THREAD

**Issue by SlyMarbo** [miekg/dns#387]
In `Conn.Write` there is special behaviour for a TCP or TLS connection, which is fine, but the subsequent code makes a type assertion to `*net.UDPConn` at `client.go:403`, where it only calls the `Write` method.

Since this is only using functionality from `net.Conn` and not specifically `*net.UDPConn`, the type assertion is unnecessary and breaks my code where I wrap the *net.UDPConn` in a type that enforces timeouts.

**Comment by miekg** [comment]
Yep, you're write, this used to do a WriteTo on a UDP socket (IIRC), but that can now be removed.

**Comment by miekg** [comment]
Has been fixed.
