### ISSUE TITLE
'bad rdlength' error for UDP queries

### ISSUE THREAD

**Issue by sanimej** [miekg/dns#391]
Docker embedded DNS server uses miekg/dns lib.

For queries over UDP that generate a reply > 512 bytes I am seeing 'bad rdlength' error. 

I am using dig version 9.9.5 which sets EDNS0 to 4096 bytes by default. If I set +bufsize=512 then the truncated bit gets set correctly and the retry over TCP works. dig +tcp works fine as well.

This seems to happen for any query that generates a > 512 bytes response. Output with 8.8.8.8 as resolver.

````
root@5008de90ff54:/# dig  docker.com any

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> docker.com any
;; global options: +cmd
;; connection timed out; no servers could be reached

root@5008de90ff54:/# dig +tcp docker.com any

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> +tcp docker.com any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24967
;; flags: qr rd ra; QUERY: 1, ANSWER: 15, AUTHORITY: 0, ADDITIONAL: 14

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;docker.com.			IN	ANY

;; ANSWER SECTION:
docker.com.		3600	IN	TXT	"google-site-verification=Nyiwo5q4kkaD5V-sEiXsW74HXyVRtKVyxYFfZuFLG7M"
docker.com.		3600	IN	TXT	"v=spf1 include:_spf.google.com include:mail.zendesk.com  include:_spf.salesforce.com include:servers.mcsv.net ~all"
docker.com.		172800	IN	NS	ns-568.awsdns-07.net.
docker.com.		172800	IN	NS	ns-1289.awsdns-33.org.
docker.com.		172800	IN	NS	ns-1981.awsdns-55.co.uk.
docker.com.		172800	IN	NS	ns-207.awsdns-25.com.
docker.com.		900	IN	SOA	ns-207.awsdns-25.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
docker.com.		60	IN	A	54.86.192.155
docker.com.		60	IN	A	52.72.199.43
docker.com.		60	IN	A	54.165.204.109
docker.com.		3600	IN	MX	5 alt2.aspmx.l.google.com.
docker.com.		3600	IN	MX	1 aspmx.l.google.com.
docker.com.		3600	IN	MX	10 alt3.aspmx.l.google.com.
docker.com.		3600	IN	MX	10 alt4.aspmx.l.google.com.
docker.com.		3600	IN	MX	5 alt1.aspmx.l.google.com.

;; ADDITIONAL SECTION:
ns-1289.awsdns-33.org.	109379	IN	A	205.251.197.9
ns-1981.awsdns-55.co.uk. 109337	IN	A	205.251.199.189
ns-207.awsdns-25.com.	172004	IN	A	205.251.192.207
ns-568.awsdns-07.net.	171015	IN	A	205.251.194.56
aspmx.l.google.com.	53	IN	A	74.125.28.26
aspmx.l.google.com.	189	IN	AAAA	2607:f8b0:400e:c03::1b
alt3.aspmx.l.google.com. 260	IN	A	74.125.192.27
alt4.aspmx.l.google.com. 105	IN	A	74.125.141.26
alt4.aspmx.l.google.com. 105	IN	AAAA	2607:f8b0:400c:c06::1a
alt1.aspmx.l.google.com. 155	IN	A	74.125.132.26
alt1.aspmx.l.google.com. 170	IN	AAAA	2607:f8b0:4001:c00::1a
alt2.aspmx.l.google.com. 42	IN	A	173.194.219.27
alt2.aspmx.l.google.com. 42	IN	AAAA	2607:f8b0:4002:c03::1a

;; Query time: 56 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Sun Jul 24 09:12:52 UTC 2016
;; MSG SIZE  rcvd: 1396
````
Same behavior for other queries, for ex: `dig +dnssec . any`, `dig redhat.com any`

**Comment by andrewtj** [comment]
This library supports large UDP messages. From what you've said it's not clear how "Docker embedded DNS server" is using this library or where the problem may be. If you've reviewed its use of this library and believe there's a problem in this library please specify what that problem is and demonstrate it with a small test case. If you're not sure if this library is being used correctly please provide a pointer to the code in question or an equivalent sample and someone might take a look at it.

**Comment by xytis** [comment]
Code in question: https://github.com/docker/docker/blob/3056e4884e470a43eb71584569d920d4abfde4d0/vendor/src/github.com/docker/libnetwork/resolver.go#L297

I skimmed over, yet I could not see any obvious mistake.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] 'bad rdlength' erro..." ]
>Code in question: https://github.com/docker/docker/blob/3056e4884e470a43eb71584569d920d4abfde4d0/vendor/src/github.com/docker/libnetwork/resolver.go#L297
>
>I skimmed over, yet I could not see any obvious mistake.

The only thing I can think off, is the goo' old use of msg.Compress (in a proxy
setup). The message coming in is compressed, but when replying back the client
the compression isn't applied?

/Miek

--
Miek Gieben

**Comment by andrewtj** [comment]
I don't think the `dns.Conn`'s `UDPSize` is ever set. If it's not then `dns.MinMsgSize` is used as the default buffer size. It's created [here](https://github.com/docker/docker/blob/3056e4884e470a43eb71584569d920d4abfde4d0/vendor/src/github.com/docker/libnetwork/resolver.go#L364).

**Comment by miekg** [comment]
oooh, yes. They should get that info from the incoming packet.

**Comment by sanimej** [comment]
@andrewtj @miekg Thanks for the hint. I will try setting Conn.MinMsgSize.

**Comment by miekg** [comment]
You'll probably need to do better than that. Enough dns replies today are
larger than 512 bytes and you may not want to fall back to tcp for everyone
of them. This means implementing EDNS0 in your code.
