### ISSUE TITLE
Batch multiple DNS queries into a single call

### ISSUE THREAD

**Issue by nguyenxuantuong** [miekg/dns#396]
Hi,

I am wondering if it's possible to query A record for multiple domains in one shot. I have tried something like the following but it doesn't seem to work.

```
c := dns.Client{}
m := dns.Msg{}
//instead of
//m.SetQuestion(target+".", dns.TypeA)
m.Id = dns.Id()
m.RecursionDesired = true
m.Question = make([]dns.Question, 2)
m.Question[0] = dns.Question{"example.com.", dns.TypeA, dns.ClassINET}
m.Question[1] = dns.Question{"google.com.", dns.TypeA, dns.ClassINET}
r, t, err := c.Exchange(&m, server+":53")
```

The error I got is "failed to unpack truncated message"

Thanks.

**Comment by rafaeljusto** [comment]
The problem is in the DNS server. Multiple questions aren't really supported as defined in RFC 1035. 

Alan Clegg [wrote](https://groups.google.com/forum/#!topic/comp.protocols.dns.bind/uOWxNkm7AVg):
> Multiple queries in a question section have not been supported in DNS
> due the applicability of some DNS Message Header flags (such as AA) and
> of the RCODE field only to a single QNAME, QTYPE, and QCLASS.
