### ISSUE TITLE
Why does tcpMsgLen not use tcpRead()?

### ISSUE THREAD

**Issue by spsholleman** [miekg/dns#398]
tcpMsgLen() is below:

```
// tcpMsgLen is a helper func to read first two bytes of stream as uint16 packet length.
func tcpMsgLen(t io.Reader) (int, error) {
    p := []byte{0, 0}
    n, err := t.Read(p)
    if err != nil {
        return 0, err
    }
    if n != 2 {
        return 0, ErrShortRead
    }
    l, _ := unpackUint16(p, 0)
    if l == 0 {
        return 0, ErrShortRead
    }
    return int(l), nil
}
```

I was seeing a bunch of errors returned from this with ErrShortRead.  I believe that we are trying to read the TCP data before it's actually present and therefore err != nil but n < 2.

I changed this function to call tcpRead(t, p) instead of t.Read(p) and things work fine.  Is there anything I'm missing and any reason to not be doing this?

**Comment by miekg** [comment]
Hit this as well, and made another fix that reads (or tries to read all bytes from the network), see 4e95323

Didn't see that this bug was open.
