### ISSUE TITLE
SetEdns0() can result in invalid DNS messages

### ISSUE THREAD

**Issue by shane-kerr** [miekg/dns#409]
I had some code that was calling `SetEdns0()` to set the EDNS buffer size, but the message already had an OPT record. The `SetEdns0()` call happily created a new OPT record and added this. Some name servers considered this an invalid message and returned `FORMERR`.

I have written the following function to work around this in my code:

```go
// If the DNS message already has an OPT record, change the values for UDP buffer size & the DO bit.
// If the DNS message does not already have an OPT record, add one.
func SetOrChangeEdns0(msg *dns.Msg, udpsize uint16, do bool) *dns.Msg {
    for _, rr := range msg.Extra {
        if rr.Header().Rrtype == dns.TypeOPT {
            e := rr.(*dns.OPT)
            e.SetUDPSize(udpsize)
            e.SetDo(do)
            return msg
        }
    }
    msg.SetEdns0(udpsize, do)
    return msg
}
```
It's sort of like an [upsert](https://en.wikipedia.org/wiki/Merge_(SQL)).

It might be nice if the `SetEdns0()` function worked this way. Technically it's an API change, but I think this behavior is closer to what a user would expect. An alternate approach would be to add the `SetOrChangeEdns0()` itself to the library.

If it makes sense, I'm happy to submit a pull request!

**Comment by miekg** [comment]
See `IsEdns0` that returns an opt record (if its there).
```
o := msg.IsEdns0()
if o == nil {
      makeNewOPT()
      return
}
o.SetUDPSize(4096)
o.SetDo()
```

Not perfect but short enough that we probably don't have to add something.

Note we might revisit and populate some handy functions in `dnsutil/` sub pacakge.

**Comment by miekg** [comment]
Also, generating invalid messages is not something this package discourages. If you want, you can.

**Comment by shane-kerr** [comment]
Okay, `IsEdns0()` can make this method a little bit shorter:

```go
func SetOrChangeEdns0(msg *dns.Msg, udpsize uint16, do bool) *dns.Msg {
    e := msg.IsEdns0()
    if e == nil {
        msg.SetEdns0(udpsize, do)
    } else {
        e.SetUDPSize(udpsize)
        e.SetDo(do)
    }
    return msg
}
```

I still think that `SetEdns0()` is dangerous, because it is easy to make an invalid DNS message, but since the package explicitly has no safety net, I guess it's fine. :smile:
