### ISSUE TITLE
How to lookup NS's specified for a domain at the domain registrar?

### ISSUE THREAD

**Issue by tssajo** [miekg/dns#416]
@miekg Is it possible to get the NS records which are specified for a domain at its domain registrar?
For example, if you visit https://intodns.com/github.com the very first section shows the NS's for the domain as "Parent" -> "Domain NS records" -> "Nameserver records returned by the parent servers are:" and the NS's are listed there, followed by e.g.: "a.gtld-servers.net was kind enough to give us that information."

How to lookup these parent NS records for a domain with your Go DNS package?

Thanks in advance for the answer!

**Comment by andrewtj** [comment]
NS records are specified via registrars but aren't actually at a registrar per se. Put another way, registrars are just an interface to getting NS records placed in a zone somewhere. To find the referring NS records you can recursively query for the name starting somewhere higher in the tree (like one of the root servers) following referrals until you reach the authoritative servers.

**Comment by tssajo** [comment]
@andrewtj Thanks for your answer. Here is my problem: I have a list of 200+ domain names in a text file, I need to find which domains' NS records are set at their domain name registrar to a specific name server which is now physically down. The authoritative name servers of those domains are not available, and the recursive lookup will fail, so I'm not sure that I can use a recursive lookup in this case. Also, a recursive lookup failure in itself does not necessary mean that the domain is set to use that specific NS I am looking for...

I need to write a Go program which goes through all domains and determines which ones are set to use the now defunct name server, so we can notify the owners of such domains to update the NS's at their domain registrar. Worst of all, not all domains are .com, some of them are country specific, etc. This makes the task a bit more difficult, because we cannot always start by asking a .com root name server.

Any advise?

**Comment by andrewtj** [comment]
@tssajo I suggested you implement a recursive lookup, not just send a query with RD set ;) [This should get you started.](https://gist.github.com/andrewtj/056ed6225898d652288f0d416eb3cc3f)

**Comment by tssajo** [comment]
@andrewtj Thanks a lot! Your example code is very helpful.

I'm closing this ticket now.

**Comment by miekg** [comment]
As Andrew says, just start at the root and do the recursion yourself.
