### ISSUE TITLE
Too-long character-strings are parsed rather than rejected

### ISSUE THREAD

**Issue by gibson042** [miekg/dns#422]
(related: #420)

I noticed this in #421, but did not immediately fix it there because the [behavior](https://github.com/miekg/dns/blob/46df8c9462fa287d54225d6bdebbcfd41da434f7/scan_rr.go#L89) seems to be [intentional](https://github.com/miekg/dns/blob/46df8c9462fa287d54225d6bdebbcfd41da434f7/parse_test.go#L240) (if misguided). When the length of a character-string exceeds 255 octets, the parser breaks it into _multiple_ strings, all but the last of length 255. But this can mask user errors, and in my opinion such cases should instead result in  `ParseError`s.

**Comment by miekg** [comment]
That's feature. AFAIK powerdns' parser does something similar.

**Comment by gibson042** [comment]
It violates RFC 1035, and forces me to manually process input instead of relying on this library. Would you be willing to change it and/or point me to the powerdns documentation?

**Comment by miekg** [comment]
Why do you need to manually parse stuff?

**Comment by gibson042** [comment]
Because I am ultimately sending the data to a nameserver. When a user submits a \<character-string> that would require 300 octets on the wire, I need to reject it up front because if I don't then BIND/Knot/NSD/etc. will refuse to load the entire zone. And while I can suggest a split after 255, I cannot _assume_ that automatically introducing one is acceptable. But that's precisely what this library currently does, therefore I cannot rely on it for input validation (which I would prefer to do) while parsing silently alters data in ways that are visible on the wire.

**Comment by miekg** [comment]
I still don't understand. Why would BIND etc reject such a message?

Even so, you should be able to count the text elements after the parse and reject if it's larger than 1? This does not have to happing during the parse?

**Comment by andrewtj** [comment]
> On 2 Dec. 2016, at 3:56 pm, Richard Gibson <notifications@github.com> wrote:
> 
> therefore I cannot rely on it for input validation (which I would prefer to do)

Depending on the details that might not work out so well as this library doesn't enforce length limits on domain names

**Comment by gibson042** [comment]
> I still don't understand. Why would BIND etc reject such a message?

Because it's invalid. The presentation-format data in my zone file specifies a record that cannot be expressed in wire format, so the nameservers refuse to load it.

> Even so, you should be able to count the text elements after the parse and reject if it's larger than 1? This does not have to happing during the parse?

That won't work, because you're actually _transforming_ the input. For readability, let's assume the limit is 6 characters instead of 255 and consider the following records:
```
example.com. 3600 IN TXT rdata abcdef ghijkl	; 3 valid character-strings
example.com. 3600 IN TXT rdata abcdefghijkl	; 1 valid character-string + 1 invalid
```
This parser currently produces identical data structures for both records, forcing me to duplicate its efforts.

> Depending on the details that might not work out so well as this library doesn't enforce length limits on domain names

That should be fixed as well, but I can at least check the length myself because input distinctiveness is preserved.

**Comment by miekg** [comment]
Think you are mistaken, multiple text elements are perfectly fine as long
as the total length does not exceed 64k

**Comment by miekg** [comment]
The 256 length on domain names is complete arbitrary.  If you want to put
longer names on the wire this library allows for it.

**Comment by gibson042** [comment]
> Think you are mistaken, multiple text elements are perfectly fine as long
as the total length does not exceed 64k

I'm not claiming otherwise. It's not that this library produces invalid TXT RDATA, it's that produces valid TXT RDATA from _invalid_ input.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Too-long character-..." ]
>> Think you are mistaken, multiple text elements are perfectly fine as long
>as the total length does not exceed 64k
>
>I'm not claiming otherwise. It's not that this library produces invalid TXT RDATA, it's that produces valid TXT RDATA from _invalid_ input.

ah. And, invalid = doing to automatic split?

/Miek

--
Miek Gieben

**Comment by gibson042** [comment]
"Invalid" as in "a sequence of characters, in the position of a \<character-string>, that would require more than 255 octets on the wire". Attempts to parse strings including such sequences should probably yield `ParseError`s (just like attempts to parse strings with unbalanced quotes) but should **not** introduce _new_ \<character-strings>.

If you wanted to continue returning RRs in such cases, though, that would seem like an acceptable way to remain general-purpose, e.g. (maintaining my 6-character limit from above)
```go
rr, err := dns.NewRR("example.com. 3600 IN TXT rdata abcdefghijkl")
if err == nil {
	t.Errorf("expected error from too-long character-string")
}
if rr == nil {
	t.Errorf("expected non-nil record with too-long character-string")
}
if len(rr.Txt) != 2 {
	t.Errorf("expected 2 character-strings; got %d: %v", len(rr.Txt), rr.Txt)
}
if rr.Txt[0] != "rdata" {
	t.Errorf("expected first character-string %s; got %s", "rdata", rr.Txt[0])
}
if rr.Txt[1] != "abcdefghijkl" {
	t.Errorf("expected second character-string %s; got %s", "abcdefghijkl", rr.Txt[1])
}
```

**Comment by miekg** [comment]
oh, it's a *presentation* issue. We allow longer strings, but bind doesn't so you can't exchange (text) data?
That's probably worth fixing even.

**Comment by miekg** [comment]
But as @andrewtj some will be true for domain name, as we don't enforce the limit there

**Comment by gibson042** [comment]
Then let's recognize this as two issues.
1. We MUST stop splitting \<character-string>s, because doing so alters user input.
2. We SHOULD provide a signal when we know a \<character-string> is invalid for excessive length (e.g., in TXT RDATA). I believe that such a signal should take the form of a `ParseError`, but am agnostic on the question of whether it should be accompanied by a nil or non-nil RR.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Too-long character-..." ]
>Then let's recognize this as two issues.
>1. We MUST stop splitting \<character-string>s, because doing so alters user input.

Yep.

>2. We SHOULD provide a signal when we know a \<character-string> is invalid for excessive length (e.g., in TXT RDATA). I believe that such a signal should take the form of a `ParseError`, but am agnostic on the question of whether it should be accompanied by a nil or non-nil RR.

sgtm.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I think this is actually fixed now. @tmthrgd

**Comment by tmthrgd** [comment]
@miekg I don’t think so. I touched unpacking domain names, but I think this is unrelated and about parsing TXT records which are a different set of functions.

**Comment by miekg** [comment]
https://github.com/miekg/dns/pull/1245
