### ISSUE TITLE
Names are being compressed in non-compressible RRDatas

### ISSUE THREAD

**Issue by andrewtj** [miekg/dns#425]
In [`msg_generate.go`](https://github.com/miekg/dns/blob/21314e18383acb467f46185ec965fa0815335d13/msg_generate.go#L119-L122) `PackDomainName` is passed the compress flag for both
`dns:"cdomain-name"` and `dns:"domain-name"`.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Names are being compres..." ]
>In [`msg_generate.go`](https://github.com/miekg/dns/blob/21314e18383acb467f46185ec965fa0815335d13/msg_generate.go#L119-L122) `PackDomainName` is passed the compress flag for both
>`dns:"cdomain-name"` and `dns:"domain-name"`.

But, but, `compress` should be false for the latter. But I haven't double check
this (now).

**Comment by fnevesbr** [comment]
Hit this same issue when auto generating compressed messages with NSEC records. Supposing tag declarations for all types are correct the following small diff passing false in the case of noncompressible names should fix it.

https://github.com/fnevesbr/dns/commit/bf450b5c633807a3bc2b7176479b67fdb3f3148d

**Comment by miekg** [comment]
Thanks!
