### ISSUE TITLE
NSEC3 HashLength is set incorrectly

### ISSUE THREAD

**Issue by andrewtj** [miekg/dns#426]
Looks like padding is required to parse an NSEC3 record and padding is generated when unpacking.  From [RFC 5155](https://tools.ietf.org/html/rfc5155#section-1.3):
```
   Base32:  the "Base 32 Encoding with Extended Hex Alphabet" as
      specified in [RFC4648].  Note that trailing padding characters
      ("=") are not used in the NSEC3 specification.
```

Additionally when parsing `NSEC3`'s `HashLength` is set incorrectly which results in them packing okay but failing to unpack.

Test case:

```go
package main

import (
	"log"

	"github.com/miekg/dns"
)

func main() {
	rr, err := dns.NewRR(". 0 IN NSEC3 0 0 0 0 C0 TYPE0")
	if err != nil {
		log.Fatalf("new rr failed: %s (unexpected)", err)
	}
	m := new(dns.Msg)
	m.Answer = []dns.RR{rr}
	_, err = m.Pack()

	log.Printf("bug 1: parsing NextDomain requires padding")
	if err == nil {
		log.Fatal("expected pack to fail")
	} else {
		log.Printf("pack failed: %s (expected)", err)
	}
	rr, err = dns.NewRR(". 0 IN NSEC3 0 0 0 0 CO====== TYPE0")
	if err != nil {
		panic(err)
	}
	m.Answer = []dns.RR{rr}
	buf, err := m.Pack()
	if err != nil {
		log.Fatalf("pack failed: %s (unexpected)", err)
	}

	log.Printf("bug 2: HashLength isn't set correctly (set to: %d)",
		rr.(*dns.NSEC3).HashLength)
	err = m.Unpack(buf)
	if err == nil {
		log.Fatalf("expected unpack to fail")
	} else {
		log.Printf("unpack failed: %s (expected)", err)
	}

	rr.(*dns.NSEC3).HashLength = 1
	m.Answer = []dns.RR{rr}
	buf, err = m.Pack()
	if err != nil {
		log.Fatalf("pack failed: %s (unexpected)", err)
	}
	err = m.Unpack(buf)
	if err != nil {
		log.Fatalf("unpack failed: %s (unexpected)", err)
	}
	nd := m.Answer[0].(*dns.NSEC3).NextDomain
	switch nd {
	case "CO======":
		log.Printf("bug3: next domain is padded on unpack")
	case "CO":
		log.Fatalf("next domain is unpadded (unexpectedly)")
	default:
		log.Fatalf("didn't expect next domain to be: %s", nd)
	}
}
```

```
go run nsec3_bug.go 
2016/12/08 04:53:39 bug 1: parsing NextDomain requires padding
2016/12/08 04:53:39 pack failed: illegal base32 data at input byte 0 (expected)
2016/12/08 04:53:39 bug 2: HashLength isn't set correctly (set to: 20)
2016/12/08 04:53:39 unpack failed: dns: overflow unpacking base32 (expected)
2016/12/08 04:53:39 bug3: next domain is padded on unpack
```

**Comment by miekg** [comment]
brrr.. :-(

I never actually seen an NSEC3 like that in the wild. When do you pad with base32?

**Comment by andrewtj** [comment]
Base32 uses a 40-bit window so it shouldn't come up in the wild

**Comment by miekg** [comment]
Do you have a PR in mind?

**Comment by andrewtj** [comment]
Nah I'd forgotten about this. In trying to jog my memory, I just tried copying and pasting an example from RFC 5155:

`. NSEC3 1 1 12 aabbccdd 2vptu5timamqttgl4luu9kg21e0aor3s A RRSIG`

It failed first with `illegal base32 data at input byte 1` as the base32-hex was lower case and then wouldn't unpack with `dns: overflow unpacking nsecx`. I haven't dug any further.

**Comment by andrewtj** [comment]
Looks like `dns: overflow unpacking nsecx` is caused by [the salt not being packed](https://github.com/miekg/dns/blob/75229eecb7af00b2736e93b779a78429dcb19472/zmsg.go#L804-L805).

**Comment by andrewtj** [comment]
I've started on this with andrewtj@4246b6e

**Comment by andrewtj** [comment]
Go 1.9 adds [support for Base32 without padding](https://tip.golang.org/pkg/encoding/base32/#Encoding.WithPadding). Should we switch to that when 1.10 drops?

Also what do you think of dropping the byte-length fields?

**Comment by miekg** [comment]
Ack, makes sense.

Dropping the byte-length is also OK - I think I only added them to make the pack/unpack function slightly easier - they are mostly a nuisance to end-users I think.

**Comment by andrewtj** [comment]
I'm going to try and get to these around the end of this month when Go 1.10 is due to drop. If anyone else wants to have a go instead please chime in.

For backward compatibility I'm thinking I'll keep the length fields around even though they'll go unused. Does that seem reasonable?

HIP seems to be the only RR where the length doesn't immediately precede the field. If it makes the generator simpler (haven't looked), any qualms about implementing HIP manually?

**Comment by miekg** [comment]
Go ahead.

Re: HIP; if things get simpler then +1

**Comment by andrewtj** [comment]
I finally had a go at dropping the length fields in a138983. Tests pass but I don't think it's baked yet.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] NSEC3 bugs: NextDom..." ]
>I'm not going to finish this. If the approach in a138983 seems sane and someone wants to pick it up, go for it.

I might pick this up (some day :) )
