### ISSUE TITLE
Support RFC 2308 Type 3 NODATA Response

### ISSUE THREAD

**Issue by MikeSchroll** [miekg/dns#428]
After many many attempts; I was unable to successfully provide an [RFC 2308](https://tools.ietf.org/html/rfc2308) compliant Type 3 NODATA response.

I ended up doing a Type 2.

The problem seems to be in providing 'no answer'.
Has anyone succeeded in creating valid A and AAAA RR responses but that are lacking an answer?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Support RFC 2308 Type 3..." ]
>After many many attempts; I was unable to successfully provide an [RFC 2308](https://tools.ietf.org/html/rfc2308) compliant Type 3 NODATA response.
>
>I ended up doing a Type 2.
>
>The problem seems to be in providing 'no answer'.
>Has anyone succeeded in creating valid A and AAAA RR responses but that are lacking an answer?

What have you done? Where is your code? etc. etc.

**Comment by xinbenlv** [comment]
In 2024, I am filing #1615 to backup this request from 2017 :p
