### ISSUE TITLE
Support generic RRs

### ISSUE THREAD

**Issue by Arachnid** [miekg/dns#429]
I'm writing a DNS server that gets its data from a database that stores (type, class, ttl, data) tuples; data is the uninterpreted RDATA for the DNS response.

There doesn't seem to be any good way to construct an RR from this; all the methods assume either text format or a known-at-compile-time RR type. RFC3597 provides an option for a kludge, but it isn't great.

It'd be really handy if the library either:

 - Provided an `UnpackRData(header, data)` method
 - Provided a GenericRR that contains a `data []byte`
 - Exported all the methods implemented by `dns.RR` so one can write their own RRs.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Support generic RRs (#4..." ]
>I'm writing a DNS server that gets its data from a database that stores (type, class, ttl, data) tuples; data is the uninterpreted RDATA for the DNS response.

No domain name is stored here?

>There doesn't seem to be any good way to construct an RR from this; all the methods assume either text format or a known-at-compile-time RR type. RFC3597 provides an option for a kludge, but it isn't great.
>
>It'd be really handy if the library either:
>
> - Provided an `UnpackRData(header, data)` method
> - Provided a GenericRR that contains a `data []byte`
> - Exported all the methods implemented by `dns.RR` so one can write their own RRs.

You can actually do private RRs https://miek.nl/2014/September/21/idn-and-private-rr-in-go-dns/
But that might even be farther from what you need.

If you store the data in wireformat and you also create the wireformat for the
header you can just use UnpackRR to get the native go dns RR.

/Miek

--
Miek Gieben

**Comment by Arachnid** [comment]
> No domain name is stored here?

Not in plaintext; I plan to use the name from the query to provide this field.

> You can actually do private RRs https://miek.nl/2014/September/21/idn-and-private-rr-in-go-dns/
But that might even be farther from what you need.

I don't think that's what we need - we need to be able to create arbitrary existing public DNS RRs from data that's provided at runtime.

> If you store the data in wireformat and you also create the wireformat for the
header you can just use UnpackRR to get the native go dns RR.

Since name isn't stored explicitly at all, and TTL is stored in a separate record, we can't do this, unfortunately.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Support generic RRs..." ]
>> If you store the data in wireformat and you also create the wireformat for the
>header you can just use UnpackRR to get the native go dns RR.
>
>Since name isn't stored explicitly at all, and TTL is stored in a separate record, we can't do this, unfortunately.

Well, you *can* do it, use `.` and 0 as ttl, but it kludgy...

On don't want to massively increase the API for just this case. But maybe there
is something small and nice that would make this possible.

/Miek

--
Miek Gieben

**Comment by Arachnid** [comment]
> Well, you *can* do it, use `.` and 0 as ttl, but it kludgy...

Right, and encoding the wire format just so I can decode it, modify it, and encode it again seems like a bad idea, especially since it'd require me to write my own DNS encoding code!

> On don't want to massively increase the API for just this case. But maybe there
is something small and nice that would make this possible.

I think the simplest option would be to split [UnpackRR](https://github.com/miekg/dns/blob/master/msg.go#L552) into two parts, with the latter being a public `UnpackRdata` function that takes an `RR_Header` and a byte slice and returns a fully unpacked RR.

If you agree, I'd be happy to submit a PR.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Support generic RRs..." ]
>> Well, you *can* do it, use `.` and 0 as ttl, but it kludgy...
>
>Right, and encoding the wire format just so I can decode it, modify it, and encode it again seems like a bad idea, especially since it'd require me to write my own DNS encoding code!

Well, for those few values its pretty easy to do. Also you're going that route
anyway because the internal format for Go DNs is native Go types anyway. I.e.
there is not benefit of storing it in binary in the database, might as well be 
text.

>I think the simplest option would be to split [UnpackRR](https://github.com/miekg/dns/blob/master/msg.go#L552) into two parts, with the latter being a public `UnpackRdata` function that takes an `RR_Header` and a byte slice and returns a fully unpacked RR.
>
>If you agree, I'd be happy to submit a PR.

Yes, that looks small enough. Also need to have something for the Pack side
though.

Also for some reason I don't like the name UnpackRdata - but can't think of a
better name atm.


/Miek

--
Miek Gieben

**Comment by Arachnid** [comment]
> Also you're going that route
anyway because the internal format for Go DNs is native Go types anyway. I.e.
there is not benefit of storing it in binary in the database, might as well be
text.

Well, in this case the database is a blockchain, so storage is at a premium. Storing in binary is definitely the more efficient solution.

> Yes, that looks small enough. Also need to have something for the Pack side
though.

Is that necessary? When packing, you always have a concrete type.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Support generic RRs..." ]
> Yes, that looks small enough. Also need to have something for the Pack side
>though.
>
>Is that necessary? When packing, you always have a concrete type.

Currently the API is pretty symmetric between packs and unpacks.
I like to keep it that way.


/Miek

--
Miek Gieben
