### ISSUE TITLE
Support RFC-6762 / mDNS fields

### ISSUE THREAD

**Issue by sayotte** [miekg/dns#436]
I don't see it in the API or in the README: does this library directly support encoding/decoding records with RFC-6762 fields (see: https://tools.ietf.org/html/rfc6762#section-19)?

Namely:
* The Cache-Flush bitfield (first bit in Class field of RR header)
* The Unicast-Response-Acceptable bitfield (first bit of Class field in Query header)

And also:
* The [RFC-6763 (DNS-SD) section 6.3](https://tools.ietf.org/html/rfc6763#section-6.3) TXT record format

I created [an mDNS library](https://github.com/sayotte/rawmdns) mostly for fun over the holidays, but now that it's done I worry someone might find it and try to **use** it. The world would be better off if a widely-adopted, community supported library such as this one had the functionality instead.

**Comment by miekg** [comment]
See this thread: https://github.com/miekg/dns/issues/423

No, there aren't any functions directly dealing with these fields and yes, make sense to add them.

**Comment by shotahino** [comment]
@miekg Is this still open and on your list?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Support RFC-6762 / ..." ]
>@miekg Is this still open and on your list?

Support for this is still welcome, noone is working on it though.
