### ISSUE TITLE
method for getting RDATA from RR?

### ISSUE THREAD

**Issue by weineran** [miekg/dns#437]
Maybe this already exists in some form and I'm just missing it, but it would be very handy to have a method for getting the RDATA octets from an RR.

**Comment by gibson042** [comment]
I've wanted something more convenient, but you can do this now by [`Pack()`](https://godoc.org/github.com/miekg/dns#Msg.Pack)ing a single-RR message.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] method for getting RDAT..." ]
>Maybe this already exists in some form and I'm just missing it, but it would be very handy to have a method for getting the RDATA octets from an RR.

No we having of the sorts. Big problem here is what to give the caller. A
[]interface{}, or return the difference parts a new (per RR) struct?

**Comment by weineran** [comment]
I was thinking it would return a `[]byte`.

Just be clear though, I'm only referring to the RDATA field of the RR, not the entire RR.  For example, if I had a `CNAME` struct, I'd like to be able to do something like this:
`cNameBytes := myCname.GetRdata()`
In this case, `cNameBytes` would then contain the (compressed) canonical name.

Likewise, if I called `GetRdata()` on an `HINFO` struct, the result would contain the CPU and OS character-strings.

In either case, it would then be up to the caller to decompress/parse the `[]byte` if needed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] method for getting ..." ]
>I was thinking it would return a `[]byte`.
>
>Just be clear though, I'm only referring to the RDATA field of the RR, not the entire RR.  For example, if I had a `CNAME` struct, I'd like to be able to do something like this:
>`cNameBytes := myCname.GetRdata()`
>In this case, `cNameBytes` would then contain the (compressed) canonical name.
>
>Likewise, if I called `GetRdata()` on an `HINFO` struct, the result would contain the CPU and OS character-strings.
>
>In either case, it would then be up to the caller to decompress/parse the `[]byte` if needed.

Yes, but we don't have the `[]byte`, so that needs a pack and then returning the
bytes at the right offset. It would be more in line with the rest of library to
return some kind of struct that just has the fields - problem is that it then
needs to be a `[]interface{}` (IMO)

**Comment by weineran** [comment]
I see what you mean.  I will fiddle around and see if I can come up with a good solution.  Will keep you posted.

**Comment by miekg** [comment]
In ldns we abstracted the rdata and named it 'rdata fields', rdf's for short. And that reminds me, we do a have `Fields` function? Does that work for you use case?

**Comment by weineran** [comment]
Actually yes, that was perfect.  For future readers, I am using Field to get the canonical name as a string like this:
`canonicalName := dns.Field(cNameRecord, 1)`

Thanks!  Shall I close this issue?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] method for getting ..." ]
>Actually yes, that was perfect.  For future readers, I am using Field to get the canonical name as a string like this:
>`canonicalName := dns.Field(cNameRecord, 1)`
>
>Thanks!  Shall I close this issue?

Please do :)
