### ISSUE TITLE
Modify zone in RFC 1035

### ISSUE THREAD

**Issue by vtolstov** [miekg/dns#445]
I want to try store zones in kv storage key - domain, val - full zone.

But if i need update zone for example add / delete record do it possible to do that using this package?
Or how can i do that?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Modify zone in RFC 1035..." ]
>I want to try store zones in kv storage key - domain, val - full zone.
>
>But if i need update zone for example add / delete record do it possible to do that using this package?
>Or how can i do that?

Uhm? How is this question related to go dns? Other than that you're storing DNS
data.

**Comment by vtolstov** [comment]
Ok, i have zonefile , and i parse it via this package, does it possible to add RR record to exiting parsed zone or modify ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Modify zone in RFC ..." ]
>Ok, i have zonefile , and i parse it via this package, does it possible to add RR record to exiting parsed zone or modify ?

This package has no concept of a zone, there only is a []dns.RR so you'll have
to implement that yourself.

**Comment by vtolstov** [comment]
Thanks! If i have []dns.RR does this package support serializing it to buffer in RFC 1035 style ?

**Comment by miekg** [comment]
Yes, this package supports the wireformat
