### ISSUE TITLE
Is Server.Shutdown() working as expected ?

### ISSUE THREAD

**Issue by pierrre** [miekg/dns#457]
Hello,

According to the documentation https://godoc.org/github.com/miekg/dns#Server.Shutdown
```
Shutdown gracefully shuts down a server. After a call to Shutdown, ListenAndServe and ActivateAndServe will return. All in progress queries are completed before the server is taken down. If the Shutdown is taking longer than the reading timeout an error is returned.
```

I've 2 issues:

-------------------

The graceful shutdown doesn't work for me.
If I call `Shutdown()`, `Server.ListenAndServe()` returns before all queries are completed.
Basic code inside my `Handler`:
```
fmt.Println("a")
time.Sleep(5 * time.Second)
fmt.Println("b")
```
If `.Shutdown()` is called during `time.Sleep()`, `b` is not displayed before `Server.ListenAndServe()` returns.

-------------------

Other issue: when I call `Server.Shutdown()`, `Server.ListenAndServe()` randomly returns an error:
```
accept tcp [::]:1053: use of closed network connection
```
Basic code:
```
s := &dns.Server{
// ....
}
go func() {
    time.Sleep(5 * time.Second)
    _ = s.Shutdown()
}()
err := s.ListenAndServe()
if err != nil {
    panic(err)
}
```

-------------------

If you can't reproduce, I can write a minimal code.

**Comment by miekg** [comment]
I don't think we ever hooked up the actual gracefullness of this in the udp/tcp handlers... Mostly of fair of impairing the performance. But I have to check the actual code to double check what is there.

We could chalk it up as a documention bug... but a proper fix would be better of course.

**Comment by miekg** [comment]
Do you want to debug/fix this?

**Comment by jraqula** [comment]
👍  also have experienced this, shopped around and saw this solution to the same problem in another repo: https://github.com/tylerb/graceful/commit/119c58e176bce26fd40698146d9a106c8f1723a5

the issue which prompted that change was https://github.com/tylerb/graceful/issues/57

**Comment by miekg** [comment]
I'm open to PR(s) to fix this. And a test that shows the error.

Thanks!

**Comment by miekg** [comment]
any work being done here?

**Comment by oif** [comment]
@miekg
Hi,
I'm caught in in the same situation as well (using master branch).
Would like to know which PR (s) fixed this issue?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Is Server.Shutdown(..." ]
>@miekg
>Hi,
>I'm caught in in the same situation as well (using master branch).
>Would like to know which PR (s) fixed this issue?

noone submitted code, so there is no PR

**Comment by oif** [comment]
so this issue is waiting for someone to fix?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Is Server.Shutdown(..." ]
>so this issue is waiting for someone to fix?

yes

/Miek

--
Miek Gieben

**Comment by oif** [comment]
ok, I will try to fix this issue, and open a PR once make sure this issue is fixed.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Is Server.Shutdown(..." ]
>ok, I will try to fix this issue, and open a PR once make sure this issue is fixed.

thank you!

**Comment by oif** [comment]
I solve(maybe) this issue like tylerb/graceful@119c58e as @jraqula commented(ignore listener.Accept excepted error when calling Shutdown)
But confused about `server.ListenAndServe()` returns nil in package test case while returns a "use of closed network connection" error outside the package. Need to be further confirmed

**Comment by miekg** [comment]
fyi: If ripped out the graceful shutdown stuff, because of bugs in the impl. and not working properly (for you) in #561 

This is not to say we don't want graceful shutdown; but it should be lightweight, relative straight forward impl and not be buggy :)
