### ISSUE TITLE
dns.Transport

### ISSUE THREAD

**Issue by miekg** [miekg/dns#464]
In CoreDNS (github.com/coredns/coredns) we use gRPC for for encapsulation dns messages. The server side impl. is quite hacky (github.com/coredns/grpc), because this library only supports udp/tcp. It would be nice to abstract this into some kind of dns.Transport which can be used for a server so it natively speaks gRPC (or whatever).

Also see #423 about the discussion of this in the context of mDNS (which is again diff. because it changes the semantics of the DNS a bit [which we could allow and maybe switch on the underlying transport])

**Comment by miekg** [comment]
Pondering what the right approach is. Currently think that I should hack grpc into "dns" and then abstract both tcp/udp and gRPC out of it to see if it will fit a `dns.Transport`-thingy. Of course we already support DNS-over-TLS so what should follow the same route.

Then we have concerns about backwards compat of the whole thing - cause I don't want to break that either.

**Comment by miekg** [comment]
Pondering again. Currently server-side we have `server.Net`, this indicates what kind of server it is. TLS is also supported there. Although not the most extensible piece of art it works quite well. I'm inclined to just extend this with gRPC and follow the same route. This is obviously not related to any standard, but I think this could be fixed by writing the damn RFC

**Comment by johnbelamaric** [comment]
Yes, that seems to be the right place to do it without any major refactoring. One thing to consider though is whether this should just be a different kind of protocol handler on top of the existing TLS code. If we can just somehow hand off the listener to CoreDNS then you may be able to leave the gRPC pieces outside of this lib.

https://github.com/coredns/grpc/blob/master/middleware/grpc/grpc.go#L33

**Comment by miekg** [comment]
Yeah, figured that as well, See https://github.com/coredns/coredns/pull/574 which is completely reworked, and makes a gRPC local to CoreDNS.

**Comment by miekg** [comment]
Closing for now. We've found a solution local to CoreDNS - the server.Net is currently the extension mechanism we have (for better or worse)
