### ISSUE TITLE
Misleading error for failed/refused XFR

### ISSUE THREAD

**Issue by janeczku** [miekg/dns#467]
It seems that the library does not evaluate the return code of the messages received during XFR transfers. When the server returns a REFUSED or SERVAIL code for an XFR query, instead of passing through the error code, an ominous "No SOA" error is returned.

dig

```
; <<>> DiG 9.8.3-P1 <<>> @yadifa.sidnlabs.nl types.wb.sidnlabs.nl axfr +all
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 5274
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;types.wb.sidnlabs.nl.		IN	AXFR

; Transfer failed.
```

miekg/dns

> dns: no SOA

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Misleading error for fa..." ]
>It seems that the library does not evaluate the return code of the messages received during XFR transfers. When the server returns a REFUSED or SERVAIL code for an XFR query, instead of passing through the error code, an ominous "No SOA" error is returned.

Ack. That could indeed be done better. PR(s) welcome.
