### ISSUE TITLE
Salt is not packed for NSEC3 records

### ISSUE THREAD

**Issue by rolandshoemaker** [miekg/dns#473]
#392 was meant to stop packing the salt from NSEC3/NSEC3PARAM records if the salt was empty (i.e. had the `-` value) but instead just completely stopped packing salts. This causes signature verification failure for signatures of NSEC3/NSEC3PARAM records.

**Comment by andrewtj** [comment]
This also came up in [#426](https://github.com/miekg/dns/issues/426#issuecomment-280956852).
