### ISSUE TITLE
Fields should stringify txt just as txt.String() does

### ISSUE THREAD

**Issue by tlimoncelli** [miekg/dns#476]
If I have a dns.RR, and I want to print its components, I'm doing a lot of work.  Maybe I'm over-thinking this.

For example, to print rr.Header().Name, code always passes the string through sprintName() first.  That function isn't exposed, which leaves me to either reproduce the code, or use rr.String() and then split on \t to get the individual parts.

The target and other data of a rr is also difficult to obtain.  Again it is easier to rr.String(), then split it, etc.  For example:

    items := strings.SplitN(rr.String(), "\t", 5)
    name = items[0]
    target = items[4]
    # if type is MX, split target.
    # if type is SRV, split target.
    # if type is TXT, remove surrounding quotes.
    # etc.

It seems like either (1) I'm making this too hard on myself because there's an easier way that I'm not seeing, or (2) dns should export sprintTxt() and sprintName() so that users don't have to parse the output of rr.String().

**Comment by andrewtj** [comment]
What are you trying to accomplish?

**Comment by tlimoncelli** [comment]
Here are 3 examples from [dnscontrol](https://github.com/StackExchange/dnscontrol).  In all three cases we have a RR and want to output it to a text file in one format or another:

(1) The easiest case to explain is the code that pretty-prints a DNS zone file.  When we print a label, it seems prudent to pass it through sprintName():
https://github.com/StackExchange/dnscontrol/blob/master/providers/bind/prettyzone.go#L90

(2) When we print a TXT record, we want to get the quoting correct, which is very tricky. The easiest method we've found is to use rr.String() and parse out the TXT strings:
(same function in https://github.com/StackExchange/dnscontrol/blob/master/providers/bind/prettyzone.go#L90)

(3) In another example, without access to sprintName(), printing the target of an MX record is done by parsing rr.String() then parsing item[4] to split out the preference and the MX target:
https://github.com/StackExchange/dnscontrol/blob/master/misc/convertzone/main.go#L113

**Comment by miekg** [comment]
Can't you use `Field` and `NumField` to access the rdata?

**Comment by tlimoncelli** [comment]
Ah!  I didn't know those existed.

Looking at them, I don't think TXT does the quoting the same way rr.String() does, nor does it pass host targets through sprintName().

I might be misunderstanding sprintName()'s purpose.  Is the point to properly quote special chars in a label?

**Comment by andrewtj** [comment]
> Looking at them, I don't think TXT does the quoting the same way rr.String() does, nor does it pass host targets through sprintName().

Seems like a bug imo.

> I might be misunderstanding sprintName()'s purpose. Is the point to properly quote special chars in a label?

Pretty much—it should make you sure get the same output as if you'd packed and unpacked a name in wire format.

**Comment by tlimoncelli** [comment]
Yes, it feels like a bug to me.

**Comment by miekg** [comment]
Field and NumField are also probably out of date w/ respect to all the additions. happy to take PRs here,

**Comment by miekg** [comment]
think noone is fixing or looking into this
