### ISSUE TITLE
Client `exchange` with default port 53 support

### ISSUE THREAD

**Issue by Colstuwjx** [miekg/dns#491]
Currently, it seems that we need to call `client.Exchange(msg, DNS_SERVER:PORT)` with full dns server and port. Could dns.client support fill out default port 53 while there is no setup?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Client `exchange` with ..." ]
>Currently, it seems that we need to call `client.Exchange(msg, DNS_SERVER:PORT)` with full dns server and port. Could dns.client support fill out default port 53 while there is no setup?

Addr in Go DNS is mimiced on net.Addr which AFAICT always includes the port.
Also client.Exchange already does a lot and I don't want to add SplitHostPort
and JoinHostPort in this path; which is also pretty trivial to do yourself (out
side of this method).

In short: I don't think this should be done in this method.

**Comment by Colstuwjx** [comment]
OK，thanks a lot for your reply.
