### ISSUE TITLE
Unable to punycode 😁.to

### ISSUE THREAD

**Issue by RBeaudoin** [miekg/dns#505]
When attempting to punycode 😁.to, we are getting back an empty string `""`.

I looked in RFC 5892, and I haven't seen anything that disallows `U+1F601`, and was hoping you could help me to understand better why this is happening. Here at Heroku we integrate with Let's Encrypt to issue certs. LE states that they also follow RFC 5982, and they accept 😁.to as legal IDN.

Any ideas/thoughts you have here would be very helpful. Thanks!

**Comment by rafaeljusto** [comment]
According to [RFC 5892 - Appendix B.1](https://tools.ietf.org/html/rfc5892#appendix-B.1) the Unicode `U+1F601` is reserved:

```
1F249..1FFFD; UNASSIGNED  # <reserved>..<reserved>
```

**Comment by andrewtj** [comment]
Closing as from @rafaeljusto's explanation this looks to be the same scenario as #490.
