### ISSUE TITLE
IXFR problems with VitalQIP

### ISSUE THREAD

**Issue by kahnert** [miekg/dns#506]
With VitalQIP® [Release 8.1] under Linux & FreeBSD AXFR is working, and IXFR needs a patch: [xfr.txt](https://github.com/miekg/dns/files/1228654/xfr.txt)

go version go1.8.3 linux/amd64
go version go1.8.3 freebsd/amd64

**Comment by andrewtj** [comment]
Closing in favour of #507 which is the same patch as a pull-request.
