### ISSUE TITLE
SetIxfr with empty ns and mbox -> Malformed Packet

### ISSUE THREAD

**Issue by kahnert** [miekg/dns#509]
With "dig" the ns and mbox field is empty (inside the packet a byte with value 0 for both strings).
But SetIxfr will create malformed packets which causes "dns: bad xfr rcode: 1".

BTW: Parsing the error string to get the code number is kinda cumbersome. Wouldn't it be better to have an own error type which holds the rcode number? Something like `type XfrError struct{ Rcode int }`?

**Comment by miekg** [comment]
Yes `SetIxfr` will happily do what it is told to do.

Agree with the typed errors. That would have been a better idea, sadly that horse has left the barn.

**Comment by kahnert** [comment]
> Yes `SetIxfr` will happily do what it is told to do.

And how do you tell `SetIxfr` to create a correct packet with empty ns
and mbox? `SetIxfr("example.com.", 7, "", "")` won't do the trick.


> Agree with the typed errors. That would have been a better idea, sadly that horse has left the barn.

You only export the error interface, so this should work without
breaking anything:

`type XfrError struct { Rcode int }

func (e *XfrError) Error() string {
    if e == nil {
        return "dns: <nil>"
    }
    return "dns: bad xfr rcode: " + strconv.Itoa(e.Rcode)
}`

And use it in xfr.go `c <- &Envelope{in.Answer, &XfrError{in.Rcode}}`.

But I understand if you don't take the chance to break stuff like
`err.(*dns.Error)`. Maybe something for a dns.v2.

Would also be nice to return the error string via `RcodeToString[e.Rcode]`
in dns.v2.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] SetIxfr with emtpy ..." ]
>And how do you tell `SetIxfr` to create a correct packet with empty ns
>and mbox? `SetIxfr("example.com.", 7, "", "")` won't do the trick.

SetIxfr("example.com.", 7, ".", ".")

should work.

>> Agree with the typed errors. That would have been a better idea, sadly that horse has left the barn.
>
>You only export the error interface, so this should work without
>breaking anything:
>
>`type XfrError struct { Rcode int }
>
>func (e *XfrError) Error() string {
>    if e == nil {
>        return "dns: <nil>"
>    }
>    return "dns: bad xfr rcode: " + strconv.Itoa(e.Rcode)
>}`
>
>And use it in xfr.go `c <- &Envelope{in.Answer, &XfrError{in.Rcode}}`.
>
>But I understand if you don't take the chance to break stuff like
>`err.(*dns.Error)`. Maybe something for a dns.v2.
>
>Would also be nice to return the error string via `RcodeToString[e.Rcode]`
>in dns.v2.

Yeah v2 :-)

You're right though, this can be changed without breaking code. Care to submit 
a PR?

**Comment by kahnert** [comment]
> SetIxfr("example.com.", 7, ".", ".")
> 
> should work.

You're absolutely right - can't believe I didn't tried this. ;)

My bad, issue closed.


> Yeah v2 :-)
> 
> You're right though, this can be changed without breaking code. Care
> to submit a PR?

Well, I've added it into PR #507, but if this is unhandy and you prefer
a new PR, let me know.

**Comment by miekg** [comment]
It's better to do as a separate PR (1 issue -> 1 pr)
