### ISSUE TITLE
IXFR may end prematurely

### ISSUE THREAD

**Issue by kahnert** [miekg/dns#512]
Imagine this case (not sure if it can happen at all). You request an IXFR and got this answer (example taken out of RFC 1995):

JAIN.AD.JP.         IN SOA serial=3               
JAIN.AD.JP.         IN SOA serial=1               
NEZU.JAIN.AD.JP.    IN A   133.69.136.5           
JAIN.AD.JP.         IN SOA serial=2               
JAIN-BB.JAIN.AD.JP. IN A   133.69.136.4           
JAIN-BB.JAIN.AD.JP. IN A   192.41.197.2           
JAIN.AD.JP.         IN SOA serial=2               
JAIN-BB.JAIN.AD.JP. IN A   133.69.136.4           
JAIN.AD.JP.         IN SOA serial=3               
JAIN-BB.JAIN.AD.JP. IN A   133.69.136.3           
JAIN.AD.JP.         IN SOA serial=3

Than `if v, ok := in.Answer[len(in.Answer)-1].(*SOA); ok` will end prematurely on `len(in.Answer) == 9`. You'll miss the last part. I haven't fixed this in my PR #507, yet either, because this isn't a problem with QIP.

**Comment by miekg** [comment]
good find. Yes this is a bug

**Comment by kahnert** [comment]
fixed in #507

**Comment by miekg** [comment]
Should probably not pile more on #507. I left some comments on that PR though
