### ISSUE TITLE
Package no longer works on AppEngine (as it needs Go 1.6)

### ISSUE THREAD

**Issue by bramp** [miekg/dns#515]
Go on AppEngine is [on version 1.6](https://cloud.google.com/appengine/docs/standard/go/runtime). In the last few months miekg/dns has started to use features only in Go 1.7. As such this no longer compiles when using the AppEngine version.

As far as I can tell there is currently only one compile error:
```
vendor/src/github.com/miekg/dns/client.go:7:2: cannot find package "context" in any of:
	/Users/bramp/bin/go_appengine/goroot/src/context (from $GOROOT)
```

I understand the PITA supporting old versions, so I'm not going to argue too hard, but it would be possible to use build tags to move the go 1.7+ features into a separate file which is not compiled on Go 1.6. I'm happy to send a patch over for that if this project is willing.

**Comment by miekg** [comment]
hmmm, didn't realize at the time that context.Context was using the 1.7 package and not the out of tree one. We try to support the last two go version which now are: 1.8 and 1.7. I'm not a fan of pushing complexity upstream because of downstream issues...

**Comment by bramp** [comment]
Yes I understand this is not ideal. So for the record, 2d7eb4f050c25a6d4401af9abd939d42ac773331 is the last version that works on AppEngine, and for my case I'll pin my app to using that.

However, I just did some digging, and found that Go 1.8 is current in beta for AppEngine, so this problem will go away soon (I hope).
