### ISSUE TITLE
Don't compress domain names in post-1035 record types

### ISSUE THREAD

**Issue by gibson042** [miekg/dns#521]
Per [RFC 3597](https://tools.ietf.org/html/rfc3597#section-4):
> servers MUST NOT compress domain names embedded in the RDATA of types that are class-specific or not well-known... it is hereby specified that only the RR types defined in [[RFC1035](https://tools.ietf.org/html/rfc1035)] are to be considered "well-known".

Therefore, `compressionLenHelperType` and `pack`s should _only_ use domain name compression logic in RDATA for
* NS
* SOA
* CNAME
* PTR
* MB
* MD
* MF
* MG
* MINFO
* MR
* MX

**Comment by miekg** [comment]
I failed to understand the rational behind the MUST in the RFC. If something is a domainname why can't you just compress it.

> RRs containing compression pointers in the RDATA part cannot be
   treated transparently, as the compression pointers are only
   meaningful within the context of a DNS message.  Transparently
   copying the RDATA into a new DNS message would cause the compression
   pointers to point at the corresponding location in the new message,
   which now contains unrelated data.  This would cause the compressed
   name to be corrupted.

So don't do that, decompress message; then fiddle with the binary.

**Comment by gibson042** [comment]
That wouldn't work; you can't decompress a pointer unless you recognize it **as** a pointer, and you can't recognize it as a pointer if it's in the RDATA of a record type you don't understand. For example, RDATA 0xC00C _could_ represent a domain name matching the QNAME, or _could_ represent a two-octet sequence—there's no way to know without the context of the RR type's RDATA format.

**Comment by miekg** [comment]
Ah, true. Thanks. Yes, we should stop doing this then.

**Comment by miekg** [comment]
Looking at #657 I don't think we compress these values, we only use these to set compression pointers *to* (except for AFSDB, that's a bug)

**Comment by andrewtj** [comment]
@miekg I just tested this and I think you're right. If I add some SRV RRs to a message, the SRV's Target isn't compressed but is used as a destination for a compression pointer.
