### ISSUE TITLE
Return error when encountering a disallowed compression pointer

### ISSUE THREAD

**Issue by gibson042** [miekg/dns#522]
Per [RFC 3597](https://tools.ietf.org/html/rfc3597#section-4):
> Receiving servers MUST decompress domain names in RRs of well-known type, and SHOULD also decompress RRs of type RP, AFSDB, RT, SIG, PX, NXT, NAPTR, and SRV... Future specifications for new RR types that contain domain names within their RDATA MUST NOT allow the use of name compression for those names

Therefore, `unpack` should return an error for any record containing a compression pointer unless it is one of the following types:
* NS
* SOA
* CNAME
* PTR
* MB
* MD
* MF
* MG
* MINFO
* MR
* MX
* RP
* AFSDB
* RT
* SIG
* PX
* NXT
* NAPTR
* SRV

**Comment by miekg** [comment]
Think there is even a comment somewhere saying we're too lenient (compress to many types). Note that we still need to deal with these types coming in compressed

**Comment by tmthrgd** [comment]
RFC 3597 doesn't actually prohibit decompressing names outside that list.

The key paragraph is the following:
```
   Receiving servers MUST decompress domain names in RRs of well-known
   type, and SHOULD also decompress RRs of type RP, AFSDB, RT, SIG, PX,
   NXT, NAPTR, and SRV (although the current specification of the SRV RR
   in [RFC2782] prohibits compression, [RFC2052] mandated it, and some
   servers following that earlier specification are still in use).
```

Note decompressing well-known types is a MUST, and decompressing the above list is a SHOULD. It makes no mention of what to do when encountering compression pointers in other types. This is implementation specific and it makes equal sense to accept or prohibit them IMHO.

The change required to implement this is very simple if @miekg wants that approach.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Return error when e..." ]
>RFC 3597 doesn't actually prohibit decompressing names outside that list.
>
>The key paragraph is the following:
>```
>   Receiving servers MUST decompress domain names in RRs of well-known
>   type, and SHOULD also decompress RRs of type RP, AFSDB, RT, SIG, PX,
>   NXT, NAPTR, and SRV (although the current specification of the SRV RR
>   in [RFC2782] prohibits compression, [RFC2052] mandated it, and some
>   servers following that earlier specification are still in use).
>```
>
>Note decompressing well-known types is a MUST, and decompressing the above list is a SHOULD. It makes no mention of what to do when encountering compression pointers in other types. This is implementation specific and it makes equal sense to accept or prohibit them IMHO.
>
>The change required to implement this is very simple if @miekg wants that approach.

I though we decompress anything that is a domain name already?

/Miek

--
Miek Gieben

**Comment by tmthrgd** [comment]
We do decompress everything, sorry for the confusion. What I was saying was the change required to prohibit them and return an error, as OP wanted, is simple.

**Comment by miekg** [comment]
but wouldn't this then lead to semi legal messages being rejected?  I don't think that's an OK thing to do

**Comment by tmthrgd** [comment]
@gibson042 Could you elaborate on where the security implication comes from?

**Comment by gibson042** [comment]
Dyn mostly provide authoritative service, and so would never receive wire format messages except for AXFR, in which we would reject as invalid compressed domain names in record data that do not allow them (and that we _do_ accept would be bugs to fix). The most important thing is just to never _emit_ compression pointers in such RDATA, though I am not sure how e.g. Unbound would respond to receiving them.

**Comment by tmthrgd** [comment]
Closing, see https://github.com/miekg/dns/pull/848#issuecomment-443417196.

This library is already compliment with RFC 3597 in regards to only compressing well-known names (after #847), and the RFC doesn't clearly state that decompression should be prohibited.

In a perfect world we would be strict here, but alas.

**Comment by gibson042** [comment]
I said "the most important thing", not "the _only_ important thing". This library can be strict here, and in my opinion should be. The RFC doesn't state that decompression is prohibited, but it doesn't need to—compression is prohibited, and compression pointers in these RDATA are invalid. As I've argued in several other issues, **accepting invalid data is bad**.

**Comment by tmthrgd** [comment]
@gibson042 Oh I do agree with you on all of that, but it’s not my call.
