### ISSUE TITLE
Expose a dnsutil function for interpreting potentially-relative domain names

### ISSUE THREAD

**Issue by gibson042** [miekg/dns#525]
As suggested in https://github.com/miekg/dns/pull/513#discussion_r141078933 , `toAbsoluteName` fits the bill after a slight rename:
```go
func Join(name, origin string) (absolute string, err error) {
	// check for an explicit origin reference
	if name == "@" {
		// require a nonempty origin
		if origin == "" {
			return "", &Error{err: "origin reference without origin"}
		}
		return origin, err
	}

	// require a valid domain name
	_, ok = IsDomainName(name)
	if !ok || name == "" {
		return "", &Error{err: "not a domain name"}
	}

	// check if name is already absolute
	if name[len(name)-1] == '.' {
		return name, err
	}

	// require a nonempty origin
	if origin == "" {
		return "", &Error{err: "relative domain name without origin"}
	}
	return appendOrigin(name, origin), err
}
```

**Comment by miekg** [comment]
Yep something like this. However `join(labels []string, origin string) ...` is better as a function signature

**Comment by gibson042** [comment]
That would make the behavior less predictable... for example, what should we do when a "label" in the first parameter contains a dot? That is, would `join([]string{"foo.bar", "baz"}, "example.com.")` be equivalent to `"foo.bar.baz.example.com."`, or to `"foo\046bar.baz.example.com."`? There's no such issue when we're just interpreting a complete—if potentially relative—domain name relative to an origin.

**Comment by miekg** [comment]
> That is, would join([]string{"foo.bar", "baz"}, "example.com.") be equivalent to "foo.bar.baz.example.com.", or to "foo\046bar.baz.example.com."?

The first, we don't care. If all done properly that first label should be `foo\\.bar` in the first place.

**Comment by gibson042** [comment]
In that case, the first argument is not a list of labels but rather a list of domain names for interpretation against an origin in right-to-left order. So would `join([]string{"foo.", "bar"}, "example.com.")` (in which one of the elements is absolute) return `"foo."`?
