### ISSUE TITLE
"context" path?

### ISSUE THREAD

**Issue by paulehoffman** [miekg/dns#541]
Possibly a newbie error, but I get this blocking error while pulling in this project to make CoreDNS:

```
# go get github.com/miekg/dns
package context: unrecognized import path "context" (import path does not begin with hostname)
```

**Comment by edmonds** [comment]
@paulehoffman Looks like this package was added to the Go standard library in Go 1.7. Are you using an older version?

**Comment by paulehoffman** [comment]
Yep, 1.6. FWIW, "apt install golang" on Unbuntu installs `go1.6.2` and there doesn't seem to be a package for 1.7.

**Comment by miekg** [comment]
Yes, latest 2 releases are supported: 1.8 and 1.9, so we've moved to `context.Context` which is in the std lib, since 1.7 (or 1.8)
