### ISSUE TITLE
Move to github org?

### ISSUE THREAD

**Issue by miekg** [miekg/dns#557]
~~Also see https://github.com/miekg/dns/issues/555~~

~~I propose we drop this; implement dnsutil somewhere else, but not maintained within this package.~~

~~This is backwards incompatible, but easy to fix; copy the function into your own code.~~

**Comment by andrewtj** [comment]
What do you reckon of making a new GitHub organisation? Might be a good place to peel off `dnsutil` and `idn`, as well as any other esoteric or dependency-requiring things. Possibly whatever comes out of the GSS-TSIG discussion for instance.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] proposal: drop dnsu..." ]
>What do you reckon of making a new GitHub organisation? Might be a good place to peel off `dnsutil` and `idn`, as well as any other esoteric or dependency-requiring things. Possibly whatever comes out of the GSS-TSIG discussion for instance.

That's sounds like a good idea. But you move the repo (even with the github 
redirection you break a lot of builds, no?)

**Comment by miekg** [comment]
any ideas for a name, dns is obviously taken. godns is still free, but somewhat dislike the 'god'ns 
(can't hurt to acquire a name before we do something)

**Comment by miekg** [comment]
doesn't preclude dropping it from miekg/dns now though (resurrect it in a new org)

**Comment by andrewtj** [comment]
Yeah I'd assume moving the repo will break things. Maybe issues, etc can be disabled on this repo and it can be be run as a mirror for a while.

I don't have any ideas for a name at the minute but maybe inspiration will strike. Do you want an available .com/.net/.org to go along with the name? And I suppose on that, is moving to a vanity import URL worthwhile? I doubt GitHub is going anywhere but if you wanna snag a namespace, might as well use it I guess.

It look like there isn't too many (public) users of either pkg going by the [dnsutil](https://godoc.org/github.com/miekg/dns/dnsutil?importers) and [idn](https://godoc.org/github.com/miekg/dns/idn?importers) importers. I can probably find the time to drop an issue to each of them pointing back here if you like.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] proposal: drop dnsu..." ]
>Yeah I'd assume moving the repo will break things. Maybe issues, etc can be disabled on this repo and it can be be run as a mirror for a while.

Yep, that might work. We should also move to semver after such a move. Now with 
'dep' this finally makes sense.

>I don't have any ideas for a name at the minute but maybe inspiration will strike. Do you want an available .com/.net/.org to go along with the name? And I suppose on that, is moving to a vanity import URL worthwhile? I doubt GitHub is going anywhere but if you wanna snag a namespace, might as well use it I guess.

Ok. I'll ponder this a bit as well. Yes, domain name will be nice.

>It look like there isn't too many (public) users of either pkg going by the [dnsutil](https://godoc.org/github.com/miekg/dns/dnsutil?importers) and [idn](https://godoc.org/github.com/miekg/dns/idn?importers) importers. I can probably find the time to drop an issue to each of them pointing back here if you like.

Super. Thank you!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] proposal: drop dnsu..." ]
>I don't have any ideas for a name at the minute but maybe inspiration will strike. Do you want an available .com/.net/.org to go along with the name? And I suppose on that, is moving to a vanity import URL worthwhile? I doubt GitHub is going anywhere but if you wanna snag a namespace, might as well use it I guess.

github.com/go-dns

exists now - reversed for lack of a better name.

**Comment by fbettag** [comment]
Well why not name it miekdns? Resemblance to the old/your name while easier to say as a word without the g ;)

**Comment by miekg** [comment]
Well, we are well beyond me doing most of the work - so dropping my name from it is fine. mdns would work, but that is already a dns thingy.

**Comment by fbettag** [comment]
mgdns on the other hand goes off the tongue like butter and isn't taken as far as i see

**Comment by tlimoncelli** [comment]
Would the repos then have names like these?

* github.com/mgdns/dns
* github.com/mgdns/idn
* github.com/mgdns/dnsutil

**Comment by miekg** [comment]
If we are going to go there, yes.

**Comment by andrewtj** [comment]
I've created issues at the [`idn`](https://godoc.org/github.com/miekg/dns/idn?importers) importers referring back to #518.

For [`dnsutil`](https://godoc.org/github.com/miekg/dns/dnsutil?importers) it looks like there's really only two importers to contact. Since one of them is StackExchange and @tlimoncelli is already in this thread, I'll assume `dnsutil` will live on and leave contacting the other one till the new import path is decided.

**Comment by miekg** [comment]
I'm all in favor of doing this, but I have 0 cycles to push this forward (at this time). Unless someone (@andrewtj ?) steps up and presses buttons this wont happen this year.

(still need to discuss a name - maybe best to do that via email? But shit if someone hijacks possible names)

**Comment by miekg** [comment]
It also wont happen this year
