### ISSUE TITLE
Support ReadMsgUDP on Windows

### ISSUE THREAD

**Issue by fastest963** [miekg/dns#571]
Looks like with the addition of https://github.com/golang/go/issues/9252 in Go 1.10 we should be able to support #524 on Windows. We need to wait for https://go-review.googlesource.com/c/go/+/76391 to be merged into x/net first, but I thought I would open this issue for tracking. This would be a good point to switch to using `godep` as well.

**Comment by miekg** [comment]
@fastest963 We're now (merged this few minutes ago) using dep to manage dependencies. Probably makes sense to drop our `internal` dir and properly vendor the net/tools ?

**Comment by miekg** [comment]
Should this still be open?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Support ReadMsgUDP ..." ]
>Given that https://go-review.googlesource.com/c/go/+/76393 is merged into go 1.10, it looks like we should be able to support this. Are we comfortable with requiring go 1.10 (on Windows) or should I add a build flag to the file so it only opportunistically (Windows+1.10) does this?

Should probably wait until 1.11 then...

**Comment by tmthrgd** [comment]
This was fixed in #738.
