### ISSUE TITLE
Using 'ANY' as class in presentation format

### ISSUE THREAD

**Issue by spsholleman** [miekg/dns#577]
This works fine
	x, xErr := NewRR("www.miek.nl. 3600 IN TXT \"first\" \"second\"")

but this doesn't:
	x, xErr := NewRR("www.miek.nl. 3600 ANY TXT \"first\" \"second\"")
	if xErr != nil {
		t.Fatalf("failed to parse TXT: %s", xErr)
	}

it fails with the following error:
	dns_test.go:461: failed to parse TXT: dns: unknown RR type: "TXT" at line: 1:26

I assume this should work - or am I confused?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Is (#577)..." ]
>This works fine
>	x, xErr := NewRR("www.miek.nl. 3600 IN TXT \"first\" \"second\"")
>
>but this doesn't:
>	x, xErr := NewRR("www.miek.nl. 3600 ANY TXT \"first\" \"second\"")
>	if xErr != nil {
>		t.Fatalf("failed to parse TXT: %s", xErr)
>	}
>
>it fails with the following error:
>	dns_test.go:461: failed to parse TXT: dns: unknown RR type: "TXT" at line: 1:26
>
>I assume this should work - or am I confused?

I don't know. What section in which RFC makes you think this?

**Comment by spsholleman** [comment]
I was having problems getting the parser to recognize TSIG or TKEY when ANY was used so I came up with a TXT example.  That may not have been the best idea.  I agree the TXT RFC says it should be of IN class but RFC 2845 and 2930 state that TSIG and TKEY should be of class ANY but don't provide any suggested textual representation.  All three return the same error about not recognizing the RR type and it seemed that the parser just doesn't support the ANY class.

I can try and dig into it later but figured others more familiar with the parser might immediately know why.

**Comment by gibson042** [comment]
"ANY" is not a real class mnemonic (cf. [DNS CLASSes](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-2)), and we're right to reject it. Per [RFC 3597](https://tools.ietf.org/html/rfc3597#section-5), the proper text representation is "CLASS255".

**Comment by andrewtj** [comment]
That seems like a poor error message if it's an intentional failure due to the CLASS.

It also seems strange to accept CLASS255 since it'll then be presented as ANY and will then fail to parse on a subsequent parse. Eg:

```
package main

import (
	"log"

	"github.com/miekg/dns"
)

func main() {
	rr, err := dns.NewRR(`www.miek.nl. 3600 CLASS255 TXT "first" "second"`)
	if err != nil {
		log.Fatalf("first parse failed: %s", err)
	}
	rr, err = dns.NewRR(rr.String())
	if err != nil {
		log.Fatalf("second parse failed: %s", err)
	}
}
```

**Comment by miekg** [comment]
We should translate `CLASS255` into `ANY`

**Comment by miekg** [comment]
oh shit, this may be used in dynamic updates?

Then we probably *do* need to parse this. hpmf

**Comment by miekg** [comment]
or maybe not; still think https://github.com/miekg/dns/issues/577#issuecomment-346309303 is the way forward.

**Comment by gibson042** [comment]
Right. ANY can't be parsed because it would be ambiguous, so translation to ANY is incorrect.

**Comment by miekg** [comment]
Can we get away with:
~~~
diff --git a/ztypes.go b/ztypes.go
index 0613ba0..c89241b 100644
--- a/ztypes.go
+++ b/ztypes.go
@@ -85,7 +85,6 @@ var TypeToString = map[uint16]string{
        TypeA:          "A",
        TypeAAAA:       "AAAA",
        TypeAFSDB:      "AFSDB",
-       TypeANY:        "ANY",
        TypeATMA:       "ATMA",
        TypeAVC:        "AVC",
        TypeAXFR:       "AXFR",
~~~
This needs to happen in type_generate.go so the actual change will be bigger.

**Comment by andrewtj** [comment]
With the caveat that I've forgotten how the parsing mechanics work and I don't have time to revisit it now, I think we should be parsing all mnemonics and then rejecting based on the concrete uint16 value with an error that reflects why it's rejected. This is probably also as good an opportunity as any to revisit the parser's design.

**Comment by miekg** [comment]
Grr, scratch my comment it is for classes.  (@andewjt I don't disagree with rewrites, but the current text parser has been doing it work for the past 6 years, with relatively few bugs, except maybe: https://miek.nl/2017/november/17/switching-to-vodafone-uncovered-a-bug/).

The *correct* diff to disallow the text representation for the ANY class will be:
~~~
diff --git a/msg.go b/msg.go
index afce176..07bdb6b 100644
--- a/msg.go
+++ b/msg.go
@@ -133,7 +133,6 @@ var ClassToString = map[uint16]string{
        ClassCHAOS:  "CH",
        ClassHESIOD: "HS",
        ClassNONE:   "NONE",
-       ClassANY:    "ANY",
 }
~~~
Output from above program:
~~~
% go run main.go
www.miek.nl.	3600	CLASS255	TXT	"first" "second"
~~~

**Comment by miekg** [comment]
I think this change will be backwards incompatible, hence, let's leave it like it is.

**Comment by gibson042** [comment]
What change are you rejecting, and what backwards incompatibility are you worried about? Can you provide an example? From the conversation and a personal execution of provided code, the problem seems to be generation of invalid _output_ like `www.miek.nl.	3600	ANY	TXT	"first" "second"`.

**Comment by miekg** [comment]
I mean removing ANY from TypeToString

Looking into what people do in CoreDNS and other code, it seems this is something that is burned into the API (for better or worse)

**Comment by gibson042** [comment]
Sorry to pester, but can you provide a concrete example of what will break? Input like `www.miek.nl. 3600 ANY TXT "first" "second"` is _already_ rightfully rejected, so what could count on us producing it?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Using 'ANY' as clas..." ]
>Sorry to pester, but can you provide a concrete example of what will break? Input like `www.miek.nl. 3600 ANY TXT "first" "second"` is _already_ rightfully rejected, so what could count on us producing it?

Code line https://github.com/coredns/coredns/pull/1318 will break
Although that one doesn't check a class right now, but using ANY as a wildcard
is not far fetched.

This stops working when we drop it from the map.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
sorry wrong PR: https://github.com/coredns/coredns/pull/1298

**Comment by gibson042** [comment]
Are you seriously advocating that this library remain not only broken, but broken in a self-inconsistent way? "ANY" is trivially easy to address in coredns, as demonstrated in my [feedback](https://github.com/coredns/coredns/pull/1298/files#r160030429) there. _This_ repository claims to be a "Complete and usable DNS library", and specifically mentions "RFC 1035 zone file parsing"—let's make good on that.

**Comment by miekg** [comment]
I'm advocating not breaking dozen's over users who came to rely on this.

**Comment by miekg** [comment]
Anyway, specically RFC 2136, talks about class ANY for dynamic update which why I think I added these in the first place.

And https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml has this:
~~~
255 | 0x00FF | QCLASS * (ANY)
~~~

Coming back to the original issue and actually starting to lean against: why not allow it? The only nit I would have is that `ANY` maybe should have been `*`; but that ship has sailed. And of course the overlap with the rrtype ANY

**Comment by andrewtj** [comment]
@miekg I'm still not sure the current behaviour with CLASS ANY is intentional. If you change [my previous example](https://github.com/miekg/dns/issues/577#issuecomment-346250620) to use CLASS NONE it succeeds which suggests it is not. I wonder if the parse gets out of whack because ANY is both a TYPE and a CLASS. I'll try to take a look later today.

**Comment by gibson042** [comment]
> I'm advocating not breaking dozens of users who came to rely on this.

Came to rely on _what_? RFC 2136 is irrelevant because it's only concerned with wire format, and we already correctly reject "ANY" in presentation format.

**Comment by andrewtj** [comment]
@miekg I've had a leaf through the parser and I'm now pretty sure this isn't intentional:

In [`zlexer()`](https://github.com/miekg/dns/blob/ac8cd7878c723b698420572df92b293dd041d9ff/scan.go#L565-L569), if `rrtype` isn't set the next token is tried as a TYPE. "ANY" is a TYPE so that succeeds, `l` is marked as a `zRrtpe` and `rrtype` is set to true. No early break or return is done here, [so the same token](https://github.com/miekg/dns/blob/ac8cd7878c723b698420572df92b293dd041d9ff/scan.go#L583-L585) is then tried as a CLASS. "ANY" is a CLASS so this also succeeds. `l` is then marked as a `zClass` and returned on the channel. Meanwhile `parseZone()` is [now expecting](https://github.com/miekg/dns/blob/ac8cd7878c723b698420572df92b293dd041d9ff/scan.go#L463-L469) a `zRrtpe`.

**Comment by gibson042** [comment]
Yes, that is _precisely_ the reason for the [RFC 3597 presentation format](https://tools.ietf.org/html/rfc3597#section-5) and yet another reason for fixing the code to reject ANY in all cases.
> This convention allows types and classes to be distinguished from each other and from TTL values, allowing the "[\<TTL>] [\<class>] \<type> \<RDATA>" and "[\<class>] [\<TTL>] \<type> \<RDATA>" forms of [RFC1035] to both be unambiguously parsed.

**Comment by miekg** [comment]
@gibson042 The reason why I want to keep the map as-is is that it creates silent breakage in code that had been working. It's not a compile error so you won't notice it easliy.

Class "NONE" is in the same boat. As DNS is dubiously specced and noone ever said somethin about the presentation format of dynamic RRs I feel we have some leeway here.

**Comment by miekg** [comment]
thanks @andrewtj

**Comment by miekg** [comment]
Ok, 5 min staring at that old code. Regardless of what you think of it, it *is* correct, i.e. ANY can only be a type. If we would allow the above parse we would have to look ahead (ugh).

That would mean *not* translating CLASS255 into ANY, which can still be done without removing the string from the map (which I'm still not confortable with)

**Comment by gibson042** [comment]
> silent breakage in code that had been working

@miekg Can you _please_ point me to such code? So far, your only example has been to a **still-open** PR. And for that matter, why should supporting what looks to me like abuse of a presentation-format-to-wire-format map trump actual correctness of what this library claims to support? Your advocating for the willful incorrectness of _this_ code.

> noone ever said somethin about the presentation format of dynamic RRs I feel we have some leeway here.

On a functional level, we cannot parse input including arbitrary TYPE values that could be confused for a class because the RR contents presentation format is `[<TTL>] [<class>] <type> <RDATA>`—`example.com. ANY TXT foo` _could_ mean CLASS=255 TYPE=16 RDATA="foo" or _could_ mean CLASS=(last specified) TYPE=255 RDATA="TXT foo", and there's no way to infer user intent.

**However**, the collisions are not actually arbitrary—"ANY" is the only value that appears in both StringToClass and StringToType. What would you say to keeping it in both arrays and adding code to the parser that explicitly rejects input including "ANY" in a position that could be an RR class?

**Comment by miekg** [comment]
> @miekg Can you please point me to such code?

I can't point to such code, because I don't know what crazy shit people do. It is part of the exported API, for better or worse, so prolly code depends on it :(

Yes you are (technically) correct about that this is wrong, but I hate breaking this API in a backwards incompatible way. As I said, I rather introduce a compile time error than hard to detect runtime things.

**Comment by gibson042** [comment]
What about my last suggestion, to keep "ANY" in both maps and reject ambiguous input?
```patch
--- i/scan.go
+++ w/scan.go
@@ -497,6 +497,7 @@ func zlexer(s *scan, c chan lex) {
 	escape := false
 	space := false
 	commt := false
+	rrclass := false
 	rrtype := false
 	owner := true
 	brace := 0
@@ -563,9 +564,13 @@ func zlexer(s *scan, c chan lex) {
 				l.tokenUpper = strings.ToUpper(l.token)
 				l.length = stri
 				if !rrtype {
+					if !rrclass {
+						if t, ok := StringToClass[l.tokenUpper]; ok {
+							if _, ok := StringToType[l.tokenUpper]; ok {
+								l.token = "ambiguous class"
+								l.err = true
+								c <- l
+								return
+							}
+							l.value = zClass
+							l.torc = t
+							rrclass = true
+						} else {
+							if strings.HasPrefix(l.tokenUpper, "CLASS") {
+								t, ok := classToInt(l.token)
+								if !ok {
+									l.token = "unknown class"
+									l.err = true
+									c <- l
+									return
+								}
+								l.value = zClass
+								l.torc = t
+								rrclass = true
+							}
+						}
+					}
+					if l.value != zClass {
 						if t, ok := StringToType[l.tokenUpper]; ok {
 							l.value = zRrtpe
 							l.torc = t
+							rrclass = true
 							rrtype = true
 						} else {
 							if strings.HasPrefix(l.tokenUpper, "TYPE") {
@@ -578,23 +583,10 @@ func zlexer(s *scan, c chan lex) {
 								}
 								l.value = zRrtpe
 								l.torc = t
+								rrclass = true
+								rrtype = true
 							}
 						}
-					if t, ok := StringToClass[l.tokenUpper]; ok {
-						l.value = zClass
-						l.torc = t
-					} else {
-						if strings.HasPrefix(l.tokenUpper, "CLASS") {
-							t, ok := classToInt(l.token)
-							if !ok {
-								l.token = "unknown class"
-								l.err = true
-								c <- l
-								return
-							}
-							l.value = zClass
-							l.torc = t
-						}
 					}
 				}
 				c <- l
```

**Comment by miekg** [comment]
the program in https://github.com/miekg/dns/issues/577#issuecomment-346250620 (add to fmt.Println's) now prints:
~~~
% go run x.go
2019/07/25 06:20:08 www.miek.nl.	3600	CLASS255	TXT	"first" "second"
2019/07/25 06:20:08 www.miek.nl.	3600	CLASS255	TXT	"first" "second"
~~~
this looks fixed.
