### ISSUE TITLE
bug: for UDP handling there are no Close() call

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [miekg/dns#578]
Looks like for serveUDP() there are no Close() call, for
`func (srv *Server) serve(a net.Addr, h Handler, m []byte, u *net.UDPConn, s *SessionUDP, t net.Conn)`
`u` and `s` are not nil and `t (w.tcp)` is nil
and we have return without w.Close() // https://github.com/miekg/dns/blob/master/server.go#L561
So `if u != nil` statement should be placed straight after Exit label

```Exit:
	if w.tcp == nil {
		return
	}
	// TODO(miek): make this number configurable?
	if q > maxTCPQueries { // close socket after this many queries
		w.Close()
		return
	}

	if w.hijacked {
		return // client calls Close()
	}
	if u != nil { // UDP, "close" and return
		w.Close()
		return
	}
```

**Comment by miekg** [comment]
I *think* you're right, but I'm not 100% clear what you mean. Care to send a PR?

**Comment by UladzimirTrehubenka** [comment]
Just in UT (that test UDP server) coverage you can see that code inside statement is not covered:
https://codecov.io/gh/miekg/dns/src/acff9ce3fa5f04b7abb500613e6ee80c45321c47/server.go#L574

**Comment by miekg** [comment]
oh sure. We have 58% coverage, so some bits will be missing
