### ISSUE TITLE
semver?

### ISSUE THREAD

**Issue by miekg** [miekg/dns#592]
I'm a bit ambivalent about doing semver, because it implies doing releases, which are just toil. OTOH it might make using this lib easier; because you can version check if you're on the right version (can see a need for this in coredns/coredns).

We could just version without actually releasing?
Can we automatically bump a minor an each PR merged? Start with 1.0.0 --> 1.0.1 etc?

**Comment by andrewtj** [comment]
I don't see a distinction between implementing semver and doing releases. A release has as much fanfare as a project can muster. As long as it's clear what a release/version implies somewhere prominent in the readme and package doc anything's fine.

A bump on every PR shouldn't be too onerous at current contribution levels.

**Comment by fastest963** [comment]
One thing I haven't understood, is how does a user utilize versions in go packages. Unless they're doing vendoring, they just get the latest master whenever they run `go get`. Do enough people use vendoring (or something similar)? Recently at corp we had to stick a package to a particular version (tag) and we had to go in and manually add a build step to cd into the repo in the gopath and check out the older tag.

**Comment by andrewtj** [comment]
I don't know much about it but [dep](https://github.com/golang/dep) is on the road to being the official solution and so I assume the community will rally around it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] semver? (#592)..." ]
>One thing I haven't understood, is how does a user utilize versions in go packages. Unless they're doing vendoring, they just get the latest master whenever they run `go get`. Do enough people use vendoring (or something similar)? Recently at corp we had to stick a package to a particular version (tag) and we had to go in and manually add a build step to cd into the repo in the gopath and check out the older tag.

There isn't user versioning (yet). `dep` is the first step and at least let's 
you vendor the local deps for the package. Users still get master.
