### ISSUE TITLE
dns.Msg with only header

### ISSUE THREAD

**Issue by miekg** [miekg/dns#604]
A `dig @9.9.9.9 +norec . NS` returns a packet with only the header and no question section.

Unpack() returns an Truncated error on this packet, which may or may not be in line with the DNS standard.

Should such a packet be considered valid?

**Comment by andrewtj** [comment]
Yes it should be considered valid. It may or may not be a sensible response in context, but in isolation it is a valid message.

**Comment by miekg** [comment]
closed via #608
