### ISSUE TITLE
NSEC3 interations max

### ISSUE THREAD

**Issue by miekg** [miekg/dns#611]
From 5155:
~~~
 zone owner MUST NOT use a value higher than shown in the table
   below for iterations for the given key size.  A resolver MAY treat a
   response with a higher value as insecure, after the validator has
   verified that the signature over the NSEC3 RR is correct.

                         +----------+------------+
                         | Key Size | Iterations |
                         +----------+------------+
                         | 1024     | 150        |
                         | 2048     | 500        |
                         | 4096     | 2,500      |
                         +----------+------------+

   This table is based on an approximation of the ratio between the cost
   of an SHA-1 calculation and the cost of an RSA verification for keys
   of size 1024 bits (150 to 1), 2048 bits (500 to 1), and 4096 bits
   (2500 to 1).
~~~
Should probably cap at 5000 or smth and return a error unpacking RRs what more than that.

**Comment by shane-kerr** [comment]
Why 5000? Why not use the value based on the key size, like in the RFC? 😄

**Comment by miekg** [comment]
Because that section is already rotten as it only speaks about RSA keys. Just a limit < 64K seems OK and easy enough to do

**Comment by miekg** [comment]
Hmmm, hashname is not used internally, so this change will only affect users of this functions.

There is also no error to be returned :/ We could settle for the empty string here?

Packing and unpacking NSEC3 from the wire should still allow any value.

**Comment by vdukhovni** [comment]
It is important to understand that the correct limit is 150, independently of the key size.  This is the largest interoperable value, everything else causes breakage when users unwittingly break the limits when switching from RSA to ECDSA (for example).  Please read https://tools.ietf.org/html/draft-york-dnsop-deploying-dnssec-crypto-algs-05#section-2.3.1 carefully. The table in RFC5155 is a design error, and the only workable work-around is flatten the limit to 150.

**Comment by vdukhovni** [comment]
Also almost nobody uses iteration counts larger than 150, and the tiny fraction of zones that do should switch to 150 or less. https://www.ietf.org/mail-archive/web/dnsop/current/msg21656.html

**Comment by vdukhovni** [comment]
Just to be clear, my comments are for zone-signers, limiting iteration count in the NSEC3PARAM record they create at the zone apex to avoid interoperability and operational issues.  Zone-signers need to avoid values greater than 150.  The story is different for DNS resolvers.  They must support caps that are at least the caps in RFC5155 (based on key size), and the simplest approach is to support 2500 across the board, but larger values also work, if one is willing to accept the CPU hit.

Note that on the resolver end, correctly signed NSEC3 records with iteration counts that exceed the limits need to be accepted without checking the hashes, making denial of existence completely insecure for domains that publish excessive iteration counts.

Is this project doing zone-signing or DNS resolution?

**Comment by vdukhovni** [comment]
What was the resolution?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] NSEC3 interations m..." ]
>What was the resolution?

We don't care; as we're a library

**Comment by vdukhovni** [comment]
Agreed, as a library, you certainly don't need to worry about caps on sensible iteration counts in authoritative zones.  On the validation side, do you set any limits on how many iterations you support? Those need to match or exceed the limits in the table from the RFC. My advice would 2500 across the board, unless you're willing to do 65535 (which I would not recommend).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] NSEC3 interations m..." ]
>Agreed, as a library, you certainly don't need to worry about caps on sensible iteration counts in authoritative zones.  On the validation side, do you set any limits on how many iterations you support? Those need to match or exceed the limits in the table from the RFC. My advice would 2500 across the board, unless you're willing to do 65535 (which I would not recommend).

limits in the validation may make sense. Still not sure if this is something we 
should do.

**Comment by tmthrgd** [comment]
I threw together a small benchmark:
```go
func BenchmarkHashName(b *testing.B) {
	const (
		label = "some.example.org."
		salt  = "deadbeef"
	)
	for _, iter := range []uint16{
		150, 2500, 5000, 10000, ^uint16(0),
	} {
		b.Run(strconv.Itoa(int(iter)), func(b *testing.B) {
			for n := 0; n < b.N; n++ {
				if HashName(label, SHA1, iter, salt) == "" {
					b.Fatalf("HashName failed")
				}
			}
		})
	}
}
```

This is the results:
```
BenchmarkHashName/150-12                  100000             20399 ns/op            4568 B/op          7 allocs/op
BenchmarkHashName/2500-12                   5000            324722 ns/op            4568 B/op          7 allocs/op
BenchmarkHashName/5000-12                   2000            646740 ns/op            4568 B/op          7 allocs/op
BenchmarkHashName/10000-12                  1000           1291771 ns/op            4568 B/op          7 allocs/op
BenchmarkHashName/65535-12                   200           8493314 ns/op            4568 B/op          7 allocs/op
```

If this was going to be adopted, the best place to handle this would probably be in unpacking the `NSEC3` RR. It could return an error when the iteration count is too high. I don't know how worthwhile that would be.

**Comment by vdukhovni** [comment]
If limits are set, it is __critical__ that the limits are applied after the RRSIG on the NSEC RR is validated, and not before.  Otherwise it becomes trivial to downgrade NSEC3 to insecure by modifying the iteration count.  Only __validated__ iterations counts that are too high may be used to skip checking the hash and accepting an insecure NODATA or NXDOMAIN.

**Comment by tmthrgd** [comment]
@vdukhovni Ack. This doesn't seem worth it then, there's only a x10 hit between 5000 and 65535 iterations.
