### ISSUE TITLE
CPU gets pegged at 100% if a udp listener fails / is closed

### ISSUE THREAD

**Issue by twitchyliquid64** [miekg/dns#613]
**Problem**

The issue is caused by this: https://github.com/miekg/dns/blob/master/server.go#L511

There is an extremely tight CPU-bound loop that the thread gets locked into in the event of any permanent error with `server.readUDP()`. This bug causes excessive user->kernel context switches (due to IO) and pegs a CPU.

**Fix**

The following fix mitigated the issue for us: (line 510ish of server.go)

```go
if err != nil {
	if strings.Contains(err.Error(), "use of closed network connection") {
		return err
	}
	continue
}
```

Unfortunately `internal/poll.ErrNetClosing` is not exported, and I couldn't think of another way to check the error.

A better (and much more efficient) way to do this would be to `continue` only for io timeout errors, and `return err` for all other errors. I'll leave such decisions to you.

**Comment by twitchyliquid64** [comment]
(my fix in vendor is here: twitchyliquid64/colex@a76397b)

**Comment by miekg** [comment]
Can't you use `! Temporary()` in this case? But this might encomposs too many errors?

**Comment by twitchyliquid64** [comment]
It looks like `ErrNetClosing` is one of the few errors that does not implement `net.OpError`, so `!err.Temporary()` wont work :/

See: https://golang.org/search?q=ErrNetClosing

But we could do it the other way maybe?

```go
# Completely untested, written freehand so probs doesnt compile
if opErr, ok := err.(*net.OpError); ok && opErr.Temporary() {
  continue
}
```

**Comment by miekg** [comment]
similar code is used in the tcp reader - thought we applied it here as well, apparantly not.

**Comment by twitchyliquid64** [comment]
SGTM

**Comment by miekg** [comment]
Are sending a PR?

**Comment by twitchyliquid64** [comment]
Oh, I can if you want to?

**Comment by twitchyliquid64** [comment]
Please see my PR for the minimal fix I have.

**Comment by tmthrgd** [comment]
@miekg This should be reopened after #620.
