### ISSUE TITLE
DNS client: TCP connection reuse for TCP and DNS-over-TLS

### ISSUE THREAD

**Issue by daareiza** [miekg/dns#614]
Hi, while using the DNS client I have noticed a performance challenge if a TCP or DNS-over-TLS server is used to resolve queries, this compared against an UDP server (that said, 1.5x-2.0x times slower for TCP, and up to 4x times slower for DNS-over-TLS), so in the long term, there is a drastic performance drop for a heavily used DNS client (e.x.: local server proxy/forwarder).

That performance drop is mainly caused by the opening/closing of a _new TCP connection for every DNS request_,  and the required handshake things that are inherit to the protocol (worse for a TCP TLS handshake).

So, as an improvement, it may be good to have an option to reuse an already made TCP connection and send the requests over it, reducing the handshake things over and over again, specially for a DNS-over-TLS server, where a cert is involved.

As a general idea:

- Add a new bool flag to enable/disable the reuse of TCP connections (not valid for UDP) [client.go#L30](https://github.com/miekg/dns/blob/master/client.go#L30)
- Add a new client attribute with the reusable connection [client.go#L30](https://github.com/miekg/dns/blob/master/client.go#L30)
- On every request, check if the reusable connection is NOT nil/closed, and use that connection [client.go#L160](https://github.com/miekg/dns/blob/master/client.go#L160)
- If the connection is nil/closed, make the `Dial` call to establish a new connection [client.go#L162](https://github.com/miekg/dns/blob/master/client.go#L162)
- Avoid closing the connection after the message exchange finishes [client.go#L167](https://github.com/miekg/dns/blob/master/client.go#L167)
- Add an idle timeout to check for inactive connections and automatically close them
- Add a handler to check/capture connection state changes (I don't know if that is possible)

**Comment by miekg** [comment]
this is a difficult thing to implement and out of scope for this project.
