### ISSUE TITLE
custom transaction id

### ISSUE THREAD

**Issue by ammmir** [miekg/dns#629]
would it be possible to specify a custom transaction id that's not random? i know there's the dns.Id function but it's not ideal for me to implement, since in my use case there are potentially hundreds of simultaneous dns queries in flight and i don't want to introduce a mutex.

for now, i'm modifying the first 2 bytes (i.e., the transaction id) returned from Pack() to set my custom transaction, but a more elegant fix would be nice :)

**Comment by tmthrgd** [comment]
@ammmir Just set the `Id` property on `Msg` before calling `Pack()`.
