### ISSUE TITLE
making typeToUnpack and unpack functions public

### ISSUE THREAD

**Issue by chantra** [miekg/dns#633]
Hi,

I have a use case where I pretty much have all the RR_Header set and all that needs to be unpacked is the RR data.

With the current implementation, all the `unpack` functions are private (unpackA, unpackAAAA..) after there were generated in `zmsg.go`, same goes with `typeToUnpack` .

There would be a few solutions I suppose.
* workaround: Create a new buffer with the header packed (non-public function), append the data and unpack using `UnpackRR()`.
* have a `pack` on `RR_Header` be public so it is easier to pack/concat/unpackRR
* Implement a UnpackRRWithHeader() e.g:
```
func UnpackRRWithHeader(h RR_Header , msg []byte, off int) (rr RR, off1 int, err error) {
```
* make typeToUnpack and the individual unpack function public.

I wonder if there is any reasons (but having a smaller API) to keep those private and if they could just be made public. If not, what do you think is a reasonable approach.

**Comment by miekg** [comment]
I think `UnpackRRWithHeader` is the cleanest way to implement this. I don't really want to export all the unpack/packs just for this usecase

**Comment by chantra** [comment]
@miekg sorry for taking so long... but finally got around to apply the change in #643 

Coverage reports less coverage after this change... but really, all this change does is to split the original `UnpackRR` in 2.
