### ISSUE TITLE
TSIG verification via nsupdate failing "dns: bad signature"

### ISSUE THREAD

**Issue by ennetech** [miekg/dns#640]
Hello!
I have a simple DNS server inplace and i'm using this piece of code to implement tsig validation:
```
secret := conf.SystemConfig.TsigKey
logger.Info("USING THIS KEY "+secret)
pack, _ := r.Pack()
err = dns.TsigVerify(pack, secret, "", false)
if err != nil {
	logger.Error("TSIG VERIFICATION FAILED " + err.Error())
} else {
	logger.Info("TSIG VERIFICATION SUCCEDEED")
}
```
(https://github.com/ennetech/consul-dns/blob/master/pkg/dns/dns.go Line 70)

When sending this update (nsupdate -v update):
```
debug yes
key hmac-md5:mydomain.com. {{ conf.SystemConfig.TsigKey }}
server 192.168.1.101 53535 // Local server
zone mydomain.com.
update add snd.mydomain.com. 300 A 127.0.0.1
send
```
I receive an error "dns: bad signature", if i substitute "snd.mydomain.com." with "snd" the TSIG verification passes but the update request is wrong

I am generating the keys this way:
```
	// hmac-md5
	hmacmd5 := hmac.New(md5.New, []byte(generatingSecret))
	res += "hmac-md5: " + base64.StdEncoding.EncodeToString(hmacmd5.Sum(nil))
	// hmac-sha1
	hmacsha1 := hmac.New(sha1.New, []byte(generatingSecret))
	res += "hmac-sha1: " + base64.StdEncoding.EncodeToString(hmacsha1.Sum(nil))
	// hmac-sha256
	hmacsha256 := hmac.New(sha256.New, []byte(generatingSecret))
	res += "hmac-sha256: " + base64.StdEncoding.EncodeToString(hmacsha256.Sum(nil))
	// hmac-sha512
	hmacsha512 := hmac.New(sha512.New, []byte(generatingSecret))
	res += "hmac-sha512: " + base64.StdEncoding.EncodeToString(hmacsha512.Sum(nil))
```

I am experiencing the same error with letsencrypt certbot but not with hashicorp terraform
RFC2136+RFC2845

**Comment by andrewtj** [comment]
> I receive an error "dns: bad signature", if i substitute "snd.mydomain.com." with "snd" the TSIG verification passes but the update request is wrong

This could be caused by `pack, _ := r.Pack()` not packing the message the exact same way `nsupdate` did. Comparing what goes over the wire (and possibly toggling `Msg.Compress`) might provide some further clues. (Short on time so forgive the brevity of this response.)

**Comment by ennetech** [comment]
I can just paste the .String() output of the incoming messages (nsupdate, terraform)? Or there is a better way?

**Comment by andrewtj** [comment]
Your [solution](https://github.com/ennetech/consul-dns/commit/68faada3ca13dda85c64840ffa7e36eaa948188a) probably works most of the time but if this package and the client sending the update don't compress things the same way it'll fail.

There is a bit of an API gap here in that I don't think you can get the raw bytes of a message from the server in this package (which is geared toward using [`Server`'s TsigSecret map](https://godoc.org/github.com/miekg/dns#Server)). It might be best to replace `Server` with something crafted specifically for your use-case.

**Comment by ennetech** [comment]
Thank you for the reply but i don't think i will write a server implementation from scratch just for this, as long as terraform, certbot and nsupdate all work i can tollerate the 'hacked' solution
