### ISSUE TITLE
cannot find package "context"

### ISSUE THREAD

**Issue by 6543** [miekg/dns#641]
-> https://github.com/6543/dns/commit/ac9ecdee6bb46bedc7b77a9f37ef15627b11b738

is this solution good enouth for you?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] cannot find package "co..." ]
>-> https://github.com/6543/dns/commit/ac9ecdee6bb46bedc7b77a9f37ef15627b11b738
>
>is this solution good enouth for you?

no, context has moved to the std lib. You should probably upgrade your Go 
version to at least 1.8 (i believe, maybe 1.9)

**Comment by 6543** [comment]
thanks 1.9 fix this too :+1:
