### ISSUE TITLE
TSIG on Transfer.Out()?

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/dns#644]
I am writing a DNS server that will mostly just handle zone transfers (AXFR and IXFR).
I am having trouble on the TSIG part. Is it possible to send the TSIG record using the Transfer.Out() interface?

Thanks in advance

**Comment by andrewtj** [comment]
Did you work this out?

**Comment by andrewtj** [comment]
I'm closing this as I assume it's gone stale. Please reopen if I'm mistaken.

**Comment by cesarkuroiwa** [comment]
Hi, sorry for the delay.
Actually, I couldn't make it work the TSIG part with the Transfer.Out interface, so I simply started sending the response packets the usual way, with WriteMsg(msg)

**Comment by miekg** [comment]
That won't work with multiple envelope axfr messages. I think you got lucky.
