### ISSUE TITLE
UDP OOB failures on ARM under QEMU

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#660]
As first noted in https://github.com/miekg/dns/pull/653#issuecomment-377780398, something is wrong on ARM. This was what I discovered in https://github.com/miekg/dns/pull/653#issuecomment-377835878 and https://github.com/miekg/dns/pull/653#issuecomment-377836333.

Kernel and Golang version:
```
$ uname -a
Linux thrax 4.15.13-300.fc27.x86_64 #1 SMP Mon Mar 26 19:06:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ go version
go version go1.10 linux/amd64
```

Running with:
```
GOARCH=arm go test -c .
qemu-arm-static ./dns.test
```

Gives this line interspersed throughout the output:
> Unsupported ancillary data: 41/50

It also gives this ~interesting~ crash, ~I'm pretty sure something is very wrong with the OOB handling on ARM~:
```
--- FAIL: TestParseDstFromOOB (0.00s)
        udp_test.go:82: failed to parse IPv4 in IPv6: <nil>
        udp_test.go:92: failed to parse IPv6: <nil>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20cbb4]

goroutine 587 [running]:
testing.tRunner.func1(0x10984000)
        /usr/lib/golang/src/testing/testing.go:742 +0x264
panic(0x38ced8, 0x5a5268)
        /usr/lib/golang/src/runtime/panic.go:505 +0x204
github.com/tmthrgd/dns/vendor/golang.org/x/net/ipv4.(*ControlMessage).Parse(0x10964060, 0x10ad0040, 0x20, 0x20, 0x0, 0x0)
        /home/tom/go/src/github.com/tmthrgd/dns/vendor/golang.org/x/net/ipv4/control.go:90 +0x2a4
github.com/tmthrgd/dns.parseDstFromOOB(0x10ad0040, 0x20, 0x20, 0x1096ef58, 0x1, 0x1)
        /home/tom/go/src/github.com/tmthrgd/dns/udp.go:68 +0xb4
github.com/tmthrgd/dns.TestParseDstFromOOB(0x10984000)
        /home/tom/go/src/github.com/tmthrgd/dns/udp_test.go:99 +0x318
testing.tRunner(0x10984000, 0x3e6850)
        /usr/lib/golang/src/testing/testing.go:777 +0xb0
created by testing.(*T).Run
        /usr/lib/golang/src/testing/testing.go:824 +0x250
```

The crash doesn't occur on arm64/aarch64, but the "Unsupported ancillary data" lines do.

This is reproducible on master (83c435cc65d2862736428b9b4d07d0ab10ad3e4d).

**Comment by tmthrgd** [comment]
Both errors are completely unchanged by updating the vendored code (x/net).

**Comment by tmthrgd** [comment]
For reference:

```
$ dnf info qemu-user-static
Installed Packages
Name         : qemu-user-static
Epoch        : 2
Version      : 2.10.1
Release      : 3.fc27
Arch         : x86_64
Size         : 116 M
Source       : qemu-2.10.1-3.fc27.src.rpm
Repo         : @System
From repo    : updates
Summary      : QEMU user mode emulation of qemu targets static build
URL          : http://www.qemu.org/
License      : GPLv2+ and LGPLv2+ and BSD
Description  : QEMU is a generic and open source processor emulator which achieves a good
             : emulation speed by using dynamic translation.
             : 
             : This package provides the user mode emulation of qemu targets built as
             : static binaries
```

**Comment by tmthrgd** [comment]
3710182f0f8db59ebf80c44944deb17511630ebb is known good. dea4cb300a66d7034349b02e0156ea325c876e9c is known bad. 3710182f0f8db59ebf80c44944deb17511630ebb is the parent of dea4cb300a66d7034349b02e0156ea325c876e9c.

Running the test under ARM on dea4cb300a66d7034349b02e0156ea325c876e9c gives:
> Unsupported ancillary data: 0/8

**Comment by tmthrgd** [comment]
Interestingly, it occurs even if you make `correctSource` into a no-op.

```go
func correctSource(oob []byte) []byte {
	return oob
}
```

**Comment by tmthrgd** [comment]
It even occurs if you set `oob` to `nil` for `WriteMsgUDP`:

```go
// WriteToSessionUDP acts just like net.UDPConn.WriteTo(), but uses a *SessionUDP instead of a net.Addr.
func WriteToSessionUDP(conn *net.UDPConn, b []byte, session *SessionUDP) (int, error) {
	oob := correctSource(session.context)
	_ = oob
	n, _, err := conn.WriteMsgUDP(b, nil, session.raddr)
	return n, err
}
```

**Comment by tmthrgd** [comment]
Oh, oh, oh, now this is truly bizarre. The errors actually have *nothing* to do with `WriteMsgUDP`, they're surfacing from `ReadMsgUDP`.

If `oob` is `nil` in the call to `ReadMsgUDP` the errors go away!
```go
// ReadFromSessionUDP acts just like net.UDPConn.ReadFrom(), but returns a session object instead of a
// net.UDPAddr.
func ReadFromSessionUDP(conn *net.UDPConn, b []byte) (int, *SessionUDP, error) {
	oob := make([]byte, 40)
	n, oobn, _, raddr, err := conn.ReadMsgUDP(b, nil)
	if err != nil {
		return n, nil, err
	}
	return n, &SessionUDP{raddr, oob[:oobn]}, err
}
```

```
$ GOARCH=arm go test -c . && qemu-arm-static ./dns.test
--- FAIL: TestTimeout (0.01s)
        client_test.go:528: exchange took longer 12.12885ms than specified Timeout 11ms
--- FAIL: TestSetUDPSocketOptions (0.00s)
        udp_test.go:52: empty session context: &{0x108924e0 []}
--- FAIL: TestCorrectSource (0.00s)
        udp_test.go:120: unexpected oob for ipv4 address: []
        udp_test.go:129: unexpected oob for IPv6 address: []
FAIL
```

(I'm skiping `TestParseDstFromOOB` on ARM, because I think might just be caused by hard coding the OOB data).

**Comment by tmthrgd** [comment]
I missed https://github.com/qemu/qemu/blob/f184de7553272223d6af731d7d623a7cebf710b5/linux-user/syscall.c#L1976. That line is in `host_to_target_cmsg` which is called from `do_sendrecvmsg_locked` when `send` is false (*i.e.* when receiving), which is called (with `send = 0`) from `do_sendrecvmsg`, which is called for `TARGET_SYS_RECVMSG` from `do_socketcall` and for `TARGET_NR_recvmsg` from `do_syscall`.

**Comment by tmthrgd** [comment]
I suspect this is just a bug in QEMU that only occurs when running ARM binaries. I don't *think* this is a real problem and I don't *think* it will ever happen outside of QEMU.

Is there anyone who could test on an actual ARM device and confirm?

**Comment by tmthrgd** [comment]
The panic is an easy one to solve in the end. The hard-coded OOB data in `TestParseDstFromOOB` and `TestCorrectSource` use 64-bit lengths, but 32-bit architectures need 32-bit lengths. x/net is interpreting that incorrectly and crashing.

That can either be fixed by using different OOB hard-coded data for 32/64-bit, or just skipping the tests on unsupported architectures.

**Comment by miekg** [comment]
This can be closed now, no?

**Comment by tmthrgd** [comment]
@miekg The panic has been fixed, and I don’t believe the other is anything but an annoying QEMU bug. So yeah I think this can be closed.

Has anyone been able to run the test suite on an ARM machine to verify?

**Comment by andrewtj** [comment]
Seems to work:
```
% uname -a
Linux raspberrypi 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux
% go test github.com/miekg/dns
ok  	github.com/miekg/dns	151.459s
go test github.com/miekg/dns  258.23s user 7.37s system 81% cpu 5:26.99 total
```
