### ISSUE TITLE
DNS configuration over a VPN

### ISSUE THREAD

**Issue by jkemp101** [miekg/dns#665]
I'm a little outside my wheelhouse here (don't know a lot about Go) but I am wondering if there were any plans to enhance the client resolution process to include client DNS configurations beyond `resolv.conf` (I'm specifically concerned with OS X).  My particular issue is resolving some domains against specific DNS servers that are configured by VPN client software.  On a Mac you need to run `scutil -dns` to see the true DNS configuration since a lot isn't necessarily in `resolv.conf`.

Many projects like the ease of native Go libraries for a number of reasons including simple cross compiling versus enabling cgo which solves the problem by using the native C resolution libraries.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] DNS configuration over ..." ]
>I'm a little outside my wheelhouse here (don't know a lot about Go) but I am wondering if there were any plans to enhance the client resolution process to include client DNS configurations beyond `resolv.conf` (I'm specifically concerned with OS X).  My particular issue is resolving some domains against specific DNS servers that are configured by VPN client software.  On a Mac you need to run `scutil -dns` to see the true DNS configuration since a lot isn't necessarily in `resolv.conf`.
>
>Many projects like the ease of native Go libraries for a number of reasons including simple cross compiling versus enabling cgo which solves the problem by using the native C resolution libraries.

This is out of scope for this library; you can send a DNS query to any address. 
There is just a convience function to read config from /etc/resolv.conf.


/Miek

--
Miek Gieben

**Comment by jkemp101** [comment]
@miekg Would you expect an external library (either 3rd party or native Go) to determine the list of DNS servers to query for a particular hostname?  It seems like a DNS client isn't complete unless it is able to figure that out.  For instance to know that `x.example1.com` should be queried at `1.1.1.1` but `x.example2.com` should be queried at `2.2.2.2`.

**Comment by andrewtj** [comment]
If you're after a platform-native connection experience on OS X, getting a connection via the high-level socket APIs and then extracting an fd is generally the way to go.

**Comment by jkemp101** [comment]
I took another look at `clientconfig.go` and it is pretty lightweight, doesn't even try to assume where `resolv.conf` might reside.  So as you said probably not the best place for this type of thing.
