### ISSUE TITLE
NSEC3 hashed owner calculation issue 

### ISSUE THREAD

**Issue by shadrick** [miekg/dns#676]
Hi, i'm on `1f2aa4c` and have experienced issues with nsec3 name matching. Let me exemplify.
```
/// one of the NSEC3s returned by the TLD zone to (for example) <microsoft.com IN NS> (with DO flag)
rr, _ := dns.NewRR("CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM6QPQR81H5M9A  NS SOA RRSIG DNSKEY NSEC3PARAM")
fmt.Printf("[%v]\n", rr.(*dns.NSEC3).Match("com."))
/// outputs false
fmt.Printf("[%s]\n", dns.HashName("com.", 1, 0, ""))
/// outputs CK0POJMG874LJREF7EFN8430QVIT8BSM
```

The issue, as i see it, is with passing the decorative `-` as salt (meaning, no salt is used) to the hex packer routine.

Best regards!

**Comment by tmthrgd** [comment]
@shadrick Would you mind clarifying what behaviour you expect to see here is?

**Comment by shadrick** [comment]
Sure thing.
I would expect to see (and would logically be expected) to see a `true` return of the match function.
The problem lies in passing the decorative `-` string to the `HashName` function instead of an empty string as salt value. It the propagates it down to the hex decoder, which gets confused and instead of the result it returns an empty string and an error. This pattern taints the nsec3.Cover and .Match functions.
In this small test function it's clear that if you call the hashing function with an actual empty string it produces the correct output. A quick check against `"-"` in `HashName` should fix it;

```
func TestIssue676(t *testing.T) {
	rr, _ := dns.NewRR("CK0POJMG874LJREF7EFN8430QVIT8BSM.com. 86400 IN NSEC3 1 1 0 - CK0Q1GIN43N1ARRC9OSM6QPQR81H5M9A  NS SOA RRSIG DNSKEY NSEC3PARAM")
	control := "CK0POJMG874LJREF7EFN8430QVIT8BSM"
	nsec3, _ := rr.(*dns.NSEC3)

	t.Logf("Does NSEC3 match [com.]? -> [%v]", nsec3.Match("com."))
	t.Logf("Should NSEC3 match [com.]? -> [%v]", control == dns.HashName("com.", 1, 0, ""))
	if !nsec3.Match("com.") {
		t.Fail()
	}
}
```

**Comment by shadrick** [comment]
Confirmed fix.
