### ISSUE TITLE
Add dns.Equal(r1 RR, r2 RR) bool function

### ISSUE THREAD

**Issue by miekg** [miekg/dns#679]
Add an equal function that determines if two rr's are equal from a dns protocol standpoint. This should exclude the TTL, but include the rest of the header and the rdata.

This should make dns.Dedup a lot cheaper and can be used by projects to not add duplicate RRs to a packet.

We can generate most of this function. It should mostly avoid any allocations.

**Comment by gibson042** [comment]
I really like the idea, but `Equal` is not the best name for a function that ignores TTL. Referring to [RFC 2181](https://tools.ietf.org/html/rfc2181#section-5), what about something like `Duplicates` or `IsDuplicate`?

A related function that only checks type and rdata would be useful as well (e.g., `RdataEqual(r1 RR, r2 RR)`).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Add dns.Equal(r1 RR..." ]
>I really like the idea, but `Equal` is not the best name for a function that ignores TTL. Referring to [RFC 2181](https://tools.ietf.org/html/rfc2181#section-5), what about something like `Duplicates` or `IsDuplicate`?
>
>A related function that only checks type and rdata would be useful as well (e.g., `RdataEqual(r1 RR, r2 RR)`).

agreed.

I do like Equal though because it you probably looks for something with that 
name..?


/Miek

--
Miek Gieben

**Comment by fastest963** [comment]
Yeah, I agree `Equal` is weird considering it ignores TTL. An alternative idea is that something that wants to Dedup can set the TTL to 0 on both before passing it into `Equal` if it doesnt want those to invalidate the equality.
