### ISSUE TITLE
Transfer In and Out need some tests and polish

### ISSUE THREAD

**Issue by jeffbean** [miekg/dns#685]
Based on trying to unit test the Transfer In I ran into issues when doing so. The surrounding code to Transfer looks to be known to be a work in progress with TODO's. `Think we need to away to stop the transfer` 

I am getting i/o read timeouts based on the tests seen here. https://raw.githubusercontent.com/jeffbean/dns/dffc41a423f896c0b7cf9da6def2b561890495c4/xfr_test.go

I have not invested to much time looking at solutions but the test code shows  how flaky the `transfer.In` is without better coordination of the connection. This issue will serve as a tracking task for myself as well on work produced to fix these issues around flaky results.

My forked branch can be found here https://github.com/jeffbean/dns/tree/adding-xfr-tests 

and to reproduce the timeouts run `go test ./... -count 50`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Transfer In and Out nee..." ]
>Based on trying to unit test the Transfer In I ran into issues when doing so. The surrounding code to Transfer looks to be known to be a work in progress with TODO's. `Think we need to away to stop the transfer`
>
>I am getting i/o read timeouts based on the tests seen here. https://raw.githubusercontent.com/jeffbean/dns/dffc41a423f896c0b7cf9da6def2b561890495c4/xfr_test.go
>
>I have not invested to much time looking at solutions but the test code shows  how flaky the `transfer.In` is without better coordination of the connection. This issue will serve as a tracking task for myself as well on work produced to fix these issues around flaky results.
>
>My forked branch can be found here https://github.com/jeffbean/dns/tree/adding-xfr-tests
>
>and to reproduce the timeouts run `go test ./... -count 50`

Haven't run that tests, but some cleanups and possibly fixes are welcome of 
course.

Note that in my use of CoreDNS as a secondary this seems to work quite well.

**Comment by jeffbean** [comment]
I think it might even be the testing setup using Transfer itself as the server response. I will try to work on a PR for `xfr.go` itself to get it reliably testable. It works fine in production so just getting testability is important as well.

**Comment by miekg** [comment]
This issue looks stale, so I'll close it soon.

**Comment by miekg** [comment]
we've merged a thing referencing this, closing
