### ISSUE TITLE
Client / Dialer timeout is always overwritten by the Client writeTimeout

### ISSUE THREAD

**Issue by fturib** [miekg/dns#689]
It seems worthless to set the net.Dialer Timeout, as it is overwritten in the client.Dial(...) function by the client's WriteTimeout.

https://github.com/miekg/dns/blob/master/client.go, at line 88:

```
/ Dial connects to the address on the named network.
func (c *Client) Dial(address string) (conn *Conn, err error) {
	// create a new dialer with the appropriate timeout
	var d net.Dialer
	if c.Dialer == nil {
		d = net.Dialer{}
	} else {
		d = net.Dialer(*c.Dialer)
	}
	d.Timeout = c.getTimeoutForRequest(c.writeTimeout()) . <===== HERE !
        ....
        conn = new(Conn)
	if useTLS {
		conn.Conn, err = tls.DialWithDialer(&d, network, address, c.TLSConfig)
	} else {
		conn.Conn, err = d.Dial(network, address)
	}
        ...
}
```

Is that expected behavior ?
If not, what was the reason of this instruction ?

NOTE: this is coming from a refactoring that aimed to introduce a timeout for the Dialer ! See https://github.com/miekg/dns/pull/511

**Comment by tmthrgd** [comment]
Without that line the struct level timeouts wouldn’t work for `Dial`. I can’t see any reason why that line couldn’t be wrapped in a `if d.Timeout != 0` though. Do you want to open a PR for that?

**Comment by fturib** [comment]
Somehow, c.Dial.timeout is already part of computation in getTimeoutForRequest(), but only if lower than timeout provided by the client.

What I think make sense is to replace `c.getTimeoutForRequest(c.writeTimeout())` by `c.getTimeoutForRequest(c.dialTimeout())`. At least we'll be able to program the dialTimeout without involving the read or write timeout.

And (I think) that make more sense to use dialTimeout than writeTimeout here ...

**Comment by miekg** [comment]
shouldn't we just move that
~~~
d.Timeout = c.getTimeoutForRequest(c.writeTimeout()) . <===== HERE !
~~~ 
line into the `c.Dialer == nil` case?

**Comment by fturib** [comment]
That make sense for me and would work for me in the case c.Dialer is nil.
If the other case, do we consider that whatever value of c.Dialer.timeout or c.Dialer.deadline, it is overriding the timeout valued of Client ?

See the comments about timeout of the Client.
```
	// Timeout is a cumulative timeout for dial, write and read, defaults to 0 (disabled) - overrides DialTimeout, ReadTimeout,
	// WriteTimeout when non-zero. Can be overridden with net.Dialer.Timeout (see Client.ExchangeWithDialer and
	// Client.Dialer) or context.Context.Deadline (see the deprecated ExchangeContext)

```

Also, should we keep `c.getTimeoutForRequest(c.writeTimeout())` or move to `c.getTimeoutForRequest(c.dialTimeout())` that makes more sense here ?
