### ISSUE TITLE
Vendor libs update to support darwin/arm64

### ISSUE THREAD

**Issue by tnako** [miekg/dns#690]
Hello,

I have error on build for darwin/arm64:
`# github.com/miekg/dns/vendor/golang.org/x/net/internal/socket
/Users/chado/go/src/github.com/miekg/dns/vendor/golang.org/x/net/internal/socket/cmsghdr.go:9:10: undefined: cmsghdr
`

The same error and fix - https://github.com/golang/go/issues/22301

As hotfix I remove dir "vendor/golang.org/x/net" on my mac

Thanks

**Comment by andrewtj** [comment]
Would you like to a send a PR updating the vendored code?

(Related: #655)
