### ISSUE TITLE
Vendor not using latest versions?

### ISSUE THREAD

**Issue by h8liu** [miekg/dns#695]
The vendor folders do not seem to use the latest of `golang.org/x/net` and `golang.org/x/crypto`. Is there a specific reason for that?

I am asking because some of the packages are vendor'ed in an incomplete fashion. I tried `dep ensure` with latest public HEADs but cannot reproduce that.

For example:
```
go build github.com/miekg/dns/vendor/golang.org/x/crypto/ssh
```
does not build, gets:
```
src/github.com/miekg/dns/vendor/golang.org/x/crypto/ssh/cipher.go:21:2: use of internal package not allowed
```
because the `internal` package is missing.

Thanks.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Vendor not using HEAD? ..." ]
>The vendor folders do not seem to use the latest of `golang.org/x/net` and `golang.org/x/crypto`. Is there a specific reason for that?
>
>I am asking because some of the packages are vendor'ed in an incomplete fashion. I tried `dep ensure` with latest public HEADs but cannot reproduce that.
>
>For example:
>```
>go build github.com/miekg/dns/vendor/golang.org/x/crypto/ssh
>```
>does not build, gets:
>```
>src/github.com/miekg/dns/vendor/golang.org/x/crypto/ssh/cipher.go:21:2: use of internal package not allowed
>```
>because the `internal` package is missing.

why would you even do the above?

**Comment by h8liu** [comment]
> why would you even do the above?

For context, this is triggered by [smallrepo.com](https://smallrepo.com), where it tries to build all go language packages in the repo. `github.com/miekg/dns` has had no issue on building until the `vendor` got updated.

Example build log:
https://smallrepo.com/builds/20180606-174438-cf44e9db

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Vendor not using la..." ]
>> why would you even do the above?
>
>For context, this is triggered by [smallrepo.com](https://smallrepo.com), where it tries to build all go language packages in the repo. `github.com/miekg/dns` has had no issue on building until the `vendor` got updated.

sure, but why even build vendor. I don't understand.

https://github.com/miekg/dns/pull/694 made things work (apparently, this vendor 
stuff is always hard to test). So why should we update again?

/Miek

--
Miek Gieben

**Comment by h8liu** [comment]
> sure, but why even build vendor. I don't understand.

It's fine.. the build engine is different.. or I can also just blacklist the vendor'ed package.

> #694 made things work (apparently, this vendor stuff is always hard to test). So why should we update again?

I assume it is often best to use the latest version, but it is your choice after all. :)
