### ISSUE TITLE
When multi questions in msg, the Exchange() call always timeout.

### ISSUE THREAD

**Issue by Sherlock-Holo** [miekg/dns#700]
When I add multi `dns.Question` in a msg and call `Exchange` , it says 

> 2018/06/11 21:23:36 read udp 192.168.42.181:53874->114.114.114.114:53: i/o timeout

I have heard some guys said some devices don't support multi questions dns query, so a lot of dns server not support multi questions dns query.

wireshark says the dns query packet created by `miekg/dns` is correct, so it's not the lib fault, right?

**Comment by andrewtj** [comment]
Yeah it's probably not this package.

In practice DNS is limited to a single question because a question may be answered in part by bits in the message header and there's only one message header.

**Comment by wtoorop** [comment]
However, with DNSSEC answers, all status conveyed in the header could also be deduced from the RRs (i.e. NXDOMAIN, authenticity etc).  So, when all DNS would be DNSSEC signed, multiple questions in one DNS message would be viable :)

**Comment by miekg** [comment]
Multiple questions was a fine idea, but as Andrew said, doesn't work in
practice. Consider it unsupported.

**Comment by wtoorop** [comment]
Sure, I just wanted to remark that in theory, when all zones in the whole world would be DNSSEC signed, and we would ignore support in existing software, multiple questions in one message could be viable.

**Comment by miekg** [comment]
Yes :) and you've also supplied the reasons we won't see this happening in
our lifetimes :)
