### ISSUE TITLE
$GENERATE requires all modifier components

### ISSUE THREAD

**Issue by 4a6f656c** [miekg/dns#702]
The BIND `$GENERATE` directive allows an optional modifier - the modifier specifies an offset, an optional width and an optional type (aka base):
```
{ offset [ ,width [ ,type ] ] }
```
For further details see [here](http://www.zytrax.com/books/dns/ch8/generate.html) or [here](https://ftp.isc.org/isc/bind9/cur/9.9/doc/arm/Bv9ARM.ch06.html#generate_directive).

The `$GENERATE` parsing implemented by this package does not allow for the width and/or type to be optional, instead requiring all three components of the modifier. This means that the following (which is valid for BIND), will fail to parse correctly:
```
$GENERATE 10-12 foo${0,2} IN A 127.0.0.$
```

**Comment by miekg** [comment]
closed via #703
