### ISSUE TITLE
DoH support

### ISSUE THREAD

**Issue by miekg** [miekg/dns#707]
I'm coming back on the need of having DoH support directly in this library.

HTTP(/2) is a different beast and we should probably defer those implementation bits to net/http and friends.

What we do want to support is creating a Get or Post request and than handing it off. 

Connection re-use and all kinds of complication could then be left out of this libary as it (mostly) deals with DNS binary conversions.

DNS over TCP (DoT) remains an interesting one; because that requires some of the bits (connection reuse, etc). and is easier to support because it is a simpler protocol.

@tmthrgd wdyt?

**Comment by tmthrgd** [comment]
@miekg I’m not sure I agree. Everything connection-reuse related is entirely internal to net/http, as is everything HTTP(2). The transports that have complications regarding reuse are DNS-over-TLS and DNS-over-TCP.

In my eyes, the complication with DOH in this library comes entirely down to the existing API, which it doesn’t match up quite perfectly to.

If DOH support were to be removed from this library, I wouldn’t suggest adding any request creation functions in its place. It’s mostly trivial to construct a DOH request.

I think there’s value in having support for a secure transport that seems likely to gain adoption and use. (Granted there is no server support yet).

**Comment by miekg** [comment]
> If DOH support were to be removed from this library, I wouldn’t suggest adding any request creation functions in its place. It’s mostly trivial to construct a DOH request.

I agree with this.

As to "it doesn't fit the API", that's true; but that requires a lot of work and I don't think anyone has time for that.
If starting implementing DoH client support in CoreDNS, and there is nothing that I wanted from this lib (unless it had a perfect implementation).

So, until there is a plan and time to properly implement a `Client2`, DoH should be dropped. The lack symmetry with the server is also jarring in my mind :)

**Comment by tmthrgd** [comment]
With #800 merged, this issue seems fixed.

**Comment by shynome** [comment]
if anyone need doh-client support, you can use my lib [doh client](https://github.com/shynome/doh-client) and this lib to query dns over https
```go
package main

import (
	"fmt"

	"github.com/miekg/dns"
	"github.com/shynome/doh-client"
)

func main() {
	q := dns.Question{
		Name:   dns.Fqdn("remoon.net"),
		Qtype:  dns.TypeA,
		Qclass: dns.ClassINET,
	}
	m := &dns.Msg{
		MsgHdr:   dns.MsgHdr{Id: dns.Id(), Opcode: dns.OpcodeQuery, RecursionDesired: true},
		Question: []dns.Question{q},
	}
	co := &dns.Conn{Conn: doh.NewConn(nil, nil, "1.1.1.1")}
	if err := co.WriteMsg(m); err != nil {
		panic(err)
	}
	m, err := co.ReadMsg()
	if err != nil {
		panic(err)
	}
	if len(m.Answer) == 0 {
		panic("answer length must greater than 0")
	}
	fmt.Println(m.Answer)
}

```

**Comment by phuslu** [comment]
Hello I am fastdns author who come from google search, if anyone is interested in an efficient DoH client, here is an example:
```go
package main

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"time"

	"github.com/phuslu/fastdns"
)

func main() {
	doh := "https://1.1.1.1/dns-query"

	client := &fastdns.Client{
		Addr: doh,
		Dialer: &fastdns.HTTPDialer{
			Endpoint:  func() (u *url.URL) { u, _ = url.Parse(doh); return }(),
			UserAgent: "fastdns/0.9",
			Transport: http.DefaultTransport,
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	fmt.Println(client.LookupNetIP(ctx, "ip", "cloud.phus.lu"))
	fmt.Println(client.LookupHTTPS(ctx, "cloud.phus.lu"))
}
```
