### ISSUE TITLE
Add CachedLen()

### ISSUE THREAD

**Issue by miekg** [miekg/dns#709]
Think aloud here...

PR #708 tries to fit a message in a buffer; this is expensive because of compression when calling the Len() function on a message.

Len() in general is expansive because it goes over the entire message looking for compression points, so O(n) and it needs a map to store all that info, so it generates garbage as well.

What if we cached the length and map in Msg... If you are just adding RR(sets) we only need to count the new ones. This only works if you layer and message correctly; i.e answer first and authority and then a potential additional. Just would make Len() a lot cheaper. Of course it can be called `Len()` so we need something else, `CachedLen()`.

I think this can even work if you remove RRs, at least if you start at the end; the only difficulty there is know how long the RR will be because it may have been compressed (meaning you need to do some lookups). Removing from the ends works because compression pointers can only point forward.

**Comment by tmthrgd** [comment]
In the context of #708 and after the merging of #833, `msgLenWithCompressionMap` is a really simple function so it should be possible to implement message truncation really efficiently without needing a `CachedLen` method or to store any state on `Msg`.

What would a good algorithm for truncating messages be? Is the one in [coredns](https://github.com/coredns/coredns/blob/bf67c9134c47dd1e0655a49b57a9113a6089ff48/request/request.go#L237) suitable? I'll have a go at implementing this if so.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Add CachedLen() (#7..." ]
>In the context of #708 and after the merging of #833, `msgLenWithCompressionMap` is a really simple function so it should be possible to implement message truncation really efficiently without needing a `CachedLen` method or to store any state on `Msg`.
>
>What would a good algorithm for truncating messages be? Is the one in [coredns](https://github.com/coredns/coredns/blob/bf67c9134c47dd1e0655a49b57a9113a6089ff48/request/request.go#L237) suitable? I'll have a go at implementing this if so.

Yes, that was the best I could come up with.
Also note: https://github.com/coredns/coredns/pull/2333/files


/Miek

--
Miek Gieben

**Comment by tmthrgd** [comment]
I'm not sure how I can incorporate `SizeAndDo` because it relies on having access to the request message:

https://github.com/coredns/coredns/blob/bf67c9134c47dd1e0655a49b57a9113a6089ff48/request/request.go#L194-L196

**Comment by tmthrgd** [comment]
Ignore that, I figured it out and I'll send a PR shortly.

**Comment by miekg** [comment]
CLosing this with infeasible. The truncate impl where discussion in #854 is another angle of attack.
