### ISSUE TITLE
Support non-standard BIND comments in zone file parser?

### ISSUE THREAD

**Issue by carlpett** [miekg/dns#710]
It appears BIND allows non-RFC1035 comments in zone files, `#` and `//` also work (but not `/* ... */`). `dns.ParseZone` does not treat these as comments, so parsed records such as `#foo.example.com` turn up when parsing zones in the wild.
Would it be acceptable to add support for these even though it (I guess) is a spec violation?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Support non-standard BI..." ]
>It appears BIND allows non-RFC1035 comments in zone files, `#` and `//` also work (but not `/* ... */`). `dns.ParseZone` does not treat these as comments, so parsed records such as `#foo.example.com` turn up when parsing zones in the wild.
>Would it be acceptable to add support for these even though it (I guess) is a spec violation?

that's an interesting question, because `#foo.example.com` is a valid name. So 
I'm leaning against allowing this, because you then *also* need to introduce 
some escaping to make that valid again.
So `sed -i` will need to be your friend here, I'm afraid.

**Comment by carlpett** [comment]
Well, that settles it :)
Thanks! (I'm ever surprised by what is allowed by spec vs allowed in principle)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Support non-standar..." ]
>Well, that settles it :)
>Thanks! (I'm ever surprised by what is allowed by spec vs allowed in principle)

yeah, the whole be lenient in what you accept really backfired for DNS.

**Comment by carlpett** [comment]
Armed with this new knowledge, I had to do some testing, and it turns out BIND does the right thing (perhaps not that surprising, after all). People just assume # is a comment, since `foo.example.com` does resolve if you add a # in front, but BIND does resolve `#foo.example.com`...
