### ISSUE TITLE
Accessing tls.ConnectionState from ResponseWriter

### ISSUE THREAD

**Issue by mingtaoy** [miekg/dns#711]
The `ResponseWriter` currently exposes some information about the connection, such as the `LocalAddr()` of the server and the `RemoteAddr()` of the client.

Given that the DNS server supports TLS connections, it may be helpful to access the `tls.ConnectionState` of the TLS connection. Handlers can utilize this information for logging purposes, or to craft a different response if it is known that the request was made over a secure connection.

I suggest adding the following method to `ResponseWriter`

```
// ConnectionState returns the the tls.ConnectionState information associated with
// the request, if it was made over a TLS connection. Otherwise, returns nil
TLSConnectionState() *tls.ConnectionState
```

Would be happy to send a PR if there are no objections to extending the ResponseWriter interface. Any comments/objections?

/cc @chantra

**Comment by chantra** [comment]
@miekg do you have any opinion on this?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Accessing tls.Connectio..." ]
>The `ResponseWriter` currently exposes some information about the connection, such as the `LocalAddr()` of the server and the `RemoteAddr()` of the client.
>
>Given that the DNS server supports TLS connections, it may be helpful to access the `tls.ConnectionState` of the TLS connection. Handlers can utilize this information for logging purposes, or to craft a different response if it is known that the request was made over a secure connection.
>
>I suggest adding the following method to `ResponseWriter`
>
>```
>// ConnectionState returns the the tls.ConnectionState information associated with
>// the request, if it was made over a TLS connection. Otherwise, returns nil
>TLSConnectionState() *tls.ConnectionState
>```
>
>Would be happy to send a PR if there are no objections to extending the ResponseWriter interface. Any comments/objections?
>
>/cc @chantra

How does the http package do this?

**Comment by chantra** [comment]
*tls.ConnectionState is available through both http.Request and http.Response:

https://golang.org/pkg/net/http/#Request
```
        // TLS allows HTTP servers and other software to record
        // information about the TLS connection on which the request
        // was received. This field is not filled in by ReadRequest.
        // The HTTP server in this package sets the field for
        // TLS-enabled connections before invoking a handler;
        // otherwise it leaves the field nil.
        // This field is ignored by the HTTP client.
        TLS *tls.ConnectionState
```

https://golang.org/pkg/net/http/#Response
```
        // TLS contains information about the TLS connection on which the
        // response was received. It is nil for unencrypted responses.
        // The pointer is shared between responses and should not be
        // modified.
        TLS *tls.ConnectionState
```

**Comment by chantra** [comment]
@miekg, Based on HTTP interface, how do you feel in having a `TLS() *tls.ConnectionState` as part of `ResponseWriter`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Accessing tls.Conne..." ]
>@miekg, Based on HTTP interface, how do you feel in having a `TLS() *tls.ConnectionState` as part of `ResponseWriter`

You can't extend the ResponseWriter's interface. This needs to be another interface 
that can be implemented by responsewriters.

**Comment by johnbelamaric** [comment]
cc @fturib carrying this through to be available in the metadata/policy plugins enables some interesting use cases for split-horizon DNS based on client cert (among other things)
