### ISSUE TITLE
Configure the maximum number of workers

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/dns#722]
Is there a way to limit the maximum number of workers a server can spawn.
I see on the code that the limit is maxWorkersCount = 10000, but how can I change it, other than editing the code?

Thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Configure the maximum n..." ]
>Is there a way to limit the maximum number of workers a server can spawn.
>I see on the code that the limit is maxWorkersCount = 10000, but how can I change it, other than editing the code?

you can't. And I'm really opposed to exporting this as a thing you can tweak.

**Comment by tmthrgd** [comment]
@cesarkuroiwa What do you want to limit the maximum number of workers for?

**Comment by cesarkuroiwa** [comment]
The thing is I have a DNS server that basically just have to answer a bunch of zone transfer once in a while. Every 5 minutes or so, it gets about 10k requests for (A|I)XFR almost at once, and we're seeing its memory usage spike at those moments.

I am inclined to believe that, since those requests come all at once, the server spawns a lot of goroutines to handle each request, which may cause the spike in memory usage. At some moments, I've the server with about 1000 goroutines, but the actual number might be higher than that.

Some zone transfers are considerably large (about 1gb), I've seen the server get close to 26gb of memory (it is running on a machine with 32gb of RAM)

So, that's why I was thinking that, maybe, putting a limit to the number of spawned servers might limit the memory usage, while also decreasing the performance, which wouldn't be very critical in our case.

**Comment by tmthrgd** [comment]
@cesarkuroiwa Would you mind trying the following (or something similar):

```go
...
var h dns.Handler = ... // (existing handler)
limit := make(chan struct{}, 500)
limited := dns.HandlerFunc(func(w dns.ResponseWriter, r *dns.Msg) {
    limit <- struct{}{}
    defer func() { <-limit }()
    h.ServeDNS(w, r)
})
srv := &dns.Server{Handler: limit}
...
```

That should limit the number of concurrent dns requests being handled to 500. (I typed this out on mobile so apologise if there are typos).

**Comment by tmthrgd** [comment]
Also to clarify, `maxWorkersCount` is poorly named. It doesn’t actually control the maximum number of workers that can run, but the maximum that are allowed to stay idle before being torn down. If that limit is reached, the server will just keep spawning workers (goiroutines) for each new request, they’ll just only be used once.

**Comment by larytet** [comment]
@tmthrgd 
I need a rate limiter. The scenario:
- Very busy system 
- Burst of 20K queries
- The system runs out of free files
I want to limit the number of accepted connections by some small number. I use the following code
```
	dnsPending := atomic.AddUint64(&c.DnsPending, 1)
	if dnsPending < MaxNumberOfPendingQueries {
                   // do my stuff
	} else {
                   // ignore
        }
	atomic.AddUint64(&c.DnsPending, ^uint64(0))
```
On busy systems it does not help.

**Comment by tmthrgd** [comment]
@larytet The UDP code only ever uses a single socket and does not dial, so I'm not sure where you're seeing that error. Also, `dns.ResponseWriter.Close` is no-op for UDP given the single socket. Although I don't know how that error is related, you might want to try increasing the linux (I presume) max file descriptor limit.

**Comment by larytet** [comment]
My bad. I have  a limit of 4K of ports for the process. I got the error from dns.Exchange(). My DNS client could not survive bursts larger than a couple of Ks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Configure the maxim..." ]
>@larytet The UDP code only ever uses a single socket and does not dial, so I'm not sure where you're seeing that error. Also, `dns.ResponseWriter.Close` is no-op for UDP given the single socket. Although I don't know how that error is related, you might want to try increasing the linux (I presume) max file descriptor limit.

Yes, 4K is very small. Doesn't look like a problem with this library.

**Comment by tmthrgd** [comment]
I’m going to assume my earlier replies helped OP out and close this issue. Feel free to reopen.
