### ISSUE TITLE
maxWorkersCount

### ISSUE THREAD

**Issue by larytet** [miekg/dns#725]
Hi,

The constant maxWorkersCount is 10000.   The constant is not exported. My understanding of the code is that the application is not expected to serve more than maxWorkersCount DNS requests simultaneously. In other words the application can not have more than maxWorkersCount pending requests. 
If,  for example, it takes 2s on average for the application to figure out a correct response the application will serve 5K requests/s.

Is my understanding correct?

**Comment by tmthrgd** [comment]
See my comment on https://github.com/miekg/dns/issues/722#issuecomment-412932068:
> Also to clarify, `maxWorkersCount` is poorly named. It doesn’t actually control the maximum number of workers that can run, but the maximum that are allowed to stay idle before being torn down. If that limit is reached, the server will just keep spawning workers (goroutines) for each new request, they’ll just only be used once.

This line is where new goroutines are spawned
https://github.com/miekg/dns/blob/208cd1e89ec4a671e7ae6891f8c94cfe75399570/server.go#L366

and `maxWorkersCount` is only checked here
https://github.com/miekg/dns/blob/208cd1e89ec4a671e7ae6891f8c94cfe75399570/server.go#L330

after `srv.serve` has been called, but before the worker waits idling.

**Comment by larytet** [comment]
My bad. I I did not pay enough attention that there is a call to srv.serve(w) before the cleanup.

**Comment by tmthrgd** [comment]
@larytet Not a problem, I hope I've cleared that all up for you.
