### ISSUE TITLE
RCode string for NotImp incorrect

### ISSUE THREAD

**Issue by bcorijn** [miekg/dns#733]
Hi,
While trying to write a template section for my CoreDNS deployment, I noticed I got a `unknown rcode` error when trying to use rcode `NOTIMP` which uses the `dns.StringToRcode` method. Taking a quick look at the code, I see the map is defined with string `NOTIMPL` (https://github.com/miekg/dns/blob/master/msg.go#L154) instead of the official `NOTIMP` string.

This would be a very simple PR/change but there might be people who rely on this typo by now, for who it would be a breaking change?

**Comment by miekg** [comment]
I think we should just make this change.
