### ISSUE TITLE
NSEC type bitmap bug

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/dns#741]
Hi

I believe there is bug in the way NSEC RR is packed into wireformat
when compression is turned ON.

The problem occurs when the first label of the NSEC ownername is long enough
(about 20 bytes is enough) and it is encoded with compression on the
wireformat of the DNS message.

On the func 'packDomainName' in msg.go, the msg is filled up until the
first '.' is found, and then, if compression is available, the pointer
is added, but the extra bytes of the label that were filled previously
are left there (they don't get zeroed). What happens next, is that on
func 'packDataNsec', the bitmap part of the msg is filled with the
operator '|=', on a byte might already be set.

I don't know if I made myself clear enough, but if any doubts remain, I'd be happy to help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] NSEC type bitmap bug (#..." ]
>Hi
>
>I believe there is bug in the way NSEC RR is packed into wireformat
>when compression is turned ON.
>
>The problem occurs when the first label of the NSEC ownername is long enough
>(about 20 bytes is enough) and it is encoded with compression on the
>wireformat of the DNS message.
>
>On the func 'packDomainName' in msg.go, the msg is filled up until the
>first '.' is found, and then, if compression is available, the pointer
>is added, but the extra bytes of the label that were filled previously
>are left there (they don't get zeroed). What happens next, is that on
>func 'packDataNsec', the bitmap part of the msg is filled with the
>operator '|=', on a byte might already be set.
>
>I don't know if I made myself clear enough, but if any doubts remain, I'd be happy to help.

Could you potentially morph this into a failing test?

**Comment by cesarkuroiwa** [comment]
Hi
I managed to produce a small program that reproduces this scenario.

https://gist.github.com/cesarkuroiwa/ebc2b4fb1103a7e88824865184f0c73c

One thing I forgot to mention is that the NextDomain of the NSEC also has to be a short name for this to happen

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] NSEC type bitmap bu..." ]
>Hi
>I managed to produce a small program that reproduces this scenario.
>
>https://gist.github.com/cesarkuroiwa/ebc2b4fb1103a7e88824865184f0c73c
>
>One thing I forgot to mention is that the NextDomain of the NSEC also has to be a short name for this to happen

Thanks for the gist; that *def.* looks fishy.

**Comment by miekg** [comment]
I won't have time to work on this for at least several week. If you want to take a stub at fixing this be my guest.
