### ISSUE TITLE
Unable to bind to 0.0.0.0:53 when systemd-resolved is running

### ISSUE THREAD

**Issue by teran-mckinney** [miekg/dns#743]
This is the same issue as #680, just ran into it again on Ubuntu 18.04. Any example you have that tries to bind to port 53 while systemd-resolved should trigger this.

**Comment by teran-mckinney** [comment]
Related: #487 

Would be nice to request socket options with this library.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Unable to bind to 0.0.0..." ]
>This is the same issue as #680, just ran into it again on Ubuntu 18.04. Any example you have that tries to bind to port 53 while systemd-resolved should trigger this.

you bind to a port where something is running... that's WAI

**Comment by teran-mckinney** [comment]
systemd-resolved is bound to 127.0.0.53 port 53 with SO_REUSEADDR. If we have the option to enable SO_REUSEADDR when binding 0.0.0.0 port 53, these two can coexist just fine.

**Comment by tmthrgd** [comment]
@teran-mckinney `SO_REUSEADDR` hasn’t been implemented, while `SO_REUSEPORT` has been. After some quick reading, what you’re trying to do is valid and exactly what `SO_REUSEADDR` was designed for. (This is a somewhat verbose explanation: https://stackoverflow.com/a/14388707).

It wouldn’t be a huge amount of work to add, but we would start to get a multitude of socket options hanging off `Server`.

**Comment by teran-mckinney** [comment]
Thanks for looking into this. I agree, maybe there's a cleaner way to implement the options but I don't know Go very well.

**Comment by miekg** [comment]
you should make your own conn and use that; not something this lib should provide.

**Comment by tmthrgd** [comment]
@teran-mckinney Use the `ListenConfig` type and it’s methods from the `net` package to create a connection with the `SO_REUSEADDR` flag set (see <listen_go111.go>). Then set either the `Listener` or `PacketConn` fields on `Server` and call `ActivateAndServe` like you would `ListenAndServe`.

**Comment by teran-mckinney** [comment]
@tmthrgd thank you! I appreciate it.
