### ISSUE TITLE
"dns: overflow unpacking uint16" on (dns.ResponseWriter).TsigStatus()

### ISSUE THREAD

**Issue by thyth** [miekg/dns#748]
I'm having trouble verifying TSIGs on requests when running a DNS server built upon this library: when the TSIG is present, calling TsigStatus() on the dns.ResponseWriter produces the error `dns: overflow unpacking uint16` where I expect `nil`.

I am also seeing this behavior in a case based upon the sample code listed in the docs @ https://godoc.org/github.com/miekg/dns#hdr-TRANSACTION_SIGNATURE -- with the exact code I'm using at this gist: https://gist.github.com/thyth/28115553537dbff36093cce962185b04

When running that gist, this is my output (from a fresh Ubuntu 16.04 environment). Seeing the same issue on macOS (with same Go version) too:
```
ubuntu@chroniton:~/scratch$ sudo ./scratch
panic: dns: overflow unpacking uint16

goroutine 21 [running]:
main.handleRequest(0x761840, 0xc000154090, 0xc000166000)
	/home/ubuntu/scratch/scratch.go:42 +0x40f
github.com/miekg/dns.HandlerFunc.ServeDNS(0x7279c8, 0x761840, 0xc000154090, 0xc000166000)
	/home/ubuntu/go/src/github.com/miekg/dns/server.go:112 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc000088c30, 0x761840, 0xc000154090, 0xc000166000)
	/home/ubuntu/go/src/github.com/miekg/dns/server.go:238 +0x62
github.com/miekg/dns.(*Server).serveDNS(0xc000112000, 0xc000154090)
	/home/ubuntu/go/src/github.com/miekg/dns/server.go:773 +0x140
github.com/miekg/dns.(*Server).serve(0xc000112000, 0xc000154090)
	/home/ubuntu/go/src/github.com/miekg/dns/server.go:725 +0x210
github.com/miekg/dns.(*Server).worker(0xc000112000, 0xc000154090)
	/home/ubuntu/go/src/github.com/miekg/dns/server.go:356 +0x4d
created by github.com/miekg/dns.(*Server).spawnWorker
	/home/ubuntu/go/src/github.com/miekg/dns/server.go:396 +0x86

ubuntu@chroniton:~/scratch$ go version
go version go1.11 linux/amd64

ubuntu@chroniton:~/scratch$ uname -a
Linux chroniton 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@chroniton:~/scratch$ cd ~/go/src/github.com/miekg/dns/
ubuntu@chroniton:~/go/src/github.com/miekg/dns$ git rev-parse HEAD
5debfeec63c371d5806bb64f4553078717b2eef5
```

**Comment by thyth** [comment]
I've bisected this issue:
```
$ git bisect good
bf6da3a5bd358659e9541a45d948f45de8ffb3d3 is the first bad commit
commit bf6da3a5bd358659e9541a45d948f45de8ffb3d3
Author: Tom Thorogood <me+github@tomthorogood.co.uk>
Date:   Sun Sep 9 01:45:17 2018 +0930

    Reduce UDP server memory usage (#735)
    
    * Clear the response.msg field after unpacking
    
    The allocated buffer cannot be freed by the garbage collector while the
    response is alive, by clearing msg here, the GC can collect the buffer
    sooner.
    
    * Use a sync.Pool for UDP message buffers
    
    * Return UDP message buffer to pool in all paths
    
    * Move udpPool.New closure out of (*Server).init
    
    The closure used to capture the *Server which would cause a reference
    loop and prevent it from ever being released by the garbage collector.
    
    This also gives the closure a more obvious name in memory profiles:
      github.com/miekg/dns.makeUDPBuffer.func1 rather than
      github.com/miekg/dns.(*Server).init.func1.

:100644 100644 575c657d2ab474deca40f4465626b3c2b4367d38 c0f18037d1bea7add7497d9f82ae3ae110fb9671 M	server.go
```
Commits prior to this revision print "Validated!" instead of producing the error when running my gist.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] "dns: overflow unpa..." ]
>I've bisected this issue:
>```
>$ git bisect good
>bf6da3a5bd358659e9541a45d948f45de8ffb3d3 is the first bad commit
>commit bf6da3a5bd358659e9541a45d948f45de8ffb3d3
>Author: Tom Thorogood <me+github@tomthorogood.co.uk>
>Date:   Sun Sep 9 01:45:17 2018 +0930
>
>    Reduce UDP server memory usage (#735)
>
>    * Clear the response.msg field after unpacking
>
>    The allocated buffer cannot be freed by the garbage collector while the
>    response is alive, by clearing msg here, the GC can collect the buffer
>    sooner.
>
>    * Use a sync.Pool for UDP message buffers
>
>    * Return UDP message buffer to pool in all paths
>
>    * Move udpPool.New closure out of (*Server).init
>
>    The closure used to capture the *Server which would cause a reference
>    loop and prevent it from ever being released by the garbage collector.
>
>    This also gives the closure a more obvious name in memory profiles:
>      github.com/miekg/dns.makeUDPBuffer.func1 rather than
>      github.com/miekg/dns.(*Server).init.func1.
>
>:100644 100644 575c657d2ab474deca40f4465626b3c2b4367d38 c0f18037d1bea7add7497d9f82ae3ae110fb9671 M	server.go
>```
>Commits prior to this revision print "Validated!" instead of producing the error when running my gist.

Thanks for the bisect, very helpful. Yes this was a big change, and I think I 
have a hunch what could be wrong here; you happen to get an initial buffer that 
is too small? Do you have in inducation of the incoming packet size?

**Comment by thyth** [comment]
I'm using the high level APIs of the library (basically copying code straight from the examples in the docs) and haven't used any APIs at the level of packet buffer allocations. My bisection Gist (linked in the opening message of the issue) is reproduced below:
```
package main

import (
	"github.com/miekg/dns"

	"fmt"
	"time"
)

func main() {
	server := &dns.Server{Addr: "127.0.0.1:53", Net: "tcp"}
	server.TsigSecret = map[string]string{"axfr.": "so6ZGir4GPAqINNh9U5c3A=="}
	dns.HandleFunc(".", handleRequest)
	go server.ListenAndServe()

	time.Sleep(1 * time.Second)

	t := new(dns.Transfer)
	m := new(dns.Msg)
	t.TsigSecret = map[string]string{"axfr.": "so6ZGir4GPAqINNh9U5c3A=="}
	m.SetAxfr("miek.nl.")
	m.SetTsig("axfr.", dns.HmacMD5, 300, time.Now().Unix())
	c, err := t.In(m, "127.0.0.1:53")
	if err != nil {
		panic(err)
	}
	for r := range c {
		fmt.Println(r)
	}
}

func handleRequest(w dns.ResponseWriter, r *dns.Msg) {
	m := new(dns.Msg)
	m.SetReply(r)
	if r.IsTsig() != nil {
		if w.TsigStatus() == nil {
			// *Msg r has an TSIG record and it was validated
			fmt.Println("Validated!")
			m.SetTsig("axfr.", dns.HmacMD5, 300, time.Now().Unix())
		} else {
			// *Msg r has an TSIG records and it was not valided
			panic(w.TsigStatus())
		}
	}
	w.WriteMsg(m)
}
```

FWIW, when testing my actual application, TSIG messages that are generated via this library and via using `nsupdate` were both resulting in the same error. I didn't capture packets on the wire, but I suspect that both cases were generating packets in the ~100-200 byte ranges.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] "dns: overflow unpa..." ]
>I'm using the high level APIs of the library (basically copying code straight from the examples in the docs) and haven't used any APIs at the level of packet buffer allocations. My bisection Gist (linked in the opening message of the issue) is reproduced below:
>```
>package main
>
>import (
>	"github.com/miekg/dns"
>
>	"fmt"
>	"time"
>)
>
>func main() {
>	server := &dns.Server{Addr: "127.0.0.1:53", Net: "tcp"}
>	server.TsigSecret = map[string]string{"axfr.": "so6ZGir4GPAqINNh9U5c3A=="}
>	dns.HandleFunc(".", handleRequest)
>	go server.ListenAndServe()
>
>	time.Sleep(1 * time.Second)
>
>	t := new(dns.Transfer)
>	m := new(dns.Msg)
>	t.TsigSecret = map[string]string{"axfr.": "so6ZGir4GPAqINNh9U5c3A=="}
>	m.SetAxfr("miek.nl.")
>	m.SetTsig("axfr.", dns.HmacMD5, 300, time.Now().Unix())
>	c, err := t.In(m, "127.0.0.1:53")
>	if err != nil {
>		panic(err)
>	}
>	for r := range c {
>		fmt.Println(r)
>	}
>}

Ah, it's on AXFR! That means axfr is hitting some code path meant to be udp only 
or it's sent on udp; both are not desirable.

**Comment by thyth** [comment]
That example code is only setting up a server with `Net: "tcp"`, and I first encountered the issue with non-AFXR queries. TCP vs. UDP transport doesn't appear to make a difference.

When I went back to reproduce this issue (to make sure it wasn't some other problem with my application), I tried to copy the examples verbatim to remove as many variables as possible.

In my actual application, the client side looks pretty close to:
```
	msg := &dns.Msg{}
	msg.Opcode = dns.OpcodeUpdate
	msg.SetQuestion(config.SearchSuffix, dns.TypeSOA)

	rr := &dns.CNAME{
		Hdr: dns.RR_Header{
			Name:   mapping.Name,
			Rrtype: dns.TypeCNAME,
			Class:  dns.ClassINET,
			Ttl:    config.TTL,
		},
		Target: mapping.Target,
	}
	msg.Ns = []dns.RR{rr}
	cli := &dns.Client{}
	cli.TsigSecret = map[string]string{key.ZoneName: key.Key}
	msg.SetTsig(key.ZoneName, key.Algorithm, 300, time.Now().Unix())
	_, _, err := cli.Exchange(msg, dnsServer.String()+":53")
```

My invocations of `nsupdate -k test.key` were commands like:
```
> server 127.0.0.1
> zone test.example.com
> update add foo.test.example.com. 300 CNAME foo.alias.example.com.
> send
``` 

Both resulted in the same error -- indeed, both should generate effectively identical DNS queries.

I should note that aside from the TSIG status generating that error, the contents of the update queries themselves (e.g. the CNAME RR) were readable.

**Comment by thyth** [comment]
I'm pretty sure I see the issue in code as a result of the commit identified in bisection.

See: https://github.com/miekg/dns/blob/833bf76c282d338e307ff7ec181b95cfc117deb2/server.go#L744

And:
https://github.com/miekg/dns/blob/833bf76c282d338e307ff7ec181b95cfc117deb2/server.go#L759

The value of w.msg on L759 will always be `nil` due to the unconditional assignment on L744, thus TSIG validation will not function on any message type processed by (*Server).serveDns.

**Comment by miekg** [comment]
Care to send a PR? (With a test please :) )

**Comment by thyth** [comment]
Opened an initial PR (#749) -- I'll add a test tomorrow.
