### ISSUE TITLE
Panic on udpsession

### ISSUE THREAD

**Issue by semihalev** [miekg/dns#766]
I got the panic two times this week. How can i handle this?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93e4db]

goroutine 129363104 [running]:
github.com/miekg/dns.(*SessionUDP).RemoteAddr(...)
	/build/go/src/github.com/miekg/dns/udp.go:34
github.com/miekg/dns.(*response).RemoteAddr(0xc0025ebdd0, 0xc0001d6a80, 0xc000952d72)
	/build/go/src/github.com/miekg/dns/server.go:773 +0x5b

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Panic on udpsession (#7..." ]
>I got the panic two times this week. How can i handle this?
>
>panic: runtime error: invalid memory address or nil pointer dereference
>[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93e4db]
>
>goroutine 129363104 [running]:
>github.com/miekg/dns.(*SessionUDP).RemoteAddr(...)
>	/build/go/src/github.com/miekg/dns/udp.go:34
>github.com/miekg/dns.(*response).RemoteAddr(0xc0025ebdd0, 0xc0001d6a80, 0xc000952d72)
>	/build/go/src/github.com/miekg/dns/server.go:773 +0x5b

on linux? With master?

**Comment by semihalev** [comment]
Yes on linux with master.

**Comment by tmthrgd** [comment]
@semihalev Would you mind supplying the full panic?

This looks like days corruption to me. Are you, directly or indirectly, using `unsafe` or Cgo?

**Comment by tmthrgd** [comment]
Actually scratch that, I know exactly what’s happening. You’re calling ‘(*response).Close` somewhere that sets `(*response).tcp` to `nil`, and *then* calling `(*response).RemoteAddr` which assumes that one of `tcp` or `udpSession` is set.

This needs to be fixed properly, but if you stop doing that it will all work.

**Comment by semihalev** [comment]
The panic log very small, there is one more function. I don't have `unsafe` or Cgo.

Yes I'm calling `Close` method on defer. I will check this but the main problem looks like , `(*SessionUDP).raddr` is nil

**Comment by tmthrgd** [comment]
It’s not `raddr` that’s `nil`, which wouldn’t cause a panic, but the method receiver, the `*SessionUDP` itself. So `s.raddr` panics when it dereferences `s`, which is really `(*s).raddr`. It’s that dereferencing of a `nil` pointer that’s causing the panic.

AFAIK, you don’t need to call `Close` in normal operation. Somewhere, you’re calling `RemoteAddr` after that defer runs.

The `response` code needs to be hardened against the interactions of `Close` with other methods.

**Comment by tmthrgd** [comment]
@semihalev If you try your program again against `master` (with #769 merged), you'll see an explicit panic that should clarify what's wrong. It's not safe to call methods on `response` after calling `Close` for a TCP connection.

**Comment by semihalev** [comment]
Thanks @tmthrgd , I updated from `master` branch. I'm looking in my code about the `Close` method usage.
