### ISSUE TITLE
Extended Rcode

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/dns#767]
On file edns.go, function SetExtendedRcode, I believe the following check is inappropriate: 
```
if v < RcodeBadVers { // Smaller than 16.. Use the 4 bits you have!`
	return
}
```
since "v" supposedly already holds the only the 8 upper bits of the RCode, as it is called on file msg.go, line 718:

```
opt.SetExtendedRcode(uint8(dns.Rcode >> 4))
```

**Comment by tmthrgd** [comment]
This issue has come up many times already, but it definitely looks wrong to me. x/net/dns/dnsmessage does it differently:

https://github.com/golang/net/blob/4dfa2610cdf3b287375bbba5b8f2a14d3b01d8de/dns/dnsmessage/message.go#L1679

https://github.com/golang/net/blob/4dfa2610cdf3b287375bbba5b8f2a14d3b01d8de/dns/dnsmessage/message.go#L1696

**Comment by tmthrgd** [comment]
See #682, #516, #517, #339, #340 & #135 for a history of Extended RCode support.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Extended Rcode (#76..." ]
>See #682, #516, #517, #339, #340 & #135 for a history of Extended RCode support.

Yes, it was wrong. Can't remember if it still is, discussion mostly stalled on 
having a backwards compatible way to doing it right IIRC

**Comment by cesarkuroiwa** [comment]
I forgot to mention that the calling of method SetExtendedRcode on file msg.go would have to changed too:

```
-               opt.SetExtendedRcode(uint8(dns.Rcode >> 4))
+               opt.SetExtendedRcode(uint16(dns.Rcode))
```

**Comment by chantra** [comment]
@cesarkuroiwa #791 should fix this

**Comment by tmthrgd** [comment]
#791 was merged on the 17th.
