### ISSUE TITLE
[help wanted] Always get timeout when dns.Exchange

### ISSUE THREAD

**Issue by imfht** [miekg/dns#784]
Hi.
  I got a problem when using miekg/dns when run a simple example programmer. when I run the code below.

```golang
package main

import (
	"log"
	"strconv"

	"github.com/miekg/dns"
	"fmt"
)

func parseQuery(m *dns.Msg) {
	for _, q := range m.Question {
		switch q.Qtype {
		case dns.TypeA:
			log.Printf("Query for %s\n", q.Name)
			in, rtt := dns.Exchange(m, "114.114.114.114:53")
			fmt.Println(in, rtt)
		}
	}
}

func handleDnsRequest(w dns.ResponseWriter, r *dns.Msg) {
	m := new(dns.Msg)
	m.SetReply(r)
	m.Compress = false

	switch r.Opcode {
	case dns.OpcodeQuery:
		parseQuery(m)
	}

	w.WriteMsg(m)
}

func main() {
	// attach request handler func
	dns.HandleFunc(".", handleDnsRequest)

	// start server
	port := 5356
	server := &dns.Server{Addr: ":" + strconv.Itoa(port), Net: "udp"}
	log.Printf("Starting at %d\n", port)
	err := server.ListenAndServe()
	defer server.Shutdown()
	if err != nil {
		log.Fatalf("Failed to start server: %s\n ", err.Error())
	}
}
```
what I want do is `start a dns server at 127.0.0.1:5356 and forward all dns request to 114.114.114.114`.
But I get `<nil> MsgHdr read udp 192.168.0.105:55680->114.114.114.114:53: i/o timeout` when I use `dig www.qq.com @127.0.0.1 -p 5356`.
I can connect the upstream dns server(114.114.114.114) via `dig @114.114.114.114 qq.com`.
Could someone give me some help?
best wishes!
ScreenShoot & log may helps :
![image](https://user-images.githubusercontent.com/15059493/46746173-0ea1e900-cce1-11e8-9692-64ba50ace2ea.png)
and the the programmer logs below
```
2018/10/10 22:59:14 Starting at 5356
2018/10/10 22:59:19 Query for www.qq.com.
<nil> MsgHdr read udp 192.168.0.105:55680->114.114.114.114:53: i/o timeout
2018/10/10 23:05:21 Query for www.qq.com.
<nil> MsgHdr read udp 192.168.0.105:53311->114.114.114.114:53: i/o timeout
```

**Comment by tmthrgd** [comment]
You're problem is quite simple. You're trying to proxy the reply message `m` and not the actual request `r`. The server 114.114.114.114:53 is seeing this invalid message, (probably) presuming it's an attempted attack traffic, and just dropping the packet without replying. Switch the `m` to `r` and it works fine.

```go
func handleDnsRequest(w dns.ResponseWriter, r *dns.Msg) {
	m := new(dns.Msg)
	m.SetReply(r)
	m.Compress = false

	switch r.Opcode {
	case dns.OpcodeQuery:
		parseQuery(m) // <-- m should be r
	}

	w.WriteMsg(m)
}
```
