### ISSUE TITLE
RRSIG verify problem

### ISSUE THREAD

**Issue by semihalev** [miekg/dns#788]
Hi,

I got dnssec verification issue for some domains but like the domains verified with other tools: <http://dnsviz.net/d/sigok.verteiltesysteme.net/dnssec/>

They are using RSA keys. I don't have deep knowledge about cryptology but when i debug the pubkey exponent len is `5` ,  I checked the old issue ( #688 ) and copy the test function for a domain:

```go
func TestVerteiltesysteme_dot_net_rrsig(t *testing.T) {
	_zsk, _ := dns.NewRR("verteiltesysteme.net.	3600	IN	DNSKEY	256 3 5 BQEAAAABv5hDo9fIU91cSFaDmnNPg7H3WljskDJNRB2MZO8/YbBwcDqFeyD7K0pTjqYSVA6wI/ZaTa9dJu3iUf1MVq3o/+3ogO5J0LKW43zyvTOSSv5UDRKAzHkrjGx92e73a+9lA3vXARwV29SSqBc0cwUHJOfHRwm/0+a4bZHJMmqFDnM=")
	_rest, _ := dns.NewRR("sigok.verteiltesysteme.net.	60	IN	A	134.91.78.139")
	_rksk, _ := dns.NewRR("sigok.verteiltesysteme.net. 60	IN	RRSIG	A 5 3 60 20181230020002 20180930020002 30665 verteiltesysteme.net. Nn6w/FS4JzB3QEnc96XNTJ1Q+VYCb4B8BunyKwPEJpiieiGScYe6W/tfk/yeFDFid5sYNSWMIPk4rhRkpso2NVhI8D8lS/XZpZ1THBunbFZxE1T3Tewls+knG8ponoIvfypln622P/+8xQHOoXHyEWpVqOeQpP5FfPHkkNBsuCE=")

	zsk := _zsk.(*dns.DNSKEY)
	rksk := _rksk.(*dns.RRSIG)
	rest := _rest.(*dns.A)

	if e := rksk.Verify(zsk, []dns.RR{rest}); e != nil {
		t.Logf("cannot verify RRSIG with keytag [%d]. Cause [%s]", rksk.KeyTag, e.Error())
		t.Fail()
	}
}
```
Result:
--- FAIL: TestVerteiltesysteme_dot_net_rrsig (0.00s)
    dnssec_test.go:19: cannot verify RRSIG with keytag [30665]. Cause [dns: bad key]

Caused here:

https://github.com/miekg/dns/blob/d74956db7b5b20451796774572d0f5a0222e377a/dnssec.go#L551-L555

**Comment by tmthrgd** [comment]
See https://www.imperialviolet.org/2012/03/16/rsae.html and golang/go#3161.

Your test case is actually failing here though:
https://github.com/miekg/dns/blob/d74956db7b5b20451796774572d0f5a0222e377a/dnssec.go#L395

**Comment by semihalev** [comment]
@tmthrgd  sorry, there was like some copy issues, I edited the test func, can you test again?

**Comment by tmthrgd** [comment]
If you switch the key tags around in the RRs, you get the failure where you described above. (@semihalev I already picked up on that and got the test failure you described).

The domain is using an exponent of `4294967297` or `2^32+1`. That is outside the allowable range for go's `crypto/rsa` package and, as stated in the linked Golang issue above, not going to ever be supported.

This is unfortunate, but domains such as the above are rare and, to quote agl, "large public exponents are both obscure and crpytographically illiterate and so are exactly the sort of thing that we omit." There is no fixing this, except to ask the owner of verteiltesysteme.net to fix their DNSSEC setup.

**Comment by semihalev** [comment]
I verified their explen is `5`

**Comment by tmthrgd** [comment]
Unfortunately there’s still nothing that can be done here. Any exponent larger than stated above is incompatible with `crypto/rsa`. Once again, the only solution is to ask the domain in question to fix their mistake.

@semihalev Can you confirm the actually exponent is outside the supported range?

**Comment by miekg** [comment]
the exp was/is indeed F5. I would treat those zones as insecure for the time being.
