### ISSUE TITLE
Travis Windows builds

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#789]
Starting yesterday, Travis has early Windows support:
*Windows is Available (Early Release)*
https://blog.travis-ci.com/2018-10-11-windows-early-release.

It's currently only supported for Node.js, Rust, and Bash, with other languages to come in the future, I believe. Once Go support is added, Windows should be added as a Travis build environment—at least for the latest stable go release. This will help catch issues like #765 / coredns/coredns#2138.

Although in the Windows breaking #738 @miekg did say:
> "who runs windows these days."

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Travis Windows builds (..." ]
>Starting yesterday, Travis has early Windows support:
>*Windows is Available (Early Release)*
>https://blog.travis-ci.com/2018-10-11-windows-early-release.
>
>It's currently only supported for Node.js, Rust, and Bash, with other languages to come in the future, I believe. Once Go support is added, Windows should be added as a Travis build environment—at least for the latest stable go release. This will help catch issues like #765 / coredns/coredns#2138.
>
>Although in the Windows breaking #738 @miekg did say:
>> "who runs windows these days."

I still don't run it. And I have no way to debug it, but if travis supports it 
might be nice to add it.

**Comment by miekg** [comment]
I noone stands up and takes ownership of the Windows side of things, I'll just close this.
