### ISSUE TITLE
Querying NS on non-apex domain results in panic

### ISSUE THREAD

**Issue by akamensky** [miekg/dns#795]
Querying for NS records on non-apex domain (for example on www subdomain that is a CNAME to apex domain) is a legitimate query and all popular DNS servers (that includes bind9 etc) will reply with a complex answer that will look like:
```
www.example.com CNAME example.com
example.com NS ns1.nameserver.org
example.com NS ns2.nameserver.org
```

No client can know in advance whether domain is apex or not, therefore the query should work on client in order to be able to fetch nameservers from any known subdomain.

However this lib (awesome as it is) gets panic:
```
panic: interface conversion: dns.RR is *dns.CNAME, not *dns.NS
```

(Meanwhile built-in client handles it just fine, presumably because it uses OS native resolver...)

**Comment by miekg** [comment]
This lib doesn't do that, so I must be some client code.

**Comment by akamensky** [comment]
That's right it does not do that, that's the point of this issue. And I believe it should do that. Else it does not work for many legitimate use-cases. At the very least it should NOT panic. I received appropriate DNS response, this is expected, why should it panic then?

**Comment by akamensky** [comment]
I think the fix is rather simple here, not blindly expect every returned record to be expected type, but check the type (and if conversion works or not) and only return requested types.

I.e. if as in example above first returned record is CNAME, but requested type is NS, then it should skip CNAME in results, but still return the other matching records instead of going to panic...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Querying NS on non-..." ]
>I think the fix is rather simple here, not blindly expect every returned record to be expected type, but check the type (and if conversion works or not) and only return requested types.

yes

/Miek

--
Miek Gieben

**Comment by tmthrgd** [comment]
What’s the stacktrace of that panic?

**Comment by akamensky** [comment]
My apologies, I just realized the current code is working as expected and the panic was coming from my own code. The type casting was done in my code and which is why it was failing. When I do proper checking if casting successful I can get NS records back as expected. So closing this one.
