### ISSUE TITLE
adding hooks on new/end of TCP connection

### ISSUE THREAD

**Issue by chantra** [miekg/dns#797]
I am looking in a way to better understand what goes on with TCP/TLS connections. Things I like to know is:
1) how many connections are using TLS session resumption or new TLS connection
2) how many queries are being handled by a single connection.
3) how long a connection had been up for
4) optionally: was this closed due to idle time, initiated on other side, reached max query per connection (can be inferred from 2 though)

Maybe more later.

For UDP, the ServeDNS entry point is usually enough as it is a 1 :1 mapping. For TCP, it does not work the same.

I suggest adding a new interface to be potentially supported by the handler:

```
// Handler is implemented by any value that implements ServeDNS.
type TCPHandler interface {
	NewConnection(w ResponseWriter)
         EndConnection(w ResponseWriter, q int, duration time.Duration, reason)
}
```

where q is the number of query handled, reason (unsure of type) could be use to find out if closed by peer, reached max queries, idletimeout kicked in, misc socket error...

Any thoughts and suggestions?

**Comment by tmthrgd** [comment]
Are you looking for this with respect to the client code or server code?

**Comment by chantra** [comment]
Server code

**Comment by tmthrgd** [comment]
Some of these are achievable with a custom `net.Listener` that returns a wrapped `net.Conn`. Have you tried such an approach?

**Comment by chantra** [comment]
Yes. But how would you know how many queries were made for instance?
You can find out when there is a new connection, by calling
conn.Handshake() , one could find out whether the tls session was revised
or not. I don’t remember on top of my head how handling error would pan
though.

**Comment by tmthrgd** [comment]
UDP has a packet per query so that’s easy to measure. TCP has a two byte length prefix per query and then that many bytes of data. It might not be the easiest, but it certainly should be possible to figure it out from the data being read through.

**Comment by miekg** [comment]
Don't think there is anything left to do here. Closing
