### ISSUE TITLE
Code sets socket to SO_REUSEPORT whether system supports it or not

### ISSUE THREAD

**Issue by stuartnelson3** [miekg/dns#802]
This option depends on the underlying system supporting it, in addition to being compiled with go1.11. Support should be checked before setting the option.

See discussion here:

https://github.com/coredns/coredns/issues/2239

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Code unconditionally se..." ]
>This option depends on the underlying system supporting it, in addition to being compiled with go1.11. Support should be checked before setting the option.
>
>See discussion here:
>
>https://github.com/coredns/coredns/issues/2239

we're not using this code, we're setting it ourselves in coredns.

**Comment by stuartnelson3** [comment]
That explains why I couldn't find where it was set :sweat_smile:

**Comment by stuartnelson3** [comment]
From the PR:
>I'm not sure where you want this to live, or if it's on the user to know they can use SO_REUSEPORT or not.

Seeing as this is being set by users of the library, not the library itself, perhaps this check belongs elsewhere.

**Comment by stuartnelson3** [comment]
Closing as the value is configurable by the user
