### ISSUE TITLE
Server leaks memory on every TCP connection

### ISSUE THREAD

**Issue by saj** [miekg/dns#807]
Hello,

These insertions into `srv.conns`:

https://github.com/miekg/dns/blob/6ae357d393978566133a91aa1d4207b4f67da2c1/server.go#L496

are never released when the connection is closed:

https://github.com/miekg/dns/blob/6ae357d393978566133a91aa1d4207b4f67da2c1/server.go#L575-L585

The preceding call to `w.Close()` nils out `w.tcp`; the `delete()` has no effect, so the map grows without bound.

I use this library by way of [coredns/coredns](https://github.com/coredns/coredns).  Here is what the leak looks like after a quick local test (y-axis is RSS bytes):

![screen shot 2018-11-03 at 04 23 29](https://user-images.githubusercontent.com/194389/47930499-41c24b80-df20-11e8-801d-9d1b1e550953.png)

I then applied this patch and tried again:

```
diff --git a/server.go b/server.go
index 4b4ec33c..ac655c4e 100644
--- a/server.go
+++ b/server.go
@@ -573,14 +573,14 @@ func (srv *Server) serve(w *response) {
        }

        defer func() {
-               if !w.hijacked {
-                       w.Close()
-               }
-
                srv.lock.Lock()
                delete(srv.conns, w.tcp)
                srv.lock.Unlock()

+               if !w.hijacked {
+                       w.Close()
+               }
+
                w.wg.Done()
        }()

```

Results:

![screen shot 2018-11-03 at 04 26 02](https://user-images.githubusercontent.com/194389/47930633-9b2a7a80-df20-11e8-9e98-1f1fb363dd45.png)

**Comment by miekg** [comment]
nice evidence. Care to send  a PR?

**Comment by tmthrgd** [comment]
Oh that’s my bad. I’ll fix this and add a test for it.
