### ISSUE TITLE
How can i resolve domain by the clientIP?

### ISSUE THREAD

**Issue by MolenZhang** [miekg/dns#812]
Hi:
   I`m confused by the dns resolve through the cllientIP, which i meaned is different region client resolve the same domain should get the different result.
   Give me some advice,please.
best regards~

**Comment by semihalev** [comment]
look the geodns project: https://github.com/abh/geodns project.

**Comment by MolenZhang** [comment]
> look the geodns project: https://github.com/abh/geodns



> look the geodns project: https://github.com/abh/geodns

**Comment by MolenZhang** [comment]
Can miekg/dns support it?

**Comment by semihalev** [comment]
it uses miekg/dns.

**Comment by miekg** [comment]
Out of scope for this library.
