### ISSUE TITLE
How to Extract an Answer Without Explicitly Knowing the Type of DNS Query

### ISSUE THREAD

**Issue by shakeelrao** [miekg/dns#813]
I've been trying to figure out this problem for a while (I'm not sure if the API already provides a solution, so I thought I would post it here).

Suppose we have the following function (skipping error checking for simplicity):

```go
// Performs a DNS query against a name server for a given domain and query type.
func query(server, domain, dnsType string) {
  c := new(dns.Client)
  m := new(dns.Msg)
  
  m.SetQuestion(dns.Fqdn(domain), dns.StringToType[dnsType])
  r, _, _ := c.Exchange(m, server)

  // The issue: how do I access the Answer field given `dnsType` as a string?
  // If we knew the query type was TXT, the documentation suggests the following:
  t, _ := r.Answer[0].(*dns.TXT)
  return t.Txt
}
```

Any suggestions?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] How to Extract an Answe..." ]
>I've been trying to figure out this problem for a while (I'm not sure if the API already provides a solution, but I thought I would post it here anyways). As a disclaimer, I'm a fairly new programmer and not an expert in Go.
>
>Suppose we have the following function (skipping error checking for simplicity):
>
>```go
>// Performs a DNS query against a name server for a given domain and query type.
>func query(server, domain, type string) {
>  c := new(dns.Client)
>  m := new(dns.Msg)
>
>  m.SetQuestion(dns.Fqdn(domain), dns.StringToType[type])
>  r, _, _ := c.Exchange(m, server)
>
>  // How to access the Answer property now since `type` is a string?
> // If we knew the query type was TXT, the documentation suggests the following:
> t, _ := r.Answer[0].(*dns.TXT)
> return t.Txt
>}
>```

You can type switch or look at r.Header().Rrtype

**Comment by miekg** [comment]
this is more of a Go question. Closing here.
