### ISSUE TITLE
Question compression

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#821]
The following new test case fails:
```go
func TestMsgCompressionMultipleQuestions(t *testing.T) {
	msg := new(Msg)
	msg.Compress = true
	msg.SetQuestion("www.example.org.", TypeA)
	msg.Question = append(msg.Question, Question{"other.example.org.", TypeA, ClassINET})

	predicted := msg.Len()
	buf, err := msg.Pack()
	if err != nil {
		t.Error(err)
	}

	if predicted != len(buf) {
		t.Fatalf("predicted compressed length is wrong: predicted %d, actual %d", predicted, len(buf))
	}
}
```

with:
```
--- FAIL: TestMsgCompressionMultipleQuestions (0.00s)
    length_test.go:387: predicted compressed length is wrong: predicted 56, actual 45
```

This fails because `compressedLen` doesn't compress any names in `dns.Question`:
https://github.com/miekg/dns/blob/1c9c9bf4c93ee029810272d3e5b8a126aee5bf1f/msg.go#L909-L912

but the packing code does compress names in `Question`:
https://github.com/miekg/dns/blob/1c9c9bf4c93ee029810272d3e5b8a126aee5bf1f/msg.go#L1093-L1094
https://github.com/miekg/dns/blob/1c9c9bf4c93ee029810272d3e5b8a126aee5bf1f/msg.go#L750

Although I know that multiple questions are very rare and largely unsupported, this is still a bug. It's very easy to fix, but I just don't know what the correct behaviour is here.

Can QNAMEs be compressed and if so, do we actually want to compress them? I can't seem to find an answer in the RFCs, but I suspect we do want to skip compressing them either way.

/cc @miekg

**Comment by tmthrgd** [comment]
@miekg Back in 2012 you added 13f1f5b0669fed2ebb653d638e200b9106f39a2a titled "Question is compressible IMO".

**Comment by miekg** [comment]
Well, yes and no.

Compression *should* only use forward pointers and question is the first thing 
you see, so it can't be compressed. However backward pointers are seen in the 
wild, so it can be compressed (just like any other name).

Every name in the binary message can have a compression pointer; should *we* 
compress a question; most likely not. Can the question name be used as a 
compression target: yes.

**Comment by tmthrgd** [comment]
But in the case of multiple questions, a reference from one question to a previous one can occur and it breaks the test case above because `Len` and `Pack` handle it differently.

The only resource I can find that has anything explicit, says that QNAMEs can't be compressed, but it was hardly an authoritative resource. The RFCs arn't clear and multiple questions are rare.

I understand they can be used as a target, this is specifically about using pointers within QNAMEs.

**Comment by miekg** [comment]
Qnames are no different than other names so they can be compressed.

**Comment by miekg** [comment]
been answered.

**Comment by tmthrgd** [comment]
The test case still fails. #833 will fix and close this. I'll reopen until then.
