### ISSUE TITLE
compressedLen "one more than needed"

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#829]
`compressedLen` has a comment that I don't understand:
https://github.com/miekg/dns/blob/1c9c9bf4c93ee029810272d3e5b8a126aee5bf1f/msg.go#L922

What is it for and what does it mean?

I've hit this in trying to replace and optimise the implementation of `compressedLen` with one that should be *far* more resilient to problems.

/cc @miekg

**Comment by tmthrgd** [comment]
I've figured it out. The `OPT` records have a NAME set to `.` which the `(*RR_Header).len` code doesn't appropriately handle, while `packDomainName` special cases the root domain.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] compressedLen "one ..." ]
>I've figured it out. The `OPT` records have a NAME set to `.` which the `(*RR_Header).len` code doesn't appropriately handle, while `packDomainName` special cases the root domain.

Yeah.... dns ....

**Comment by miekg** [comment]
Oh, the +1 (or one more) was to get around Len bugs the returned the length slightly wrong. In the end I could cut it down to -/+1 and just left it there.
