### ISSUE TITLE
"too many compression pointers"

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#834]
The following test case fails:
```go
func TestPackUnpackManyCompressionPointers(t *testing.T) {
	m := new(Msg)
	m.Compress = true
	m.SetQuestion("example.org.", TypeNS)

	for domain := "a."; len(domain) < maxDomainNameWireOctets; domain += "a." {
		m.Answer = append(m.Answer, &NS{Hdr: RR_Header{Name: domain, Rrtype: TypeNS, Class: ClassINET}, Ns: "example.org."})

		b, err := m.Pack()
		if err != nil {
			t.Fatalf("Pack failed for %q and %d records with: %v", domain, len(m.Answer), err)
		}

		var m2 Msg
		if err := m2.Unpack(b); err != nil {
			t.Fatalf("Unpack failed for %q and %d records with: %v", domain, len(m.Answer), err)
		}
	}
}
```

with:
```
--- FAIL: TestPackUnpackManyCompressionPointers (0.00s)
    msg_test.go:276: Unpack failed for "a.a.a.a.a.a.a.a.a.a.a.a." and 12 records with: dns: too many compression pointers
```

We should be able to unpack every message we pack IMHO, and this is a semantically valid message. The problem is that each label (intentionally) compresses into the previous one forming a long chain of compressed labels. This trips the following arbitrary limit in `UnpackDomainName`:

https://github.com/miekg/dns/blob/7ae05cdcf8241aef158afa93d26863126796a302/msg.go#L402-L404

This limit is necessary to prevent infinite loops as `UnpackDomainName` doesn't restrict pointers to earlier offsets in the message. There are two solutions I can see here, one is to accept any compression pointer provided it heads backwards. The other is to raise the limit to the maximum any valid name could be. (`maxDomainNameWireOctets / 2`?)

**Comment by tmthrgd** [comment]
An alternatively would be to not build a compression chain that long in `PackDomainName`, but that approach would be quite complicated I think.

**Comment by miekg** [comment]
Name of the game is preventing loops, the current limit is arbitrary.
