### ISSUE TITLE
UnpackDomainName DOS potential, large allocations

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#836]
The following code shows that `UnpackDomainName` will allocate a lot of memory when unpacking potentially malicious domain names.

```go
func TestNameCompressionAllocations(t *testing.T) {
	name := []byte("\x3Faaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuu\xC0\x00")

	allocs, mem := allocsPerRun(10, func() {
		_, _, err := UnpackDomainName(name, 0)
		if e, ok := err.(*Error); err != ErrLongDomain && (!ok || e.err != "too many compression pointers") {
			t.Fatalf("UnpackDomainName failed with: %v", err)
		}
	})
	t.Error(allocs, mem)
}

// allocsPerRun is like testing.AllocsPerRun but also reports
// the heap allocations made in bytes.
func allocsPerRun(runs int, f func()) (allocs, total float64) {
	defer runtime.GOMAXPROCS(runtime.GOMAXPROCS(1))

	// Warm up the function
	f()

	// Measure the starting statistics
	var memstats runtime.MemStats
	runtime.ReadMemStats(&memstats)
	mallocs := 0 - memstats.Mallocs
	talloc := 0 - memstats.TotalAlloc

	// Run the function the specified number of times
	for i := 0; i < runs; i++ {
		f()
	}

	// Read the final statistics
	runtime.ReadMemStats(&memstats)
	mallocs += memstats.Mallocs
	talloc += memstats.TotalAlloc

	// Average the mallocs over the runs (not counting the warm-up).
	// We are forced to return a float64 because the API is silly, but do
	// the division as integers so we can ask if AllocsPerRun()==1
	// instead of AllocsPerRun()<2.
	return float64(mallocs / uint64(runs)), float64(talloc / uint64(runs))
}
```

For the current maximum number of compression points, 10, this generates 1936B (~1.8KiB) of garbage before returning an error. After the proposed raising in #835, this generates 36112B (~35.3KiB) of garbage before returning an error.

This could be fixed by checking the maximum allowed length after each label has been unpacked. That may subtle change the semantics of `UnpackDomainName` though. As this will only principally effect the compression pointer case, which already returns an empty string instead of the name, perhaps we could just special case it there.

/cc @miekg

**Comment by tmthrgd** [comment]
Could we change `UnpackDomainName` to throw away the name if it's too long?

I can't see this special case being used anywhere, and it's not documented:
https://github.com/miekg/dns/blob/7ae05cdcf8241aef158afa93d26863126796a302/msg.go#L419-L422

**Comment by semihalev** [comment]
Look at the heap file, always big alloc from UnpackDomainName, I didn't check the details but if you want i can check.

[heap.svg.zip](https://github.com/miekg/dns/files/2624151/heap.svg.zip)

**Comment by miekg** [comment]
we should be safely be able to throw away a name that is too long; you can't use that anyway. At least not for something good.

**Comment by semihalev** [comment]
Carefully about the NSEC3 hash names.

**Comment by tmthrgd** [comment]
@semihalev I can't see any uses of `UnpackDomainName` in [nsecx.go](https://github.com/miekg/dns/blob/6bf402f3c4b2338dd6c357941c58155317768104/nsecx.go). Where do you think this might be a problem?

**Comment by miekg** [comment]
NSEC3 name hashes are bound to the same limits; can't be longer than 63 octets
