### ISSUE TITLE
Escaped names compression length mismatch

### ISSUE THREAD

**Issue by tmthrgd** [miekg/dns#841]
The following test case fails due to differences in escaping between `PackDomainName` and `Len`:
```go
func TestMsgCompressionEscapingCompressionMap(t *testing.T) {
	msg := new(Msg)
	msg.Compress = true
	msg.SetQuestion("www.example.org.", TypeA)
	msg.Answer = append(msg.Answer, &NS{Hdr: RR_Header{Name: "ex\\097mple.org.", Rrtype: TypeNS, Class: ClassINET}, Ns: "ns.example.org."})

	predicted := msg.Len()
	buf, err := msg.Pack()
	if err != nil {
		t.Error(err)
	}
	if predicted != len(buf) {
		t.Fatalf("predicted compressed length is wrong: predicted %d, actual %d", predicted, len(buf))
	}
}
```

with:
```
--- FAIL: TestMsgCompressionEscapingCompressionMap (0.00s)
    length_test.go:398: predicted compressed length is wrong: predicted 61, actual 50
```

The problem is that `\\097` is a perfectly valid escaping of `a`, `PackDomainName` handles this by putting the unescaped name (only the first label is unescaped) into the compression map, while the `Len` code puts the escaped name in the compression map. (This isn't effected by #833).

I'm not sure what the best way to fix this is, fixing this in `Len` would (I think) require extra allocations, and fixing this in `PackDomainName` is trickier than it might seem.

This is one of the corner cases I mentioned in https://github.com/miekg/dns/issues/652#issuecomment-442426951.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Escaped names compressi..." ]
>This is one of the corner cases I mentioned in https://github.com/miekg/dns/issues/652#issuecomment-442426951.

Ack.

I'm all for normalizing this and not making this horrible (internal type 
that we convert from and to?). It's clear that the current impl. is not the best 
one and we can keep on finding non-working corner cases.

Which may be harder than it sounds...
