### ISSUE TITLE
EDNS0 interface needs to be exported

### ISSUE THREAD

**Issue by miekg** [miekg/dns#857]
The EDNS0 interface is
~~~
type EDNS0 interface {
	// Option returns the option code for the option.
	Option() uint16
	// pack returns the bytes of the option data.
	pack() ([]byte, error)
	// unpack sets the data as found in the buffer. Is also sets
	// the length of the slice as the length of the option data.
	unpack([]byte) error
	// String returns the string representation of the option.
	String() string
}
~~~
This means I can't externally define a new option; i.e. a bogus 100 one to do some EDNS0 compliance testing.

**Comment by tmthrgd** [comment]
This seems sensible to me. Should `pack` take a `[]byte` to allow it to avoid allocation and be more like `PrivateRR`?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] EDNS0 interface nee..." ]
>This seems sensible to me. Should `pack` take a `[]byte` to allow it to avoid allocation and be more like `PrivateRR`?

Maybe, don't you then need to know the size before hand?

**Comment by tmthrgd** [comment]
It would need a `Len` method then. Right now `(*OPT).len` calls `pack` just for the length.

`PrivateRdata` has one:
```go
// PrivateRdata is an interface used for implementing "Private Use" RR types, see
// RFC 6895. This allows one to experiment with new RR types, without requesting an
// official type code. Also see dns.PrivateHandle and dns.PrivateHandleRemove.
type PrivateRdata interface {
	// String returns the text presentaton of the Rdata of the Private RR.
	String() string
	// Parse parses the Rdata of the private RR.
	Parse([]string) error
	// Pack is used when packing a private RR into a buffer.
	Pack([]byte) (int, error)
	// Unpack is used when unpacking a private RR from a buffer.
	// TODO(miek): diff. signature than Pack, see edns0.go for instance.
	Unpack([]byte) (int, error)
	// Copy copies the Rdata.
	Copy(PrivateRdata) error
	// Len returns the length in octets of the Rdata.
	Len() int
}
```

**Comment by tmthrgd** [comment]
#1041 was reverted, see #1045 and #1046. Reopening for decision.

**Comment by micahhausler** [comment]
I'm developing a CoreDNS plugin and have a need to set a non-spec'd EDSN0 option, I see that the interface was made exportable and then reverted, is there a plan to make this breaking change tied to a future release? Is there a workaround for this besides forking this repository?

**Comment by miekg** [comment]
You probably don't need that to just have a custom EDNS0 option.

**Comment by miekg** [comment]
We've tried, maybe too hard, maybe something for a v2....
