### ISSUE TITLE
Serve DNS requests multiple times?

### ISSUE THREAD

**Issue by haosdent** [miekg/dns#865]
Hi, miekg masters.  I am reading the code of miekg, but I notice it seems process dns requests multiple times. Is it a bug?

In https://github.com/miekg/dns/blob/master/server.go#L282 , it enqueue the requests.

```
	case srv.queue <- w:
```

then in 

https://github.com/miekg/dns/blob/master/server.go#L244

```
	srv.serve(w)
```

and https://github.com/miekg/dns/blob/master/server.go#L269

```
			inUse = true
			srv.serve(w)
```

it processes the requests multiple times.

**Comment by tmthrgd** [comment]
@haosdent There's no bug here. The first line sends a request to an existing worker goroutine to process, the second is where it actually processes the request. The third line uses a shadowed variable:

https://github.com/miekg/dns/blob/450ab7d57fb96d2a1d85cc507d30a91d00185dd4/server.go#L264-L269

It's a different `w *request` variable that's just been removed from the queue.

**Comment by haosdent** [comment]
@tmthrgd thanks for your reply, but for

https://github.com/miekg/dns/blob/450ab7d57fb96d2a1d85cc507d30a91d00185dd4/server.go#L243-L244

We didn't dequeue it, so it would be processed again at 

https://github.com/miekg/dns/blob/450ab7d57fb96d2a1d85cc507d30a91d00185dd4/server.go#L263-L266

?

**Comment by tmthrgd** [comment]
@haosdent Oh I understand you're confusion.

In `spawnWorker` we **try** to enqueue the request with a non-blocking send:

https://github.com/miekg/dns/blob/450ab7d57fb96d2a1d85cc507d30a91d00185dd4/server.go#L280-L286

If no current worker is waiting on the queue, we then spawn a new worker goroutine that receives the `w *response`. So the `w *response` that's part of the `worker` function signature was never in the queue in the first place.

I hope that clears that up for you.

**Comment by haosdent** [comment]
@tmthrgd thanks a lot for your nice explanation, it is clear to me. Sorry for the stupid question.

**Comment by haosdent** [comment]
thx @miekg and @tmthrgd Orz
