### ISSUE TITLE
Reject nscount > 0?

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/dns#867]
https://github.com/miekg/dns/blob/450ab7d57fb96d2a1d85cc507d30a91d00185dd4/acceptfunc.go#L47

Regarding the DefaultMsgAccept function, I am not sure it would be appropriate to consider Nscount > 0 a reason to reject the request. An IXFR request could have a SOA record in the NS section.

Even though I know I could simply use a custom MsgAcceptFunc, I'm just considering if it'd be appropriate to be the default behaviour

**Comment by miekg** [comment]
Prolly make sense to allow that. Which RFC is this?

**Comment by cesarkuroiwa** [comment]
[RFC 1995](https://tools.ietf.org/html/rfc1995)

**Comment by miekg** [comment]
Sgtm.. please reference section 3 of that rfc in your PR
