### ISSUE TITLE
New revision of EDNS(0) Update Lease

### ISSUE THREAD

**Issue by andrewtj** [miekg/dns#869]
Draft 2 adds a new field: https://tools.ietf.org/html/draft-sekar-dns-ul-02#section-4

Might be better to tear it out till there's demand or a stable spec.

**Comment by miekg** [comment]
I have no problem with introducing a backward incomp change is the spec changes.

**Comment by andrewtj** [comment]
The new lease format is used in iOS 13 and macOS 10.15 so I doubt there'll be any further changes coming. Since a lease of zero seconds doesn't make a lot of sense, perhaps we can add the new `KeyLease` field as a `uint32` and not include it at pack time if it's zero.
