### ISSUE TITLE
syntax check zone

### ISSUE THREAD

**Issue by vtolstov** [miekg/dns#871]
i need to check syntax of zone file for example that MX record contains domain names and not ip address, os zone have SOA and NS records.
Does it possible to use something that already exists and uses RFC to check syntax, or i need to write own tool?

**Comment by tmthrgd** [comment]
Try the `ZoneParser` API. You can then check that all of the returned records meet your requirements.

**Comment by vtolstov** [comment]
i know about this, but i need to handle all stuff by hand and check

**Comment by miekg** [comment]
Yes you need to check the returned values yourself.
