### ISSUE TITLE
Notify messages no longer contain a serial number

### ISSUE THREAD

**Issue by paulf69487623** [miekg/dns#898]
Hello,

I have a tool that listens to NOTIFY messages from ISC Bind and reacts to them.  Between 1.0.15 and 1.1.0, the packet is no longer fully parsed.  Before, the Msg.Answers slice contained the SOA with the serial number.  Afterwards, the Msg.Answers slice is zero length.

I did a binary search through the commits, and it seems to break between 6aa28be and ab67d69, around 2018-11-28.  With 6aa28be it works as expected, but with ab67d69 the Answers slice is empty.

I'm happy to continue using 1.0.15 for now, but I figured I should report the issue.  If you have any further questions or would like an isolated test case, let me know and I can put something together.

Thanks,

Paul

**Comment by tmthrgd** [comment]
Thanks for the report. Are you able to provide a binary dump of one of these messages?

**Comment by tmthrgd** [comment]
Have you tried with 1.1.1+? Perhaps #868 is related.

**Comment by paulf69487623** [comment]
It looks like this change fixes it!  I rebuilt with HEAD and just this change, and the serial numbers are coming through as expected now.  Thanks!

I also feel like I should say that this is one of the best DNS libraries I've come across.  It has a great combination of both flexibility and usability.  Sending simple queries is simple, but doing more complicated things like sending and receiving NOTIFY messages is possible.  Fantastic work, everybody!

**Comment by miekg** [comment]
Thank you.

regarding this fix (and thanks for testing) care to send a PR?

**Comment by paulf69487623** [comment]
I'd be happy to, even though I didn't _actually_ make the fix! :)

My github keys are at home, so I'll put one together tonight.

Thanks again!

Paul

**Comment by paulf69487623** [comment]
Hello,

I just opened PR #899 with the fix I tested earlier today.

Thanks,

Paul

**Comment by miekg** [comment]
fixed via #900 (and #899)

**Comment by paulf69487623** [comment]
Thanks again, everybody!

Paul
