### ISSUE TITLE
Zone file parsing ignores meaningful line boundaries

### ISSUE THREAD

**Issue by gibson042** [miekg/dns#901]
When parsing zone files, a line break immediately following record type is ignored, resulting in acceptance and misinterpretation of invalid input:
```go
$ cat main.go
package main

import (
	"fmt"
	"github.com/miekg/dns"
	"strings"
)

func main() {
	fmt.Printf("; miekg/dns version: %v\n", dns.Version)

	zone := `
$ORIGIN example.com.
example.com. 3600 IN SOA ns.example.net. hostmaster.example.com. 1 86400 60 86400 3600
example.com. 3600 NS ns.example.net.

example.com. 60 PX
1000 TXT 1K
`
	for token := range dns.ParseZone(strings.NewReader(zone), "", "") {
		if token.Error != nil {
			fmt.Printf("; ERROR: %v\n", token.Error)
		} else {
			fmt.Println(token.RR.String())
		}
	}
}

$ go run main.go
; miekg/dns version: 1.1.3
example.com.	3600	IN	SOA	ns.example.net. hostmaster.example.com. 1 86400 60 86400 3600
example.com.	3600	IN	NS	ns.example.net.
example.com.	60	IN	PX	1000 TXT.example.com. 1K.example.com.
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] Zone file parsing ignor..." ]
>example.com. 60 PX
>1000 TXT 1K

Jep that's a bug, this is only allowed when using parens:

~~~ txt
example.com. 60 PX (
1000 TXT 1K )
~~~

**Comment by miekg** [comment]
So, we actually allow this for (again) dynamic updates. I added a guard against this:
~~~
diff --git a/scan.go b/scan.go
index a8691bca..62ac9aa3 100644
--- a/scan.go
+++ b/scan.go
@@ -650,10 +650,13 @@ func (zp *ZoneParser) Next() (RR, bool) {
 
                        st = zExpectRdata
                case zExpectRdata:
+                       if l.value == zNewline {
+                               return zp.setParseError("unexpected newline", l)
+                       }
                        r, e := setRR(*h, zp.c, zp.origin, zp.file)
                        if e != nil {
-                               // If e.lex is nil than we have encounter a unknown RR type
-                               // in that case we substitute our current lex token
+                               // If e.lex is nil than we have encounter an unknown RR type
+                               // in that case we substitute our current lex token.
                                if e.lex.token == "" && e.lex.value == 0 {
                                        e.lex = l // Uh, dirty
                                }
~~~
and this breaks other tests, like `TestLenDynamicA`. We could potentially check if this is near EOF or some such.

Even more when we parse the RDATA we should call `c.Next() // zBlank` is most places, all of those can be a newline as well - which will then be ignored and we happily parse the next line as well...

**Comment by gibson042** [comment]
Dynamic updates are conveyed via wire format, not master files... there is no valid context in which scanning presentation format data should accept a record without RDATA. I'm not sure about the rest, but that new guard seems good.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Zone file parsing i..." ]
>Dynamic updates are conveyed via wire format, not master files... there is no valid context in which scanning presentation format data should accept a record without RDATA. I'm not sure about the rest, but that new guard seems good.

it's backwards incompatible because we allow it now. And it's a convience way of 
building such a wire message, and thus this can't go in, in this form.

**Comment by miekg** [comment]
Some changes we can make here:
* `setRR` can be a method on `*ZoneParser` giving it more context. It should probably also get the lexer state
* if there we can check `l.value` as this is not checked at the moment and see if we got a newline *and then also see another token*

If the latter is true we error, otherwise we continue.

In a sense a `zp.Peek` would be nice, but I've looked at it and there is quite some state we carry, so I'm not sure how simple that would be to implement.

**Comment by tmthrgd** [comment]
Adding something like `(*zlexer).Peek` or maybe `(*zlexer).UnreadNext` should be easy because we don’t actually need to keep the previous state around. All we need is the ability to have two calls to `(*zlexer).Next` (or `Peek` + `Next`) return the same leader token.

Then it could be as simple as:
```
if l.value == zNewline && z.Peek().token != "" {
```

**Comment by miekg** [comment]
What do you mean exactly? We don't need (at least cache) the bytereader,
line and column values (for instance)?

**Comment by tmthrgd** [comment]
@miekg I’ll try and throw together a PR tomorrow to explain. I’m talking about the `l` and `nextL` fields on `zlexer`.

**Comment by tmthrgd** [comment]
@miekg We might be able to approach this differently by moving the dynamic update check out of the individual `parse` methods in `scan_rr.go`.

Almost all the different types have a dynamic update check (implicitly or explicitly), except for `RFC3597` and `TKEY`. Is not supporting dynamic updates in these two records intentional?

**Comment by miekg** [comment]
Sgtm.

TKEY and RFC3597 might be just an oversight.
