### ISSUE TITLE
Issue with dnssec validation

### ISSUE THREAD

**Issue by bcebere** [miekg/dns#907]
Hi,

I am testing some scenarios for DNSSEC validation and I have a few situations where I am not sure am I doing the right thing.

Reproduction steps:

 - dig albumarium.com(some random domain, I have other examples too)
 - Validation for section `albumarium.com.	1800	IN	A	37.205.9.229`
 - RRSIG for section `albumarium.com.	1800	IN	RRSIG	A 7 2 1800 20190918094616 20180918094616 56890 albumarium.com. O4XqePOXkQsXzVZAbvDwOq/JVHMczM6uPwCVT33Z5UIjJRTIvE3YA03cnPrMbfSq/DcdvK9NOc3RlzoVOoHa0mEfQc3Vdlaz/nCR49lfcDv4qHPFgvEZGzh94ZoPm0cWcrONAC+Ja8xVr+rmnUon1U2du8Sa701iuSgkUrcLgI0bahVKdfBUN2HK2cGtIGVuXxPm3oVROz4Xxoc8zrOBAXqBxD2M/W6UPMTDBEhFPNDHQE2EbMPU0OKDZ03v1aIY1H/ku35Obj4gltXwQEdHEgGpILGNiKkGb0LsUfqJkSyjIVH1rCg5Lj/D+1bMxCobkI1hudBLCjqm0VnXG08QoMJyew5OXRNRE7Wp4gyvmBeTCa2b3rGI6ilA/BdJcCh5MHIZw+qQV8I/w/MOs88aXv47qavS8ORJr8zWVn4kHRYD6IFwdkJhwZENQ/u+WomMzy+pZrgVILJ5YtwpR0bXyLglvRu0s/0Ue4CUxh1pDg8JYOdLE8oduN8MJ0CA9Ok9YcSwJj3wuDVzjU1a18FBZcUiRZmK4Kk/6ZqGLGVoV2Xrh+hhT41HYfLJEZ4G2UIrazVd09lj9f61paeeOvKe5b50QbOrycserKVk2ZHENalc0dcOQEWPhdBrOIfUKGi/BTvopJAPlmRTJlPqgoXQAFvkKf2i57HF9epTJkXs99A=`
 - Key for validation: `albumarium.com.	1800	IN	DNSKEY	256 3 7 BQEAAAAB9QdSKCeptWzBV1tlAFU+AaiSGgU7XaUY6YHgtUQ1ggPvJAplv3N9Xt8vB+z7/FThK4gxzQ3xZ+Y0xZ0sEnQVdl05XTfrrOGjwr6x3PwxwepWONVZ6FXDb+LhEFx95kYOIjhLnyr5UvOHu9vFOEu1mMENo9gdg00DMBX+tXNBxiHIXzsFUE90QmXBro2GH4EHqTX+4ZVuNCOFhzAnp3h+O7SQTR8npmdRrmWJvC42uT6ODGEFOnstZ+vJDQnc3ZLvzJvuaXK9pUGJmIQ75MEs9xcngf7JXRmW/FqsTph0ZcAXUoad8+Tu43Z0+V1Znf7WtCfODqqjKsKklt7CdY7R6NzEV9b5F//rvG88wZeg+PKXNVbQFFSzyguEsFrvjrTThdKjyDPfbMRl/vMeoB/dfnB1VP5Ds1zMpqqYqiPPVLBmCjuRC2EalK3tPh3y9U2xE+A2vytXETew+T+nX9ZG62rS7YnKwsMYrSzUPDTXYgCVwsDM/2Ecl5XEpemOnTvMmQGh7LUuYs/kK2hImPew5ntAQC6jnGr37xC3xtBfkFQN4sV5iSOvZWs5mjP2iEhGEFl5fRqU0Zvck0vOCHBBU0oRj8k4VUpUKSFe2W4iKolj2VS9Jr7S5WIFGFMHUfhyC1j5FVAqSyLBnEKOWper3O+dMQrtWTRl5L1H7v96O/E=`

 - Verify exits with `badkey` error. Adding logs to the dns library, I can see that there was a null public key extracted for algorithm RSASHA1-NSEC3-SHA1, (dnssec.go:450)
 - The public key is null because the condition at dnssec.go:543 fails. explen is 5 there.

Comparing notes, I see that the validation should be fine
 https://dnssec-analyzer.verisignlabs.com/albumarium.com

Am I doing something wrong here?

Thanks

**Comment by tmthrgd** [comment]
This is working as intended, see https://github.com/miekg/dns/issues/788#issuecomment-429248467.

The use of such large exponents isn’t good practice and won’t be supported by go or this library.
