### ISSUE TITLE
make udp.go more efficient

### ISSUE THREAD

**Issue by miekg** [miekg/dns#910]
Right now in udp.go we have
~~~
// parseDstFromOOB takes oob data and returns the destination IP.
func parseDstFromOOB(oob []byte) net.IP {
	// Start with IPv6 and then fallback to IPv4
	// TODO(fastest963): Figure out a way to prefer one or the other. Looking at
	// the lvl of the header for a 0 or 41 isn't cross-platform.
	cm6 := new(ipv6.ControlMessage)
	if cm6.Parse(oob) == nil && cm6.Dst != nil {
		return cm6.Dst
	}
	cm4 := new(ipv4.ControlMessage)
	if cm4.Parse(oob) == nil && cm4.Dst != nil {
		return cm4.Dst
	}
	return nil
}

// correctSource takes oob data and returns new oob data with the Src equal to the Dst
func correctSource(oob []byte) []byte {
	dst := parseDstFromOOB(oob)
	if dst == nil {
		return nil
	}
	// If the dst is definitely an IPv6, then use ipv6's ControlMessage to
	// respond otherwise use ipv4's because ipv6's marshal ignores ipv4
	// addresses.
	if dst.To4() == nil {
		cm := new(ipv6.ControlMessage)
		cm.Src = dst
		oob = cm.Marshal()
	} else {
		cm := new(ipv4.ControlMessage)
		cm.Src = dst
		oob = cm.Marshal()
	}
	return oob
}
~~~
this allocate a `ipvN.ControlMessage` twice - and these structure are not super tiny. Might be worth seeing if this can be done better.

**Comment by tmthrgd** [comment]
They should be stack allocated and virtually feee though? Or am I missing something?

**Comment by miekg** [comment]
Think that we can avoid allocating the ControlMessage structs twice; something along the lines of https://github.com/miekg/dns/pull/912/files

**Comment by tmthrgd** [comment]
Is this showing up in a trace or something? I’m pretty sure they should just be on the stack and not real allocations as such. Can you add a quick benchmark and compare?

**Comment by miekg** [comment]
I agrree this is a very minimal improvement; I'll file another issue shortly about what we're trying to solve.

with "on the stack" you mean they fall in the 2K stack you get per default in a goroutine and not having them wouldn't directly see any improvement?

**Comment by tmthrgd** [comment]
Are these structs really that big to begin with? I haven’t confirmed, but they don’t look that big go me.

As these don’t escape and have a known side they won’t be heap allocated or need garbage collecting. I can’t see any change here even being observable. You’d need benchmarks to confirm either way.

**Comment by miekg** [comment]
Yeah. I think you're right and this is useless and just busywork for no
gain.
