### ISSUE TITLE
remove some `defers` from the hotpath

### ISSUE THREAD

**Issue by miekg** [miekg/dns#926]
looking through the server code in server.go we can probably get rid of a few defers (at some readability cost though)

**Comment by tmthrgd** [comment]
Just doing a quick once-over, I can only see one defer that’s really in a hot path. The defer in `(*Server).serve` for TCP connections. It would be possible to eliminate it, but I’m not sure if it would worthwhile or not.

**Comment by miekg** [comment]
indeed, tackled that in the `reverty` PR. There are no early returns so `defer` does not actually make sense there.

**Comment by miekg** [comment]
closing as done.
