### ISSUE TITLE
drop queries when processing takes to long (> 6s)

### ISSUE THREAD

**Issue by miekg** [miekg/dns#936]
Just filed https://github.com/coredns/coredns/issues/2663 to think about dropping queries when forwarding. This *may* make sense to do in this lib (although I'm not yet convinced it should)

**Comment by tmthrgd** [comment]
This feels like a good idea for it to be in CoreDNS, but I don't think it makes sense in this library. Timeouts can already be set on the `Client` if desired, and I don't think there's a clean place for them in the server. Also, isn't it completely valid for queries in certain configurations (things like zone transfers) to take quite a long time?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] drop queries when p..." ]
>This feels like a good idea for it to be in CoreDNS, but I don't think it makes sense in this library. Timeouts can already be set on the `Client` if desired, and I don't think there's a clean place for them in the server. Also, isn't it completely valid for queries in certain configurations (things like zone transfers) to take quite a long time?

Yeah, I think this is too hard to do in a generic way.
