### ISSUE TITLE
Getting issue "domain must be fully qualified"

### ISSUE THREAD

**Issue by smaheshs** [miekg/dns#944]
Hi,

Using the examples I have written the below code:

```
	m := &dns.Msg{
		Question: make([]dns.Question, 1),
	}

	c := new(dns.Client)

	m.Question[0] = dns.Question{"654321910719e164arpa", dns.TypeNAPTR, dns.ClassINET}

	in, rtt, err := c.Exchange(m, "172.61.155.218:53")

	if err != nil {
		fmt.Println(err)
	}

```
However when I run it I always get the error "domain must be fully qualified". I have seen several examples in the documentation where the Exchange function is given an IP address and port.

Any help about why it is forcing a domain name would be helpful.

**Comment by miekg** [comment]
make your domain fully qualified.

**Comment by tmthrgd** [comment]
@smaheshs The problem isn’t the IP address in the `Exchange` call, but the domain name in the `dns.Question` struct. You need to make that domain fully qualified.

**Comment by smaheshs** [comment]
@tmthrgd Thanks a lot for the input. Since the error was coming in the Exchange call, wasted must time focusing only here. Fixed finally.
