### ISSUE TITLE
question: Is there any known net.Resolver drop-in using this project?

### ISSUE THREAD

**Issue by bwplotka** [miekg/dns#953]
Sorry for spam, but as per title, wonder if there is any implementaiton using https://github.com/miekg/dns/blob/master/client.go#L29 that has the same interface as `net.Resolver`?  (:

**Comment by miekg** [comment]
Not that I'm aware but is probably trivial to write

**Comment by bwplotka** [comment]
Wow, I am surprised (: Might be super useful. Our attempt in [Thanos](https://github.com/improbable-eng/thanos): https://github.com/improbable-eng/thanos/pull/1016 Only for two methods though.

I think major blocker for this is that golang net.Resolver might be too restrictive. (e.g no way to return SRV record TTL.). 

Anyway, though someone already did this work (I am pretty sure it's there in some closed source ;>).

Thanks for a good work on this!
