### ISSUE TITLE
Question: TTL is signed int or unsigned int

### ISSUE THREAD

**Issue by yygt** [miekg/dns#956]
In the code, I see Ttl is uint32:
type RR_Header struct {
	Name     string `dns:"cdomain-name"`
	Rrtype   uint16
	Class    uint16
	Ttl      uint32
	Rdlength uint16 // Length of data after header.
}

But in RFC 1035:
TTL             a 32 bit signed integer that specifies the time interval
                that the resource record may be cached before the source
                of the information should again be consulted.  Zero
                values are interpreted to mean that the RR can only be
                used for the transaction in progress, and should not be
                cached.  For example, SOA records are always distributed
                with a zero TTL to prohibit caching.  Zero values can
                also be used for extremely volatile data.

So it's by design or not? I know there is no much difference, just curious :-)

**Comment by miekg** [comment]
I never knew that a TTL was signed, hence the uint32 (which is technically 
wrong). I don't think the sign bit is actually used. Doing negative TTLs does 
make for an interesting experiment though.

**Comment by Habbie** [comment]
From [erratum 2130](https://www.rfc-editor.org/errata/eid2130): 

> It should say:
> 
> TTL             a 32 bit unsigned integer

From [2181 8](https://tools.ietf.org/html/rfc2181#section-8):

> The definition of values appropriate to the TTL field in STD 13 is
>  not as clear as it could be, with respect to how many significant
>  bits exist, and whether the value is signed or unsigned.  It is
> hereby specified that a TTL value is an unsigned number, with a
> minimum value of 0, and a maximum value of 2147483647.

Also from 2181 8, regarding 'negative' TTLs:

> Implementations should treat TTL values received with the most
> significant bit set as if the entire value received was zero.

**Comment by miekg** [comment]
ha TIL. We don't do this atm. *Probably* makes sense to implement 2181 is normalize returned TTL values; right now you just get a big value

**Comment by yygt** [comment]
Thanks for the answer. RFC gives us direction, also the questions :-)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Question: TTL is si..." ]
>Thanks for the answer. RFC gives us direction, also the questions :-)

As said, might be worth following up with a PR to mask the higher or lower bits 
in the TTLs

**Comment by pusateri** [comment]
We ran into this question with the DNS Push Notifications draft and I polled all the DNS experts at the IETF Hackathon in Prague and they all said the TTL is unsigned.
