### ISSUE TITLE
fully support DNS cookies (RFC 7873)

### ISSUE THREAD

**Issue by miekg** [miekg/dns#963]
DNS Cookies look useful and regardless it's an IETF standard so this lib should have support for it. See https://tools.ietf.org/html/rfc7873

**Comment by miekg** [comment]
OK, after a read of RFC 7873 a summary, we already have the `*EDNS0_COOKIE` type.

## General

* client cookie is: hash(client ip + server ip + secret) (needs to change the secret "regularly")
* server cookie is: hash(client ip + client cookie + secret) (needs to change the secret "regularly")

This can be implemented by just providing some functions that do this, leaving the "regularly" part out of it.

## Querying

Just add the cookie to the request, if lucky the client has the server cookie, if not the server can respond with BADCOOKIE (which has the server cookie). Or the client can query for the server cookie via a special request: https://tools.ietf.org/html/rfc7873#section-5.4
(This requires changes the default `AcceptFunc` to allow an empty question section.

## Replying 

5 possibilities
1. no OPT or no cookie in client, handle as-is (in some future this would obvs become discard the query)
2. malformed cookie --> FORMERR
3. only client cookie (see below)
4. client cookie, invalid server cookie -> error
5. client cookie and server cookie -> handle

For 3. there are three options
1. discard (do reply to 1/N of these to help bootstrap).
2. send BADCOOKIE back (with server cookie)
3. normal reply

## Implementation in this lib

It looks we can just add a few helper functions to deal with Cookies and amend the default `AcceptFunc` to check for this (this is a change that worries me a bit, because of amplification attacks)

**Comment by miekg** [comment]
See https://twitter.com/OGudm/status/1125929451919892480 which will probably make me reconsider. We still may want to add some helpers; but people can also write their own.

**Comment by tmthrgd** [comment]
What do other DNS implementations do? Cloudflare’s 1.1.1.1 and Google’s 8.8.8.8 for example, BIND, etc.

Helpers sound fine. Integration sounds doable and not too hard to integrate.

**Comment by miekg** [comment]
both seems to not support it, dig hides things from you, but I expect to loudly exclaim that a cookie has been found in the reply; so my guess would be: not supported

**Comment by chantra** [comment]
@miekg during IETF 104 Hackathon, folks from NLNetLabs, ISC, CZ.NIC and PowerDNS agreed on interoperability.
please consider
* https://datatracker.ietf.org/meeting/104/materials/slides-104-dnsop-sessb-interoperable-dns-server-cookies-00
* https://tools.ietf.org/html/draft-sury-toorop-dns-cookies-algorithms-00

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] fully support DNS c..." ]
>@miekg during IETF 104 Hackathon, folks from NLNetLabs, ISC, CZ.NIC and PowerDNS agreed on interoperability.
>please consider
>* https://datatracker.ietf.org/meeting/104/materials/slides-104-dnsop-sessb-interoperable-dns-server-cookies-00
>* https://tools.ietf.org/html/draft-sury-toorop-dns-cookies-algorithms-00

Thanks that makes it slightly easier to implement some helper functions. Note 
that SIPHASH(24) is not in the std lib.

**Comment by tmthrgd** [comment]
@miekg A helper function could perhaps take a user supplied `func() hash.Hash` (see crypto/hmac) so that callers can pass in `func siphash.New() hash.Hash` or something similar.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] fully support DNS c..." ]
>@miekg A helper function could perhaps take a user supplied `func() hash.Hash` (see crypto/hmac) so that callers can pass in `func siphash.New() hash.Hash` or something similar.

 :-) I was thinking along the same lines. Does it need to be a function? Or can 
 we just use hash.Hash?

**Comment by tmthrgd** [comment]
@miekg It can just be a `hash.Hash`, but we’ll need to call `Reset` before using it. That probably makes more sense given the usage and that it’s a keyed MAC.

**Comment by miekg** [comment]
I may do a final pass to see if this warrants adding something to the lib, otherwise I'll close

**Comment by miekg** [comment]
so, this looks to be too trivial:
~~~
// CookieClient calculates the client cookie using h.
func CookieClient(h hash.Hash, client, server net.IP, secret string) []byte {
	h.Write(client)
	h.Write(server)
	io.WriteString(h, secret)
	return h.Sum(nil)
}
~~~
as an example. ServerCookie is similar, don't really see added benefit of adding these.
