### ISSUE TITLE
NAPTR Replacement escaped characters

### ISSUE THREAD

**Issue by TeoV** [miekg/dns#965]
Greetings,

First, we want to thank you for such a great library.
Second, we have a problem with Replacement from NAPTR struct ( https://github.com/miekg/dns/blob/master/types.go#L630 ) 
We have a basic configuration ( client send a request to server and server reply with a response) 
We want to obtain the following Replacement in reply: ` sip:\1@172.16.1.1. `
We tried to send the following strings to dns.ResponseWriter to be written into the reply : 
```
Case 1 : sip:\1@172.16.1.1. we got in reply : sip:1\\@172.16.1.1.
Case 2 : sip:\\1@172.16.1.1. we got in reply : sip:\\\\1\\@172.16.1.1.
```
Also after a quick search found that this function : 
https://github.com/miekg/dns/blob/master/types.go#L513

What's the solution to achieve the response in Replacement from above? 

Thanks,
TeoV

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] NAPTR Replacement escap..." ]
>Greetings,
>
>First, we want to thank you for such a great library.
>Second, we have a problem with Replacement from NAPTR struct ( https://github.com/miekg/dns/blob/master/types.go#L630 )
>We have a basic configuration ( client send a request to server and server reply with a response)
>We want to obtain the following Replacement in reply: ` sip:\1@172.16.1.1. `
>We tried to send the following strings to dns.ResponseWriter to be written into the reply :
>```
>Case 1 : sip:\1@172.16.1.1. we got in reply : sip:1\\@172.16.1.1.
>Case 2 : sip:\\1@172.16.1.1. we got in reply : sip:\\\\1\\@172.16.1.1.
>```
>Also after a quick search found that this function :
>https://github.com/miekg/dns/blob/master/types.go#L513
>
>What's the solution to achieve the response in Replacement from above?

Sorry, what's the problem? 'Replacement' is defined as a domain name so escaping 
these characters is completely according to the spec.

**Comment by TeoV** [comment]
Hi @miekg,

Thanks for the response.
Please tell us what should we put for Replacement to obtain `sip:\1@172.16.1.1.` in response for the client. ( the server build the response and send to the client. What value/string should we put for Replacement so the client receives the data from above ) 
We tried a lot of possibilities but we can't find the right one :(. 

Thanks,
TeoV
