### ISSUE TITLE
DNSSEC: remove old(er) algorithms

### ISSUE THREAD

**Issue by miekg** [miekg/dns#968]
See https://tools.ietf.org/html/rfc6944 and https://indico.dns-oarc.net/event/31/contributions/688/attachments/650/1067/matthijs-mekking-oarc30-unsupported-algorithms.pdf (what does BIND9 do) on what algorithms should be used.

This means `RSAMD5` should not be supported going forward, and probably a couple of others. I'm in favour of actually returning an "Unsupported Algorithm" error in such cases.

**Comment by tmthrgd** [comment]
I 100% support this. Old algorithms should be removed when possible. If all other major software has removed support for RSAMD5, then we should too and hopefully that won’t break anyone. The others removed in BIND9 should probably be removed as well.

**Comment by miekg** [comment]
closed via 9c315c51 and 0930b62a
