### ISSUE TITLE
How to create answers to qType ANY

### ISSUE THREAD

**Issue by renanbastos93** [miekg/dns#969]
I am trying use this lib, but I did not understand how to create RR to type ANY

**Comment by miekg** [comment]
ANY is a meta type, you can't make an RR to respond with it. In fact any reply is valid, see https://tools.ietf.org/html/rfc8482 for instance.

**Comment by renanbastos93** [comment]
Really? But I am based on resolutions of the AWS and NS1, it returns all answers set to question.

Example:
```
$ dig ANY example.com
; <<>> DiG 9.10.6 <<>> ANY example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38323
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.com.			IN	ANY

;; ANSWER SECTION:
example.com.		135429	IN	NS	ns-1.yourdns-07.com.
example.com.		135429	IN	NS	ns-2.yourdns-02.net.
example.com.		135429	IN	NS	ns-3.yourdns-44.org.
example.com.		135429	IN	NS	ns-4.yourdns-44.co.uk.
```

**Comment by miekg** [comment]
yes, anything goes with ANY, this reply is valid to your query. You're asking for all record types of the name `example.com.`

**Comment by renanbastos93** [comment]
Exactly, but I am trying to implement the same answer in my DNS.
I did have evolution but the `dig` show the 2 warnings.
![image](https://user-images.githubusercontent.com/8202898/58051640-1b18da80-7b29-11e9-92c4-283bb0bf03b7.png)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] How to create answe..." ]
>Exactly, but I am trying to implement the same answer in my DNS.
>I did have evolution but the `dig` show the 2 warnings.
>![image](https://user-images.githubusercontent.com/8202898/58051640-1b18da80-7b29-11e9-92c4-283bb0bf03b7.png)

you claim to have 7 RRs in the answer section and there are only two?

Anyway this does not seem to concern this library as such

**Comment by renanbastos93** [comment]
yep, but I register in my struct 3 awnsers see below

@ reference the apex domain
```
Qtype   Record     Zone                    Awnser
 A           @           `kaiowas.com`    `10.1.3.2`
 AAAA       @           `kaiowas.com`    `2800:3f0:4001:805::200e`
 MX        @           `kaiowas.com`    `1 mail.something.com`
```

But I guess that is can an error logic, I will to try another approach.

**Comment by renanbastos93** [comment]
I resolved thanks a lot
