### ISSUE TITLE
zone parsing: return more comments

### ISSUE THREAD

**Issue by miekg** [miekg/dns#978]
Right now the zoneparser returns comment after an RR:
`example.org. IN A 10.10.10.1 ; a comment`
will return "a comment" to the caller.

This is useful-ish, but I'm contemplating to more DNSSEC work in CoreDNS and leaving comments intact while rewriting a zonefile has some appeal. 

I'm looking to see if we can attach comment string to the next RR being read and return that. i.e.
~~~
; a comment
example.org IN A 10.10.0.1; another comment
~~~
would return "a comment another comment" as the comment string. 

This would allow the following use-cases:
* store state of DNSSEC operations in a comment at the top
* keep user's comment while rewriting zone files.

Attaching comments to a RR means that a comment after the last RR won't be seen by the parser and will be ignored.

**Comment by tmthrgd** [comment]
I’m pretty sure this would be non-trivial, though I could be wrong.

Both `ParseZone` and `ZoneParaer` are documented as discarding comments that are on a blank line, so this would be a change to documented behaviour.

**Comment by miekg** [comment]
Yeah, I think I agree. Alternatively I can use the current behaviour and
store some metadata on the SOA record or something; need to work out what I
want/need exactly.
