### ISSUE TITLE
response.Close is not thread safe

### ISSUE THREAD

**Issue by miekg** [miekg/dns#983]
See https://github.com/coredns/coredns/pull/2866#issuecomment-499901882
This should just work, but hits a data race in this lib, from the looks of it on the `close` member in the response.

This probably need a mutex or some such.

**Comment by tmthrgd** [comment]
I have a suspicion that `coredns/plugin/file/xfr.go` is racy otherwise.

What happens if we flip the order of `w.hijacked` and `w.closed` checks in `serveTCPConn`? I think that would fix any data races as `Hijack` needs to be called in the `ServeDNS` goroutine.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] response.Close is n..." ]
>I have a suspicion that `coredns/plugin/file/xfr.go` is racy otherwise.
>
>What happens if we flip the order of `w.hijacked` and `w.closed` checks in `serveTCPConn`? I think that would fix any data races as `Hijack` needs to be called in the `ServeDNS` goroutine.

Wondering the same thing, but didn't have time to play with it yet. Will do that 
today (hopefully)

**Comment by miekg** [comment]
Having some discussion: https://github.com/coredns/coredns/pull/2886

It looks highly natural you can Close and Hijack in different goroutines, so I'm inclined to say these should be guarded by some kind of mutex.

**Comment by tmthrgd** [comment]
`Hijack` has to be called before the `ServeDNS` Handler exits, but I guess it doesn’t need to be in that goroutine.

Adding a mutex will add overhead for what feels like a niche use case with a simple enough workaround. As far as I know, nowhere is it documented that methods are safe to call concurrently.

My personal preference would be to document that `ResponseWriter` must not outlive the `ServeDNS` handler and that methods can’t be called concurrently. That is exactly how `net/http` is documented, see [here](https://golang.org/pkg/net/http/#ResponseWriter) and [here](https://golang.org/pkg/net/http/#Handler).

**Comment by miekg** [comment]
Fair enough.. deviating from net/http also doesn't sit well we me.

Thanks for your input.

**Comment by miekg** [comment]
this has been fixed by *not* using Hijack, but waiting for the transfer to be done and then returning (and letting the server call w.Close).
