### ISSUE TITLE
TTL field under Answer is not coming correctly

### ISSUE THREAD

**Issue by rathega** [miekg/dns#985]
In dns.Msg I am interested in the Answer part. The TTL value in Answer is always coming as 5 so I suspected an error and was debugging the msg before unpacking the fields and also did a packet capture to compare them.

Added a print in github.com/miekg/dns/msg_helpers.go as follows:
func unpackHeader(msg []byte, off int) (rr RR_Header, off1 int, truncmsg []byte, err error) {
    hdr := RR_Header{} 
    if off == len(msg) { 
        return hdr, off, msg, nil
    }

    fmt.Printf("\nInitial Offset: %v Msg: %v", off, msg[off:])

Output:
Initial Offset: 32 Msg: [192 12 0 1 0 1 0 0 0 5 0 4 172 217 194 104 192 12 0 1 ....]

From packet capture:
0000   c0 0c 00 01 00 01 00 00 00 f5 00 04 ac d9 c2 68

www.google.com: type A, class IN, addr 172.217.194.104
    Name: www.google.com                                                 -> c0 0c   (192 12)
    Type: A (Host Address) (1)                                             -> 0 1        (00 01)
    Class: IN (0x0001)                                                           -> 0 1        (00 01)
    Time to live: 245                                                              -> 0 0 0 5 (00 00 00 f5) --> ((wrong))
    Data length: 4                                                                  -> 0 4        (00 04)
    Address: 172.217.194.104                                               -> 172 217 194 104 (ac d9 c2 68)

The pointed time to live field msg value is wrong from packet capture. Please point to any root cause if already known or correct me if I am wrong.

**Comment by tmthrgd** [comment]
Is this coming up using `dns.Client` or `dns.Server`? Do you have a simple reproduction we can test or steps to reproduce (including what DNS resolver or resolver software you're using)?

**Comment by rathega** [comment]
This is with dns.Client. Please find the setup used at https://github.com/rathega/testdns.git. Follow readme file to repro. Also Added print to display Dns Answer fields along with TTL field.

**Comment by rathega** [comment]
Tried few things and found this. Looks like the behaviour is not because of the library but because of the platform.

(for any website the same value 5 comes irrespective of wifi network connected to and saw the same behaviour in other Mac machines as well!)
**On my Mac, I got the following values for nslookup**:
----------------------------------------------------
RATHEGS-M-C3XA:app rathegs$ nslookup -debug google.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

------------
    QUESTIONS:
	google.com, type = A, class = IN
    ANSWERS:
    ->  google.com
	internet address = 172.217.163.174
	**ttl = 5**
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:	google.com
Address: 172.217.163.174

**On a Lenovo Thinkpad getting ttl values like expected**:
--------------------------------------------------------
C:\Users\rakbansa>nslookup -qa=A -debug google.com 8.8.8.8
------------
Got answer:
   HEADER:
        opcode = QUERY, id = 3, rcode = NOERROR
        header flags:  response, want recursion, recursion avail.
        questions = 1,  answers = 1,  authority records = 0,  additional = 0
 
    QUESTIONS:
        google.com, type = A, class = IN
    ANSWERS:
    ->  google.com
        internet address = 172.217.26.174
        **ttl = 286 (4 mins 46 secs)**


So looks to be a different issue and not related to library. Please add in your comments if any and I will close this issue.
