### ISSUE TITLE
dns.Truncate return size as int

### ISSUE THREAD

**Issue by miekg** [miekg/dns#990]
It would be nice if `Truncate` returned the length of the message. I'm finding myself doing another Len() to see if I can avoid fragmentation when talking over UDP.

This would be a breaking change, but Truncate is relatively new.

**Comment by tmthrgd** [comment]
This is doable, but slightly more complicated than it seems. `truncateLoop` doesn’t keep track of the exact length when it hits the limit. We’d have to add a third return value to `truncateLoop` and return `l` before adding the record length.

**Comment by miekg** [comment]
don't care *that* much. Closing
