### ISSUE TITLE
feedback: relative String() for an RR

### ISSUE THREAD

**Issue by miekg** [miekg/dns#991]
I'm trying to output an RR relative to an origin; to write out a zone file. This turns out to be non-trivial, mostly because an `@` is a zonefile construct and doesn't exist in actual DNS data. I.e current attempt to rewrite the domain name itself returns:
~~~
\@	3600	IN	TXT	"blaat"
~~~
I wonder if there is something that can be done here, or that I just need to be more creative.

Sidenote: why not output the zone as-is? Well, the zone may be shared between multiple origins when *reading* it. Outputting it fully qualified means multiple copies and also bloats the file unnecessary.

**Comment by gibson042** [comment]
I have thought for a while that it might be useful to add something like a `RelativeString(origin string, relativeRdata bool)` method to RR. An `origin` field might also be useful, either separately or in conjunction.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] feedback: relative ..." ]
>I have thought for a while that it might be useful to add something like a `RelativeString(origin string, relativeRdata bool)` method to RR. An `origin` field might also be useful, either separately or in conjunction.

Thanks for your thoughts.

I think adding another field might be prohibitive from a memory standpoint.

I've seen other requests for something like this, so maybe a callback function 
might work better, but then you know what rdata field your working on. So maybe 
that overkill and the above is the only thing that's needed.

**Comment by miekg** [comment]
Adding #992 for some code to discuss

**Comment by miekg** [comment]
I can't use this for the use case I had in mind (signing a relative zone) as the signer's name is included in the signature data. 

From dnssec.go:
~~~
// For signing, lowercase this name
sigwire.SignerName = strings.ToLower(rr.SignerName)
~~~
This might still be useful; but it's a big change, so I won't push for it.

**Comment by tmthrgd** [comment]
I don’t like the idea (#992) of every RR type having to have two `String` implementations that then have to be kept in sync.

Doesn’t something like this work? (Or could we make something like this work).
```go
r2 := dns.Copy(rr)
r2.Header().Name = "@"
r2.String()
```

**Comment by miekg** [comment]
That converts @ into \@ on string conversion.

**Comment by tmthrgd** [comment]
If there will always be a single @, this should work:
```go
r2 := dns.Copy(rr)
r2.Header().Name = "@"
strings.Replace(r2.String(), "\\@", "@", 1)
```

While it’s not exactly elegant, I think having to add a second String method should be a deal breaker so the above might be the best option.

**Comment by gibson042** [comment]
> I can't use this for the use case I had in mind (signing a relative zone) as the signer's name is included in the signature data.

That's why I suggested a two-parameter `RelativeString(origin string, relativeRdata bool)`, with the second parameter controlling whether or not RDATA should also be presented relative to the specified origin. But that gets into @tmthrgd's concern:

> I don’t like the idea (#992) of every RR type having to have two `String` implementations that then have to be kept in sync.

Which I agree in principle, but in practice changes to serialization should be so rare that it may not matter.

> ```go
> r2 := dns.Copy(rr)
> r2.Header().Name = "@"
> strings.Replace(r2.String(), "\\@", "@", 1)
> ```

That works for the specific case of owner name matching zone origin (as would e.g. `r2.String()[1:]`), but such manipulation seems to be a sign that something has gone wrong.

That said, I like the _direction_ of the changes but don't know if I'm convinced that they are warranted.

**Comment by miekg** [comment]
closing this, thanks for the discussion.
