### ISSUE TITLE
resource is not signed with RRSIG

### ISSUE THREAD

**Issue by hazcod** [miekg/dns#993]
Hi, I am trying out `miekg/dns` in `github.com/hazcod/goresolver`.
Calling `r, err := resolver.StrictNSQuery("ironpeak.be", dns.TypeA)` returns: `resource is not signed with RRSIG`.

Reason of this issue is that my domain is behind Cloudflare where DNSSEC should be enabled.
Code:  https://github.com/hazcod/goresolver/blob/master/lookup.go#L111

Any ideas?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] resource is not signed ..." ]
>Hi, I am trying out `miekg/dns` in `github.com/hazcod/goresolver`.
>Calling `r, err := resolver.StrictNSQuery("ironpeak.be", dns.TypeA)` returns: `resource is not signed with RRSIG`.
>
>Reason of this issue is that my domain is behind Cloudflare where DNSSEC should be enabled.
>Code:  https://github.com/hazcod/goresolver/blob/master/lookup.go#L111
>
>Any ideas?

You need to open an issue in that repo, not here.

**Comment by hazcod** [comment]
Linking https://github.com/peterzen/goresolver/issues/2

**Comment by hazcod** [comment]
My resolver did not support dnssec.
