### ISSUE TITLE
wildcard DNS records

### ISSUE THREAD

**Issue by Shagon94** [miekg/dns#995]
How would we go about checking if one DNS record is a wildcard and therefor matches a specific one?

To give you a rough idea if we have a `*.domain.com` and `example.domain.com` how would we check and match them? The closest thing I came across is the `CompareDomainName` however that only checks from the right; What I'm trying to say is how do we go about checking if a DNS record, that's a wildcard matches a specific one?

If we use `CompareDomainName` then should we check for the class and the type of the DNS record to match them?

A more structured question would be: With a set of 2 DNS records how do we check if one matches another?

Additionally if we have a slice of `[]dns.RR{}` how do we go about checking and replacing old records?

Currently I have the following in place:

```
| domain             | ttl  | record | value   |
|--------------------|------|--------|---------|
| random.domain.name | 3600 | A      | 1.1.1.1 |
| a.s.d              | 3600 | A      | 2.2.2.2 |
| example.com        | 3600 | A      | 3.3.3.3 |
```

Then when refreshing the `[]dns.RR{}` with the new records:

```golang
rrs := []dns.RR{}
rrsSize := len(rrs)

p := dns.NewZoneParser(reader, "", zurl)
for rr, ok := p.Next(); ok; rr, ok = p.Next() {
  rrs = append(rrs, rr)
}

rrs = rrs[rrsSize:]
m := make(map[string]dns.RR)
rrs = dns.Dedup(rrs, m)
```

Granted I've taken chunks out of the code out however the current implementation adds to the array and then dedups it after searching from the appended place to the end.

i.e. if the array had 3 records and we updated the DNS zone file as so:

```
| domain              | ttl  | record | value   |
|---------------------|------|--------|---------|
| random.domain.name  | 3600 | A      | 1.1.1.1 |
| a.s.d               | 3600 | A      | 2.2.2.2 |
| example.com         | 3600 | A      | 8.8.8.8 |
| another.example.com | 3600 | A      | 7.7.7.7 |
```

Changing `example.com` and adding `another.example.com` the `rrs` would be of length 7 then we truncate it `rrs = rrs[rrsSize:]` and dedup it for any duplicates `rrs = dns.Dedup(rrs, m)`

This implementation feels..dirty. Now I feel I've strayed away from the topic adding another question to the original thread however this might be a 2 part question, how do we handle wildcard DNS records and is there a proper way of updating `[]dns.RR{}` granted the latter might be program specific and the implementation may vary..

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/dns] wildcard DNS records (#..." ]
>To give you a rough idea if we have a `*.domain.com` and `example.domain.com` how would we check and match them? The closest thing I came across is the `CompareDomainName` however that only checks from the right; What I'm trying to say is how do we go about checking if a DNS record, that's a wildcard matches a specific one?

you have to special case "*"
