### ISSUE TITLE
read udp 10.xx.xx.xx:44940->172.xx.xx.xx:53: i/o timeout

### ISSUE THREAD

**Issue by Crazy-Geng** [miekg/dns#996]
when "r, _, err := c.Exchange(m, net.JoinHostPort(ip, port))" , i get this errmsg ,"read udp 10.xx.xx.xx:44940->172.xx.xx.xx:53: i/o timeout", occasionally

i cant handle it
so, how do it?

	//构造客户端
	c := new(dns.Client)
	//构造请求报文
	m := new(dns.Msg)

	m.SetQuestion(dns.Fqdn(record), dns.TypeA)
	m.RecursionDesired = true

	r, _, err := c.Exchange(m, net.JoinHostPort(ip, port))
	if err != nil {
		logger.Println(err)
		return false
	}
	//logger.Println(r)
	if r.Rcode != dns.RcodeSuccess {
		logger.Printf("*** invalid answer name %s after MX query for %s\n", ip, record)
		return false
	}

**Comment by fregie** [comment]
I met this problem,too.
It just appear occasionally,I am sure my network is ok.

**Comment by breezemight** [comment]
I get this sometimes right away and sometimes after 4/5 queries. Why's the repo ignoring this issue everywhere
