### ISSUE TITLE
No TXT records found for $ORIGIN

### ISSUE THREAD

**Issue by donnyv12** [miekg/dns#998]
```
func CheckTXT(recordName string, nameserver string, filename string) {
	if recordName == "@" {
		recordName = "example.com."
	}
	hostName := strings.TrimSpace(recordName)
	c := dns.Client{}
	m := dns.Msg{}
	m.SetQuestion(hostName, dns.TypeTXT)
	r, t, err := c.Exchange(&m, nameserver+":53")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Took %v", t)
	if len(r.Answer) == 0 {
		log.Printf("%s %s %s", hostName, " Had no results at ", nameserver)
	}
       //do something with the valid result 
```

Using a bind file, I am trying to list all of the TXT records and am able to get subdomain's no problem, but $ORIGIN domain (in this case example.com) TXT records are failing. I can run `dig  example.com. TXT` and get the 8 records, but when I run the above, I get `example.com had no results` 

Any suggestions on how I can debug this further?

**Comment by donnyv12** [comment]
to further clarify, if `hostName` is a subdomain such as `foo.example.com` and there are txt records, I get the expected result.

**Comment by miekg** [comment]
Impossible to tell and not related to the code in this library. FWIW that code looks like it should just work.
